### ISSUE TITLE
Nice to have : DBConnection allow attribute override when using refid

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#100]
Currently DBConnection does not allow other attributes when using **refid**. It gives error **"You must not specify more than one attribute when using refid"**. 
It would be nice if it was possible to override of attributes.

Example override singleUser : 

``` xml
<DBConnection id="db" dbName="mydb" dbDir="data/mydb" singleUser="false"/>

<target name="loaddf">
  <PCTLoadSchema srcFile="mydb.df" dlcHome="${progress.DLC}" cpstream="${cpstream}">
    <DBConnection refid="db" singleUser="true" />
  </PCTLoadSchema>
</target>
```

**Comment by jakejustus** [comment]
Agreed, would be nice.
IIRC, when I implemented refid on DBConnection, it wasn't possible to easily do that. But it's worth having another look.

Gilles

**Comment by jakejustus** [comment]
Fixed in dev, will go into next release
