### ISSUE TITLE
PCTLoadData errorTolerance

### ISSUE THREAD

**Issue by vdende** [Riverside-Software/pct#101]
The errorTolerance attribute in PCTLoadData only works when using srcFile, but not with srcDir.

**Comment by jakejustus** [comment]
I think you have to fork the project first.

Gilles

On Tue, Jun 23, 2015 at 10:22 AM, Arno van der Ende <
notifications@github.com> wrote:

> The errorTolerance attribute in PCTLoadData only works when using srcFile,
> but not with srcDir.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jakejustus/pct/issues/101>.
>



-- 
Gilles QUERRET

Riverside Software
15d route de Bellevue • 69440 Mornant • France
Mob : +33 662.525.532

**Comment by vdende** [comment]
?
Yesterday I already created a fork.
Should I create the issue/ticket in my own fork?

**Comment by jakejustus** [comment]
Merged
