### ISSUE TITLE
Strange PCTLoadSchema error after succesful load

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#102]
I have a strange issue with PCTLoadSchema , I don't see it all the time and I'm not able to reproduce it on sports db.
I hope this rings a bell why I could get the behaviour I see, if it doesn't I will try to debug this.

the target (see below) shows following result

``` log
[PCTLoadSchema] Loading /usr2/cce/schema/version/smartmerge/delta.df in database
[PCTLoadSchema] 22922 errors and 0 warnings during load
[PCTLoadSchema] Log file can be found in /usr2/cce/schema/LISA.e.23062015.37025.1124
```

The load is as far as I can tell successful. There is no logfile in /usr2/schema/LISA this directory is write protected and should not be used. The basedir is /usr2/cce/schema/version/smartmerge . My PROPATH environment contains .:/usr2/cce/schema:/usr2/cce/schema/tools
If I unset the PROPATH the issue does not occur. 

``` xml
        <PCTLoadSchema srcFile="${dffile}" dlcHome="${progress.DLC}" cpstream="${cpstream}" debugPCT="${debugPCT}" >
            <DBConnection refid="db" />
        </PCTLoadSchema>
```

**Comment by jakejustus** [comment]
I'll try with a write-protected directory, there may be an impact.
Do you use 11.3+ or a previous version ? A different procedure is triggered depending on the version.

**Comment by gquerret** [comment]
Not reproduced.
