### ISSUE TITLE
PCTCreateBase option to specify source database

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#105]
Add option to start from non empty database

As far as I know it's not possible to create a database starting from an existing database
e.g. the equivalent of prodb sports2000 sports2000

A workaround exists by calling prodb (see  [build.xml](https://github.com/cverbiest/dbanalys-charts/blob/master/build.xml)) but it would be nice if PCTCreateBase had this option

**Comment by stefandrissen** [comment]
Seems like a duplicate of #31 ?

**Comment by cverbiest** [comment]
closed as duplicate of #31
