### ISSUE TITLE
pct:db_create something getting mixed up?

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#109]
On our Jenkins server (Windows 8.1) with PCT v194 something strange happened last night, while executing:

```
<target name="test-0-database.oracle">
    <pct:db_create dbName="exactcssh" destDir="${test}/db" schemaFile="${other}/db/oracle/exactcssh.df" />
```

The attempt to load the schema was attempted in a different workspace than the directory in which the empty database was created.

```
[bl] $ cmd.exe /C '"ant.bat -file build.xml -Ddlc=oe11.5 -Ddb.oracle.tnsname=oracle12c test-oracle && exit %%ERRORLEVEL%%"'
Buildfile: C:\Program Files (x86)\Jenkins\jobs\7.12 - work - edis run - 11.5 - oracle 12c\workspace\bl\build.xml

test-oracle:

test:

test-0-environment:
   [delete] Deleting directory C:\Program Files (x86)\Jenkins\jobs\7.12 - work - edis run - 11.5 - oracle 12c\workspace\build\oe11.5\test\oracle
    [mkdir] Created dir: C:\Program Files (x86)\Jenkins\jobs\7.12 - work - edis run - 11.5 - oracle 12c\workspace\build\oe11.5\test\oracle\db

test-0-database.oracle:
[pct:db_create] Copying empty DB to exactcssh
[pct:db_create] Unable to connect to -db 'C:\Program Files (x86)\Jenkins\jobs\7.12 - work - edis run - 11.4 - openedge\workspace\build\oe11.4\test\progress\db\exactcs' -1
[pct:db_create] ** The database C:\Program Files (x86)\Jenkins\jobs\7.12 - work - edis run - 11.4 - openedge\workspace\build\oe11.4\test\progress\db\exactcs is in use in single-user mode. (263)
```

Notice that the connection attempt (to load the schema) is attempting to connect to a database in a different workspace (11.4 - openedge) instead of (11.5 - oracle).

The empty database was created fine, but no further attempt on this database was attempted, nearly first and last lines of the log:

```
Formatting extents:
   size                area name   path name
      4    Primary Recovery Area C:\Program Files (x86)\Jenkins\jobs\7.12 - work - edis run - 11.5 - oracle 12c\workspace\build\oe11.5\test\oracle\db\exactcssh.b1 00:00:00
     16              Schema Area C:\Program Files (x86)\Jenkins\jobs\7.12 - work - edis run - 11.5 - oracle 12c\workspace\build\oe11.5\test\oracle\db\exactcssh.d1 00:00:00

Copying c:\progress\oe11.5\empty8 to exactcssh... (6715)

...Copy complete. (6722)
Database copied from c:\progress\oe11.5\empty8. (1365)
Procopy session end. (334)
```

This is not reproducible and I am not sure this is a PCT issue. I have seen other strange stuff occur on this machine with TFS (source control) intermittently not recognizing the workspace it is in (see https://social.msdn.microsoft.com/Forums/vstudio/en-US/0f9a3368-de75-47b7-925b-3cfbe9ac810c/tf-get-intermittently-reports-unable-to-determine-workspace?forum=tee).

Can anyone provide any hints or clues as to what is going on here?

Thanks!

Stefan

**Comment by jakejustus** [comment]
The weird thing is this is coming from the same build, so the basedir of Ant shouldn't change (you didn't remove extra lines from the output, right ?)
As it seems you're using single user mode, PCT relies on file resolution from Ant, which is in turn based on the directory where the process is running on Jenkins. One more point is that it seems the database is locked, so another build may be running on this database. Without more details and if you can't reproduce the problem, I guess it will be hard to find if this is coming from PCT, Ant, Jenkins or TFS... Will close, but feel free to reopen if you think this is related to PCT.
