### ISSUE TITLE
Invalid datatype specified in case of a class reference

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#110]
I have strange bug compiling a ABL Class against a PL Library. 

The ABL class looks like this: 

```
USING be.mips.ablframework.smartcomponents.implementation.MipsDataBrowser FROM PROPATH. 
CLASS be.mips.ablframework.gui.MyBrowserControl: 
  DEFINE PROTECTED VARIABLE mipsDataBrowser AS MipsDataBrowser NO-UNDO. 
END CLASS. 
```

The r-code is in a PL library with the correct path, correct casing. When trying to compile the class using PCTCompileExt, I'm getting next error: 

> PCTCompile - Progress Code Compiler 
> Error compiling file C:\Workspace\GitRepositories\made-build-scripts.git\src/be/mips/ablframework/gui/MyBrowserControl.cls at line 5 column 50 
> DEFINE PROTECTED VARIABLE mipsDataBrowser AS MipsDataBrowser NO-UNDO. 
> -------------------------------------------------^ 
> Invalid datatype specified: MipsDataBrowser. Specify a datatype such as 'character' or the name of a class. (5638) 
> *\* C:\Workspace\GitRepositories\made-build-scripts.git\src\be\mips\ablframework\gui\MyBrowserControl.cls Could not understand line 5. (196) 

What is even stranger is that if I take a copy of the file (so a second class) with the name MyBrowserControl2.cls, then that file IS compiled. And they have exactly the same content (only the Class name of course is MyBrowserControl2. 

I really can't get my head around this one. If I create a MyBrowserControl3.cls, MyBrowserControl4.cls, they all get compiled. It's like the first class with a reference to MipsDataBrowser gets the problem, but after that, things seem to be good for the other files... 

Now, if I put the source class file, the cls file of MipsDataBrowser, in my propath, then MyBrowserControl.cls does get compiled, but so does MipsDataBrowser. So then I have a MyBrowserControl.r file and a MipsDataBrowser.r file. But that's not what I want. I want MyBrowserControl.cls to use the r file that is in the PL library. 

Any ideas? 

I have tried to reproduce this in an Eclipse OpenEdge project, but in there the two files do compile. Probably Eclipse compiles the files differently, or with other options, than PCTCompileExt? 

Have tried with multiCompile and without, same error keeps popping up. Have also tried changing the class to: 

```
USING be.mips.ablframework.smartcomponents.implementation.MipsDataBrowser FROM PROPATH. 
CLASS be.mips.ablframework.gui.MyBrowserControl: 
  DEFINE PROTECTED VARIABLE mipsDataBrowser AS be.mips.ablframework.smartcomponents.implementation.MipsDataBrowser NO-UNDO. 
END CLASS. 
```

Notice the small difference, but that doesn't work either. 

OE Version is 11.3.2. Trying it out against 11.4 or 11.5 isn't much of a use for us because we won't build our application with 11.4 or 11.5 in the near future... 

For PCT, I'm using revision aa553cd99e66, don't know which version that is and if, since then, this kind of problem has been seen/solved.

Kind regards, Lieven Cardoen

**Comment by lievencardoen** [comment]
By the way, using PCTCompile gives me the same problems, but even worse... That's another suggestion I would like to make, getting rid of either PCTCompile or PCTCompileExt. Now I find it just confusing. With PCTCompile, I'm getting errors that I don't get using PCTCompileExt...

Have also opened a case with OpenEdge. Their answer:

> I assume that with PCT you mean the Progress Compilation Tools (http://jakejustus.github.io/pct/ ) ?
> If yes, be aware that that is not developed by Progress Software, thus we do not provide support on those.
> 
> From the description you provide, it sounds like the PCT tools don't set up the propath correctly until after the first file is compiled. 
> That would also mean that if you rename/remove the "MyBrowserControl.cls", the next one in line would start failing (the "MyBrowserControl2.cls", assuming alphabetic order).
> I don't know how the tools manage the propath settings for the AVM they use though. 
> 
> In contrast, compiling from within Eclipse /PDS:OE will use the Project AVM. And I can confirm that AVM will get the propath set based on project settings (or Shared AVM config if you use that) as part of it's startup cycle, before any compiles can be perfomed.
> 
> Did you contact the creator of the PCT tools as well ? 
> I won't be able to provide much further assistance unless they can explain how the internals of their tools work.

So I'm kind of in the dark here. Seems like a really strange bug. By the way, I don't think it is PCT related, as we also have the issue with our 'old' build system (using an ABL procedure to compile the sources, somewhat the same as PCT does in the background, creating a temp ABL procedure to compile the source).

Kind regards, Lieven Cardoen

**Comment by lievencardoen** [comment]
I have set up a  project where I compile the same Classes using a custom compile.p ABL procedure. This procedure is started with prowin32.exe.

I can't reproduce the error when doing that.

My compile.p looks like:

```
PROPATH=".,Cls.pl,Consultingwerk.pl".
ASSIGN COMPILER:MULTI-COMPILE = TRUE. 
COMPILE be/mips/ablframework/gui/MyBrowserControl.cls
  SAVE INTO C:\Workspace\EclipseWorkspaceOE_11_3\BugClassRCode\_ant_rcode_progress
  MIN-SIZE=TRUE.
COMPILE be/mips/ablframework/gui/MyBrowserControl2.cls
  SAVE INTO C:\Workspace\EclipseWorkspaceOE_11_3\BugClassRCode\_ant_rcode_progress
  MIN-SIZE=TRUE.
```

I'm starting compile.p from proenv (11.3.2) and executing 
    prowin32.exe compile.p -assemblies assemblies

I'm not getting the error I'm getting with PCT.

Is there a way to know the exact command that is used by PCT when compiling MyBrowserControl? + the ABL Procedure that is used to compile it?

Lieven Cardoen

**Comment by lievencardoen** [comment]
Does this ring a bell...

I can compile the Class if I put the PL libraries in the beginning of my PROPATH instead of at the end.

So I have a src folder where my changed sources are copied to.

Those changed sources are compiled against the PL Progress libraries.

So, when failing to compile, propath looks like:

src, Cls.pl, Consultingwerk.pl

When I change the order to

Cls.pl, Consultingwerk.pl, src

Then the source does compile;

The source that I'm trying to compile is located in that src folder.

Lieven

**Comment by jakejustus** [comment]
Hi Lieven,
- About getting rid of PCTCompile or PCTCompileExt : yes, that will be merged. However, that's just a huge work that probably won't be done, as I'm looking for improvements which will change the way builds are managed in OpenEdge. There will probably be an "open" session during the PUG Challenge in Copenhagen on this topic, another very good idea to be present at this event
- The problem when you get the rcode of the parent class in your build directory when compiling the child class is known by Progress. Not sure if they plan to change the behavior
- About the procedure triggered by PCT to execute the compilation, you can add debugPCT="true" verbose="true" in PCTCompile. You'll find the temp files in the $TEMP directory.
- On the latest comment, would you be able to provide a small code sample ? That would really help me to debug the issue.
- About version aa553cd99e66 : that's included in build 187. Could you try the latest version of PCT ?

Gilles

**Comment by jakejustus** [comment]
Uploaded test case for this issue : http://pugfr.riverside-software.fr/Issue110.zip
But this works with both build 198 and 187. However, I don't have 11.3 available, so it was tested with 11.5.
Can you verify with 11.3, and change the test case if it's not correct ?

**Comment by jakejustus** [comment]
Were you able to play with the test case ?

Gilles

**Comment by lievencardoen** [comment]
Hey, Jake, I'll take a look into it in about two weeks. On vacation. But I
will get to the bottom of this ;-)

Kind regards, Lieven Cardoen

**Comment by lievencardoen** [comment]
Back. I have also created a small test case and with 11.3 I can't seem to reproduce the problem.

So this will be a hard one. When doing the same with thousands of classes, I do get the error. Trying to reproduce it with just two or three classes doesn't give me the error. Typically OpenEdge problems...

Lieven

I'll check out your test case against 11.3 and let you know.

**Comment by lievencardoen** [comment]
Hi Gilles,

Output of the test case against 11.3.3.16:

C:\Users\lievenc\Desktop\Issue110\Issue110>ant
Buildfile: C:\Users\lievenc\Desktop\Issue110\Issue110\build.xml
[PCTCompileExt] PCTCompile - Progress Code Compiler
[PCTCompileExt] cpstream is not defined. You may have problems if file names have characters outside of ASCII range. You really should define it !
[PCTCompileExt] 0 file(s) compiled
[PCTLibrary] Building PL : C:\Users\lievenc\Desktop\Issue110\Issue110\lib1.pl
[PCTLibrary] Compressing PL : C:\Users\lievenc\Desktop\Issue110\Issue110\lib1.pl
[PCTCompileExt] PCTCompile - Progress Code Compiler
[PCTCompileExt] cpstream is not defined. You may have problems if file names have characters outside of ASCII range. You really should define it !
[PCTCompileExt] 1 file(s) compiled
[PCTLibrary] Building PL : C:\Users\lievenc\Desktop\Issue110\Issue110\lib2.pl
[PCTLibrary] Compressing PL : C:\Users\lievenc\Desktop\Issue110\Issue110\lib2.pl
[PCTCompileExt] PCTCompile - Progress Code Compiler
[PCTCompileExt] cpstream is not defined. You may have problems if file names have characters outside of ASCII range. You really should define it !
[PCTCompileExt] 1 file(s) compiled

BUILD SUCCESSFUL
Total time: 1 second

So I guess I'm back to square 1. Have tried to isolate the problem, but as said before, when isolating it, the problem disappears (the error).

I've been absent for 4 weeks, so I will have to do some digging before I'm up and running again with this problem. 

Lieven

**Comment by lievencardoen** [comment]
Tried with OE 11.5. Same problem. Strange. Very, very strange. And I'm tired spending time on things that should work. So not really a PCT bug and since I can't reproduce it in a small example, OpenEdge won't look into it either... So, I just wrote a workaround that adds the sources to the propath in cases where the problem occurs. Anyway, thx for helping. Will close this issue.

**Comment by jakejustus** [comment]
Does it _always_ fail on your large codebase ?
Also, feel free to contact me offline if you need consulting on this topic.

**Comment by lievencardoen** [comment]
No, that's the strange thing, I have a Jenkins slave running on another server and there the problem does not occur. And it's the same OE version...
