### ISSUE TITLE
pct:compile: leaves debug listing in root when aborted, causing subsequent compile to fail once

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#111]
pct v194
openedge 11.4 / 11.5
jenkins multijob project

When a compile run is aborted (in our case due to one of the parallel jobs failing for whatever reason), the parallel siblings are aborted. When a compile task is aborted, a debug file is left behind which trips up a subsequent build which thinks there is a .p to compile.

```
...
[pct:compile] File [C:\Program Files (x86)\Jenkins\jobs\7.12\jobs\done\jobs\build_bl-11.4-oracle\workspace\bl]/[project_ifallgen_gprmes.p] not found
...
[pct:compile] 1023 file(s) compiled
[pct:compile] Failed to compile  1  file(s)
[pct:compile] Return value : 10
```

Restarting the compile run again is then successful, since the orphan debug file was deleted by the successful compile of the file itself. When there are n parallel builds, the compile needs to be restarted n-1 times to flush out each project's orphan debug listing.

```
    <pct:compile destDir="${build}/${ant.project.name}/progress" verbose="true" stackSize="512" inputChars="32000" relativePaths="false" debugListing="true" listing="true" keepXref="true" xmlXref="true">
        <pct:db_connection dbName="exactcs" dbDir="${build}/db/progress" singleUser="true">
            <alias name="exactcssh" />
        </pct:db_connection>
        <fileset dir="${src}" includes="**/*.p" />
        <propath>
            <pathelement location="${src}/../i" />
            <pathelement location="${src}" />
            <pathelement location="/bl," />
        </propath>
    </pct:compile>
```

Work-arounds: 
1. set debugListing to false - not tested, but also not desirable
2. before starting the compile delete files matching ___.p

**Comment by jakejustus** [comment]
What is the content of this debug file ?

**Comment by stefandrissen** [comment]
That depends on the file that was being compiled when aborted - ie it is a debug listing which is later moved to the .dbg directory.

**Comment by stefandrissen** [comment]
I see that markdown has obfuscated work-around 2 - it stated *_*.p (being typical for debug-listing filles),

**Comment by stefandrissen** [comment]
Had another aborted run yesterday, debug listing system_trig_tw_twearolrec.p trips up the next run, partial log

```
[pct:compile] Compiling system\xml\xml3570.p in directory d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\bl TO d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\build\oe11.4\bl\oracle/system\xml\
[pct:compile] File [d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\bl]/[system_trig_tw_twearolrec.p] not found
[pct:compile] Compiling tools\cimport\cmenu.p in directory d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\bl TO d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\build\oe11.4\bl\oracle/tools\cimport\
...
[pct:compile] Compiling webservice\exceladdin\login.p in directory d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\bl TO d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\build\oe11.4\bl\oracle/webservice\exceladdin\
[pct:compile] 88 file(s) compiled
[pct:compile] Failed to compile  1  file(s)
[pct:compile] Return value : 10

BUILD FAILED
d:\jenkins\workspace\7.20\work\build_bl-11.4-oracle\bl\build.xml:171: Return code : 10
```

Instead of first putting the debug-listings in the root folder, can't they be saved to the .dbg folder directly?

**Comment by jakejustus** [comment]
Could you try build #198 ? The debug listing is saved automatically in the .dbg folder directory : https://github.com/jakejustus/pct/commit/9aae478588ede72cb298fc6b4db0af279d3131d4

**Comment by stefandrissen** [comment]
Code changes look like they will do the trick. Thanks!
