### ISSUE TITLE
.cls files compiled to baseDir.r 

### ISSUE THREAD

**Issue by dmarteinson** [Riverside-Software/pct#115]
I've got an application for which the propath has a number of directories containing .cls files.
For our purposes assume they are a/, b/ etc.
The base directory is NOT part of the propath.

We're creating a PCT build for this.

The legacy build script compiles these classes to the corresponding folder, e.g. a/a1.cls -> a/a1.r
Compiling with PCT a/a1.cls goes to a1.r in the root folder.

Following a suggestion hinted at in another issue I tried using a custom mapper in PCTCompileExt to set the 'to' attribute to keep the folder but in doing this I get the following compilation error:
"Name of the class in the CLASS statement 'HelloWorldBase' must match the pattern of the name of the file .... (12629)"

As the requirement is to have these .cls files compiled to .r files in the same folder, is there a way to achieve this with PCT?

**Comment by jakejustus** [comment]
Do you use `<fileset dir="a" includes="*.cls" />` ? This syntax should work (also include the directory in your propath).
Using `<fileset dir="parent_dir_of_a" includes="a/*cls" />` is likely to fail.

**Comment by dmarteinson** [comment]
Wow speedy response :)

Exactly, what I have looks like the latter as it's a single fileset with include's for each directory in the propath.  

OK, so perhaps an optimization question but would that mean running a separate compile task for each directory or is there a way to pass multiple filesets?

**Comment by jakejustus** [comment]
You can have multiple filesets (or any resource collection) in a single PCTCompile, and that will still result in a single compile task.

**Comment by dmarteinson** [comment]
OK so given a project with two folders one containing a cls and one a .p like so:

subfolder/
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; HelloWorld.cls
anotherfolder/
   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; custom.p

I'm trying to configure PCT so that the .r files end up in the same folders like so:
subfolder/
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  HelloWorld.r
anotherfolder/
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   custom.r

Even though the class HelloWorld does not have a package subfolder.
By specifying the folder names as part of the fileset includes this seemed to be working previously for files other than .cls files which went to the root.

OK, so using the approach you've indicated given a PCTCompile task inside a build target like so:

``` xml
<PCTCompile destDir="." .. various other options ...>
     <fileset dir="subfolder" includes="*.p,*.cls" casesensitive="no" />
     <fileset dir="anotherfolder" includes="*.p,*.cls" casesensitive="no" />

    <propath>
         <pathelement location="subfolder" />
         <pathelement location="anotherfolder" />
    </propath>
</PCTCompile>
```

destDir is "." as there are multiple source folders in my use case.
I guess I'd say that we're looking for what amounts to a compile-in-place configuration, as this is the customer's existing practise; and seems feasible except for these classes that lack package names.

I'm seeing all of the files end up in the root folder, what have I missed?

**Comment by jakejustus** [comment]
When classes are compiled in 'target' directory, they will end up as 'target/Hello.r' if no package is provided and to 'target/package/subpackage/Hello.r' if a package name is specified.
By the way, it's not a good practice to have classes without package name in OE, in Java, or whatever...
