### ISSUE TITLE
Enhancement request: Support -k parameter in pctcompile with excludefilter

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/pct#118]
It would be really nice if pctcompile could support the -k parameter (keyword forget list)
But i would need a bit more than the default OpenEdge feature.

I would like to have a filter to "exclude" files for each keyword individually.
The best case would be if i could give pct a xml file (or some other file format), where each keyword is listed with all the files where the keyword is still allowed.
The file would be nice because the keyword forget list can be different for each branch since the keywords are usually disabled in the dev branch and (for some time) still allowed in the stable branch.

The usecase for this is that i wrote wrapper for some ABL keywords to add some additional functionality (for example a mandatory logging etc.) and at the moment there is nothing to stop our developers to use the keyword and not the custom method.
So i would need to disable the keyword everywhere except for this one file.

The secod usecase are keywords that we can't use in our program because the don't work under certain circumstances. (For example the OS-\* keywords don't work on UNC paths in Windows).
But we use some third party toolsets that we only have xcoded and they use some of these keywords so i would need to exclude those.

**Comment by bulagump** [comment]
You could create an Ant macro and then use Ant fileset selectors to do
this.  The macro would just wrap your pctcompile statement, and the macro
would also contain the fileset Selectors.

It doesn't make sense to change pctcompile itself.

**Comment by jakejustus** [comment]
As said in the previous comment, PCTCompile won't be modified such a case. You can already use <Option name="-kwfl" value="/path/to/file" /> in PCTCompile (there's no dedicated attribute for keyword forget list). Mixed with a macro or an Ant contrib-task, or executed from Groovy, you'll easily achieve the desired result.

Gilles
