### ISSUE TITLE
PCTCompileExt does not return when ini file name is wrong

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/pct#122]
It appears that PCTCompileExt never returns (back to the ANT script) when the ini file parameter is wrong. We started 4 threads.

[PCTVersion] PCT Version 1.1-pre - Build 194

[PCTCompileExt] PCTCompile - Progress Code Compiler
[PCTCompileExt] E:\Jenkins\workspace\ini\consultingwerk_fak11.ini file not found. (5643)
[PCTCompileExt] E:\Jenkins\workspace\ini\consultingwerk_fak11.ini file not found. (5643)
[PCTCompileExt] E:\Jenkins\workspace\ini\consultingwerk_fak11.ini file not found. (5643)
[PCTCompileExt] E:\Jenkins\workspace\ini\consultingwerk_fak11.ini file not found. (5643)
[PCTCompileExt] Result: 2
[PCTCompileExt] Result: 2
[PCTCompileExt] Result: 2
[PCTCompileExt] Result: 2

**Comment by jakejustus** [comment]
Not only when INI file is not found, but when the OE process is not able to connect to the server socket.
Introduced a quick fix in Dev

**Comment by jakejustus** [comment]
Will be merged in QA build, and part of next release
