### ISSUE TITLE
PCTCompile: how to ignore changes in includes

### ISSUE THREAD

**Issue by axelebnerpcsat** [Riverside-Software/pct#125]
Is it possible to exclude certain includes from a referenced compile?

Configured by the fileset:
excludeinc name="Commithash.i"

**Comment by jakejustus** [comment]
Hi,

There's currently no way to do that, it's unfortunately all or nothing.

Gilles

**Comment by axelebnerpcsat** [comment]
Hi Gilles,

OK thank you.

Axel

**Comment by jakejustus** [comment]
Just in case (as I won't have time to implement it myself), I can still provide help in case you're willing to do the implementation.

**Comment by axelebnerpcsat** [comment]
I'm not familiar with JAVA, but I can try it, if you give me a hand.

**Comment by jakejustus** [comment]
After having checked out the code, you can follow those short instructions here : https://github.com/jakejustus/pct/wiki/FAQ, and verify you can compile PCT and that unit tests are executed correctly.
Once it's done, you can first try to create a new test case in PCTCompile (new directory in tests/PCTCompile, you can find numerous examples there), which will obviously fail (as didn't change any PCT code yet).
Then you can have a look at src/progress/pct/v11/pctCompile.p, which is the progress procedure executed by PCTCompile. You can try to introduce hard-coded modifications there, then you'll be able to add parameters in src/java/com/phenix/pct/PCTCompile.java.

Gilles

**Comment by jakejustus** [comment]
Won't be able to help you this week, but will have some more time next week.
