### ISSUE TITLE
PCTRun to launch interactive session

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#129]
Is it possible to use PCTRun to launch an interactive prowin32/_progress client ?
In the documentation I find not option for batch/interactive

Use case: 
build.xml contains all the required config (databases, propath, ...) to compile the application.
It would be nice if that same config could be used to actually start an application

**Comment by jakejustus** [comment]
No, there's no option to remove the -b switch. You could easily add it in your own fork of PCT (there's even an attribute in PCTRun), but it's unlikely it will be integrated in the main branch as I'm pretty sure that will lead to a huge pile of problems.

**Comment by cverbiest** [comment]
Ok thanks for the fast reply, not in the mood to run into a huge pile of problems, I'll take an alternative approach .
I created following target to help define a session with the same parameters as the PCT build.
It creates an ini file with the propath from the build file

```
<target name="makeinifile" >
    <ProgressVersion dlcHome="${progress.DLC}" majorVersion="progress.version.major" minorVersion="progress.version.minor" />
    <inifile 
      source="${progress.DLC}/bin/progress.ini" 
      dest="${projects_root}/oe${progress.version.major}${progress.version.minor}_build.ini" >
      <set section="Startup" property="PROPATH" value="${toString:PCTPropath}" />
    </inifile>
  </target>
```
