### ISSUE TITLE
The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129)

### ISSUE THREAD

**Issue by lakehouse-david** [Riverside-Software/pct#135]
Currently there is intermittent issues when using PCT to compile code.
The error looks like this:

``` bash
compile-progress-proxy:
build   10-May-2016 02:21:02        
[mkdir] Created dir: /dr01/bamboo/xml-data/build-dir/QRA-QRAD-BL/tmp/wc1759838280/bl/work/progress-proxy-rcode
build   10-May-2016 02:21:02
[PCTCompile] PCTCompile - Progress Code Compiler
build   10-May-2016 02:21:27    
[PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
build   10-May-2016 02:21:27    
[PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
build   10-May-2016 02:21:27    
[PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
```

This error occurs in our several QRA related bamboo builds as you can refer to
[QRA base integrate bamboo build](https://bamboo.qad.com/download/QRA-QRADBASEINT-BL/build_logs/QRA-QRADBASEINT-BL-4743.log)
[QRA bamboo build](https://bamboo.qad.com/download/QRA-QRAD-BL/build_logs/QRA-QRAD-BL-2265.log)

PCT - version : qra-pct-0.19.0.176
DLC - version : dlc11464 ( OpenEdge 11.4 64-bit)

Reference ticket: https://projects.qad.com/browse/DVS-10940

Any other information needed? Due to its intermittency, find it hard to create a verbose log.

**Comment by lakehouse-david** [comment]
HOST & OS info: 

``` bash
coli49:92 /users/dr2 $ cat /etc/redhat\-release
Red Hat Enterprise Linux Server release 5.11 (Tikanga)    
coli49:92 /users/dr2 $ uname -a    
Linux coli49 2.6.18-410.el5 #1 SMP Fri Apr 8 05:48:52 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jakejustus** [comment]
Hi,

You're using a custom version of PCT as shown by the PCT Version string, so that will be difficult to reproduce the issue.
I also don't have access to your bamboo server.

**Comment by lakehouse-david** [comment]
There is a recent error occurs with the message.
My email is dr2@qad.com hoping to contact with you.

There is an email that gives the possible resolution to this, 

> From: Gilles QUERRET g.querret@gmail.com
> Date: Mon, May 9, 2016 at 1:13 PM
> Subject: Re: intermittent PCT compile error
> To: Doug Norton dzn@qad.com
> Hi Doug,
> Please report the issue on GitHub, and make sure you include the PCT version number, OE version and OS version.
> One idea for this (129) message : do you specify the -tmpbsize parameter in the PCTCompile node (or inherit from some .pf file) ? An index was added some time ago on the ttXref (as there were performance problem on large projects involving lots of include files), but that may be a problem when tmpbsize is set to 1 (leading to 180 characters limitation on indexes).
> Gilles

The file attched is the log file, but is not very friendly.
[QRA-QRADBASEINT-BL-4844.log.txt](https://github.com/jakejustus/pct/files/290775/QRA-QRADBASEINT-BL-4844.log.txt)

Any other information needed please contact me. I'm currently creating environment to reproduce the issue.

**Comment by jakejustus** [comment]
Does a rebuild of the same exact version in Bamboo triggers again the issue ?
There's a mention of a PCT version, can you confirm the version being used ? Use PCTVersion task in your build, or have a look at the META-INF/MANIFEST.MF file in your JAR file. Without a version number, I can't say anything.
You can also trigger the build with -v in order to generate a verbose log. That will help finding the root cause.

**Comment by lakehouse-david** [comment]
Is a ant -v enough or also should include **verbose="true"** in the PCTCompile statement? But the latter would be difficult to configure in our bamboo job. I'm currently run the build in verbose to see if this intermittent error occurs.

I copied the pct.jar from the bamboo work area and shows:
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.8.1
Created-By: 1.7.0_02-b13 (Oracle Corporation)
Built-By: root

Name: common
Specification-Title: PCT
Specification-Version: 0.19-pre
Specification-Vendor: Riverside Software
Implementation-Title: PCT
Implementation-Version: Build 176
Implementation-Vendor: Riverside Software

**Comment by jakejustus** [comment]
Build 176 is quite old, you also should consider upgrading to the latest version.
Not sure if ant -v will be enough, but that's at least a first step !

**Comment by lakehouse-david** [comment]
### Today got the verbose log of the error:

_build  06-Jun-2016 12:14:48    compile-impl:
build   06-Jun-2016 12:14:48        [mkdir] Skipping /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/tmp/wc556105753/bl/work/rcode because it already exists.
build   06-Jun-2016 12:14:48    [PCTCompile] OpenEdge version found : OpenEdge Release 11.3.1 as of Fri Sep 13 19:00:23 EDT 2013
build   06-Jun-2016 12:14:48    [PCTCompile] Using object : com.phenix.pct.ProgressV11
build   06-Jun-2016 12:14:48    [PCTCompile] PCTCompile - Progress Code Compiler
build   06-Jun-2016 12:14:49    [PCTCompile] Current OS is Linux
build   06-Jun-2016 12:14:49    [PCTCompile] Setting environment variable: DLC=/qad/progress/dlc113164
build   06-Jun-2016 12:14:49    [PCTCompile] Executing '/qad/progress/dlc113164/bin/_progres' with arguments:
build   06-Jun-2016 12:14:49    [PCTCompile] '-b'
build   06-Jun-2016 12:14:49    [PCTCompile] '-q'
build   06-Jun-2016 12:14:49    [PCTCompile] '-inp'
build   06-Jun-2016 12:14:49    [PCTCompile] '32000'
build   06-Jun-2016 12:14:49    [PCTCompile] '-cpinternal'
build   06-Jun-2016 12:14:49    [PCTCompile] 'utf-8'
build   06-Jun-2016 12:14:49    [PCTCompile] '-s'
build   06-Jun-2016 12:14:49    [PCTCompile] '128'
build   06-Jun-2016 12:14:49    [PCTCompile] '-param'
build   06-Jun-2016 12:14:49    [PCTCompile] '/tmp/pct_params33270.txt'
build   06-Jun-2016 12:14:49    [PCTCompile] '-p'
build   06-Jun-2016 12:14:49    [PCTCompile] '/tmp/pctinit27595.p'
build   06-Jun-2016 12:14:49    [PCTCompile] 
build   06-Jun-2016 12:14:49    [PCTCompile] The ' characters around the executable and arguments are
build   06-Jun-2016 12:14:49    [PCTCompile] not part of the command.
**build 06-Jun-2016 12:15:53    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
build   06-Jun-2016 12:15:53    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
build   06-Jun-2016 12:15:53    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)**
build   06-Jun-2016 12:15:53      [antcall] Exiting /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/tmp/wc556105753/bl/build.xml.
build   06-Jun-2016 12:15:53          [ant] Exiting /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/tmp/wc556105753/bl/build.xml.
error   06-Jun-2016 12:15:53  
error   06-Jun-2016 12:15:53    BUILD FAILED
error   06-Jun-2016 12:15:53    /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/module.build.xml:206: The following error occurred while executing this line:
error   06-Jun-2016 12:15:53    /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/tmp/wc556105753/bl/bl.build.xml:851: The following error occurred while executing this line:
**error 06-Jun-2016 12:15:53    /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/tmp/wc556105753/bl/bl.build.xml:434: Progress procedure failed - No output file**
error   06-Jun-2016 12:15:53        at com.phenix.pct.PCTRun.execute(PCTRun.java:632)
error   06-Jun-2016 12:15:53        at com.phenix.pct.PCTCompile.execute(PCTCompile.java:513)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
error   06-Jun-2016 12:15:53        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
error   06-Jun-2016 12:15:53        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
error   06-Jun-2016 12:15:53        at java.lang.reflect.Method.invoke(Method.java:606)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Task.perform(Task.java:348)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Target.execute(Target.java:392)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Target.performTasks(Target.java:413)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
error   06-Jun-2016 12:15:53        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
error   06-Jun-2016 12:15:53        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
error   06-Jun-2016 12:15:53        at java.lang.reflect.Method.invoke(Method.java:606)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Task.perform(Task.java:348)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Target.execute(Target.java:392)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Target.performTasks(Target.java:413)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:442)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
error   06-Jun-2016 12:15:53        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
error   06-Jun-2016 12:15:53        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
error   06-Jun-2016 12:15:53        at java.lang.reflect.Method.invoke(Method.java:606)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Task.perform(Task.java:348)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Target.execute(Target.java:392)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Target.performTasks(Target.java:413)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Main.runBuild(Main.java:811)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.Main.startAnt(Main.java:217)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
error   06-Jun-2016 12:15:53        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
**error 06-Jun-2016 12:15:53    Caused by: java.io.FileNotFoundException: /tmp/PCTResult18301.out (No such file or directory)**
error   06-Jun-2016 12:15:53        at java.io.FileInputStream.open(Native Method)
error   06-Jun-2016 12:15:53        at java.io.FileInputStream.<init>(FileInputStream.java:146)
error   06-Jun-2016 12:15:53        at java.io.FileReader.<init>(FileReader.java:72)
error   06-Jun-2016 12:15:53        at com.phenix.pct.PCTRun.execute(PCTRun.java:617)
error   06-Jun-2016 12:15:53        ... 42 more_

### and the bl.build.xml line 434 is running the following target:

```
<target name="compile-impl" depends="compile-api,create-database,generate-webservices">

        <mkdir dir="work/rcode"/>

        <PCTCompile destDir="work/rcode" dlcHome="${DLC}" cpInternal="utf-8"          // Line 434 problem occurs
            inputChars="32000" stackSize="128">
            <PCTConnection dbName="work/db/module" LogicalName="${module}" ReadOnly="true"/>
            <propath>
                <pathelement path="src/api"/>
                <pathelement path="src/impl"/>
                <pathelement path="${api.path.depends}"/>
                <pathelement path="${impl.path.depends}"/>
            </propath>
            <fileset dir="src/impl">
                <include name="**/*.cls"/>
                <include name="**/*.p"/>
            </fileset>

            <fileset dir="work/gen">
                <include name="**/*.p"/>
            </fileset>

        </PCTCompile>

    </target>
```

**Comment by lakehouse-david** [comment]
Would this **error 06-Jun-2016 12:15:53 Caused by: java.io.FileNotFoundException: /tmp/PCTResult18301.out (No such file or directory)** caused by pct problem or the system problem? Because we have scripts to cleanup the files under /tmp if there is little space, but we have check that it  didn't trigger when the bamboo has this error, so not sure the exact reason.

**Comment by jakejustus** [comment]
If you still have a PCTXREF file in the root folder of your workspace build (that should be /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/tmp/wc556105753/bl/ or something close), please attach it to this ticket.

**Comment by lakehouse-david** [comment]
Hi Gilles:
Is this PCTXREF file in the .jar or just a configuration file outside?

Another question is that:
Should those PCTResultxxx.out, pct_paramxxx.txt be removed after running this build? Is there some cleanup target?
I've found lots of those pct_paramxxx.txt under /tmp folder which created by our bamboo.
`
coli49:92 /tmp $ ll -lt | grep pct
-rw-r--r--   1 devel   devel         96 Jun  6 22:25 pct_params6299.txt
-rw-r--r--   1 devel   devel        105 Jun  6 19:16 pct_params6721.txt
-rw-r--r--   1 devel   devel        101 Jun  6 19:16 pct_params62134.txt
-rw-r--r--   1 devel   devel        106 Jun  6 17:51 pct_params51909.txt
-rw-r--r--   1 devel   devel        100 Jun  6 17:50 pct_params61887.txt
-rw-r--r--   1 devel   devel        106 Jun  6 15:08 pct_params744.txt
-rw-r--r--   1 devel   devel        100 Jun  6 14:55 pct_params50814.txt
-rw-r--r--   1 devel   devel        105 Jun  6 12:41 pct_params583.txt
-rw-r--r--   1 devel   devel        101 Jun  6 12:40 pct_params31282.txt
-rw-r--r--   1 devel   devel        106 Jun  6 12:09 pct_params51311.txt
-rw-r--r--   1 devel   devel        100 Jun  6 12:06 pct_params52793.txt
......

`

**Comment by jakejustus** [comment]
PCTXREF is a regular file in the filesystem ; it's created on the fly by PCT during compilation to extract XREF data. 
The PCTResult and pct_params are automatically removed after the build, unless a crash occurs. In this case, those temp files are kept on disk. You can remove then remove them manually (as it's a build server, just don't delete files which may currently be in use).

**Comment by lakehouse-david** [comment]
No i can not find it, I have a backup of the work area during the build that is the /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/, but no finding. I guess just after the compile is done the file will be removed?

**Comment by lakehouse-david** [comment]
If you can give me a basic content or what the file is like may help me to do the search.

**Comment by jakejustus** [comment]
Are you able to trigger a command line directly in this build directory ? If so, please add verbose="true" keepXref="true" to the PCTCompile node and restart the build process directly.

**Comment by lakehouse-david** [comment]
Got it, but this PCTXREF is not from that fail build, is from a currently running build.
[PCTXREF.txt](https://github.com/jakejustus/pct/files/302008/PCTXREF.txt)

**Comment by jakejustus** [comment]
That won't be the right one

**Comment by lakehouse-david** [comment]
Btw, I find a interesting thing. As I find the /tmp folder is another work area in additional to dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/ and is for every build. I got the PCTXREF from /tmp and the PCTResultxxx.out is also under that. There is two agent that can run build at the same time on our bamboo server. So my guess is, what's your naming rule for PCTResultxxx.out ? Would that possible that two bamboo run PCTCompile at the same time using same PCTResult or wrongly remove  other build's PCTResult? 
Because we have several times there are two build fail in it at just the same time.

Those fail do occur at the same time:
https://bamboo.qad.com/browse/QRA-QRADSALESINT-3104/log
05-Jun-2016 21:31:14    compile-impl:
05-Jun-2016 21:31:14    [PCTCompile] PCTCompile - Progress Code Compiler
**05-Jun-2016 21:32:46  [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
05-Jun-2016 21:32:46    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
05-Jun-2016 21:32:46    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)**
https://bamboo.qad.com/browse/BAMTST-IBST-8/log
05-Jun-2016 21:31:20    compile-impl:
**05-Jun-2016 21:31:20  [PCTCompile] PCTCompile - Progress Code Compiler
05-Jun-2016 21:32:46    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
05-Jun-2016 21:32:46    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)
05-Jun-2016 21:32:46    [PCTCompile] The total length of the fields in an index exceeds max key size. Index typ of table (TEMP-TABLE)ttXref (129) (11353)**

So should a set the PCT output location different a potential solution? Compared to get the PCTXREF of a fail build, test this may be more easier because all PCTXREF is under /tmp PCTXREF and may be overwrite by other build before I get it.

**Comment by lakehouse-david** [comment]
Is there some parameter to specify the PCT tmp folder same as -Djava.io.tmpdir=/tmp/BAMTST-IBST-BL when running the ant build?

**Comment by jakejustus** [comment]
Numbers are randomly generated in PCT. I'd say it's really unlikely that a conflict could occur.

**Comment by jakejustus** [comment]
you can still try using java.io.tmpdir

**Comment by jakejustus** [comment]
But if this specific build _always_ crash, then it's not random conflict ; the error message is about an index size problem when reading XREF file.

**Comment by lakehouse-david** [comment]
There are several builds intermittently fails, they both fail in PCT compile.
If the error is point to XREF, so there would be possible that a create /tmp/PCTXREF and running compile and b create another /tmp/PCTXREF and overwrite it. 
But why is this PCTXREF just under /tmp folder, not under java.io.tmpdir? We do specify java.io.tmpdir differently for each build.

**Comment by jakejustus** [comment]
The version you're using is several years old, and I don't remember where the PCTXREF was generated (and don't have time to do it now).
The latest versions don't use this file anymore, so it may be a good idea to test the latest version.

**Comment by lakehouse-david** [comment]
Hi, Is there some parameter to specify the PCT tmp folder or to pass the java.io.tmpdir in the pct target?
It seems that that the PCT still uses the /tmp folder while the build.xml get the java.io.tmpdir as /tmp/ENV-NAME

**Comment by lakehouse-david** [comment]
I've search the website that there is a <systemproperty> not sure if it works.

**Comment by jakejustus** [comment]
For the Java part, it's using java.io.tmpdir : https://github.com/jakejustus/pct/blob/master/src/java/com/phenix/pct/PCTRun.java#L94
For the Progress part, that's controlled by the tempDir attribute, which points by default to the $WRKDIR variable defined during installation.

**Comment by lakehouse-david** [comment]
Thanks for your code information, yes, I've checked 
`status = new File(System.getProperty("java.io.tmpdir"), "PCTResult" + statusID + ".out");`
and also pctparam files are created under wrong java.io.tmpdir, seems it not passed into the pct.jar in the build.xml when executing pct target. is there way to set the property in the build.xml in pct target same way as set verbose and Keepxref?

**Comment by jakejustus** [comment]
Add a line <echo message="Temp dir ${java.io.tmpdir}" /> in your build file to verify the value.
And to my mind, you can set the value using `ant -Djava.io.tmpdir=/path/to/directory`

**Comment by lakehouse-david** [comment]
I do an echo in the compile-impl target and get this 

> build 15-Jun-2016 00:14:54    compile-impl:
> build 15-Jun-2016 00:14:54        [mkdir] Skipping /dr01/bamboo/xml-data/build-dir/BAMTST-IBST-BL/tmp/wc2136576154/bl/work/rcode because it already exists.
> **build   15-Jun-2016 00:14:54         [echo] /tmp/BAMTST-IBST-BL/devel**
> build 15-Jun-2016 00:14:54    [PCTCompile] OpenEdge version found : OpenEdge Release 11.3.1 as of Fri Sep 13 19:00:23 EDT 2013
> build 15-Jun-2016 00:14:54    [PCTCompile] Using object : com.phenix.pct.ProgressV11
> build 15-Jun-2016 00:14:54    [PCTCompile] PCTCompile - Progress Code Compiler
> build 15-Jun-2016 00:14:54    [PCTCompile] Current OS is Linux
> build 15-Jun-2016 00:14:54    [PCTCompile] Setting environment variable: DLC=/qad/progress/dlc113164
> build 15-Jun-2016 00:14:54    [PCTCompile] Executing '/qad/progress/dlc113164/bin/_progres' with arguments:
> build 15-Jun-2016 00:14:54    [PCTCompile] '-b'
> build 15-Jun-2016 00:14:54    [PCTCompile] '-q'
> build 15-Jun-2016 00:14:54    [PCTCompile] '-inp'
> build 15-Jun-2016 00:14:54    [PCTCompile] '32000'
> build 15-Jun-2016 00:14:54    [PCTCompile] '-cpinternal'
> build 15-Jun-2016 00:14:54    [PCTCompile] 'utf-8'
> build 15-Jun-2016 00:14:54    [PCTCompile] '-s'
> build 15-Jun-2016 00:14:54    [PCTCompile] '128'
> build 15-Jun-2016 00:14:54    [PCTCompile] '-param'
> **build   15-Jun-2016 00:14:54    [PCTCompile] '/tmp/pct_params57020.txt'**
> build 15-Jun-2016 00:14:54    [PCTCompile] '-p'
> **build   15-Jun-2016 00:14:54    [PCTCompile] '/tmp/pctinit61329.p'**

and the according build.xml is 

  echo message="${java.io.tmpdir}/${user.name}"/>

  PCTCompile destDir="work/rcode" dlcHome="${DLC}" cpInternal="utf-8" inputChars="32000" stackSize="128" verbose="true" keepXref="true">

It seems that the java.io.tmpdir is not passed into the PCTCompile target.

**Comment by jakejustus** [comment]
Yes, that's what I wrote in the previous comment. You have to add tempDir attribute in PCTCompile, otherwise you fall back to the default directory specified during the installation

**Comment by lakehouse-david** [comment]
PCTCompile destDir="work/rcode" dlcHome="${DLC}" cpInternal="utf-8"
            inputChars="32000" stackSize="128" verbose="true" keepXref="true"
            tempDir="${java.io.tmpdir}">
Like this?

**Comment by jakejustus** [comment]
Yes, that should work

**Comment by lakehouse-david** [comment]
build   15-Jun-2016 01:04:28    [PCTCompile] '-param'
build   15-Jun-2016 01:04:28    [PCTCompile] '/tmp/pct_params61812.txt'
build   15-Jun-2016 01:04:28    [PCTCompile] '-T'
build   15-Jun-2016 01:04:28    [PCTCompile] '/tmp/BAMTST-IBST-BL'
build   15-Jun-2016 01:04:28    [PCTCompile] '-p'
build   15-Jun-2016 01:04:28    [PCTCompile] '/tmp/pctinit41720.p'

So the -T means the java.tmp.dir is set? But why the parameter file still under /tmp?
Should I set this to all the other PCT target such as PCTRUN besides PCTCompile?
Because this problem is mainly lies in PCTXREF because its name is not randomly generated, so I want to make sure the PCTXREF will be generated under /tmp/BAMTST-IBST-BL'

**Comment by lakehouse-david** [comment]
Ok, I got PCTXREF under the desired place! So currently I think there shouldn't be PCTXREF conflict during bamboo build. I'll keep them running to see if it works. Thanks for your help

**Comment by jakejustus** [comment]
Please also note that your PCT version is quite old and that you should upgrade as soon as possible !
