### ISSUE TITLE
PCTLibrary doesn't support tempDir like PCTCompile does

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#138]
Our library process generates a very large PL file.  By default, PCTLibrary seems to use /tmp.
If the filesystem is low on space, there is no method for moving the temporary area to somewhere else.
It would be nice to have PCTLibrary support the tempDir value like PCTCompile does.

**Comment by jakejustus** [comment]
You can still run Ant with -Djava.io.tmpdir=/path/to/dir in order to change the temp directory for this process.
