### ISSUE TITLE
Feature Request: Create a chocolatey package for installation of PCT

### ISSUE THREAD

**Issue by schnitty** [Riverside-Software/pct#162]
First off, love your work.  Using your PCT tools along with puppet to automate our deployments.  As such I was wondering if you could create a chocolatey package for PCT to help automate the deployment of environments that use your wonderful tools.

https://github.com/chocolatey/choco/wiki/CreatePackages

I'm happy to give it a crack (create a chocolatey package) for your tools but thought it would be polite to ask you first in case you want to create and control that part of it.

**Comment by jakejustus** [comment]
I don't have plans myself for Chocolatey packages, so feel free to build them !
