### ISSUE TITLE
Unknown or invalid source file specified in COPY-LOB statement. (11345)

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#164]
PCT: v206, ANT: v196, Progress: v11.6.2

When compiling code that has been encrypted, but there are errors in the build, the following error appears in the log:
Unknown or invalid source file specified in COPY-LOB statement. (11345)

Worse for me; no hints are given that the program didn't compile, only the above error and "Failed to compile  1  file(s)".

Is it possible to display the filename that was being attempted when the compile failed?  I realize that no code is returned to the error handler, but there should be something to allow the user looking through the logs to know what files didn't compile.
For example:
"Error compiling file abc.p (encrypted)"

Otherwise, there is no quick way to know what didn't compile:

```
     [echo] Compiling *.w in gui-code:
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Unknown or invalid source file specified in COPY-LOB statement. (11345)
[PCTCompile] 10% 10:51:18 Compiling server/oe/t-oee.w...
[PCTCompile] 20% 10:52:02 Compiling server/sdo/ap/sdo_apei_applycredit.w...
[PCTCompile] 30% 10:52:05 Compiling server/sdo/ap/sdo_apsv_dynamic.w...
[PCTCompile] 40% 10:52:09 Compiling server/sdo/cm/sdo_cmst_act_lu_cl.w...
[PCTCompile] 50% 10:52:12 Compiling server/sdo/ic/sdo_icsef_lu_cl.w...
[PCTCompile] 60% 10:52:14 Compiling server/sdo/pd/sdo_pdsps_lu.w...
[PCTCompile] 70% 10:52:18 Compiling server/sdo/sa/sdo_sasc_lu_cl.w...
[PCTCompile] 80% 10:52:19 Compiling server/sdo/sa/sdo_sasta.w...
[PCTCompile] 90% 10:52:21 Compiling server/sdo/wl/sdo_wlal_lu.w...
[PCTCompile] 100% 10:52:43
[PCTCompile] 272 file(s) compiled
[PCTCompile] Failed to compile  1  file(s)
```

Thanks!

**Comment by jakejustus** [comment]
Could you double-check your PCT version ? Here is the output of one of the unit tests : 

```
test1:
[PCTVersion] PCT Version : jenkins-QA-PCT-206
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Error compiling file /home/gquerret/dev/pct/testbox/PCTCompile/test17/src/xcode/test.p at line 1 column 15
[PCTCompile] ** Unable to understand after -- "'S49Q�4Mx[". (247)
[PCTCompile] ** Unmatched square bracket, or missing expression in subscript. (397)
[PCTCompile] ** /home/gquerret/dev/pct/testbox/PCTCompile/test17/src/xcode/test.p Could not understand line 1. (198)
[PCTCompile] >> Can't display xcoded source /home/gquerret/dev/pct/testbox/PCTCompile/test17/src/xcode/test.p
[PCTCompile]
[PCTCompile] 0 file(s) compiled
[PCTCompile] Failed to compile  1  file(s)
```

Please use the `<PCTVersion />` task in your script.

**Comment by wilddoug** [comment]
Looks like I may be using an old version?  or pre-release?

version:
[PCTVersion] PCT Version : jenkins-QA-PCT-206

**Comment by wilddoug** [comment]
I downloaded a current version of PCT-206 and it does seem to work correctly. I must have an out-of-date version...
Thanks for putting up with me.  :)
