### ISSUE TITLE
Dead link at PCT docu

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/pct#167]
The link to the PUC Challenge presentation from this page here is no longer valid:

"Read requirements here, slides 41 to 45."

I have attached the PDF to this ticket. Can you host the PDF with the wiki pages?

[SmartDox PUG Challenge.pdf](https://github.com/Riverside-Software/pct/files/392036/SmartDox.PUG.Challenge.pdf)

**Comment by jakejustus** [comment]
Fixed !
