### ISSUE TITLE
[SOLVED] XmlDocumentation - task not found

### ISSUE THREAD

**Issue by simondrum** [Riverside-Software/pct#170]
Hi,

I was trying generating doc form my sources and I encountered an issue while using XMLDocumentation.

My build.xml looks like this:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<project name="MyProject" default="build" basedir=".">
<property environment="env" />
 <taskdef resource="PCT.properties" />
 <typedef resource="types.properties" />
 <taskdef resource="extras115.properties" />
 <target name="build" description="Builds source files">
  <mkdir dir="build"/>
  <PCTCompile destDir="build" dlcHome="${env.DLC}">
    <fileset dir="src">
      <include name="*.cls" />
    </fileset>
  </PCTCompile>
  <ClassDocumentation destDir="doc" dlcHome="${env.DLC}">
    <fileset dir="src" includes="**/*.cls" />
      <propath path="scr" />
  </ClassDocumentation>
  <XmlDocumentation sourceDir="doc" destFile="src.xml" dlcHome="${env.DLC}" />
 </target>
</project>
```

When I build everythings goes just fine until the last line.
Then task is undefined and when I check the requirement I don't understand what you mean by:
- OO programmers best friend
- "Initialize OpenEdge Tooling" provides list of classes and members (methods / properties / events)

Thanks for help!

**Comment by jakejustus** [comment]
There should be an error message with a stack trace, please include them in the bug report.

**Comment by simondrum** [comment]
Couldn't find any stack trace:
![image](https://cloud.githubusercontent.com/assets/11162968/17581285/1bf4ad5a-5fa5-11e6-8f95-3902954a5a67.png)

**Comment by gquerret** [comment]
There's a typo in the example. The task name has to be spelled XMLDocumentation and not XmlDocumentation

**Comment by simondrum** [comment]
Ahah, I wasn't expecting something like this! 
Tanks for help!
