### ISSUE TITLE
Files identified for compile output i.e. XML/Json

### ISSUE THREAD

**Issue by paulmowat** [Riverside-Software/pct#173]
Hi,

Is there a way using the pctcompile noCompile or displayFiles options to output this somehow in a structured way so it can be interrogated easily e.g. to a xml or json string/file?

I'm building a automated build/release workflow and would like to identify this information to feed back to our jira instance/release tools as required.

Thanks

Paul

**Comment by jakejustus** [comment]
On holidays, will answer next week

Envoyé de mon téléphone

**Comment by gquerret** [comment]
There's currently no way to customize the output of displayFiles, but it could be a good enhancement request.

**Comment by paulmowat** [comment]
Thanks. I think it would be quite handy.

**Comment by gquerret** [comment]
If you want to do that by yourself, please create a pull request. I can provide some help on how to setup environments and what should be modified.
If you don't want to do the change by yourself, but still want the feature implemented quickly, you can rely on our consulting services ; otherwise, it will be implemented some day, but don't expect it quickly given the current agenda !

**Comment by paulmowat** [comment]
I'll easy give it a go. Some pointers on what would need changed would be a good starting point. Is there notes on setting up a PCT dev environment?

**Comment by gquerret** [comment]
The section 'How to build PCT' in https://github.com/Riverside-Software/pct/wiki/FAQ will give you completely undetailed steps on how to build PCT :-)
File `src/progress/pct/compile.p` is the one to understand first. Then `src/java/com/phenix/PCTCompile.java`
At first glance, I'd add a new parameter or a new possible value for displayFiles attribute, and handle that compile.p

**Comment by gquerret** [comment]
And make sure you add unit tests !

**Comment by paulmowat** [comment]
Thanks. I'll give it a go.

**Comment by gquerret** [comment]
Any progress on this topic ? Or stuck somewhere ?

**Comment by gquerret** [comment]
Any progress ? Ready to open a pull request ?
