### ISSUE TITLE
Startup parameter -checkdbe seems to be ignored in session.pf

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#183]
I'm using PCTCompile with a paramFile.
In the paramFile -checkdbe is set. (check double byte enabled).
But when executing the ant script, it doesn't seem to pick up the -checkdbe...
If I put an error in the pf file, it does fail, so the session.pf file is used somehow.
But for some reason -checkdbe is ignored... any idea?

```
OpenEdge version found : OpenEdge Release 11.6.2.006  as of Mon Jul 25 11:46:25 EDT 2016
Using object : com.phenix.pct.ProgressV113
PCTCompile - Progress Code Compiler
Current OS is Windows 7
Setting environment variable: DLC=C:\Workspace\OpenEdge116\DLC
Executing 'C:\Workspace\OpenEdge116\DLC\bin\_progres.exe' with arguments:
'-pf'
'C:\Workspace\GitRepositories\stomp.git\compile_session.pf'
'-b'
'-q'
'-inp'
'32000'
'-param'
'C:\Users\lievenc\AppData\Local\Temp\pct_params4908.txt'
'-p'
'C:\Users\lievenc\AppData\Local\Temp\pctinit17832.p'

The ' characters around the executable and arguments are
not part of the command.
9 file(s) compiled
```

There should be a WARNING because one file is NOT double byte enabled... (if I check syntax in Eclipse, it gives me the warning).

```
---------------------------
Check Syntax
---------------------------
Syntax check:
** Function SUBSTRING requires "CHARACTER", "RAW", "COLUMN" or "FIXED" for double-byte or multi-byte(UTF8) languages. (3623)
---------------------------
OK   
---------------------------
```
Any idea? I'm in the dark ;-)

I'm not using the latest version of PCT because we had to do some adjustments to support translations (we have kind of implemented a custom workflow for translations).

Kind regards, Lieven

[pct_filesets8947.txt](https://github.com/Riverside-Software/pct/files/580466/pct_filesets8947.txt)
[pct_params4908.txt](https://github.com/Riverside-Software/pct/files/580467/pct_params4908.txt)

[pctinit17832.p.txt](https://github.com/Riverside-Software/pct/files/580468/pctinit17832.p.txt)
[PCTResult24707.out.txt](https://github.com/Riverside-Software/pct/files/580469/PCTResult24707.out.txt)

**Comment by gquerret** [comment]
Depending on your PCT version (not mentioned in your report), but warnings may be written in `.warnings` files within the `.pct` folder. Please note that a bug in AVM prevents warnings to be written when xmlXref is set to true.

**Comment by gquerret** [comment]
It seems there's an issue, as warnings reported by -checkdbe are not tagged as warnings, thus not written to .warnings.

**Comment by lievencardoen** [comment]
Mmm, what we want to do is have a failed build when such a warning is shown.

Is there some kind of workaround for this? 

Can you point me to the code that supresses those warnings?

Lieven

**Comment by gquerret** [comment]
Warnings are handled here:
https://github.com/Riverside-Software/pct/blob/master/src/progress/pct/compile.p#L459

However, modifying PCT to break the build when this warning is encountered is probably a dead-end, as there are little chances this modification will ever go to the master branch.
Moreover, breaking the build might be counter-productive, as this kind of warning just means that the current code doesn't meet your quality standards, not that the product can't be built.

The way to go is probably to use a quality management tool like SonarQube which can nicely report OpenEdge warnings ( like in this example : http://sonar.riverside-software.fr/issues/search#issues=AVhNV341R_eDOBTHYrBT ), and show developers and managers code quality reports.

**Comment by gquerret** [comment]
http://knowledgebase.progress.com/articles/Article/GET-MESSAGE-TYPE-returns-wrong-value-with-checkdbe

**Comment by lievencardoen** [comment]
The exact cause is not known at this time.

Man, the times I had to read this. OpenEdge is a fucked up technology. With
all due respect. ;-)

I'll have a look at it monday at work. If Eclipse shows the warnings, why
can't PCT show it?

**Comment by gquerret** [comment]
True that I've also seen this message too many times...
PCT could display the checkdbe warnings, but I'd have to introduce an ugly check. Would like to see if I can do it in a better way.

**Comment by lievencardoen** [comment]
Well... I would like to have it work in our Jenkins builds. After all
sources have been compiled, I check the log file for certain matches (for
instance the three warnings about checkdbe).

Mmm, maybe I'll first try to upgrade our PCT to the latest version. That'll
be a huge work... I already compared our version from a couple of years ago
with the current version and a lot has changed. So I'm also kind of scared
that all jenkins jobs will need to be re looked at.

**Comment by lievencardoen** [comment]
"However, modifying PCT to break the build when this warning is encountered is probably a dead-end, as there are little chances this modification will ever go to the master branch."

Can't seem to follow you Gilles. I do not want the build to break. I would just want the warnings about checkdbe being logged...

Is that a bug in OpenEdge that they are nog logged (because they are seen as errors) or is it something PCT suppresses? 

Kind regards, L.

**Comment by lievencardoen** [comment]
Hi Gilles,

Now I compile all files, so failOnError is set to false.

Afterwards I parse the log file (a ant recorder logs everything to a file) and check for things like:
- Error compiling file
- Insufficient disk space or Write access denied. (291)
- Unable to load shared library (14945)
- There is no server active for database
- Could not connect to server for database
  ...

Now I would like to add the warnings about checkdbe...

Kind regards, Lieven Cardoen

**Comment by gquerret** [comment]
Warnings are not suppressed by PCT, they're just not displayed if compiler:get-message-type() doesn't return 2 (warning), and this is where the -checkdbe bug lies.
If you have your own branch and don't want to merge with the current master, you may want to change the "if" condition to detect specific error messages for example.

**Comment by lievencardoen** [comment]
Thx! I'll try to update my version to the latest version and then try to
tweak it. I'll also create a support case to know when they will solve it.

**Comment by gquerret** [comment]
Did you get an answer on when they will fix the issue ?

**Comment by lievencardoen** [comment]
From OpenEdge? I have just created an OpenEdge case, so I'll let you know as soon as I can.
In the meantime I still need to upgrade to the latest version of PCT, but that will also take some time.

**Comment by gquerret** [comment]
-checkdbe warnings now reported in .warnings file (which can then be imported in SonarQube)
