### ISSUE TITLE
pctcompile languages issue in jenkins-PCTNewJob-master-4

### ISSUE THREAD

**Issue by djbrown92** [Riverside-Software/pct#184]
We appear to be facing an issue with languages compilations since having moved from PCT Version 0.19-pre - Build 162 to jenkins-PCTNewJob-master-4.

The languages do not appear to have been compiled into programs at all, with the application displaying text in the native language (English) when run in Chinese or English(US) (for example).

We are using Jenkins ver 1.651.3 and OpenEdge Release 10.2B06.

**Comment by gquerret** [comment]
Sorry, but how did you get access to this build ???

**Comment by djbrown92** [comment]
We are using a pre-release build for an OE11 project. I’ve now learned that we have two versions of Ant installed on the same machine, Ant-1.9.4 and now Ant-1.9.4-v11. Our Test-OE11 job is configured to run Ant-1.9.4-v11 and all the others remain set to run the “Default” Ant version. The problem now is that we cannot find where in Jenkins the Default Ant version is specified as it seems like the wrong “default” is being selected. This could be a problem with the path environment variable so we shall keep digging.

**Comment by gquerret** [comment]
But could you still tell me how you got access to this `jenkins-PCTNewJob-master-4` build ? This build server is private, so I'm curious...

**Comment by djbrown92** [comment]
.... via my colleague, Wayne Hanson ;)

**Comment by gquerret** [comment]
Oh, sorry, didn't know you're working there.

**Comment by gquerret** [comment]
Ant installations can be configured through "Manage Jenkins" -> "Global tool configuration"
Then you'll be able to configure multiple Ant versions

**Comment by djbrown92** [comment]
Thank you, Gilles. I think I'm looking in the right place. In our version of Jenkins under Manage Jenkins > Configure System, in the Ant Section we have the two versions of Ant now configured, Ant 1.9.4 first and then below it Ant 1.9.4 V11 Openedge. However, there does not appear to be an option to nominate which of the multiple Ant version should be taken to be the default.

In the meantime, Wayne has altered the 'path' environment variable. We're now waiting for the current builds to finish in order to perform a Jenkins restart (as the change has not taken effect and we suspect we need a restart to pick up this environment variable change.

**Comment by gquerret** [comment]
I don't remember exactly how to set the default (it may just be the first one being defined).
Don't change the system-wide path variable, just define the version to be used per-job.

**Comment by djbrown92** [comment]
I'll keep that option as my last resort - I realise that setting the version per job should work, but the trouble is that I have dozens if not hundreds of jobs to change (still running OE10) - at the moment we only have a single OE11 job which needs to use the newer version of PCT!

**Comment by djbrown92** [comment]
Per-job it may have to be!

**Comment by djbrown92** [comment]
Thank you again for your valuable assistance on this one, Gilles. It is very much appreciated.

We have decided that we will manually set the appropriate Ant version on a per-job basis, to avoid any ambiguity over which version Jenkins considers to be the "default" version.

**Comment by gquerret** [comment]
Please note that if you have many jobs, the easiest way is to directly modify config.xml files in the Jenkins directory on the server.
