### ISSUE TITLE
PCTCompile hangs when compiling a cls file

### ISSUE THREAD

**Issue by markbeynon** [Riverside-Software/pct#190]
Hi,
This is a strange one. This one file (Menus.cls) just hangs the compile process?
Occasionally a protrace is generated which I have attached.
This is on a Windows 7 64bit machine running 32bit OE102.A.05
I've attached all the sources and pasted the section in question below.
Many Thanks,
Mark.
P.S. Please let me know if you need any more info.

[Menus.zip](https://github.com/Riverside-Software/pct/files/619526/Menus.zip)

[protrace.21304.txt](https://github.com/Riverside-Software/pct/files/619482/protrace.21304.txt)
  <PCTCompile destDir="${prop.BUILD_RCODE}" graphicalMode="true" compileUnderscore="true" dlcHome="${prop.DLC}"
       assemblies="${prop.assemblies}" >  
      
    <fileset dir="${SOURCE_PATH}\ris\shearings\util">
      <include name="Menus.cls" />
    </fileset>     
    
    <PCTConnection dbName="${prop.risDB}"   HostName="${prop.host}" logicalName="${prop.logrisDB}"   dbPort="${prop.risPort}" singleUser="${prop.singleUser}"/>
    <PCTConnection dbName="${prop.stbDB}"   HostName="${prop.host}" logicalName="${prop.logstbDB}"   dbPort="${prop.stbPort}" singleUser="${prop.singleUser}"/>
    <PCTConnection dbName="${prop.cacheDB}" HostName="${prop.host}" logicalName="${prop.logcacheDB}" dbPort="${prop.cachePort}" singleUser="${prop.singleUser}"/>
    <propath>
      <pathelement location="${prop.DLC}"/>
      <pathelement location="${SOURCE_PATH}\stb"/>
      <pathelement location="${SOURCE_PATH}\ris"/>
      <pathelement location="${SOURCE_PATH}\alg"/>
      <pathelement location="${SOURCE_PATH}\ris\"/>
    </propath> 
  </PCTCompile>

**Comment by gquerret** [comment]
Thanks for your report. What's the PCT version ?
And does it consistently hangs the process ? Or only once in a time ?
I'm missing the DB schema in order to trigger the build.

**Comment by markbeynon** [comment]
Thanks for the reply. It happens every time the build hits the Menu.cls.
The PCT version, I’m not sure about. What’s the easiest way to determine this?
As for the schema, I’d need to ask our clients if I could pass this along.

**Comment by gquerret** [comment]
You can use `<PCTVersion />` in your build script

**Comment by gquerret** [comment]
And by the way, another missing file is RPC.i. The biggest problem is however 10.2A05. This kind of issue is usually caused by the OpenEdge compiler, not by PCT, and there are no chances at all that Progress would fix anything in 10.2A.
Would you be able to trim the source code until you have something which still crashes and doesn't have too many dependencies ?

**Comment by markbeynon** [comment]
Thanks for the continued interest. I’ll see if I can trim things down. As for 102.A.05, we’re stuck with this for now.

The file in question does compile in Eclipse 10.2A.05 however.

I’m still waiting to hear from our customer to see if I can send you the source code involved and the .df/.st files so you can build the DB’s and do a compile of at least the menus class. However, this is a corporate customer and security concerns may preclude me doing this.

For the moment I have managed a work around for this problem and both myself and our client are impressed with PCT ANT and how it has simplified the build process.

**Comment by markbeynon** [comment]
I’ve managed to identify the code causing the problem in our Menus.cls;

buildMenuBar(theForm)

  CATCH e AS Progress.Lang.Error :
    MessageBox:Error(e:GetMessage(1)).
  END CATCH.
  FINALLY:
    IS_DESKTOP = FALSE.
  END FINALLY.

It’s the CATCH/FINALLY block. I’ve no idea why this code breaks things in the PCT ANT compile but for now I’ve coded around the issue;

  buildMenuBar(theForm) NO-ERROR.

  IF ERROR-STATUS:ERROR THEN
    MessageBox:Error(ERROR-STATUS:GET-MESSAGE(1)).

  IS_DESKTOP = FALSE.

As mentioned previously, the code compiled under 102A Eclipse so it’s a bit of a strange one really!

Many Thanks again for your help and input,

**Comment by gquerret** [comment]
Do you have the rcode created in the build directory ?

**Comment by markbeynon** [comment]
Yes, the compilation works fine.

Are you asking for a copy of the rcode?

**Comment by gquerret** [comment]
I probably wasn't clear ; when compilation hangs, do you have rcode for this specific file created ? Just interested to know if this comes from the compiler, or from XREF parsing (which occurs after rcode is created).

**Comment by markbeynon** [comment]
No, there’s no Menu.r file.

**Comment by gquerret** [comment]
Then I'll close the issue, it comes from the compiler, and there's unfortunately nothing I can do. And you found a workaround.

**Comment by markbeynon** [comment]
No problem. Thanks for your interest in this ☺
