### ISSUE TITLE
Warnings not appearing in the compile log?

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#202]
Using Progress OpenEdge 11.6.3 32bit in Windows 2012R2.
Using PCT v206 and ANT v196.

Recently in PDSOE, I noticed a warning when checking syntax in a program that hadn't changed on weeks/months.  So I started to wonder why the warning wasn't in my nightly build.  Naturally, I assumed I broke something ...

Compile errors have always worked in this build, but now it appears warnings are being swallowed, or ignored. And maybe they always have?

I've looked through the PCT source code and found that they should be getting written to a .warnings file, but I cannot find any files with that extension in my build area, and none of the warnings are appearing in the final logs that I'm generating.

How can I see the warnings that are being generated during PCT?

The PCTCompile:
  <PCTCompile tempDir="${tempdir}" dlcHome="${env.DLC}" destDir="${crcodedir}"  
              maximumMemory="65534" stackSize="2048" token="8000" inputChars="32000" 
              compileUnderscore="yes" languages="${pctLang}" keepXref="${debugxref}" xmlXref="true" 
              streamIO="yes" cpinternal="1252" cpstream="1252"
              debugPCT="${debugComp}" runList="yes" failOnError="no" numThreads="${env.THREADS}"
              relativePaths="yes" 
              >

**Comment by gquerret** [comment]
I think there's a missing part in your message.
Warnings are not displayed in PCTCompile output (and never were IIRC), as they are generated in .warnings files. There's unfortunately a bug in the `COMPILE` statement when using `XML-XREF`, as warnings are not raised by the compiler.
If you see .warnings files when using `xmlXref=false`, then you're just hit by this bug.

**Comment by wilddoug** [comment]
The only time the .warnings file doesn't appear is when xmlXref="true".  When this option is set to false, the .warnings file is generated.
I'll have to think about how to fix this in our builds... Maybe Saturday runs will have xmlXref="false" so that I can collect any .warnings files.
I appreciate the information, and I'll have to figure out the best to collect these files.
Thanks!

**Comment by gquerret** [comment]
11.7 is likely to include a fix for this issue.
Please also note that .warnings files can be imported into [SonarQube](https://github.com/Riverside-Software/sonar-openedge) ; if you already have automated your builds, starting the analysis with SQ is a matter of minutes.
