### ISSUE TITLE
ClassDocumentation: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ioanadan** [Riverside-Software/pct#203]
I'm unable to generate my class documentation ( `java.lang.NoSuchMethodError: com.openedge.pdt.core.ast.ProgressLexer.setExpandIncludes(Z)V`)

I'm using PCT version 206 , OpenEdge 11.6.3. I've added ast.jar and ast-dependencies.jar in PCT.properties.

![image](https://cloud.githubusercontent.com/assets/17637618/22371920/c189f7f2-e4a2-11e6-864d-51b3cba6a9e1.png)

# Results:
![image](https://cloud.githubusercontent.com/assets/17637618/22371689/1e934680-e4a1-11e6-938d-53fedab79949.png)

**Comment by gquerret** [comment]
How did you declare the ClassDocumentation task ? When using 11.5+, you have to use a different `<taskdef>` tag, see [documentation](https://github.com/Riverside-Software/pct/wiki/ClassDocumentation#from-115-and-above)

From your log file, you're using the task for OE 11.3

**Comment by gquerret** [comment]
Were you able to make it work ?

**Comment by ioanadan** [comment]
I've changed and I've declared it now as <taskdef resource="extras115.properties" >
it looks better

![image](https://cloud.githubusercontent.com/assets/17637618/22501003/7777056c-e86f-11e6-9521-650484f7fbf3.png)

but I still receive :
[ClassDocumentation] Generating XML documentation (11.5+ method)

BUILD FAILED
C:\Users\IDa_wf\git\swat-backend\ClassDocumentation\build.xml:43: The following error occurred while executing this line:
C:\Users\IDa_wf\git\swat-backend\ClassDocumentation\build.xml:51: java.lang.NullPointerException

Tested with a simple class, only one method added and comment block defined as in your documentation (I've tested also with an empty class, no methods and still i receive this error)

**Comment by gquerret** [comment]
Given the line number, it looks like a bug in the parser. Can you attach the sample procedure ?

**Comment by ioanadan** [comment]
Attached you have the sample procedure:
[RecordHdlHelper.cls.txt](https://github.com/Riverside-Software/pct/files/766661/RecordHdlHelper.cls.txt)

**Comment by gquerret** [comment]
Given your sample procedure (almost empty one), it's not possible that the ClassDocumentation fails if the requirements are met, as there are unit tests for this kind of simple problems (and more complex ones).
So please make sure that you're really using ast.jar from 11.6.3, that you're using the latest PCT version, and that there are no ast.jar somewhere in ANT_HOME/lib for example.

**Comment by gquerret** [comment]
Expecting to be fixed
