### ISSUE TITLE
-q parameter causes memory corruption when executing ABLUnit task

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/pct#204]
I use PCT ABLUnit task to execute relatively large suite of unit tests (actually integration tests). 
I encounter some kind of memory corruption, manifesting itself with `Usecount of the segment is <= 0 (14347)` warning messages and prowin32 finally crashing with `DoneSegment encountered a corrupted text segment`. I have an opened support case at Progress for this issue and was unable to isolate the problem. 

The test suite executes flawlessly when ran from OpenEdge Studio. The difference is the -q execution parameter (`Use Quick Request (-q) to tell the AVM to search PROPATH directories only on the first use of a procedure`.)

This parameter is automatically added, along with -b, for every PCTRun inherited task, when the batch mode flag is on.

Would it be feasible to have an option on the PCTRun/ABLUnit task to not set this parameter? 

Thanks

**Comment by gquerret** [comment]
Could you verify that with a custom PCT build ? Build instructions are in the FAQ ; Java code setting the `-q` parameter is in GenericExecuteOptions.java, just comment this line and rebuild PCT.

I'd like to verify that it works before introducing this change.

**Comment by maelstraggiotti** [comment]
I have commented out ` list.add("-q"); ` and the crash doesn't occurs anymore. Not elegant, but working...

Merci

**Comment by gquerret** [comment]
The way I'll resolve it will be to add an attribute quickRequest which can be set to false to remove the -q in the command line. Will be done in the coming weeks.
By the way, is there an entry in the Progress KB for this problem ?

**Comment by maelstraggiotti** [comment]
Great, thank you.

[Here is the KB entry](http://knowledgebase.progress.com/articles/Article/abl-integration-test-execution-crashes-with-exception-code-e0000003) for my support case, along with [this one](http://knowledgebase.progress.com/articles/Article/P157516) which seems related.

**Comment by gquerret** [comment]
Merged in master
