### ISSUE TITLE
Case sensitivity when compiling

### ISSUE THREAD

**Issue by markbeynon** [Riverside-Software/pct#210]
Hi,

Is it possible to get a compile to fail in PCT ANT under Windows when there are case mismatches in filenames?

Thanks.

**Comment by gquerret** [comment]
Which case are you specifically interested in ? Class names which don't match the file name ?

**Comment by markbeynon** [comment]
Class files or .p files, so…

Run myfile.p.

But the file’s name on disc is MyFile.p

Currently, this does not fail compilation on Windows.

Thanks.

**Comment by wilddoug** [comment]
In my limited experience, I need both a windows and a linux build to confirm includes, etc are cased correctly.  :\
And these do not catch run-time errors, only compile-time errors.

**Comment by gquerret** [comment]
It won't be possible to have the compilation fail on Windows, that's not the point of PCT. However, class name casing is already a rule in the OpenEdge plugin for SonarQube, see [this rule description](http://sonar.riverside-software.fr/coding_rules#rule_key=rssw-oe-main%3Aeu.rssw.antlr.proparse.checks.ClassNameCasing).

Another rule could be created for incorrect file names in `RUN` statements.

**Comment by markbeynon** [comment]
Ok, thanks for looking at this.
