### ISSUE TITLE
PCTCompile doesn't create warning

### ISSUE THREAD

**Issue by Hanna19** [Riverside-Software/pct#211]
PCT-207 won't report the warning 4027 as compiler does:
```
define var vChar as char format "x(6)" no-undo.
form  vChar at 75 with frame a no-box width 80 no-labels no-attr-space.
```
The below code will report the warning 4027:
```
define var vChar as char format "x(7)" no-undo.
form  vChar at 75 with frame a no-box width 80 no-labels no-attr-space.
```

**Comment by stefandrissen** [comment]
Are you setting the graphicalMode attribute on pct:compile?

When your example is compiled with the character client (_progres.exe) your first example also does not throw a warning and the second does. While with the graphical client (prowin.exe) your first example also throws a warning.

**Comment by gquerret** [comment]
Thanks @stefandrissen, it also seems to me that warnings are generated correctly, and that it only comes from graphicalMode attribute.

**Comment by Hanna19** [comment]
I agree, thank you Stefan and Gilles.
