### ISSUE TITLE
ClassDoc missing support for SERIALIZABLE and USE-WIDGET-POOL

### ISSUE THREAD

**Issue by PeterJudgeZA** [Riverside-Software/pct#215]
The SERIALIZABLE token appears on the CLASS statement as well as various members (as of 11.6 https://documentation.progress.com/output/ua/OpenEdge_latest/gspub/serializing-classes-to-binary-and-json-formats.html# ).

The USE-WIDGET-POOL token appears on the CLASS statement.

There are no %XXX% subtitution tokens available for these tokens in the HTML doc.  These tokens are both avialable in ABLDoc (which I assume means that they're in the AST already).

**Comment by gquerret** [comment]
Were those options added in 11.6 ? If so, this means that the runtime dependency will be on ast.jar from 11.6.

**Comment by PeterJudgeZA** [comment]
11.6 added SERIALIZABLE on members.
11.4 added SERIALIZABLE on the class statement

The USE-WIDGET-POOL modifier was there in at least 10.2B (and I suspect from day 1).

**Comment by gquerret** [comment]
Fixed in EnumClassDoc branch without changing the runtime requirement.

**Comment by mikefechner** [comment]
Did you change the ABL code of the class doc?

**Comment by gquerret** [comment]
No

**Comment by mikefechner** [comment]
Why is USE-WIDGET-POOL relevant in the class doc? Isn't that an implementation detail? Not sure if that's part of the interface to a class that's worth documenting.

**Comment by gquerret** [comment]
That's for @PeterJudge-PSC

**Comment by mikefechner** [comment]
Implemented the ABL side of this based on 

```[PCTVersion] PCT Version : pct-208.pre-PR-189-a60de4e39decc69da94e8bdc7af569f73d350aa3```

I have added two new place holders in the Document.template:

- @UNITSERIALIZABLE@ 
- @USEWIDGETPOOL@

e.g.:

```
<tr>
    <td>
        <span class="span_inherits">@UNITFINAL@ @UNITABSTRACT@ @UNITSERIALIZABLE@ @USEWIDGETPOOL@</span>
    </td>
    <td>
    </td>
</tr>
```

I expect to provide the PCT version of the code mid May.

**Comment by gquerret** [comment]
Excellent, thanks !
