### ISSUE TITLE
Cannot suppress warning 15090 

### ISSUE THREAD

**Issue by Hanna19** [Riverside-Software/pct#216]
Hi,
I am trying within PCTCompile (PCT-207.jar) to suppress warning 15090, with no success. 
I tried 2 methods within DBConnection:
1.	`<Option name="-swl" value="d:/workspace/settings/SuppressWarn" />`
2.	`<paramfile="d:/workspace/settings/startup.pf" />`

SuppressWarn file lists 15090 warning.
startup.pf has a line `-swl D:\workspace\settings\SuppressWarn`

None of them seems work.
Is it a right way to suppress a warning? 
Hanna

**Comment by gquerret** [comment]
You're right, the `-swl` attribute is not taken into account by the COMPILER handle. Could you please report this issue to Progress ?

As a side note, why would you want to remove this useful warning ?

**Comment by gquerret** [comment]
And second side note, I doubt there's a single good reason to hard code this kind of path

**Comment by cverbiest** [comment]
Known issue http://knowledgebase.progress.com/articles/Article/000036535

**Comment by gquerret** [comment]
Interestingly enough, it was possible to use SESSION:SUPPRESS-WARNINGS-LIST to discard unwanted warnings.
Merged in master
