### ISSUE TITLE
Is it possible to get support back on PCTASBroker & PCTWSBroker?

### ISSUE THREAD

**Issue by Fasaani** [Riverside-Software/pct#220]
Hi,
We were planning to update our PCT version 192 to newer maybe 207 version, but found out that support on PCTASBroker and PCTWSBroker have been removed, so is it possible to get it back? 
We have been using those at least 5 years. It would help us a lot. 

Thanks.

**Comment by gquerret** [comment]
PCTASBroker and WSBroker were removed a year ago for two reasons:
* First, we almost never get any feedback on those tasks in many years, and not using them myself directly or indiretly, my guess was that nobody was using those tasks. You proved me wrong 😞 
* Then, a small refactor of PCTRun broke the way PCTASBroker and PCTWSBroker were working. It was easier to remove those tasks than doing the refactor for them.
I can have if it's possible to bring them back again, but that won't happen really soon. If you feel you can do it, feel free to open a pull request, that will be integrated without any problem !

**Comment by stefandrissen** [comment]
For some reason I was (luckily) not aware of these tasks and create brokers (appserver & webspeed) 'manually' with an exec of mergeprop.bat feeding it a delta - this is not nice cross platformwise.

Based on what I am seeing in https://github.com/Riverside-Software/pct/blob/v202/src/java/com/phenix/pct/PCTASBroker.java and https://github.com/Riverside-Software/pct/blob/v202/src/java/com/phenix/pct/PCTBroker.java the old tasks were only able to create / update / delete brokers and not stop / start / trim them (ie a wrapper for asbman / wtbman). 

It would also be nice if asbman / wtbman (and dbman) were under control of PCT.

As an additional point of attention, I am not sure how the PASOE appservers / webspeed things are handled - you /may/ want to consider that too.

**Comment by gquerret** [comment]
Those tasks are back in branch Issue220 (almost untouched) ; tests are OK on my workstation, but not on the CI server as mergeprop has an issue with directory names used by Jenkins pipelines.
Will be merged in master soon

**Comment by gquerret** [comment]
@stefandrissen I don't plan to implement asbman / wtbman / dbman in PCT as I don't want to invest time in those "legacy" components

**Comment by gquerret** [comment]
Merged in master
