### ISSUE TITLE
Problems with java style comments when generating class documentation

### ISSUE THREAD

**Issue by Ton-Pe** [Riverside-Software/pct#224]
Java style comments // are sometimes causing problems when generating xml files for class documentation. In some cases if I have // comments just before class definition, the xml file is not generated at all. I have included two example files for that. SessionActivator.cls is working and xml file is generated. For SessionActivator2.cls the xml file is not generated. Only difference I see, is the style of comments.
 
In another case, using // comments inside the methods can cause some methods not to be generated into xml-file. I have included HybridRealm.cls where are two methods. First method has comments in // style. When I generate the xml file, the second method, ValidatePassword, in not generated into xml file (I have included the class and xml file). If I remove those comment lines, ValidatePassword method is generated into xml.
 
What makes this even more weird is that I still have some files where I do have // comments and xml-file is generated ok. 
 
I'm using
PCT Version : pct-207-master-daf7eeaeb8310f3ee4e863656b6dc95b8abccec7
Progress version 11.6.3

[pct-problem.zip](https://github.com/Riverside-Software/pct/files/889649/pct-problem.zip)

**Comment by gquerret** [comment]
Two different issues, both reproduced in branch Issue224:
* First one is that single line comments break naming of class file, leading to file name `null.xml`
* Second one is that it seems that single quotes are interpreted within comments when they obviously shouldn't be

Will have a look at how the parser can be controlled here.

**Comment by gquerret** [comment]
Fixed in branch EnumClassDoc, which already contains several changes on the class documentation. This branch is likely to be merged in a month approximately.
