### ISSUE TITLE
PCTCompile Fill-In errors

### ISSUE THREAD

**Issue by Razack0684** [Riverside-Software/pct#226]
I am using PCTCompile on unix machine to compile CHUI application.  I am getting errors like the one below.

```
PCTCompile] Error compiling file XXXX.p at line 0 column 0
[PCTCompile] /* **************************************************************************************************************** */
[PCTCompile] -^
[PCTCompile] ** Warning: Cannot fit FILL-IN prt-count with TO within FRAME prt-dtl. (4027)
[PCTCompile] Warning: Ignoring position info for TO (2054)
[PCTCompile] ** Warning: Cannot fit FILL-IN prt-amount with TO within FRAME prt-dtl. (4027)
[PCTCompile] Warning: Ignoring position info for TO (2054)
[PCTCompile] ** Warning: Cannot fit FILL-IN prt-book-per with TO within FRAME prt-dtl. (4027)
[PCTCompile] Warning: Ignoring position info for TO (2054)
[PCTCompile] ** Warning: Cannot fit FILL-IN w_period_desc with AT within FRAME b. (4027)
```

I am able to compile the same program with procedure editor. Below pasted is the pctcompile configuration.

     <PCTCompile  destDir="." stopOnError="False" MD5="True" forceCompile="True" progPerc="10" runList="True" >
       <fileset refid="compileunits"/>
	   <DBConnectionSet refid="dbset" />
	  <propath>
		<pathelement path="${CRDIRROOT}/${CRENV}/Code/cr"/>
		<pathelement path="${CRDIRROOT}/${CRENV}/Code/cr/custom"/>
	  </propath>	   
     </PCTCompile>

Regards,
Razack

**Comment by gquerret** [comment]
Use `graphicalMode="false"` to compile with _progres.

**Comment by Razack0684** [comment]
Hi Gilles

I though by default graphicalmode is false. However I set false explicitly and still getting the fill-in errors

Regards 
Razack

**Comment by gquerret** [comment]
Then just make sure you're using the same configuration in both environment. Or try compiling your code with a standard _progres session, with only propath and DB connection set (as that's what's included in your PCTCompile node)

**Comment by Razack0684** [comment]
If I use standard _progres session I get the same error

**Comment by gquerret** [comment]
Then you just have to find the difference between the standard session and the dev environment where you compile files

**Comment by Razack0684** [comment]
Is it possible to specify not to use -b switch when using PCTcompile ?

**Comment by gquerret** [comment]
No, -b is always set in PCT tasks. AFAIK, it shouldn't prevent anything from being compiled correctly. On top of my head, the only one is when using `&IF {&batch-mode}`
