### ISSUE TITLE
Dataset Parameter mode not always returned by classdocumentation Task

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/pct#231]
I have two methods in a business entity:

```
    /**
     * Purpose: Performs a Password change for a user in the _User table
     * Notes:
     * @param dsUser INPUT-OUTPUT DATASET, not used
     * @param poParameter The AuthenticationParameter with the parameter for this method
     */
    METHOD PUBLIC VOID ChangeDatabasePassword (INPUT-OUTPUT DATASET dsUser,
                                               poParameter AS ChangePasswordParameter):
```
and
```
    /**
     * Purpose:  Fetch data from the Data Access object
     * Notes:
     * @param poFetchDataRequest The IFetchDataRequest object with the parameters for this call
     * @param dsUser The dataset, intended to by passed BY-REFERENCE
     */
    METHOD PUBLIC FINAL VOID FetchDataByReference (poFetchDataRequest AS Consultingwerk.OERA.IFetchDataRequest,
                                                   OUTPUT DATASET dsUser):
```

However, only the FetchDataByReference shows a parameter mode:

```
    <method methodName="ChangeDatabasePassword" signature="ChangeDatabasePassword(INPUT-OUTPUT:dataset,INPUT:ChangePasswordParameter)" modifier="PUBLIC" isStatic="false" isFinal="false" isAbstract="false">
        <methodComment>/**&#xD;
     * Purpose: Performs a Password change for a user in the _User table&#xD;
     * Notes:&#xD;
     * @param dsUser INPUT-OUTPUT DATASET, not used&#xD;
     * @param poParameter The AuthenticationParameter with the parameter for this method&#xD;
     */</methodComment>
        <parameter name="dsUser" dataType="DATASET" position="4"/>
        <parameter name="poParameter" dataType="ChangePasswordParameter" position="5" mode="INPUT"/>
    </method>
```
while
```
    <method methodName="FetchDataByReference" signature="FetchDataByReference(INPUT:Consultingwerk.OERA.IFetchDataRequest,OUTPUT:dataset)" modifier="PUBLIC" isStatic="false" isFinal="true" isAbstract="false">
        <methodComment>/**&#xD;
     * Purpose:  Fetch data from the Data Access object&#xD;
     * Notes:&#xD;
     * @param poFetchDataRequest The IFetchDataRequest object with the parameters for this call&#xD;
     * @param dsUser The dataset, intended to by passed BY-REFERENCE&#xD;
     */</methodComment>
        <parameter name="poFetchDataRequest" dataType="Consultingwerk.OERA.IFetchDataRequest" position="8" mode="INPUT"/>
        <parameter name="dsUser" dataType="DATASET" position="9" mode="OUTPUT"/>
    </method>
```

**Comment by gquerret** [comment]
Only dsUser in the ChangeDatabasePassword method doesn't show the mode attribute.
I'll check if that's specific to INPUT-OUTPUT parameters

**Comment by gquerret** [comment]
Is that on the latest EnumClassDoc branch ?

**Comment by gquerret** [comment]
Can't reproduce on the EnumClassDoc branch right now.

**Comment by mikefechner** [comment]
The one that’s including the temp-table’s. The one that I downloaded from your website yesterday.

**Comment by gquerret** [comment]
Does that still happen with the latest version ?

**Comment by mikefechner** [comment]
It still happens with 208. Yes. We can look into that next week.

**Comment by gquerret** [comment]
Still valid ?

**Comment by mikefechner** [comment]
There was no formal release after 208 yet, correct? In which version do you want me to test this?

**Comment by gquerret** [comment]
209 pre 2, latest one available on the website

**Comment by dvandoorn** [comment]
Hi Gilles,

Mike asked me to test it and it looks like it's still there.
[classdoc.zip](https://github.com/Riverside-Software/pct/files/1883091/classdoc.zip)

BR Daniel

**Comment by gquerret** [comment]
Works for me: ![image](https://user-images.githubusercontent.com/6498723/38426229-62df26e0-39b6-11e8-8a20-38d5ffdce6e3.png)

Do you use ast.jar from 11.3 or from 11.7 ?

**Comment by gquerret** [comment]
@dvandoorn Previous comment was for you

**Comment by dvandoorn** [comment]
Hi Gilles,

OpenEdge Release 11.7.2 as of Tue Oct 24 19:02:01 EDT 2017

%ANT_HOME%\bin\ant -f build.xml -lib C:/Progress/OpenEdge117/java/ant-libs/ast.jar -lib C:/Progress/OpenEdge117/java/ant-libs/ast-dependencies.jar

BR Daniel

**Comment by gquerret** [comment]
@mikefechner @dvandoorn 
Nice, ID changed again in this version of the parser. Time to switch to a good parser.

Not a lot I can do here, except from updating to make it work with 11.7.2, but that will break the behavior with former versions. You're the one behind the documentation, do you want it for 11.7.2 ?

**Comment by mikefechner** [comment]
If my word counts, we should support it for the most recent OE release.

**Comment by gquerret** [comment]
Upgraded API to 11.7.2

**Comment by gquerret** [comment]
Merged in master

**Comment by dvandoorn** [comment]
Hi Gilles,

Is there a jar file available?

BR Daniel

**Comment by gquerret** [comment]
I've pushed it to https://dl.rssw.eu/PCT.jar

**Comment by dvandoorn** [comment]
Thanks!
