### ISSUE TITLE
RelativePath in PCTCompile has no effect

### ISSUE THREAD

**Issue by ghost** [Riverside-Software/pct#232]
When compiling with PCTComple, the File Path displayed in logfile is absolute, although that the RelativePath property is set to "true"

**Comment by gquerret** [comment]
RelativePath attribute currently only changes the way `COMPILE` is being executed (with an absolute or relative path). This has an impact on the debug segment, and especially on the include file names in this segment.
Agree it would be better to also display relative path names in case of error.

**Comment by gquerret** [comment]
Fixed in master
