### ISSUE TITLE
PCTCompile doesn't support the "noCompile" attribute

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#237]
https://github.com/Riverside-Software/pct/wiki/PCTCompile documents a noCompile parameter but it is not recognized by PCTCompile version 208

```log
Buildfile: build.xml

build:
[PCTVersion] PCT Version : pct-208-master-87b954be01663bf64f7b435edb02afdd6b4044fa

BUILD FAILED
/home/proadmin/build.xml:13: PCTCompile doesn't support the "noCompile" attribute
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<project name="Nocompile development" default="build" >

    <property environment="env" />
    <property name="DLC" value="/usr/dlc" />
    <property name="cpstream" value="utf-8" />

    <taskdef resource="PCT.properties" />
    <typedef resource="types.properties" />

    <target name="build" >
        <PCTVersion />
        <PCTCompile destDir="build" dlcHome="${DLC}" noCompile="true" >
          <fileset dir="src">
            <include name="**/*.p"/>
            <exclude name="test/**"/>
          </fileset>
          <propath>
            <pathelement path="src/include"/>
          </propath>
        </PCTCompile>
    </target>

</project>
```

**Comment by gquerret** [comment]
That's right, the noCompile attribute has been dropped. Documentation has been updated.

**Comment by gquerret** [comment]
Was that an attribute you were using previously ?

**Comment by cverbiest** [comment]
Was not using it but I had a possible use case for it. Delete outdated rcode before compile.

**Comment by gquerret** [comment]
> Delete outdated rcode before compile.

Could you add a bit more to that ?
PCTCompile should recompile outdated code, except for classes (issue #62). But I'd prefer spending time on this issue rather than re-adding noCompile.

**Comment by cverbiest** [comment]
I have a linux script to delete old rcode and was looking for pct way of achieving the same. The advantage of deleting is that a developer can start using the application before the compile is ready. I agree fixing #62 is more important though

**Comment by gquerret** [comment]
Not likely to be implemented soon.
