### ISSUE TITLE
Schema documentation - warning on SET-ATTRIBUTE

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/pct#244]
Reported by @mikefechner

Message appears when generating schema documentation (PCTSchemaDoc task)
``` 
[PCTSchemaDoc] **The SET-ATTRIBUTE attribute on the X-NODEREF widget has invalid arguments. (4065)
```
File is still generated

**Comment by gquerret** [comment]
In your case, coming from `MIN-VALUE` attribute which is not set on a sequence.
Will tag as won't fix.

**Comment by mikefechner** [comment]
OK - maybe you should file that as a known limitation on your wiki. Others may have sequences with a min value of ? as well. IMHO min value makes only sense for rotating sequences.

**Comment by gquerret** [comment]
The sequence is created, and attribute minValue is not present. So there's no limitation here.
