### ISSUE TITLE
HtmlDocumentation task error with TEMP-TABLE LIKE and SERIALIZE keywords

### ISSUE THREAD

**Issue by maelstraggiotti** [Riverside-Software/pct#251]
Using DLC 11.6.3, PCT 208, ast jars from [](https://github.com/Riverside-Software/pct/raw/master/lib/), I encounter the following exceptions : 

When a TEMP-TABLE LIKE is defined : 
```
 <temp-table name="tt" like="Table" definition="" noUndo="true">
```
```
An Consultingwerk.Exceptions.Exception has occured:
The buffer eTempTable has no field named like.
```

or when SERIALIZE is set : 
```
<temp-table name="tt" serialize="TableName">
```
```
An Consultingwerk.Exceptions.Exception has occured:
The buffer eTempTable has no field named serialize.
```

Thanks

**Comment by gquerret** [comment]
Already fixed in e7c6d82d674edc40e299735acd0201bdd989d6fc
You can use this [pre-release](https://github.com/Riverside-Software/pct/releases/tag/v209-pre1) if you don't want to compile by yourself
