### ISSUE TITLE
Java error when running ClassDocumentation

### ISSUE THREAD

**Issue by andreipopa121** [Riverside-Software/pct#252]
Hello,
I have attached a text file containing the error outputted when using the ClassDocumentation task.
And here is the ant script that I am using:
```
<target name="GenerateClassXML">
  <mkdir dir="${params.documentation.path}" />
  <delete dir="${params.documentation.path}" includes="**/*.xml" />
  <ClassDocumentation destDir="${params.documentation.path}" dlcHome="${dlc.path}">
    <fileset dir="${params.precprocess.path}" includes="**/*.cls" />
    <propath>
      <pathelement location="${params.precprocess.path}" />
    </propath>
  </ClassDocumentation>
</target>
```

I'm not sure what could be causing this problem.
Thanks!

[DocumentationGenerator.txt](https://github.com/Riverside-Software/pct/files/1172570/DocumentationGenerator.txt)

**Comment by spazzymoto** [comment]
Hey,
Would it be possible to turn run you build.xml with "ant -verbose" and send the output? Is it generating a few files before crashing? Or crashing immediately?

Also which version of PCT are you using?

**Comment by andreipopa121** [comment]
Hi,
It generates what I presume is the first the first class' documentation which is empty so it doesn't successfully generate any file.
The PCT version I am using is 'pct-208-master-87b954be01663bf64f7b435edb02afdd6b4044fa'.
Running the script with the verbose command, I get the following information in the console for GenerateClassXML:
<pre>
GenerateClassXML:
    [mkdir] Skipping C:\Users\APo_wf\git\common\setup\classdoc\smartcomponentlibrary because it already exists.
   [delete] DEPRECATED - Use of the implicit FileSet is deprecated.  Use a nested fileset element instead.
[ClassDocumentation] OpenEdge version found : OpenEdge Release 11.7.1 as of Wed Jun 14 19:02:15 EDT 2017
[ClassDocumentation] Using object : com.phenix.pct.ProgressV117
[ClassDocumentation] Generating XML documentation (11.5+ method)
[ClassDocumentation] Generating AST for C:\Users\APo_wf\git\common\setup\preprocessed\smartcomponentlibrary\Ccs\BusinessLogic\CommitScopeEnum.cls
[ClassDocumentation] Executing AST ClassVisitor C:\Users\APo_wf\git\common\setup\preprocessed\smartcomponentlibrary\Ccs\BusinessLogic\CommitScopeEnum.cls
  [antcall] Exiting C:\Users\APo_wf\git\common\setup\doc_gen.xml.
</pre>

**Comment by gquerret** [comment]
Could you have a look at #165 ? Same error message, so the same answer will probably be the right one !
