### ISSUE TITLE
LANGUAGES option not honored when XCODE option used

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#256]
We have Spanish and French data imported into XL_ tables for translation.

When using both the XCODE and the LANGAUGES options during PCTCompile, the translation data doesn't end up in the rcode.
Looking at the code for pct/compile.p, at appears that changing the compile at approx line 380-390 and adding the LANGUAGES option would fix the issue:
```
  IF (lXCode AND XCodeKey NE ?) THEN
    COMPILE
      VALUE(IF lRelative THEN ipInFile ELSE ipInDir + '/':U + ipInFile)
      SAVE = SaveR INTO VALUE(cSaveDir)
      STREAM-IO=streamIO
      V6FRAME=lV6Frame
      MIN-SIZE=MinSize
      GENERATE-MD5=MD5
      LANGUAGES (VALUE(languages))
      XCODE XCodeKey
      NO-ERROR.
```

When in an editor, the following code gets the translation data into the rcode:
compile p/sarse.p xcode "R&D" languages("es,french") save into /dv/work/

So, I think this fix is correct.
If the variable "languages" isn't loaded, the compile statement:
compile p/sarse.p xcode "R&D" languages(?) save into /dv/work/
  still loads the default strings into the rcode.

I'm in the middle of testing this change in a test area.

**Comment by gquerret** [comment]
Would you be able to open a pull request ?

**Comment by wilddoug** [comment]
Sadly, I do not know how to... Or I do not have access to?  I'll keep trying and reading up on it.

**Comment by gquerret** [comment]
You just have to commit the source and push it to your fork.

**Comment by gquerret** [comment]
Fixed in master
