### ISSUE TITLE
PCTCompile preprocess argument value ignored

### ISSUE THREAD

**Issue by andreipopa121** [Riverside-Software/pct#257]
Hi,

When running PCTCompile with the preprocess and preprocessDir parameters, the preprocess files are created even if preprocess is set to false.

This are the test cases that I have run:
1. preprocess = false; preprocessDir not specified => no preprocess files are generated
2. preprocess = true; preprocessDir not specified => preprocess files are generated in the pct folder
3. preprocess = false; preprocess specified => preprocess files are generated in the specified path
4. preprocess = true; preprocess specified => preprocess files are generated in the specified path

The problem is at test case 3, where I expect no preprocess files to be generated.

Best regards,
Andrei

**Comment by andreipopa121** [comment]
I took a look at the source code (PCTCompile.java) and it seems that if the preprocessDir is set, preprocess is automatically considered to be true (line 298-304).
Is there any way to use a single PCTCompile task which would generate or not the preprocess files based on a property?
I tried assigning the empty string, but it only started generating the preprocess files in the same folder with the script.

As a code change, this could be done by changing CompilationAttributes.java's setPreprocessDir method (line 118 - 122):
```
    @Override
    public void setPreprocessDir(File dir) {
        this.preprocessDir = dir;
    }
```
I haven't tested this myself but it's what I think might solve the issue.

**Comment by gquerret** [comment]
Can you open a pull request ?

**Comment by andreipopa121** [comment]
Yes I can, but I will need to set up my local environment first (recently did a clean install).

**Comment by gquerret** [comment]
I'm in fact relunctant to do this change, as this will break the existing behavior, and I'll probably get a ticket soon asking why this was changed. Workaround in your case is to use a <condition> task to set (or not) the property depending on the boolean value of 'preprocess'.
