### ISSUE TITLE
-assemblies is added even if the PCTCompile assemblies parameter is empty

### ISSUE THREAD

**Issue by andreipopa121** [Riverside-Software/pct#258]
Hi,

In issue #68, there was a request that -assemblies to not be added if the specified value cannot be found.
This was implemented and made available in PCT build #188 but seems to not be working anymore.
If I run PCTCompile with assemblies="" on Linux, I get the following error:
```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] -assemblies is not supported by this executable. (1610)
[PCTCompile] Result: 2
```
Best regards,
Andrei

**Comment by gquerret** [comment]
You're right, that could be improved, the value also has to be non-empty.

**Comment by andreipopa121** [comment]
Ah, so the feature is available, but not for an empty value!
Just tested and as soon as I provided a non-existing path, -assemblies was not added and the project was successfully compiled on Linux.
But, indeed, it would be better if the empty string was also handled.
Thank you!

**Comment by gquerret** [comment]
Fixed in master
