### ISSUE TITLE
ProgressVersion arch is always returning as "32bit" for both 32bit and 64bit installations

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#264]
I have OpenEdge 11.7.1 32bit installed in c:\oe_32\117 and 64bit installed in c:\oe_64\117.
Both of these will output 'arch' as a '32bits'.

XML:
```xml
  <ProgressVersion dlcHome="${env.DLC}" fullVersion="full" arch="arch" />
  <echo message="${full}; ${arch} [installed in ${env.DLC}]" />
```
Example output for each version:
     [echo] OpenEdge Release 11.7.1 as of Wed Jun 14 19:02:16 EDT 2017; 32 bits [installed in c:\oe_32\117]
     [echo] OpenEdge Release 11.7.1.002  as of Fri Jul 28 04:33:40 EDT 2017; 32 bits [installed in c:\oe_64\117]

OpenEdge clients prowin and prowin32 return the correct values using:
    `message process-architecture view-as alert-box.`

(This is also a bug using OpenEdge 11.6.3 installations.)

**Comment by stefandrissen** [comment]
``arch`` reports the architecture of the JVM running Ant - which is 32-bit in both cases.

**Comment by wilddoug** [comment]
For JAVA_HOME, I'm using %DLC%\jdk for both tests.
When I issue the command:
> c:\oe_64\117\jdk\bin\java.exe -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

From this, it appears the JVM is 64bit for the 11.7.1 64bit installation.

While using the 32bit installation, I get:
> c:\oe_32\117\jdk\bin\java.exe -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode)

From this, it appears that the JVM for the 32bit installation is not 64bit.


I'm not saying you are wrong, but I am admitting I'm confused.

**Comment by stefandrissen** [comment]
I'm sorry - I completely missed that arch is supposed to be set by PCT - I thought it was the os.arch.

But... on that note - is arch perhaps already set before the ProgressVersion task?

And an extra addition: it seems that DLCVersion.java is checking the bitness of tty/prostart.r (with RCodeInfo.java) and possibly r-code no longer contains a bitness since it was unified again in 11.x?

Both my 10.2Bx64 and 11.6x64 prostart.r files contain the MAGIC2 sequence, but my 32 bit 10.2B does not (also not MAGIC1)... over to the experts :-)

**Comment by gquerret** [comment]
> And an extra addition: it seems that DLCVersion.java is checking the bitness of tty/prostart.r (with RCodeInfo.java) and possibly r-code no longer contains a bitness since it was unified again in 11.x?

arch attribute was used internally in the pre-v11 world to extract the right PL from the JAR file (pct-v10-64.pl for 64 bits install, pct-v10.pl for 32 bits install). This is done by extracting the rcode version number of tty/prostart.r. 64 bits version have a bit set to 1 (0x4000)
As there's no rcode difference since v11, this attribute isn't used anymore (and not tested in the unit tests).

Do you have a specific need for this attribute ?

**Comment by gquerret** [comment]
> Both my 10.2Bx64 and 11.6x64 prostart.r files contain the MAGIC2 sequence, but my 32 bit 10.2B does not (also not MAGIC1)... over to the experts :-)

MAGIC1 and MAGIC2 are the magic numbers (first 4 bytes of the file) in big-endian and little-endian

**Comment by stefandrissen** [comment]
@gquerret Yes, my finding was that the 10.2B 32-bit prostart.r (windows) had neither magic1 nor magic2 - which surprised me since this would result in an error being thrown.

**Comment by gquerret** [comment]
@stefandrissen Are you sure? Here's the output of the 10.2B08 32 bits on both Windows:
```
λ xxd prostart.r | head -2
00000000: 09d3 ce56 fbac 4950 4400 0000 38ff ed03  ...V..IPD...8...
00000010: 0000 0000 0000 0000 0000 0000 0000 5800  ..............X.
```
and Linux:
```
$xxd prostart.r | head -2
00000000: 09d3 ce56 41ca 8252 4000 0000 38ff ed03  ...VA..R@...8...
00000010: 0000 0000 0000 0000 0000 0000 0000 5800  ..............X.
```

I think that would prevent PCT from starting if rcode is not read correctly. Reading the content of this file was the only option working on every platform available, and with consistent result.

**Comment by stefandrissen** [comment]
@gquerret 

![image](https://user-images.githubusercontent.com/5297464/30203902-002bb9e6-9484-11e7-9d58-7b114c001cde.png)

The 10.2B gui prostart.r has the same signature.

As does the 10.1C 32-bit prostart.r

The 10.0B 32-bit prostart.r **does** contain the expected signature. 10.0B was also the last version that supported unified r-code (prior to it being repaired in 11.2)

**Comment by gquerret** [comment]
@stefandrissen Did you already try to execute PCT with this version. tty/prostart.r is read as soon as you start a PCT task, and PCT will throw a BuildException if the magic number is not found.

**Comment by stefandrissen** [comment]
@gquerret 

````
	<target name="test" description="test">

		<pct:progress_version dlcHome="\\nl000fs01\alldata\dlc\oe10.2b" fullversion="full32" arch="arch32" />
      <pct:progress_version dlcHome="\\nl000fs01\alldata\dlc\oe10.2b.x64" fullversion="full64" arch="arch64" />
		<echo message="${full32}; ${arch32}" />
      <echo message="${full64}; ${arch64}" />

	</target>
````
Results in:
````
     [echo] OpenEdge Release 10.2B08 as of Tue Nov 12 19:06:41 EST 2013; 32 bits
     [echo] OpenEdge Release 10.2B08 as of Tue Nov 12 19:08:07 EST 2013; 64 bits
````
So the files must be ok, so I had another look at prostart.r - it seems Notepad++ is trying to be smart about something when opening the file and corrupting it. If I use powershell:

``get-content \\nl000fs01\alldata\dlc\oe10.2b\tty\prostart.r -Encoding byte | more`` 

then it returns the expected magic:

````
9
211
206
86
````

**Comment by wilddoug** [comment]
Honestly, it isn't something I 'need', no.
I was just logging more information, so that when there were compile issues, I could have a user send my a few logs and determine everything about the environment that I care about.

**Comment by gquerret** [comment]
I don't think there's a 100% reliable way to know if OE is 32 or 64 bits, without starting the OE process itself. That's the reason why I had to rely on reading rcode... Something to ask to Progress.
In the mean time, you can use $os.arch to display the bitness of the **JVM**

**Comment by wilddoug** [comment]
I'm ok with cancelling the issue.

**Comment by gquerret** [comment]
The `arch` attribute doesn't work as expected, it's just I don't know a cross-platform and reliable way to make it work under v11.
The first solution is to remove the attribute (in fact not making it public), the second one to fix it. The first one is easier :-)

**Comment by stefandrissen** [comment]
How about checking for the presence of a bin and bin32 directory in the dlc folder?

**Comment by gquerret** [comment]
I'm almost sure my 11.7 Win install is 64 bits, but I don't have a bin32 folder.

**Comment by stefandrissen** [comment]
Sry - was off the top of my head. Looking at 11.5 vs 11.5 x64 - on windows there is prowin.exe and prow.dll vs prowin32.exe and prow32.dll

I only have x64 Linux installs so can't help there.

Are there maybe tell-tale marks in the jre / jdk folders that could indicate bitness?

**Comment by gquerret** [comment]
Re-reading this issue after a while. I think I'll remove the `arch` attribute, as an easy workaround would be to execute this procedure:
```
def output param dlcArch as char.
assign dlcArch = string(process-architecture).
return '0'.
```
in a PCTRun task:
```xml
<PCTRun procedure="xxx.p">
  <OutputParameter name="arch" />
</PCTRun>
<echo message="Arch: ${arch}" />
```

**Comment by wilddoug** [comment]
Agreed.  That is essentially what I ended up doing.

**Comment by gquerret** [comment]
Property removed, documentation updated.
