### ISSUE TITLE
Improve xcode task performance

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/pct#266]
It seems that the PCT xcode tasks invokes xcode for every file. xcode can however process a set of files, either passed on the command line or passed via stdin (- parameter)

http://knowledgebase.progress.com/articles/Article/P147079

"The dash (-) option tells XCODE to take filenames from the standard input. On UNIX, this allows you pipe output from an ls, cat, or find command to XCODE."

**Comment by gquerret** [comment]
Quick test shows a difference on a 10k files codebase (windows):
* 3 min 30 when xcode is started for each file
* 20 seconds when passing files on standard input

Interesting performance improvement, but not high on the priority list :)

**Comment by gquerret** [comment]
Build available at https://jenkins.rssw.eu/job/PCTNewJob/job/feature%252FPCT-293-MTCompilation/

**Comment by mikefechner** [comment]
In our build workspace, xcode took 23 minutes before and 7 seconds now. That's a huge improvement. Windows.  Sample before is from a number of different builds.

**Comment by gquerret** [comment]
That seems too good to be true. Can you verify you really have the xcoded files ?

**Comment by mikefechner** [comment]
Looking at the build result ... I'd say yes!

**Comment by gquerret** [comment]
I didn't give you the right link. You should download this version : https://jenkins.rssw.eu/job/PCTNewJob/job/PCT-266-XCode/

The link I've sent previously doesn't even include the xcode task modification.

**Comment by mikefechner** [comment]
I have used 

[PCTVersion] PCT Version : pct-209.pre-PCT-266-XCode-3ad4cd699892cfe2ead65955efb456e3c973dce2

**Comment by gquerret** [comment]
So you tested the right version, the commit ID is the expected one.
I was just testing your observation skills, see if you were able to notice the branch was incorrect 😀

**Comment by gquerret** [comment]
Merged in master
