### ISSUE TITLE
pct:compile limit numThreads to number of available cores

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#269]
To increase the compile speed on our local machines I added numThreads="4" - this works great. However certain (virtual) machines are limited to 2 cores. The compile jobs now choke these machines.

Instead of adding extra properties or manual checks on the number of cores this /could/ be easily solved by limiting numThreads to the minimum of the provided parameter and:

````
Runtime.getRuntime().availableProcessors();
````

**Comment by bulagump** [comment]
I think I would rather see a new feature that handles numThreads="Auto", rather than overriding the users request.

**Comment by gquerret** [comment]
I'm not fond of overriding the provided attribute, but there's no *easy* way to get the number of cores as an Ant property. 
Getting this number of cores from Ant and being able to manipulate it easily would be the best idea.

**Comment by gquerret** [comment]
To be more specific, I'm just afraid that once this get implement in PCT, somebody else will ask for a limit on the number of concurrent builds, or whatever criteria they have in their environment.
Keeping this kind of computation in the build.xml file but outside of PCT will be a better idea.
Even the 'auto' value is probably not a good idea as there will be many different cases where auto won't be just the number of cores.

**Comment by cverbiest** [comment]
This may help https://stackoverflow.com/questions/1170337/how-can-i-get-the-number-of-availableprocessors-in-ant

**Comment by stefandrissen** [comment]
Thanks Carl, That SO thread is where I got the Java property from. A simple minimum( cores, input ) is just too much pain in Ant and so simple in any normal programming language which is why I offered this suggestion.

**Comment by gquerret** [comment]
This should be directly available in Ant, probably something to ask directly on Ant ML or worth opening a pull request.
