### ISSUE TITLE
PCTCreateBase fails on 11.7.1 32-bit - IDataDefinitionLoader not found.

### ISSUE THREAD

**Issue by danielbecroft** [Riverside-Software/pct#271]
Running a PCTCreateBase command on 11.7.1 32-bit (Windows) fails with the following message:

```
     [echo] OpenEdge Release 11.7.1 as of Wed Jun 14 19:02:16 EDT 2017
[PCTCreateBase] Generating redacted structure
[PCTCreateBase] Copying DB c:\Progress\DLC117\empty8 to redacted
[PCTCreateBase] Loading redacted.df in database
[PCTCreateBase] ** "OpenEdge.DataAdmin.Binding.IDataDefinitionLoader" was not found. (293)
```

The same build file works correctly under 11.7.1 64-bit (on the same machine). The PROPATH for both environments contains the same core procedure libraries. 

I can also create/load a database manually using prodb and the Data Administration window.

**Comment by stefandrissen** [comment]
I do not have a 32-bit 11.7.1 available, is OpenEdge/DataAdmin/Binding/DataDefinitionLoader.r in your DataAdmin.pl?
````
prolib %DLC%\gui\DataAdmin.pl -list
prolib %DLC%\tty\DataAdmin.pl -list
````
I /think/ the DataAdmin.pl is only used by OpenEdge Explorer, whereas Data Administration uses the legacy code.

**Comment by danielbecroft** [comment]
Thanks @stefandrissen. It turns out that our installation of the 32-bit and 64-bit versions was _slightly_ different. The 32-bit version didn't have the Data Administration component installed. We've reinstalled with that component, and it all works now.

**Comment by gquerret** [comment]
Thanks @stefandrissen for having solved the issue (and @BeakerAU for confirmation) !
