### ISSUE TITLE
No option for USE-REVVIDEO

### ISSUE THREAD

**Issue by strachpr01** [Riverside-Software/pct#273]
I can see an option for v6FRAME however I cannot use the above option too?
Taken from [here](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvref/compile-statement.html)

> By default, V6FRAME displays a border around a fill-in field. This means that your code requires more space on the screen than in Progress Version 6. You can override this behavior with one of the following options:
> - USE-REVVIDEO displays no border around a fill-in field. When a fill-in is enabled for input, the color of the fill-in changes to the color specified with the INPUT setting in the [Colors] section in the current environment (which might be the registry or an initialization file). The IBEAM cursor signals that a fill-in field has input focus.

> - USE-UNDERLINE displays no border around a fill-in widget. When a fill-in is enabled for input, the underline attribute of the font (V6FontNumber) for the fill-in is turned on. The color of a fill-in enabled for input does not change. The IBEAM cursor signals that a fill-in field has input focus.

**Comment by gquerret** [comment]
Those options are not available right now. That's probably not a lot of work if you want to dig in the PCT code (and I can provide help there...). It's just I'm unlikely to work on it in a near future due to time constraints.

**Comment by strachpr01** [comment]
I have made some changes to the compile.p that will allow the USE-REVVIDEO and USE-UNDERLINE to work however I receive the following while running. Is there somewhere else I need to make changes?
> build.xml:157: PCTCompile doesn't support the "USEREVVIDEO" attribute

Thanks,
Peter

**Comment by gquerret** [comment]
Yes, code has to be added to declare the attributes in Ant.
At least writeParams() in PCTCompile.java and declare attribute + getter/setter in CompilationAttributes.java

**Comment by gquerret** [comment]
Were you able to add your custom code in PCT ? Would you be able to open a pull request ?

**Comment by strachpr01** [comment]
Yes I added my custom code, and got it to compile, however the option did not work. I still need to investigate why.

**Comment by gquerret** [comment]
Please fork the repository and push code there. I'll then be able to help you.

**Comment by strachpr01** [comment]
Will do, bare with me, I am a first time GitHub user.

**Comment by gquerret** [comment]
Merged in master
