### ISSUE TITLE
*.inc files not generated correctly with DOS end of line

### ISSUE THREAD

**Issue by ckonstantin** [Riverside-Software/pct#275]
*.inc files not generated correctly with DOS end of line. 

With DOS end of line *.inc file generated:
```
"""ns_crmDynamicFieldsInput.i" ?
```

With UNIX end of line *.inc file generated:
```
"ns_crmDynamicFieldsInput.i" "pct/src/oe/ns_crmDynamicFieldsInput.i"
```

File which was compiled:
`{ns_crmDynamicFieldsInput.i
  " "
  "HIDDEN"
}`

**Comment by gquerret** [comment]
If I understood correctly what you sent in your separate email, you're using include files with DOS EOL on Linux?

**Comment by ckonstantin** [comment]
During *.p module compilation with DOS EOL on Linux *.inc file is generated incorrectly.

**Comment by gquerret** [comment]
So that's more or less expected. The line format used by XREF doesn't play nicely with EOL coming from another system.  So either use XML XREF (which should be handle EOL correctly), or have the right EOL type for your platform.
