### ISSUE TITLE
Publish PCT to a maven repo

### ISSUE THREAD

**Issue by gimoh** [Riverside-Software/pct#276]
Could PCT be published to a maven-type repository like [Maven Central](http://central.sonatype.org/) or [JCenter](https://bintray.com/bintray/jcenter)?

The reason for the request is that it would make it much easier to consume PCT from [Gradle](https://gradle.org/) which has fantastic [integration with Ant](https://docs.gradle.org/current/userguide/ant.html) and allows writing jobs using an easy to use Groovy-based DSL.

There is also an early but functional Gradle plugin called [grabl](https://gitlab.com/grabl/grabl) which tries to provide some integration for Gradle-based projects, but is currently using hacks to make Gradle automatically download PCT.

Consuming directly from GitHub Releases is not possible due to lack of metadata (POM files listing dependencies, etc.) and some issues to do with how releases are hosted (using S3 Signed URLs, which means HEAD requests need a different URL).

AFAICT publishing to Central / JCenter should be doable using [Apache Ivy](http://ant.apache.org/ivy/) (e.g. [see here](https://www.jfrog.com/confluence/display/RTF/Working+with+Ivy)) if you wanted to integrate with Ant build, or another option could be to use Gradle to wrap the Ant build and do publishing from it.

**Comment by gquerret** [comment]
> Could PCT be published to a maven-type repository like Maven Central or JCenter?

Pushing to bintray can be done. Is there any specific regarding the repository type so that it can be integrated to Gradle ? 

> There is also an early but functional Gradle plugin called grabl which tries to provide some integration for Gradle-based projects, but is currently using hacks to make Gradle automatically download PCT.

Interesting plugin, is it yours ?

**Comment by gquerret** [comment]
@gimoh  Any update on my previous comment ?

**Comment by gquerret** [comment]
No update, closing.
