### ISSUE TITLE
PCTCompile make destDir an optional parameter

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#277]
The progress compiler does not require a destination directory.
PCTCompile makes it mandatory.

Specifying an into directory causes rcode to be compiled into depending projects. 
```propath = "a/src,b/src,c/src".
compile ./a/src/a/a.cls save .
compile ./b/src/b/b.cls save .
compile ./c/src/c/c.cls save .
```
yields the desired results
```
./a/src/a/a.r
./b/src/b/b.r
./c/src/c/c.r
```

but
```
propath = "a/src,b/src,c/src".
compile ./a/src/a/a.cls save into ./a/src.
compile ./b/src/b/b.cls save into ./b/src.
compile ./c/src/c/c.cls save into ./c/src.
```
results in
```
./a/src/a/a.r
./b/src/a/a.r
./b/src/b/b.r
./c/src/a/a.r
./c/src/b/b.r
./c/src/c/c.r
```
6 rcode files for 3 cls sources. see also https://community.progress.com/community_groups/products_enhancements/i/openedge/add_dont-compile-hierarchy_option_to_compiler.

Currently PCTCompile does not allow the first form of the compile statement.

**Comment by cverbiest** [comment]
Fixed in https://github.com/Riverside-Software/pct/pull/278
Tried to do it with minimal changes to original code .

Don't know how to turn tests/PCTCompile/test65/build.xml into a real test. It should validate exactly 3 rcode files are created.

**Comment by gquerret** [comment]
You can create the test case in src/test/com/phenix/pct/PCTCompileTest.java
PR are tested on my Jenkins instance, I will let you know if the tests were successful.

**Comment by kbdnr** [comment]
also seeing some output mismatches on cls compilation.

```
<PCTCompileExt destDir="build/sysclass" stopOnError="StopForError" graphicalMode="true" displayFiles="1">
  <DBConnection refid="testdb1" />
  <propath>
    <pathelement location="." />
    <pathelement location="./connect" />
    <pathelement location="./sysclass" />
  </propath>
  <fileset dir="./sysclass" includes="**/*.p,**/*.P,**/*.w,**/*.W,**/*.cls,**/*.CLS" />
</PCTCompileExt>
```

creates build/sysclass and correctly places appropriate folders.  .r files are being incorrectly put in build/sysclass/sysclass - and being recompiled each build for 'missing r file' due to location discrepancy with .pct crcs

**Comment by gquerret** [comment]
@kbdnr Would you be able to submit a test case for your issue ? i.e. your build file + just a few .cls file so that I can execute locally.

**Comment by gquerret** [comment]
Merged in master, thanks Carl !
