### ISSUE TITLE
pct:ablunit fails with error "REPLACE/CONCAT may not result in data > 32000 bytes. (11678)"

### ISSUE THREAD

**Issue by vsinkievic** [Riverside-Software/pct#285]
### Subject of the issue
pct:ablunit fails with error "REPLACE/CONCAT may not result in data > 32000 bytes. (11678)"

### Your environment
Windows 10
OpenEdge Release 11.6.4 as of Mon Oct 23 11:21:54 EDT 2017
ANT version: Apache Ant(TM) version 1.8.4 compiled on May 22 2012
PCT Version : pct-208-master-87b954be01663bf64f7b435edb02afdd6b4044fa

### Actual behaviour
If project has many tests ABLUNIT tests are not run because of error:
[pct:ablunit] REPLACE/CONCAT may not result in data > 32000 bytes. (11678)
[pct:ablunit] QUIT statement found

### Expected behaviour
It is expected to execute all tests despite of the count and length of test names.

### Steps to reproduce
Create many AblUnit tests with long test names. Total length of test method names must be > 32000 characters. Execute the script. Script will fail before executing tests.

**Comment by gquerret** [comment]
Could you include your ABLUnit task definition from your build.xml, and the approximate number of unit tests ?

**Comment by vsinkievic** [comment]
I attached demo project. Run build.xml target test and you will see the fail. If you will rename any test method to be shorter by 1 char - tests will be executed.

**Comment by gquerret** [comment]
Download link doesn't work

**Comment by vsinkievic** [comment]
[pct_ablunit_bug.zip](https://github.com/Riverside-Software/pct/files/1615900/pct_ablunit_bug.zip)

**Comment by gquerret** [comment]
Reproduced, thanks for the test case. This seems to come from ABLUnit source code, not from the Ant task, so I'm not sure if that's something which could be fixed in PCT. I'll have a look.

**Comment by gquerret** [comment]
This comes from ABLUnit code, so it has to be reported to PSC.
