### ISSUE TITLE
<mapper type="flatten" /> not working as expected

### ISSUE THREAD

**Issue by markbeynon** [Riverside-Software/pct#286]
### Subject of the issue
The mapper type "flatten" works but also copies across the source code to the dest directory and also creates the src file structure

### Your environment
Windows 10 Pro 64 bit
OE102b.08
ANT Version;1.9.6
* PCT version; not sure how to get this. Modified date on PCT.jar is 09/01/2018

### Actual behaviour
Mapper=flatten does not work correctly. Original src sructure is reporoduced for rcode dest dir and original sources are copied across too.

### Expected behaviour
RCODE in dest should be flattened, with no src dir structure and no src code (*/p, *.w) in the dest rcode dir.

### Steps to reproduce
    <echo message="Building ${prop.build-name} Admin package" />
	<PCTCompile destDir="${prop.BUILD_RCODE}" forceCompile="${prop.forceCompile}"
	                                          MD5="${prop.mD5}"
	                                          assemblies="${prop.assemblies}"
	                                          xcode="${prop.xcode}"
	                                          noParse="${prop.noParse}"
	                                          displayFiles="${prop.displayFiles}"
	                                          graphicalMode="true"
	                                          dlcHome="${prop.DLC}"
	                                          tempDir="${prop.temp}"
	                                          progPerc="${prop.progPerc}"
	                                          stackSize="${prop.stackSize}"
	                                          stopOnError="${prop.stopOnError}">
      <DBConnectionSet refid="buildDbSet" />
      <fileset dir="${SOURCE_PATH}\com\mycompany\${prop.build-name}\admin">
        <include name="**/*.p"/>
        <exclude name="**/BulkUserDelete.p"/>
      </fileset>
      <propath>
        <pathelement location="${prop.DLC}" />
      </propath>
	  <mapper type="flatten" />
    </PCTCompile>

**Comment by gquerret** [comment]
The fact that source code is copied makes me wonder if this comes from the PCTCompile task as source code is never copied as part of this task. Could you double check your build ?

**Comment by gquerret** [comment]
@markbeynon Did you see the previous comment ?

**Comment by markbeynon** [comment]
Hi,
I've not got this to work but have managed to code around the issue.
Thanks,
Mark.

**Comment by gquerret** [comment]
Thanks
