### ISSUE TITLE
Is HTMLDocumentation and XMLDocumentation supported in linux

### ISSUE THREAD

**Issue by sdobbey** [Riverside-Software/pct#287]
HTMLDocumentation is not generated in Linux

* Operating system and version: Linux
* OpenEdge version: 11.7.3
* Ant version: 1.9.8
* PCT version: 208

### Actual behaviour
Throw following exception for invalid handle in linux while generating HTMLDocumentation
```
[HTMLDocumentation] Source Directory: /scratch/sdobbey/tdriver1/lx/pcthtmldoc/build
[HTMLDocumentation] Target Directory: /scratch/sdobbey/tdriver1/lx/pcthtmldoc
[HTMLDocumentation] Template Source:  /tmp/Templates2389
[HTMLDocumentation] Resource Source:  ?
[HTMLDocumentation] Custom Services:  ?
[HTMLDocumentation] GenerateTreeViewOverview:  yes
[HTMLDocumentation]
[HTMLDocumentation] Invalid handle for object System.Environment, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089. (12870)
[HTMLDocumentation] Static instance failed to load. Cannot reference class Consultingwerk.Environment. (14631)
[HTMLDocumentation] Return value : 1

BUILD FAILED
/scratch/sdobbey/tdriver1/lx/pcthtmldoc/build.xml:38: Return code : 1
        at com.phenix.pct.PCTRun.execute(PCTRun.java:452)
        at eu.rssw.pct.oedoc.OpenEdgeHTMLDocumentation.execute(OpenEdgeHTMLDocumentation.java:132)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

It is same in the case of XMLDocumentation

### Expected behaviour
Should generate html documentation for given abl files

**Comment by gquerret** [comment]
HTMLDocumentation and XMLDocumentation both rely on .Net assemblies, and can only be run on Windows.
You can try the [ABLDuck](https://github.com/Riverside-Software/pct/wiki/ABLDuck) task available in [this release](https://github.com/Riverside-Software/pct/releases/tag/v209-pre2)

**Comment by NerdFan** [comment]
Just got same issue with latest PCT.
If "only running under Windows" still valid then why not to put this important information to Wiki page and save some hours of investigation?

**Comment by gquerret** [comment]
@NerdFan Documentation has been updated.
