### ISSUE TITLE
ClassDocumentation fail if destDir not exist

### ISSUE THREAD

**Issue by Mazenrab** [Riverside-Software/pct#290]
Maybe this is expected behavior, but it seems to be an error

ClassDocumentation fail if destDir not exist.

      <ClassDocumentation destDir="dd">
         <fileset dir="${dirs.preprocess}" includes="**/*.cls" />
         <propath path="${dirs.preprocess}" />
      </ClassDocumentation>

`
...
java.io.FileNotFoundException: C:\...\dd\rt.Domain.Mail.AutoHtmlMailMessage.xml (The system cannot find the path specified)`

This does not correspond to the behavior of PCTCompile for exampe (it makes directories if not exists).
My workaround:  make dir before ClassDocumentation.

      <mkdir dir="dd"/>

### Your environment
Windows 7 64-bit
OpenEdge Release 11.6.3 as of Thu Sep  8 19:01:50 EDT 2016
PCT Version : pct-209.pre-master-ddf84dc0aafa977eda214a49b1944d5290d80cf9

### Expected behaviour
I think right way is create dir if not exist.

**Comment by Mazenrab** [comment]
**HTMLDocumentation** also

**Comment by gquerret** [comment]
Something to be improved, low priority.

**Comment by gquerret** [comment]
Fixed in master
