### ISSUE TITLE
HTMLDocumentation encoding problems

### ISSUE THREAD

**Issue by Mazenrab** [Riverside-Software/pct#291]
### Subject of the issue
**HTMLDocumentation** generate html with incorrect encoding for sources with сyrillic characters in documentation (see attached files).  Sources are in UTF-8.

![01](https://user-images.githubusercontent.com/33509675/36851290-f79bfe92-1d79-11e8-8949-e1cba9c7aeef.png)
![02](https://user-images.githubusercontent.com/33509675/36851322-07cdf054-1d7a-11e8-9a59-10665cc806cd.png)

### Your environment
Windows 7 64-bit
OpenEdge Release 11.6.3 as of Thu Sep 8 19:01:50 EDT 2016
PCT Version : pct-209.pre-master-ddf84dc0aafa977eda214a49b1944d5290d80cf9

**Comment by Mazenrab** [comment]
This is xml output and html output for with class.
[XmlAndHtml.zip](https://github.com/Riverside-Software/pct/files/1771625/XmlAndHtml.zip)

**Comment by gquerret** [comment]
You're right, the `encoding` attribute is not handled at all in ClassDocumentation task. I'll have a look

**Comment by gquerret** [comment]
Please note that ClassDocumentation defaults to `file.encoding` for the encoding. This means that you can define the environment variable ANT_OPTS like:
```
set ANT_OPTS=-Dfile.encoding=utf-8
```
before executing your script.

HtmlDocumentation should support cpStream attributes, but feel free to report any issue.

**Comment by Mazenrab** [comment]
I checked results twice,  but nope, it doesn't help, html file with and without this option is absolutely identical (except timestamp of course).

This is right way to set environment  variable?

![03](https://user-images.githubusercontent.com/33509675/36893327-af32bf66-1e18-11e8-9780-b3ec5bf9009d.png)

And if you don't mind, I have one more question about documentation - it's possible to make docs for *.p, *.w , *.i  ? By file header for example.

**Comment by gquerret** [comment]
ANT_OPTS is not read from Eclipse, that's only for the command line.
IIRC, you have to use the "Properties" tab, as file.encoding is Java property

**Comment by gquerret** [comment]
> And if you don't mind, I have one more question about documentation - it's possible to make docs for *.p, *.w , *.i ? By file header for example.

ClassDocumentation task use filesets, so you specify extension.

**Comment by Mazenrab** [comment]
> Please note that ClassDocumentation defaults to file.encoding for the encoding. This means that you can define the environment variable ANT_OPTS ...

I tried but this didn't work for me :(

**Comment by gquerret** [comment]
Could you try executing the class documentation task with the command-line version ?

**Comment by Mazenrab** [comment]
Maybe I did something wrong again, but result of HTMLDocumentation task is same.
I did this steps:
1) create system environment variable ANT_OPTS, set value -Dfile.encoding=utf-8
2) check system variable from command prompt

```
c:\oearchitect\coord1_1>echo %ANT_OPTS%
-Dfile.encoding=utf-8
```
3) run build scrit from command propt (looks terrible, i know)

```
c:\oearchitect\coord1_1>c:\DLC116\oeide\eclipse\plugins\org.apache.ant_1.8.4.v201303080030\bin\ant.bat -buildfile build.xml htmldoc -lib c:\utils\ssd\progress\pct\PCT.jar -lib c:\DLC116\oeide\eclipse\plugins\com.progress.openedge.pdt.abldoc.core_11.6.3.00\lib\ast-dependencies.jar -lib c:\DLC116\oeide\eclipse\plugins\com.progress.openedge.pdt.abldoc.core_11.6.3.00\lib\ast.jar
```

**Comment by gquerret** [comment]
Add the following line in your build.xml before the ClassDocumentation:
```
<echo message="Encoding: ${file.encoding}" />
```
I've always been able to specify encoding with this property in my tests.

**Comment by Mazenrab** [comment]
```
	<target name="htmldoc" depends="version,compile" description="Build html documentattion...">
		<echo message="Encoding: ${file.encoding}" />
		<mkdir dir="${dirs.dumpdoc}"/>      
		<ClassDocumentation destDir="${dirs.dumpdoc}">
                   <fileset dir="${dirs.preprocess}" includes="**/*.cls" />
                  <propath path="${dirs.preprocess}" />
               </ClassDocumentation>
               <mkdir dir="html"/>
              <HTMLDocumentation sourceDir="${dirs.dumpdoc}" destDir="${dirs.htmldoc}" />
	</target>

```

Output:

```
htmldoc:
     [echo] Encoding: utf-8
    [mkdir] Created dir: C:\oearchitect\coord1_1\dumpdoc
[ClassDocumentation] Generating XML documentation (11.5+ method)
    [mkdir] Created dir: C:\oearchitect\coord1_1\html
[HTMLDocumentation] Generating HTML documentation for C:\oearchitect\coord1_1\dumpdoc
```
Output XML-file generated by ClassDocumentation is ok. Cyrilic symbols is fine. But HTMLDocumentation output is broken.

**Comment by gquerret** [comment]
Documentation is wrong, HTMLDocumentation task inherits from PCTRun, not just from PCT. This means that you can use `cpInternal="utf-8" cpStream="utf-8"`. This is probably enough to solve the issue (sorry, no time to test it now)

**Comment by Mazenrab** [comment]
You mean I can write cp* attributes in HTMLDocumentation ? 
```
<HTMLDocumentation sourceDir="${dirs.dumpdoc}" destDir="${dirs.htmldoc}" cpInternal="utf-8" cpStream="utf-8" cpColl="Basic" cpCase="Basic" />
```
I tested that right now - no changes.

**Comment by gquerret** [comment]
What's the content of your HTML file ? Had a quick look at generated HTML file of unit tests, anything outside of ASCII is represented as an html entity (such as `&#233;` for &#233; )

**Comment by Mazenrab** [comment]
OMG it seems I've wasted your time.
HTML is not so bad as i showed on screenshot of first message, my browser is not switched to unicode! I'm so sorry.

In fact HTML looks almost normal. But part of symbols in uppercase. And you are right, HTML content contains html-entities. But not all symbols converted to entities. 

Source string:
`Можно отправить с помощью MailQueue.`
converted to this:
```
&#1052;&#1086;ж&#1085;&#1086; &#1086;&#1090;&#1055;ра&#1074;&#1080;&#1090;ь &#1089;&#1055;&#1086;&#1052;&#1086;&#1097;ью MailQueue.
```
part of cyrilic symbols converted to html-entities, part represented as is.

![04](https://user-images.githubusercontent.com/33509675/37351252-b1608e68-26eb-11e8-9582-15b125fa6854.png)

**Comment by gquerret** [comment]
Interesting, I end up with something a bit different, so I suspect it may come from the OE version:
```
Можно отправить с поМощью
```
And with the following entities:
```
&#1052;&#1086;&#1078;&#1085;&#1086; &#1086;тправить с п&#1086;&#1052;&#1086;щью
```
I don't really have time for that right now, but you may want to have a look at the source code of the HTML Documentation task, in src/progress/Consultingwerk directory.

**Comment by gquerret** [comment]
@Mazenrab Did you have a look at the HTML documentation code ?

**Comment by Mazenrab** [comment]
@gquerret Hi, yes. I found bug i think. I think it also maybe interesting for @mikefechner
The problem is into Consultingwerk.Studio.ClassDocumentation.ClassDocumentationHelper.cls.
Method ReplaceSpecialCharacters transform all "special" symbols (with asc-code more than 128) and use REPLACE function for transformation. But replace are not case-sensitive by default and that broke output string.

I'm add CASE-SENSITIVE option to output variable and now it work for me.

`DEFINE VARIABLE cString AS LONGCHAR NO-UNDO CASE-SENSITIVE .`

But i think it is necessary to check more fully :)

**Comment by mikefechner** [comment]
Either cString or cChar should be case-sensitive true. I have logged ticket SCL-2151 (https://jira.consultingwerkcloud.com/browse/SCL-2151) for that purpose. 

This "only" breaks the case of characters? No wrong characters used?

**Comment by Mazenrab** [comment]
@mikefechner Happy to help :) unfortunately, i don't have access to your jira, and can't view task status :)

> This "only" breaks the case of characters? No wrong characters used?

for now i seen only wrong case letters (my start message is wrong i was viewing html in wrong codepage), but if i will see somtehing strange - i notify you

**Comment by mikefechner** [comment]
We’ll update this ticket. But we can’t do any development without a ticket in our JIRA.

**Comment by mikefechner** [comment]
@gquerret Attached is the fixed version of the ClassDocumentationHelper

[ClassDocumentationHelper.zip](https://github.com/Riverside-Software/pct/files/1910983/ClassDocumentationHelper.zip)

**Comment by gquerret** [comment]
@mikefechner Thanks, I'll test that this morning

**Comment by gquerret** [comment]
Merged in master
