### ISSUE TITLE
PCT enhancement request : add TERM=ansi to env by default

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#292]
### add TERM=ansi to env by default
When executing target from within a Jenkins context, TERM is not set.
This causes various tasks that invoke _progres to print a warning `TERM env variable is not set. Assuming an ANSI terminal. (4032)` 

### Your environment
* RedHat RHEL7.4
* OE117
* Apache Ant(TM) version 1.10.1 compiled on February 2 2017
* pct-208

### Actual behaviour
```
[PCTDumpIncremental] TERM env variable is not set. Assuming an ANSI terminal. (4032)
[PCTLoadSchema] TERM env variable is not set. Assuming an ANSI terminal. (4032)
```

### Expected behaviour
TERM=ansi is added to the environment if TERM is not present, which is what _progress uses anyway. The warning is not printed

### Steps to reproduce
Invoke a target containing PCTDumpIncremental, PCTLoadSchema, ... without TERM in your environment

**Comment by gquerret** [comment]
I usually add TERM in the Jenkins job configuration, as I know why I'm using it. I'm quite relunctant to add this as the default behavior, mostly because I absolutely don't know if there could be side effects.

**Comment by gquerret** [comment]
I'll leave the code as is, I'm really unsure of the side effects. Workaround is to add the environment variable directly in the Jenkins job (and then you know exactly what you're doing).
