### ISSUE TITLE
PCT et prolint sous UNIX

### ISSUE THREAD

**Issue by DSIA-TOUZE** [Riverside-Software/pct#294]
Bonjour,
Il ne s'agit pas vraiment d'une issue mais plutôt d'une question.
S'il y a un lieu plus approprié pour cela ... je suis preneur mais je n'ai pas trouvé.

Nous souhaitons utiliser prolint lors de la compilation de nos librairies progress sous UNIX.
Pour constituer nos librairies nous utilisons PCT avec ANT sous Jenkins sous UNIX.
Est-ce quelque chose qui a déjà été fait ?
Si oui il y a t-il une documentation ?
Merci.

**Comment by gquerret** [comment]
English answer, you can contact me offline if you want more explanations in French ( email address available on this [page](https://github.com/Riverside-Software/pct/wiki) ).
Prolint support has been removed from PCT years ago, but you may still use it with PCTRun.

However, you'll achieve a far better result by using the [OpenEdge plugin for SonarQube](https://github.com/Riverside-Software/sonar-openedge).
