### ISSUE TITLE
Exception in thread; Invalid response from command PctCompile

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#295]
### Subject of the issue
Found in the compile log:
```
[PCTCompile] Exception in thread "Thread-83" Invalid response from command PctCompile(chui-code|p/aprcv.p|*chui-code|p/aprf.p|*chui-code|p/aprg.p|*chui-code|p/aprma.p|*chui-code|p/aprmp.p|*chui-code|p/aprms.p|*chui-code|p/aprmv.p|*chui-code|p/aprp.p|*chui-code|p/aprpa.p|*chui-code|p/aprpr.p|) : ''
[PCTCompile]    at com.phenix.pct.PCTBgCompile$CompilationBackgroundWorker.handleResponse(PCTBgCompile.java:321)
[PCTCompile]    at com.phenix.pct.BackgroundWorker.listen(BackgroundWorker.java:127)
[PCTCompile]    at com.phenix.pct.PCTBgRun$ListenerThread$1.run(PCTBgRun.java:681)
[PCTCompile]    at java.lang.Thread.run(Thread.java:745)
[PCTCompile] Caused by: java.lang.NumberFormatException: For input string: ""
[PCTCompile]    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[PCTCompile]    at java.lang.Integer.parseInt(Integer.java:592)
[PCTCompile]    at java.lang.Integer.parseInt(Integer.java:615)
[PCTCompile]    at com.phenix.pct.PCTBgCompile$CompilationBackgroundWorker.handleResponse(PCTBgCompile.java:317)
[PCTCompile]    ... 3 more
[PCTCompile] WARNING: Translation of 'GST' to '# reg. GST'
[PCTCompile] in language 'es' exceeds allocated length of 3 characters. (4788)
[PCTCompile] Translated stacked label '# reg. GST!' does not have enough levels. (4516)
```

### Your environment
Red Hat AS6 64bit
OpenEdge 11.7.2.010 64bit
ANT Version : 1.10.1
PCT Version : pct-208-master-87b954be01663bf64f7b435edb02afdd6b4044fa
Java used: 11.7.2.010   OpenEdge jdk

### Actual behaviour
Above error appears in the compile log.   This is when running a 5-thread compile.

### Expected behaviour
Not error?  or handle any error on my part a little more graciously?

### Steps to reproduce
Not sure I can reproduce the error, even.  I will make the attempt over the weekend.

**Comment by wilddoug** [comment]
It appears this was caused by bad translation data imported into xl_translation.
I can dig further if this is something you'd like to attempt to reproduce...

The text in the string is:  "# reg. GST!"
I'm guessing that having the "!" character as the last character is the cause.

**Comment by gquerret** [comment]
I've tried to add an exclamation mark at the end of a translation in test58, but that doesn't fail the build.
Those messages should appear in the .warnings file. If you have time, can you try extending [test58](https://github.com/Riverside-Software/pct/tree/master/tests/PCTCompile/test58) so that it fails in the same way ?

**Comment by wilddoug** [comment]
I was wrong about the character ...   it is a pipe symbol   |   not an exclamation point.
Does that make a difference in the scenario?

**Comment by gquerret** [comment]
Still not reproduced. What I don't understand is how you end up with the warning messages being displayed on stdout instead of .warnings file.
However, I'm still not able to have message 4516 (message 4788 is easy). In which statement is this string used ?

**Comment by stefandrissen** [comment]
The following uses stacked labels - if you ensure the translation is inconsistent with number of levels (divided by !) then you should get 4516:
```
define temp-table tt no-undo
   field ii as int 
   .

create tt. tt.ii = 1 .
create tt. tt.ii = 2.   
  
define query qq for tt.
define browse br query qq
   display 
      tt.ii column-label "stacked!label":t50
with size 78 by 21.

define frame fr 
  br
  with size 80 by 22.  

view frame fr.  
open query qq for each tt.  
wait-for close of frame fr.
```

**Comment by gquerret** [comment]
Reading message description of 4516 gave me the hint, the problem is about having not *enough* levels, not about having *too many* levels, so my unit test was wrong... I'm getting the warning message, and PCTCompile exits unexpectedly.

**Comment by gquerret** [comment]
Lovely, the compiler throws a STOP condition in this case. 👿

**Comment by wilddoug** [comment]
That seems excessive for a warning...

**Comment by gquerret** [comment]
Yes, this should be reported to PSC.
@wilddoug Can you take care of that ?

**Comment by wilddoug** [comment]
Case logged.  We'll see how that goes...

**Comment by gquerret** [comment]
Thanks. I've added code to handle the STOP condition in the COMPILE statement in branch `PCT-295-TranMan`. I want to verify if this happens in all versions before merging in master.

**Comment by gquerret** [comment]
@wilddoug Did you get any feedback from TS ?

**Comment by wilddoug** [comment]
Nothing yet:  "We'll take a look".

**Comment by wilddoug** [comment]
Still waiting to here something solid from Progress..  Getting "working as intended" and "really shouldn't do that" in the same response.  Hopefully hear something definite soon.

**Comment by gquerret** [comment]
Do they reproduce the problem ? It's clear to me that this STOP condition shouldn't be raised. I could understand that they don't see it as a critical problem, and probably will never fix it, but at least it should be acknowledged by TS.

**Comment by wilddoug** [comment]
Yes, they were able to reproduce the issue.

**Comment by wilddoug** [comment]
Progress has entered defect [PSC00364911](https://knowledgebase.progress.com/articles/Article/Error-4516-stops-the-compiler) for this issue

**Comment by gquerret** [comment]
Fixed in master
