### ISSUE TITLE
XRef files and rcode not being created as expected

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#304]
### Subject of the issue

```
[PCTCompile] ** "D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\enums\.pct/DataTypes.cls.xref" was not found. (293)
[PCTCompile] **The READ-XML attribute on the DATASET widget has invalid arguments. (4065)
```
These errors appear after each file to be compiled.

### Your environment
O/S: Windows 10 Enterprise
OpenEdge: 11.7.2.011
ANT: 1.10.1
PCT: pct-209-master-260e0a7951e4a94d04f43fc827196578e664bebb

### Actual behaviour
rcode is not generated at all for the files that get this error.

### Steps to reproduce
keepXref="yes", xmlXref="yes", xCode="no".
for example:
```
      <PCTCompile graphicalMode="yes" tempDir="${tempdir}" dlcHome="${env.DLC}"
            destDir="${grcodedir}/enums" relativePaths="yes" numThreads="1"
            maximumMemory="65534" stackSize="2048" token="8000" inputChars="32000"
            requireFieldQualifiers="yes" requireFullNames="yes"
            compileUnderscore="yes" cpinternal="1252" cpstream="1252"
            languages="es,french" failOnError="no" dirSize="8000"
            keepXref="yes" xmlXref="yes"
            debugPCT="yes" xCode="no" xCodeKey="R&amp;D"
            progPerc="0" multiCompile="true" paramFile="${configdir}/options.pf" >
        <DBConnectionSet refid="read" />
        <propath>
          <pathelement path="${gsrcdir}" />
          <pathelement path="${gsrcdir}/trend" />
          <pathelement path="${gsrcdir}/common" />
          <pathelement path="${gsrcdir}/enums" />
          <pathelement path="${gsrcdir}/twl" />
          <pathelement path="${gsrcdir}/twl/common" />
          <pathelement path="${gsrcdir}/twl/common/trigger" />
          <pathelement path="${gsrcdir}/twl/reports" />
          <pathelement path="${gsrcdir}/src" />
          <pathelement path="${gsrcdir}/dlc/trend" />
          <pathelement path="${gsrcdir}/dlc" />
          <pathelement path="${gsrcdir}/dlc/src" />
          <pathelement path="${env.DLC}/tty/netlib/OpenEdge.Net.pl" />
        </propath>
        <fileset dir="${gsrcdir}/enums">
          <include name="*.cls" />
        </fileset>
      </PCTCompile>
```

Toggling xCode option to "yes" stops the errors from appearing, but also stops the generation of the xref files.
Swapping back to PCT v208, no errors appear and rcode is correctly generated.

**Comment by gquerret** [comment]
I thought I asked you to test this change ( 2dec80401b659832b9b039f29b34c57847bbb53f ) as I knew it could impact your build, but I'm probably wrong. This change is about using security-policy:xcode-session-key instead of using the xcode-key option in compile statement.
It seems the xcode boolean attribute is not enforced anymore. I'll add a test case and keep you posted.

**Comment by gquerret** [comment]
Using `security-policy:xcode-session-key` makes it impossible to use `xref-xml` or `listing` attributes, throwing error message 14746.
Given the way this attribute works, I'll probably just reset the value when xcode is set to false in PCTCompile. Probably next week or so.

**Comment by gquerret** [comment]
Merged in master
