### ISSUE TITLE
Compiling triggers does not update metaschema

### ISSUE THREAD

**Issue by alexwiese** [Riverside-Software/pct#307]
### Subject of the issue
When database triggers have Check CRC enabled, and are updated and re-compiled, the CRC values in the metaschema are not updated which is causing errors at runtime. 

### Your environment
PCT-209
OpenEdge 11.7.2

### Actual behaviour
Metaschema trigger CRC values are not updated. At runtime error message is displayed "CRC for database trigger procedure does not match schema. (3242)."

### Expected behaviour
When the database trigger procedure is recompiled the CRC in the metaschema is updated to reflect this change.

### Steps to reproduce
1. Change a trigger procedure file (with Check CRC enabled).
2. Recompile using PCT
3. Run procedure editor and update/create a record to trigger the trigger

More information on how the metaschema is updated here: https://knowledgebase.progress.com/articles/Article/P2939

**Comment by stefandrissen** [comment]
I do not understand how you expect your expected behavior to work:

1. Do you expect pct to update the currently connected database?
2. Do you expect pct to checkout a df from source control and update that?

**Comment by alexwiese** [comment]
I expect it to behave the same way Data Dictionary does when re-compiling trigger procedures by updating the metaschema in the connected database.

**Comment by stefandrissen** [comment]
Interesting, the Data Dictionary actually compiles the trigger to get the r-code crc and store it in the meta-schema (see adedict/trig/_trigdlg.p).  

As you may have guessed - we do not use trigger crcs. Compiling code in the Data Dictionary /feels/ convulted, mixing up design time and deployment time activities. 

Oh well, I suppose you can always use pct:run to execute the crc updater you pointed to.

**Comment by alexwiese** [comment]
Yeah my solution was to just disable Check CRC on every trigger, not sure it's of real value anyway. Just thought this might be something others get caught on.

**Comment by gquerret** [comment]
+1 for @stefandrissen, using pct:run is the right idea.
