### ISSUE TITLE
Can PCTRun fail on duplicate parameters

### ISSUE THREAD

**Issue by dvandoorn** [Riverside-Software/pct#308]
### Subject of the issue
Can PCTRun fail on duplicate parameters

### Your environment
* Operating system and version: Windows 10
* OpenEdge version: 11.7.3 
* Ant version:  1.10.3
* PCT version: 208

### Actual behaviour
When adding by accident (or stupidity) - choose the word you like- 2 duplicate parameters to PCTRun unpredictable things can happen. 

### Expected behaviour
PCTRun should fail and raise an error

### Steps to reproduce
Add two times the same parameter to a PCTRun

**Comment by gquerret** [comment]
PCT doesn't have control over the XML content. Not sure if there's something documented at the Ant level however.

**Comment by dvandoorn** [comment]
Not sure if we are on the same page.
```
        <PCTRun 
        	procedure="`mytest.p" 
            graphicalMode="true" 
            dlcHome="${progress.DLC}" 
            cpinternal="${Default.CpInternal}" 
            cpstream="${Default.CpStream}"
            inputchars="${RunOptions.InputChars}" 
            assemblies="${Full.Assembly.Directory}"
            token="${RunOptions.Token}" 
            TTBufferSize="${RunOptions.TTBufferSize}"
            paramFile="${SmartBusinessEntityTestPF}" 
            baseDir="${Workspace.Root}">

            <propath refid="Propath" />
            <DBConnectionset refid="my.db.connectionset" />
        	
            <Parameter name="Directory"    value="${Directory}"/>            
            <Parameter name="OutputFile"   value="output.xml"/>
            <Parameter name="Directory"    value="${Directory}"/>
        	
            <PCTRunOption name="-errorstack" />        	
        </PCTRun>   
```
I would suggest to exit pctinit.p and in an error state when trying to add duplicate parameters.

**Comment by gquerret** [comment]
Was definitely thinking about something different :-)

The current behavior is clearly documented:
https://github.com/Riverside-Software/pct/wiki/PCTRun#parameter

I have to admit that I don't remember **why** I did that, that may be specified in the code, I'll have a look

**Comment by dvandoorn** [comment]
It can result in a lot of debugging when you have PCTRun in a macro and elements are passed. 
But if there's a good reason, never mind. It's more of a feature request.

**Comment by stefandrissen** [comment]
If there really is a valid reason - you could add a warning when there is duplicate when in verbose mode

**Comment by gquerret** [comment]
I think duplicates could be displayed even without verbose mode

**Comment by gquerret** [comment]
Apart from laziness, I didn't find any valid reason for this behavior. Fix will be merged in master soon.

It displays a warning when there's a duplicate:
```
Parameter XXX already exists with value YYY
```

Parameters are stored in an ordered list, so first one wins.

**Comment by gquerret** [comment]
Could you try PCT.jar from [this build](https://ci.rssw.eu/job/PCT/job/bugfix%252FPCT-308-Parameters/5/) and confirm if it works ?
Build is currently running, JAR file will be available in a few minutes.

**Comment by dvandoorn** [comment]
```
C:\Development\Build\Anttest>%ANT_HOME%\bin\ant -f testparam.xml
Buildfile: C:\Development\Build\Anttest\testparam.xml
[PCTVersion] PCT Version : pct-210.pre-bugfix/PCT-308-Parameters-18d6d7c17ca408788b851cba4daf2fae6e2292c4

build:
   [PCTRun] Parameter PARAM1 already exists with value Something over the rainbow
   [PCTRun] Inside the procedure ---> Something over the rainbow

BUILD SUCCESSFUL
Total time: 0 seconds
```
It works. Tested both with and without duplicate parameters. Thanks!

**Comment by gquerret** [comment]
Merged in master
