### ISSUE TITLE
Implement ability to customize [PCTRun] in console output

### ISSUE THREAD

**Issue by mikefechner** [Riverside-Software/pct#309]
### Subject of the issue
For use in ANT macros it would be very helpful if we could customize the [PCTRun] prefix used when writing messages to the ANT console output. 

### Your environment
* Operating system: Windows
* OpenEdge 11.7.3
* Ant 1.9.10
* PCT 2.0.9

### Actual behaviour
All console output made by PCTRun statements are prefixed with [PCTRun].

### Expected behaviour
There should be an additional, optional argument to PCTRun which allows to customize this prefix.

### Steps to reproduce
RCTRun anything.

**Comment by gquerret** [comment]
Use the standard `taskname` attribute.
