### ISSUE TITLE
Cannot run program "C:\Progress11\OpenEdge\bin\prowin32"

### ISSUE THREAD

**Issue by Ninja61** [Riverside-Software/pct#310]
### Subject of the issue
We are updating our development system from OE10.2BSP08 (32-bit) to OE11.7.3(64-bit) and when I try to run my existing build process using Ant , I get the error :- Cannot run program "C:\Progress11\OpenEdge\bin\prowin32". I do not know why it has picked prowin32 as that does not exist in the 64-bit version.

### Your environment
Windows 7 64-bit
Apache Ant(TM) version 1.9.6 compiled on June 29 2015
* PCT version

### Actual behaviour
Unable to run current build script as it is attempting to use prowin32.exe which doesn't exist in the oe11 64-bit environment.

### Expected behaviour
Build script runs correctly and the project is built

### Steps to reproduce
Doubt you can reproduce as you would need the same environment. Basically all I have done is install OE11.7.3 64-bit Progress and run our Ant build script.
I have got round the issue temporarily by copying prowin.exe and naming it prowin32.exe but this is not normal practice so am raising the issue
![build_error](https://user-images.githubusercontent.com/40558523/41898870-f18236f2-7922-11e8-9db7-814507f83cea.JPG)

**Comment by gquerret** [comment]
PCT version ?

**Comment by Ninja61** [comment]
We appear to only be using PCTCompileExt and I do not know how we obtain the version number.
Cheers

**Comment by gquerret** [comment]
Use [PCTVersion](https://github.com/Riverside-Software/pct/wiki/PCTVersion) task in your build.xml. You can also execute ant with `-v` switch.
See https://github.com/Riverside-Software/pct/blob/master/CONTRIBUTING.md

**Comment by Ninja61** [comment]
[antissue.txt](https://github.com/Riverside-Software/pct/files/2136428/antissue.txt)
I tried the ant -v option but couldn't see the version number so have attached the output, hope that helps.
Cheers

**Comment by Ninja61** [comment]
[PCTVersion] PCT Version 1.1-pre - Build 183

**Comment by gquerret** [comment]
[Changelog for build 184](https://github.com/Riverside-Software/pct/wiki/Changelog#qa-build-184-december-17th-2013) mentions that it includes a fix for 11.3 64 bits on Windows, so I assume you're hit by this issue (11.7 wasn't available at this time).
Just upgrade PCT to the latest version (locate PCT.jar in your build file or in the $ANT_HOME/lib directory). You can use the version $DLC/pct
