### ISSUE TITLE
 PCT ANT RCodeSelector issue

### ISSUE THREAD

**Issue by markbeynon** [Riverside-Software/pct#311]
### Subject of the issue
Describe your issue here.
Hello,
I'm having difficulty in getting this aspect of PCT working as I would expect. I have a PCT ANT build script which generates a library from an RCODE folder;

build/rcode

build/library

when the script runs the rcode in the RCODE folder is copied and flattened (absolute paths removed) into a temp folder.

build/rcode/temp

It's from this temp folder that the library is built.

My problem is that when the build script compares the new RCODE with the previous library, every file is reported as being a different MD5 and copied to my compare folder (see below).

When I manually checked the md5 (RCODE-INFO:MD5-VALUE) of the library and rcode .r files they are the same!

    
    <copy todir="${prop.BUILD_RCODE}\compare" includeEmptyDirs="false">
      <fileset dir="${prop.BUILD_RCODE}\temp" includes="**/*.r">
        <RCodeSelector lib="${prop.BUILD_LIBRARY}\${prop.build-name}.pl" mode="md5" />
      </fileset>
    </copy>   

### Your environment
* Operating system and version
Windows 10 Pro 64bit

* OpenEdge version
OE10.2B.08

* Ant version
Apache Ant(TM) version 1.10.1 compiled on February 2 2017

* PCT version
Latest (PCT 209)

### Actual behaviour
All rcode incorrectly identified as different MD5

### Expected behaviour
Only rcode with different MD5 should be copied to new directory

### Steps to reproduce
Tell us how to reproduce this issue.

Compare a .pl against rcode. All RCODE is copied. 

    
    <copy todir="${prop.BUILD_RCODE}\compare" includeEmptyDirs="false">
      <fileset dir="${prop.BUILD_RCODE}\temp" includes="**/*.r">
        <RCodeSelector lib="${prop.BUILD_LIBRARY}\${prop.build-name}.pl" mode="md5" />
      </fileset>
    </copy>

**Comment by gquerret** [comment]
Please download prolib.jar from the [releases](https://github.com/Riverside-Software/pct/releases/tag/v209) page, and execute `java -jar prolib.jar list -lib /path/to/library.pl`, and make sure files have the MD5 and paths. From your description, I'm not sure if files have the same path in both libraries.

**Comment by markbeynon** [comment]
Hi,
Thanks for looking at this. I ran the prolib.jar as you suggested and got the following (first two lines only);
```
   CRC                               MD5       Size File
 10106  6D73ACC29364096060F84B0670F514FD      91015 450.r
 51399  056961612BFDCC3E91D0F4D7CA5B4DBA     109618 ADOManager.r
```

So, essentially the library structure is flat.

As per my original post I'm trying to compare items in the PL to items in my temp folder which are also flat. The MD5's are the same. The error that I get from the compare are, for example;
"PLTarget ExternalInterface.r is an invalid rcode -- Resetting to invalid mark"

Thanks.

**Comment by gquerret** [comment]
Would you be able to execute `java -jar prolib.jar extract -lib /path/to/library.pl` ? That will extract the content of the PL file in the current directory. Then verify that ExternalInterface.r is a valid rcode.
Or upload the PL to https://upload.rssw.eu and I'll do a quick test.

**Comment by markbeynon** [comment]
I'll have to ask my line manager if I can upload the .pl file, however, I'm confident that the r code in the libarary is valid as I can run our application using it. I could upload two sample files (ExternalInterface.r), one from the library and one from the temp folder if this helps?

**Comment by gquerret** [comment]
PCT has its own PL management code (it doesn't use prolib.exe), the issue might be there.

**Comment by markbeynon** [comment]
OK. We've written a little Progress utility that we will call with PCTRun to build a patch so we can work around this. We are looking to build patch releases using Bambbo and PCT (just build a library of those things that have changed).
Thanks.

**Comment by gquerret** [comment]
Did you try to extract the PL with prolib.jar ? I'd be curious to know if there's a bug in the PL reader.

**Comment by markbeynon** [comment]
Yes, I did and it looks fine. I piped the output to txt file and all the rcode is there.

**Comment by gquerret** [comment]
Closing the issue for now, but let me know if you can upload the PL file.

**Comment by markbeynon** [comment]
My line manager has authorised me to let you have the .pl in question.
If I upload it, when do you think you would be able to look at this issue?

**Comment by jakejustus** [comment]
I can have a look at the file this evening (at least to see if there's anything wrong when reading the file).

**Comment by markbeynon** [comment]
That’s great. My intention was to zip up the .PL, the rcode dir I was comparing the PL against and the PCT ANT build script I’ve been using and send these to you.
The zip is 76MB. Have you got a cloud drive or link I can push this too?

**Comment by gquerret** [comment]
You can upload it https://upload.rssw.eu, that's a private Riverside server.

**Comment by markbeynon** [comment]
Done. ☺

**Comment by gquerret** [comment]
I've reproduced your issue. Will be fixed shortly, but there's also a performance issue when reading from PL compared to rcode directory, I want to fix it as well.
Thanks for your PL file !

**Comment by markbeynon** [comment]
Hi Gilles,
Glad you’ve found the issue. I look forward to being able to do an MD5 compare with PCT ANT.
Thanks,
Mark.

**Comment by gquerret** [comment]
Could you try [this version](https://ci.rssw.eu/job/PCT/job/bugfix%252FPCT-311-RCodeSelector/3/artifact/dist/PCT.jar) and confirm if it works ?

**Comment by markbeynon** [comment]
Yes, I certainly will.

**Comment by markbeynon** [comment]
The fix seems to work fine ☺
Thanks for taking  the time to look into this for us.

**Comment by gquerret** [comment]
Merged in master

**Comment by markbeynon** [comment]
My line manager has asked me if you would be kind enough to delete the RCODE and libraries I sent now that you have finished with them (if you haven’t already done so)?

**Comment by gquerret** [comment]
Yes, this has been deleted from the server.
