### ISSUE TITLE
pct:run baseDir is not set

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#312]
### pct:run baseDir is not set
When using pct:run and setting baseDir to set the base directory, this does not seem to set the base directory even though the java code seems to be attempting to do this.

### Your environment
* Windows 10 x64 version 1709
* OpenEdge 11.7.1 x64
* Ant 1.9.6
* PCT pct-209.pre-feature/PCT-293-MTCompilation-a0dcccc4457acaf45c9e9814c769b021c3d41f70

### Actual behaviour
The baseDir is ignored and the paramFile is expected to be in the directory of the build.xml.

### Expected behaviour
baseDir should be set and used.

### Steps to reproduce
````
<target name="debug" description="debug" xmlns:pct="antlib:eu/rssw/pct">
	<taskdef uri="antlib:eu/rssw/pct" resource="eu/rssw/pct/antlib.xml" classpath="${pct.jar}" />
	<pct:dlc_home value="c:/progress/oe11.7" />
	<pct:run basedir="c:/temp" paramFile="param.pf" procedure="unimportant.p" />
</target>
````

reports:

````
debug:
  [pct:run] ** Unable to open parameter file <build.xml directory>\param.pf, errno 2. (1247)
  [pct:run] Result: 2
````

When it should be reporting (in the case of no param.pf):
````
debug:
  [pct:run] ** Unable to open parameter file c:\temp\param.pf, errno 2. (1247)
  [pct:run] Result: 2
````

**Comment by gquerret** [comment]
This is a design decision in Ant, and I took the decision years ago to have PCT be consistent with the Ant behavior.
You can try this example:
```
  <target name="xxx">
    <exec executable="java.exe" dir="build" output="xxx.txt" />
  </target>
```
File `xxx.txt` will be generated in basedir, not in `build` directory. Reason is that `output`, like `paramFile`, are File attributes, which are resolved when the build file is evaluated, and not when executed.

**Comment by gquerret** [comment]
And all Ant tasks using a 'dir' or 'basedir' attribute are working this way, so it wouldn't be clear at all to have PCT behave differently.

**Comment by stefandrissen** [comment]
I don't mind either way, it's just that the wiki is documenting this as:

"The directory in which the OpenEdge runtime should be executed."

Which does not make this clear, as from any OpenEdge process point of view (appserver, webspeed, shortcuts, scheduled tasks) everything is relative to this directory. When reusing the same components for creating appserver and webspeed, this then muddies the water when pct:run is needed. 

I can follow your reasoning, but that imho needs to be cleared up in the documentation for the attributes that point to files- "all input / output files are relative to the Ant project dir and not to the baseDir attribute".

**Comment by gquerret** [comment]
Yes, I'll update the documentation.

**Comment by gquerret** [comment]
Updated
