### ISSUE TITLE
PCTCompile Languages Option Doesn't Specify Format in Wiki

### ISSUE THREAD

**Issue by kihashi** [Riverside-Software/pct#316]
### Subject of the issue
[In the wiki](https://github.com/Riverside-Software/pct/wiki/PCTCompile), the documentation on PCTCompile lists the languages option as 

> Identifies which language segments to include in the compiled r-code. LANGUAGES option of the COMPILE statement

[In the documentation](https://documentation.progress.com/output/ua/OpenEdge_latest/index.html#page/dvref/compile-statement.html), however, there are 2 possible formats depending on if you are using `Value()` or not.

> Identifies which language segments to include in the compiled r-code. The language-list is a colon-separated list of language names used to generate each text segment. If you specify VALUE ( expression ), the expression must evaluate to a comma-separated list of language names.

I'm assuming that PCT uses `value()` here (I'm not sure it could work otherwise), but the wiki doesn't specify.

### Your environment
* OE Version: Any
* PCT version: Latest

### Actual behaviour
Documentation does not clarify the format of the language option.

### Expected behaviour
Documentation clarifies the format of the language option.

**Comment by gquerret** [comment]
This might be a Progress documentation issue, as `VALUE()` is not used (see [here](https://github.com/Riverside-Software/pct/blob/master/src/java/com/phenix/pct/CompilationAttributes.java#L432) ), and I've always been using a comma-separated list.

Would you be able to confirm with PSTS ?

**Comment by kihashi** [comment]
I can clarify with them. Experimentally, it seems either one works when not using `value()`.

**Comment by gquerret** [comment]
Documentation updated.

**Comment by kihashi** [comment]
I've gotten some clarification from Progress on the documentation. As it turns out, the languages option of the compile statement doesn't actually differ if using `value()` or not. It is a comma separated list of language segments. Each language segment can be a colon separated list that defines a priority for inclusion. Basically Colons are `OR` and Commas are `AND`. The examples in the docs actually cover it pretty well, although I still think the text is very confusing (since I misread the examples based on the text of it).

I've asked for Progress to clarify their docs, but I'm not really expecting anything.

Thanks for looking into this!
