### ISSUE TITLE
pctcompile - result property is not set

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#320]
### Subject of the issue
the result property for pct compile is not correct at the end of task

### Your environment
* Windows 7
* OpenEdge 11.7.2
* Ant 1.10.5
* PCT 209

### Actual behaviour
I set failOnError to false.
When compilation failed, the result property is "0" instead of "10"

### Expected behaviour
Get the task result.

### Steps to reproduce
Failed a compilation.

### The problem
I think I found the problem here (line 99) : 
https://github.com/Riverside-Software/pct/blob/master/src/progress/pct/pctCompile.p

You should probably delete the `AND failOnErr` because it's redundant with the code in "pctrun.java"

**Comment by gquerret** [comment]
Reproduced, fix will be included in next version, thanks for feedback !

**Comment by gquerret** [comment]
Merged in master
