### ISSUE TITLE
Missing warnings with options: requireFullKeywords, requireFullNames, requireFieldQualifiers="true"

### ISSUE THREAD

**Issue by pbsky** [Riverside-Software/pct#323]
### Subject of the issue
These options have no effect in the log file. The problem seems to be in src/progress/pct/compile.p
COMPILE VALUE Generates the warnings in this case, no errors.

[compile.zip](https://github.com/Riverside-Software/pct/files/2455632/compile.zip)

### Your environment
* Linux Suse
* OpenEdge version: 11.7.3
* Ant version 
* PCT version: latest master

### Actual behaviour
Tell us what happens

### Expected behaviour
Tell us what you think should happen

### Steps to reproduce
Tell us how to reproduce this issue.

**Comment by gquerret** [comment]
That's not explained in the documentation, but warnings don't appear in the compiler output. Warnings for each file are generated in the .pct directory.

Documentation will be updated.

**Comment by pbsky** [comment]
Thanks,
I saw later that there are "* .warnings" files. Depending on the environment and configuration, it may be more convenient to see these warnings immediately in the compiler output.

**Comment by gquerret** [comment]
That's currently meant to be analyzed by the [OpenEdge plugin for SonarQube](https://github.com/Riverside-Software/sonar-openedge)
