### ISSUE TITLE
PCTCreateBase need to choose tempDir.

### ISSUE THREAD

**Issue by Tranborg** [Riverside-Software/pct#326]
### Subject of the issue
I want to change the temp dir when PCTCreate is doing it job.

### Your environment
Windows Server 2016
11.7.4
DLC/ant
DLC/pct/PCT.jar 2018-10-11

### Actual behaviour
When ANT is running PCTCreate it is also creating some temp-files, like lbia* srta* ...
Those files are created in the same folder as ANT build.xml is running.
TFS in DevStudio will try to catch those lbia#### for Pending Changes, but will only return error when those files are created/deleted so fast.

### Expected behaviour
lbia#### and other temp-files should be created in my Temp-folder i choose.
No errors from TFS

### Steps to reproduce
ANT is running from DevStudio inside the project. That's why TFS is catching all changes to files there.

**Comment by gquerret** [comment]
Not a direct answer to your question, but those files should always be in the "ignore" list of your SCM. I'm not familiar with TFS so I don't know where this is stored, but there should be something like `.gitignore` for Git

**Comment by Tranborg** [comment]
Thanx for fast answer!

ignore it is, as much I can do. 

.tfsignore
lbia*
rcda*
srta*
trpa*

But still TFS is having issues when tmp stuff is flushing in my Project.

![image](https://user-images.githubusercontent.com/42405751/48567920-8c6b9c80-e8fe-11e8-8251-280e8dba6e5b.png)


BR
Lennart Tranborg

**Comment by gquerret** [comment]
TempDir attribute has to be implemented in PCTCreateBase, this is currently not available in this task (only in PCTRun)

**Comment by gquerret** [comment]
Ran into the same issue a few days ago !
Fixed in master
