### ISSUE TITLE
PCT Hook before compilation to execute custom ABL Code

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#329]
Gilles,

I have a question, not a bug.

We've been using PCT for many years and are years behind. I want to start working with the lastest PCT, but we've added some custom code for our translations.

What we do is the following:

In **pctBgCompile.p** (don't know if that still exists) we've added a procedure TranslateProcedure. This is called before PCT compiles the source against the translation database.

```
ASSIGN CompileTarget = (IF lRelative THEN fsDir + (IF fsDir NE '' THEN '/' ELSE '') + fsFile ELSE fsRootDir + '/' + fsDir + '/' + fsFile).
RUN TranslateProcedure(ipSrcProc, CompileTarget, outputDir).
COMPILE VALUE(CompileTarget) SAVE INTO VALUE(outputDir) LANGUAGES (VALUE(languages)) TEXT-SEG-GROW=gwtFact STREAM-IO=streamIO V6FRAME=lV6Frame DEBUG-LIST VALUE(dbgList) PREPROCESS VALUE(prepro) LISTING VALUE(listingFile) MIN-SIZE=MinSize GENERATE-MD5=MD5 XREF VALUE(xreffile) APPEND=FALSE NO-ERROR.
```

Our translations are stored in a custom database of ours. In TranslateProcedure, we do a call to a procedure of ours that gets the translations for the given source from our database and stores them in the translation database. After that is done, the COMPILE from PCT runs and everything is fine ;-)

Is there a way to add some sort of hook before the Compilation in PCT where we can execute some custom code? 

I can first Clone the PCT Repository and add our custom code, but off course, it would be nice if we could just use your repository instead of our clone.

The TranslateProcedure looks like this:

```
PROCEDURE TranslateProcedure:
    DEFINE INPUT PARAM ipSrcProc   AS HANDLE     NO-UNDO.
    DEFINE INPUT PARAMETER TargetProcedure AS CHARACTER NO-UNDO.
    DEFINE INPUT PARAMETER TargetDir AS CHARACTER NO-UNDO.
    DEFINE VARIABLE TempStringXrefFile AS CHARACTER NO-UNDO.
	DEFINE VARIABLE iError AS INTEGER NO-UNDO.

    /* ------------------------------------------------------------------------------- */

    ASSIGN
        TempStringXrefFile = ENTRY(NUM-ENTRIES(TargetProcedure, "/"), TargetProcedure, "/":U)
        TempStringXrefFile = ENTRY(NUM-ENTRIES(TempStringXrefFile, "~\"), TempStringXrefFile, "~\":U)
        TempStringXRefFile = SESSION:TEMP-DIRECTORY + ENTRY(1, TempStringXrefFile, ".":U) + ".srf":U.

    /* Get all translatable strings from the source */
    COMPILE VALUE(TargetProcedure) STRING-XREF VALUE(TempStringXRefFile) /* SAVE INTO VALUE(TargetDir) */ NO-ERROR.

    IF NOT (COMPILER:ERROR AND COMPILER:NUM-MESSAGES > 0) THEN DO:
        /* Custom ABL code of ours initializing xlatedb with translations */
		RUN tm_impb.p(TempStringXRefFile, YES, NO, LoggingLevel). 
	END.

END PROCEDURE.
```

Thx, Lieven Cardoen

**Comment by gquerret** [comment]
Lieven,

The best way to do that would be to do the implementation in your clone and then to open a pull request so that I can merge it in the master branch. I'll just have some requirements before merging it:
* Shouldn't break any existing code
* Documented
* Has unit tests (enforced by code coverage in SonarQube)

I'm open minded regarding the implementation, but something similar have been done for PCTLoadData and PCTLoadSchema (callback interfaces). I think a similar model could be used for what you want to implement.

**Comment by lievencardoen** [comment]
Ok. Good plan. I'll check out PCTLoadData and PCTLoadSchema.

Thx, L.

**Comment by gquerret** [comment]
Did you start working on this enhancement ?

**Comment by gquerret** [comment]
Closing issue for now, please open pull request as soon as development is ready !
