### ISSUE TITLE
HTMLDocumentation throwing error

### ISSUE THREAD

**Issue by KiltedKanuck** [Riverside-Software/pct#330]
### Subject of the issue
After I run ClassDocumentation, I run HTMLDocumentation I receive the following error:
```
[HTMLDocumentation] ** "Consultingwerk/Studio/ClassDocumentation/generate-class-reference.p" was not found. (293)
```
I have searched through the contained pctv11.pl and do not find that contained in the pl
all compiled objects under "Consultingwerk" are not included in the pl
As well ClassDoc.zip is empty ( I did find reference to that zip in your build process)

### Your environment
Win10Pro64
11.7.4
Apache Ant(TM) version 1.10.5 compiled on July 10 2018
Detected Java version: 1.8 in: C:\Progress\OpenEdge\jdk\jre
Detected OS: Windows 10
pct-210.pre-${env.BRANCH_NAME}-${GIT_COMMIT} <-- local build

[build.errors.log](https://github.com/Riverside-Software/pct/files/2665074/build.errors.log)

[build.errors.screen.log](https://github.com/Riverside-Software/pct/files/2665075/build.errors.screen.log)

**Comment by gquerret** [comment]
You have to execute `ant classDoc` before executing `ant jar` when compiling PCT locally.

**Comment by KiltedKanuck** [comment]
Thanks. Thanks worked.
