### ISSUE TITLE
Compiler does not pick up on an assembly change

### ISSUE THREAD

**Issue by strachpr01** [Riverside-Software/pct#332]
### Subject of the issue
A DLL we use within our software has been upgraded recently. There are numberous files that reference this DLL. The assemblies file was updated.

### Your environment
* Operating system and version: Windows Server 2012r2
* OpenEdge version: 11.7.3
* Ant version: 1.9.9
* PCT version: PCT-209

### Actual behaviour
Compiler does not compile files that reference the DLL

### Expected behaviour
Compiler should notice a change in the DLL via the assemblies file and compile the dependant files.

### Steps to reproduce
DLL updated, assemblies file updated and compilation run.

**Comment by gquerret** [comment]
Knowing that file XXX references an assembly YYY is not possible during the build (unless I'm wrong), so I don't think it will be possible to achieve what you're trying to do. You'll have to rely on a full build.
