### ISSUE TITLE
Compilation Performance

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/pct#333]
### Subject of the issue
Compilation Task is very slow

### Your environment
* Windows Server 2012 R2
* OpenEdge 11.7.3
* Ant 1.9.12
* PCT 209

### Actual behaviour
Server: The Compilation with XREF-XML and Code-Listing takes 3h for 25k files (430MB).

Windows 10: PDSOE Eclipse Compile without XREF-XML and CodeListing takes 17min.
Server: Compile from custom buildsystem with XREF-String takes 41min.
 
### Expected behaviour
The Compilation should not take longer than an hour.

### Steps to reproduce
Just run PCTCompile task.

**Comment by gquerret** [comment]
How long does it take without XREF-XML ?

**Comment by lneumeier** [comment]
Compile with Code-Listing, without XREF-XML: 103min
Compile without Code-Listing and without XREF-XML: 103min.

It seems, that a compile with Code-Listing is more or less for "free", but XREF-XML takes additional ~70min. But this is still 60min longer compared with our custom buildsystem.

The custom buildsystem iterates over a temp-table and calls "COMPILE...".

**Comment by gquerret** [comment]
Do you use stringXref or xmlXref in your existing process ?

**Comment by lneumeier** [comment]
stringXref

This is the compile statement:
```
COMPILE VALUE(cFileName)
        &IF PROVERSION(1) >= "11.7.3" &THEN
          OPTIONS fCompileOptions
        &ENDIF
        SAVE INTO VALUE(cRCodeDirectory)
        XREF VALUE(cXRefDirecory + "\" + hBuffer::file_name + ".xref")
        MIN-SIZE
      NO-ERROR.
```

**Comment by stefandrissen** [comment]
A clean build with **four** compile threads on 2497 files (220 MB) on my laptop takes:

stringXref: 4 minutes 13 seconds -> 253 seconds 
xmlXref: 5 minutes 54 seconds -> 354 seconds (40% slower)

Both times are well within any window for me to look further.

How long does your custom compile take when using xmlXref instead of stringXref?

**Comment by gquerret** [comment]
Please note that `STRING-XREF` is also an option of the `COMPILE` statement (but for something different), so let's stick with `XREF` and `XREF-XML`.
Could you try with `noParse=true` ? As well as `xmlXref=false` as Stefan mentioned.

**Comment by lneumeier** [comment]
The following tests are done on my local machine:
OS Windows 10
NVMe SSD

noParse = true, keepXml = false, xmlXref = false, listing = false
20667 files compiled, 26min 31sec

noParse = false, keepXml = false, xmlXref = false, listing = false
20667 files compiled, 37min 49sec

noParse = true, keepXml = true, xmlXref = true, listing = false
20667 files compiled, 40min 19sec

noParse = false, keepXml = true, xmlXref = true, listing = false
20667 files compiled, 60min 41sec

PDSOE - Compile all files
20667 files compiled, ~18min

EDIT:
Custom Buildsystem:
20670 files compiled, 16min, 32sec

**Comment by gquerret** [comment]
Could you add a `<Profiler>` node in PCTCompile, and send the profiler output ? That might explain where time is spent.

**Comment by gquerret** [comment]
Anyway, PCT shouldn't add a 50% overhead when the same options are used.

**Comment by lneumeier** [comment]
Custom Buildsystem with XREF-XML:
20680 files compiled, 30min 22sec
XREF directory size 2.3GB
XREF-XML directory size 7GB

It seems, that XREF-XML is really slow.

**Comment by lneumeier** [comment]
PCT Compile with Profiler:

Options: noParse="true" listing="false" xmlXref="true" keepXref="true" 
Compile: 20667files 44minutes 55seconds
Profilerfile: profiler-noParse-true.out

[profiler-noParse-true.zip](https://github.com/Riverside-Software/pct/files/2745133/profiler-noParse-true.zip)

Options: noParse="false" listing="false" xmlXref="true" keepXref="true" 
Compile: 20667files 62minutes 28seconds
Profilerfile: profiler-noParse-false.out

[profiler-noParse-false.zip](https://github.com/Riverside-Software/pct/files/2745134/profiler-noParse-false.zip)

**Comment by gquerret** [comment]
Profiler probably give me the right hint. PCT-209 relies on a second compilation in order to import strict mode compiler into SonarQube. It does that because strict mode compiler generated errors in the first versions. This has been fixed in OE 11.7.3, and PCT has been updated recently to generate warnings in a single pass.
You can try the last build from master: https://ci.rssw.eu/job/PCT/job/master/

Without XREF-XML (which is slow, but I can't do anything about that) and with this new version of PCT, you should get more or less the same timings as your custom system. If you don't want to do incremental build, you can set noParse=true.

**Comment by lneumeier** [comment]
I tested the master-version and I can see, that the time of pctcomp.p is reduced by 50%. But unfortunately, the pct-version always excecutes compileXref.

Tested with xmlXref="false" keepXref="false" noParse="false" and "noParse"="true".
[profiler.zip](https://github.com/Riverside-Software/pct/files/2745836/profiler.zip)

**Comment by gquerret** [comment]
There was a long time ago a `noxref` attribute, which was dropped at some point. Now files are always compiled with XREF, and the `xmlXref` attribute controls if this is done in XML or not.
Just to be sure, do you now have the same build time as in your custom build, with PCT-master, xmlXref=false, noParse=true ? Or do you still have a difference ?

**Comment by gquerret** [comment]
Had a look the latest profiler file, you still execute the extra compile step with this version (line number is being executed). This is confirmed by: https://github.com/Riverside-Software/pct/blob/master/src/progress/pct/compile.p#L369
Now I remember I started by enabling the :warning in 11.7.3, but that didn't work correctly, so I only activated it for OE12.

**Comment by lneumeier** [comment]
> There was a long time ago a `noxref` attribute, which was dropped at some point. Now files are always compiled with XREF, and the `xmlXref` attribute controls if this is done in XML or not.
> Just to be sure, do you now have the same build time as in your custom build, with PCT-master, xmlXref=false, noParse=true ? Or do you still have a difference ?

This is still slower, the compileXRef Task takes a lot of time...

**Comment by lneumeier** [comment]
> Had a look the latest profiler file, you still execute the extra compile step with this version (line number is being executed). This is confirmed by: https://github.com/Riverside-Software/pct/blob/master/src/progress/pct/compile.p#L369
> Now I remember I started by enabling the :warning in 11.7.3, but that didn't work correctly, so I only activated it for OE12.

But the execution time of pctCompile dropped von 1800s to 800s, if I recall correct.

**Comment by gquerret** [comment]
Could you try again with this build from OE12 branch: https://ci.rssw.eu/job/PCT/job/OE12/47/ ?

**Comment by gquerret** [comment]
Any chance to try this build ? PCT 210 will be released soon, I'd like to close this issue if possible

**Comment by lneumeier** [comment]
Hello,

Here are my test results - looks very good, maybe you can find some optimizations in the "noParse" algorithm, but in general this is a very good performance improvement. Thank you.

noParse="true" xmlXref="false" keepXref="false" listing="false"
209: 26min 31seconds 
210: 14min and 17seconds

noParse="false" xmlXref="false" keepXref="false" listing="false"
209: 37min 49sec
210: 23min and 31seconds

noParse="false" xmlXref="true" keepXref="true" listing = "false"
209: 60min 41sec
210: 44min and 19seconds

noParse="true" xmlXref="true" keepXref="true" listing="false"
209: 40min 19sec
210: 29min and 2 seconds

**Comment by gquerret** [comment]
Very good, thanks for feedback !
