### ISSUE TITLE
Enhancement request: Single user fallback on PCTConnection

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#336]
### Single user fallback on PCTConnection
We have some tasks where it does not matter whether there is a database server running or not.
e.g. dump df , dump .d . compile, ...

Currently it is not possible to define a database connection that would first try a shared-memory connection but fall back to a single user connection.
It is not possible to create a single task definition for these cases. 

### Your environment
* Operating system: windows / linux
* OpenEdge version: 11.5+

### Actual behaviour
Connection fails when there is no server

### Expected behaviour
If useSingleUserFallback is true, a single user connection would be tried after a shared-memory connection failed because there is no server There is no server for database XXX. (1423)

**Comment by gquerret** [comment]
Might be done. Interested in opening a pull request ?

**Comment by cverbiest** [comment]
I'll try it.
Is the parameter name ok ?

**Comment by gquerret** [comment]
Cleaning up old issues, I assume it won't be fixed.
