### ISSUE TITLE
Enhancement request: Add verbose for ProUnit

### ISSUE THREAD

**Issue by slegian** [Riverside-Software/pct#339]
### Subject of the issue
ProUnit supports a --verbose argument. Would be nice to have the ProUnit task support this switch.

**Comment by gquerret** [comment]
I don't know how this verbose attribute is managed in ProUnit, but you may be able to use the `<Parameter>` subnode.
Please note that the ProUnit task isn't maintained anymore and won't be supported in OE12, as nobody seems to be maintaining the Prounit framework.

**Comment by slegian** [comment]
Hi Gilles,

It's really simple actually, prounit just needs the -verbose=true parameter passed on the command line. I had a go, this seems to work fine:
[ProUnit.java.txt](https://github.com/Riverside-Software/pct/files/2814547/ProUnit.java.txt)

I can leave in my "customised" pct version, but maybe you can add in the official code base.

We still use prounit with older OpenEdge versions... 

Cheers,
Simi
