### ISSUE TITLE
comment in pct/compile.p causes errors

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#343]
### Subject of the issue
The `//` comment is not compatible with version 11.5.

It appears after the PR #327 

### Your environment
* Windows 10
* OpenEdge version 11.5
* PCT version : 210 pre

### Steps to reproduce
Compile with OE 11.5

### Guilty code  
```abl
&IF DECIMAL(SUBSTRING(PROVERSION, 1, INDEX(PROVERSION, '.') + 1)) GE 11 &THEN
// PROVERSION(1) available since v11
ASSIGN bAboveEq1173 = (majorMinor GT 11.7) OR ((majorMinor EQ 11.7) AND (INTEGER(ENTRY(3, PROVERSION(1), '.')) GE 3)). /* FIXME Check exact version number */
&ENDIF
```

**Comment by gquerret** [comment]
Right, but the official PCT release is compiled with 11.7. Sorry, you'll have to change this comment to an old-style comment when doing PCT development.
