### ISSUE TITLE
Avoid to have parent class in destDir

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#344]
### Subject of the issue
Hello, 

During the build, all the parents (class and interfaces) are build in `destir`, but they should not because they are not in source directory. (same problem as issue #139)

I know that is how progress works, and PCT has to deal with it.

But, I made some tests and I observed a "funny" thing : 
* When I use strict mode compilation (requireFullName...), I have not the problem ! I concluded that is because of the precompilation (to check warnings) with no `SAVE` option. Progress probably keep some stuff in cache. 

In OE 11.7.4 or higher, and PCT 210, this precompilation is no longer useful, and for me, it's a problem.
It's a strange solution that is not 100% efficient.

To deal with it in eclipse, we use a custom `_idecompile` that compile in a temp directory and then it copy the rcode to `destDir`. 

So there is my question : is it possible to do the same thing and compile in a temp directory ? 
That would be a best behavior than the default compile behavior.

Thanks,

### Your environment
* Operating system and version Win10
* OpenEdge version 11.7.2
* Ant version 1.10.5
* PCT version 209

### Actual behaviour
Parents class of other folder are compiled in `destdir`.

### Expected behaviour
We should only have the source class compiled in source folder.

### Steps to reproduce
Execute `ant build` in this project, and you will see 2 rcode in `ProductA/rcode`

https://github.com/clement-brodu/OEcompile

**Comment by gquerret** [comment]
I'll have a look at the OECompile project

**Comment by gquerret** [comment]
Test case for this behavior [is already present](https://github.com/Riverside-Software/pct/blob/master/src/test/com/phenix/pct/PCTCompileTest.java#L1122) in PCT (was created for issue #139).
The solution has to come from Progress, as they should fix this behavior. I'll get (again) in touch with them. But compiling to a temp directory would have too much impact for now, there's a lot of code to be changed.

**Comment by gquerret** [comment]
Please note that you can easily exclude the parent classes when creating a procedure library (or a ZIP file) by using selectors in filesets (see https://ant.apache.org/manual/Types/selectors.html#presentselect ).
Another built-in solution is to create a PL for the parent classes, and use this PL in the propath instead of the source folder (which also contains the rcode).
I'm not really keen on introducing a potentially dangerous change just to work around a bug in the Progress compiler, which should be fixed by Progress.

**Comment by cverbiest** [comment]
For future reference, reply from tech support on case 00533105 "Progress compiler where rcode is created for other sources than the one asked for".

> the behavior you reported is cause by a bug, so I have logged it with development who will handle it from this point onward. Bug number is OCTA-19598. In the meantime you could create a different folder for rcode and add only that folder in propath when compiling B.cls.
