### ISSUE TITLE
Enhancement: pct:compile: add parameter to use folder hierarchy for debug-listing

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#349]
### Subject of the issue
We store debug-listings as Jenkins artifacts, this is great when tracing errors in the field in version X back to the actual source code line. However, since all debug-listing files are stored flat with underscores instead of directories, Jenkins has an unnecessarily hard time producing the list of debug-listing files.

### Your environment
* Windows 10x64
* OpenEdge 11.6.3 - 11.7.4
* 1.9.6
* PCT 210

### Actual behaviour
Debug-listing files are stored in single folder, which is normal behavior for a Progress client.

### Enhanced behaviour
Add a parameter to store debug-listing files in folder hierarchy.

**Comment by gquerret** [comment]
Attribute `flattenDebugListing` controls this behavior. It's surprising that it's not in the documentation, I'll have a look.

**Comment by stefandrissen** [comment]
> Attribute `flattenDebugListing` controls this behavior. 

Brilliant! Works as advertised! Thanks.

**Comment by gquerret** [comment]
Attribute was added in April 2015, but didn't reach the documentation. This is now done :-)
