### ISSUE TITLE
Improvement Request: PCTCompile parameter to change PAGE-SIZE and PAGE-WIDTH of Listing files

### ISSUE THREAD

**Issue by rubinhos** [Riverside-Software/pct#350]
### PCTCompile parameter to change PAGE-SIZE and PAGE-WIDTH of Listing files
Would be nice to have parameters on ```PCTCompile``` to change the PAGE-SIZE and PAGE-WIDTH of listing files in order to adapt the generated listing for custom readers.

### Your environment
* Windows 10
* OpenEdge 11.7.2
* Ant 1.10.2
* PCT 210

### Actual behaviour
PCTCompile with listing option always generates the listing file with default PAGE-SIZE and PAGE-WIDTH .

### Expected behaviour
Create two more parameters for PCTCompile in order to change PAGE-SIZE and PAGE-WIDTH of listing files.

**Comment by gquerret** [comment]
Can be added. Do you have time to open a pull request ?

**Comment by rubinhos** [comment]
Sure!

**Comment by gquerret** [comment]
Good! Please post comments here if you need help when working on this PR.

**Comment by rubinhos** [comment]
PR: https://github.com/Riverside-Software/pct/pull/351
