### ISSUE TITLE
Enhancement request: identify deleted sources when not using forceCompiling on PCTCompile

### ISSUE THREAD

**Issue by rubinhos** [Riverside-Software/pct#353]
### Identify deleted sources when not using ```forceCompiling``` on ```PCTCompile```
If possible, try to identity deleted sources on ```PCTCompile```.

### Your environment
* Operating system: Windows/Linux
* OpenEdge version: 11.7+

### Actual behaviour
When using ```forceCompiling="false"``` on ```PCTCompile```, deleted compiled sources are not removed from their ```build``` directory.

### Expected behaviour
Delete the compiled sources - based on the informed ```fileset``` - if the original source doesn't exist anymore. Also show at the console - if ```displayFiles``` is active - that the source was removed.

**Comment by gquerret** [comment]
This has been asked several times in the past, but never implemented as there are way too many cases where it will lead to problems.
