### ISSUE TITLE
PCTCompile - CompileCallBackAction causes error in OE 11.5

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#355]
### Subject of the issue
When I try to build something  in OE 11.5, I have this message : 

```
PCTCompile - Progress Code Compiler
La classe rssw.pct.CompileCallbackAction trouvée mais ne peut trouver ou générér un de ses super-classes. (12932)
Echec du chargement de l'instance statique. Impossible de référencer la classe rssw.pct.CompileCallbackAction. (14631)
6 file(s) compiled
```
Good news : my files are compiled.

Sad news : the callback feature will probably not work in OE11.5

I think it's because Progress.Lang.Enum are not working in 11.5.

May be it's a better option to return an INTERGER ?
It's also possible to say that it's not avail before OE 11.7... 

```abl
/* Callbacks are only supported on 11.3+ */
&IF DECIMAL(SUBSTRING(PROVERSION, 1, INDEX(PROVERSION, '.') + 1)) GE 11.3 &THEN
DEFINE VARIABLE callback AS rssw.pct.ICompileCallback NO-UNDO.
DEFINE VARIABLE compileAction AS rssw.pct.CompileCallbackAction NO-UNDO.
ASSIGN compileAction = rssw.pct.CompileCallbackAction:None.
&ENDIF
```

### Your environment
* Windows 10
* OpenEdge 11.5
* Ant 1.10.5
* PCT 211

### Steps to reproduce
Compile something in OE 11.5

**Comment by gquerret** [comment]
Ooops, this has to be fixed...

**Comment by gquerret** [comment]
Can you try this build: https://ci.rssw.eu/job/pct/job/bugfix%252FOE115Callback/ ?

**Comment by clement-brodu** [comment]
That's good for me, it works fine.
Problem solved 👍

**Comment by gquerret** [comment]
Merged in master
