### ISSUE TITLE
Enhancement request: ABLDuck indicate deprecated using an annotation instead of comments

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#359]
### Allow an annotation to be used to mark a method/property/class as deprecated
Currently deprecated is marked using comments but that format cannot be used by sonar-openedge, see https://github.com/Riverside-Software/sonar-openedge/issues/164

### Actual behaviour
Deprecated is indicated using comments

### Enhanced behaviour
Deprecated can be indicated using annotations that can be picked up by sonar-openedge

**Comment by gquerret** [comment]
That will be for you @spazzymoto if you work on the new version of ABLDuck

**Comment by spazzymoto** [comment]
Ah cool i was not aware of that, i will update my implementation.

**Comment by gquerret** [comment]
Will only be handled in JsonDocumentation task. See [documentation](https://github.com/Riverside-Software/pct/wiki/StandardCommentBlock#deprecated-annotation)
