### ISSUE TITLE
ablunit error handling needs improvement when baseDir incorrect

### ISSUE THREAD

**Issue by zerovian** [Riverside-Software/pct#360]
### Subject of the issue
The error handling of ABLUnit needs improvement for the case where baseDir property is not specified and the internal class name doesn't match the working directory name of the tests when invoked via ant

### Your environment
* Operating system and version: all
* OpenEdge version: 12.0
* Ant version: 1.8
* PCT version: PCT-211

### Actual behaviour
I have a build.xml that runs ABLUnit and specifies the baseDir="${basedir}"... and the tests live in a "tests" subfolder of basedir.  Said tests have a package name rooted from "tests" subfolder.  The problem arises when the baseDir is NOT the root of the package.  In such a case the error generated by ABLUnit has no information that would assist with debugging the problem.

I've attached the build.xml, the test .cls and the results.xml file.

The problem is the results.xml file has entries that look like this.  The actual underlying error is not returned.  The real error is a mismatch between the package name of the .cls and the directory name where ABLUnit is running from.

```
<testcase name="ATest" status="Error" time="0"><error>Invoke OpenEdge.ABLUnit.Reflection.ClassAnnotationInfo at line 176  (OpenEdge/ABLUnit/Reflection/ClassAnnotationInfo.r)
RunTestMethod OpenEdge.ABLUnit.Reflection.ClassAnnotationInfo at line 210  (OpenEdge/ABLUnit/Reflection/ClassAnnotationInfo.r)
RunSelectedTestMethod OpenEdge.ABLUnit.Reflection.ClassAnnotationInfo at line 138  (OpenEdge/ABLUnit/Reflection/ClassAnnotationInfo.r)
runTestClassMethod OpenEdge.ABLUnit.Runner.ABLRunner at line 1291  (OpenEdge/ABLUnit/Runner/ABLRunner.r)
runtests OpenEdge.ABLUnit.Runner.ABLRunner at line 1180  (OpenEdge/ABLUnit/Runner/ABLRunner.r)
runtests OpenEdge.ABLUnit.Runner.ABLRunner at line 1105  (OpenEdge/ABLUnit/Runner/ABLRunner.r)
runtests OpenEdge.ABLUnit.Runner.ABLRunner at line 1212  (OpenEdge/ABLUnit/Runner/ABLRunner.r)
runtests OpenEdge.ABLUnit.Runner.ABLRunner at line 1105  (OpenEdge/ABLUnit/Runner/ABLRunner.r)
RunTests OpenEdge.ABLUnit.Runner.ABLRunner at line 152  (OpenEdge/ABLUnit/Runner/ABLRunner.r)
ABLUnitCore.p at line 78  (ABLUnitCore.r)
C:\Users\mbaker\AppData\Local\Temp\pctinit2676065.p at line 25  (C:\Users\mbaker\AppData\Local\Temp\pctinit2676065.p)</error></testcase>
```

### Expected behaviour
The underlying ABL error message from the compiler that indicates the mismatch in package name.  Currently it generates a generic error message which is unhelpful.

### Steps to reproduce
Save the attached build.xml to some directory
create a subfolder "tests" in that directory
create a subfolder "SubDir" in the 'tests' folder
save "MyClass.cls to the "SubDir" directory
run the build.xml from the original directory.

Open the results.xml and see it failed with 1 error...but the message is useless.

**Comment by zerovian** [comment]
zip includes the build.xml the test class and the results.xml I am getting

[ablunit.zip](https://github.com/Riverside-Software/pct/files/3117849/ablunit.zip)

**Comment by zerovian** [comment]
[ablunit.zip](https://github.com/Riverside-Software/pct/files/3117856/ablunit.zip)

**Comment by zerovian** [comment]
The correction is of course to change baseDir="${basedir}" to baseDir="${basedir}/tests".  But it took way too long to debug this because the ABL compiler message regarding the mismatch between the filename and the package name was lost in the error handling.

**Comment by gquerret** [comment]
Better than changing baseDir, I'd just include the right propath with:
```
<propath>
  <pathelement path="tests" />
</propath>
```

And I agree that the message is not especially clear, but that's coming from ABLUnitCore.r, provided by Progress, and I'd like to avoid modifying Progress files if possible. What can be done however is to add a warning message as in PCTCompile when directories specified in test filesets are not included in the propath.

**Comment by zerovian** [comment]
If it coming from Progress.  Then I guess I'll just log a bug...since I work there :).

**Comment by zerovian** [comment]
Logged Progress OpenEdge bug ADAS-17008 for addressing the bad error handling.

**Comment by gquerret** [comment]
A warning message is now added when test fileset is not in propath:
```
com.phenix.pct.ABLUnitTest#test9

Messages
--
Fileset directory /ebs/ebs1/jenkins-public-slave/workspace/PCT_bugfix_PCT-360-ABLUnit@3/testbox/ABLUnit/test9/tests not found in PROPATH
QUIT statement found
Total tests run: 2, Failures: 0, Errors: 2
```

**Comment by gquerret** [comment]
Is the issue ADAS-17008 publicly visible or is that internal ?

**Comment by zerovian** [comment]
OpenEdge doesn't have a public bug list...so only internal.  I referenced this bug.  If you call tech support and ask about it, tech support will attach your company to it and the bug will get flagged as related to a customer. Any customer flagged bugs get release notes when they are fixed in a release.
