### ISSUE TITLE
RCODE-INFO:UNDO-THROW-SCOPE

### ISSUE THREAD

**Issue by torbenjc** [Riverside-Software/pct#365]
### Subject of the issue
RCODE-INFO:UNDO-THROW-SCOPE wrong after complete compile

### Your environment
* Operating system and version: Windows 10 Pro 1809
* OpenEdge version: 11.7.4.0.1685 (Windows 32)
* Ant version: 1.9.7
* PCT version: pct-211-master-7badf2f956c915c0b835eea56c98fad57f2cc7ac

### Actual behaviour
When making a complete compile then afterwards some of the r-codes has:
RCODE-INFO:UNDO-THROW-SCOPE = "" (Even when source has BLOCK-LEVEL ON ERROR UNDO, THROW.)
If I re-compile a single file then afterwards it has correct: RCODE-INFO:UNDO-THROW-SCOPE = "BLOCK-LEVEL"

### Expected behaviour
RCODE-INFO:UNDO-THROW-SCOPE should always display as "BLOCK-LEVEL" after any compile when source has: "BLOCK-LEVEL ON ERROR UNDO, THROW."

### Steps to reproduce
Delete content of .Pct (or *.r) to trigger total compile (Wrong result)
Afterwards edit a single cls file to trigger compile of a single source. (Correct result)

Note has opened support ticked with Progress for same issue: 
Case - 00491630

**Comment by torbenjc** [comment]
[r-code.zip](https://github.com/Riverside-Software/pct/files/3182120/r-code.zip)
Attached r-code.zip
In 'MissingUndoThrow' directory is r-code with wrong RCODE-INFO:UNDO-THROW-SCOPE (+ content of .pct for file)
In 'ReCompile' directory is r-code after tigger of re-compile with correct  RCODE-INFO:UNDO-THROW-SCOPE ("BLOCK-LEVEL")  (+ content of .pct for file)

(this was done using pct-210-master-86e958f5f04cf2832a2fdc0bb1c471312e0e0f12)

**Comment by gquerret** [comment]
Is everything always compiled with PCT ? Or is it from a dev environment, where multiple build processes could occur ?

**Comment by gquerret** [comment]
I'll need a test case, a quick look at an existing code doesn't show anything wrong.

**Comment by torbenjc** [comment]
Hi Giles,
Only a single PCT task is running. (Compiling changed/missing files)
It seems to more an OpenEdge bug, than a PCT bug.
Compiling with standard OpenEdge COMPILE command shows same behaviour when compiling class, that inherits from other classses / implements interfaces.

Fx:
// This compile causes problem, because r-code for parent classes and interfaces are saved wrong!
COMPILE Ams\Row\Account\Custom.cls SAVE.
RESULT:
Ams\Row\Account\Custom.r                          BLOCK-LEVEL
Ams\Row\Account\Main.r                            
Ams\Row\Account\Table.r                           
Ams\Row\Base.r                                    
Ams\Row\iCustom.r                                 


// This COMPILE will cause correct behaviour because parent classes and interfaces are compiled again after compile for child class
COMPILE Ams\Row\Account\Custom.cls SAVE.
COMPILE Ams\Row\Account\Table.cls SAVE.
COMPILE Ams\Row\Account\Main.cls SAVE.
COMPILE Ams\Row\iCustom.cls SAVE.
COMPILE Ams\Row\Base.cls SAVE.
RESULT:
Ams\Row\Account\Custom.r                          BLOCK-LEVEL
Ams\Row\Account\Main.r                            BLOCK-LEVEL
Ams\Row\Account\Table.r                           BLOCK-LEVEL
Ams\Row\Base.r                                    BLOCK-LEVEL
Ams\Row\iCustom.r                                 BLOCK-LEVEL

So it seems like after a compile (that inherits or implements interface) then the class inherited from or interface needs to be compiled ....

**Comment by gquerret** [comment]
Then I'll close for now as it seems to be a Progress bug. Please re-open if this is in fact coming from PCT.

**Comment by torbenjc** [comment]
Hi Giles,
there still might be an issue with PCT independent of the OE Compile!

Using following compile statement:
`                  <PCTCompile destDir="${input.destDir}"
                              dlcHome="${dlcHome}"
                              graphicalMode="${compile.graphicalMode}"
                              paramFile="${paramFile}"
                              iniFile="${path.iniFile}"
                              failOnError="True"
                              forceCompile="False"
                              languages="DKK,GBP,DEM,FRF"
                              displayFiles="1"
                              runList="True"
                              multiCompile="True">
                     <PCTConnection dbName="api3" dbDir="${dbDir}" readOnly="true"/>
                     <PCTConnection dbName="${compile.apitransName}" dbDir="${transDir}" readOnly="true"/>
                     <propath >
                        <pathelement path="${propath}"/>
                     </propath>
                     <fileset dir="@{path}" includes="${fileSet.compile}" excludes="${fileSet.compileExclude} ${compileExcludeExtra}" casesensitive="false"/>
                  </PCTCompile>`

If I delete all r-codes in Ams\Row\Account 
I get following console output;
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Ams\Row\Account\Custom.cls [No r-code]

And RCODE-INFO:UNDO-THROW-SCOPE shows:
APIPRO10\Ams\Row\Account\Custom.r                           BLOCK-LEVEL
APIPRO10\Ams\Row\Account\Main.r                             
APIPRO10\Ams\Row\Account\Table.r                            


If I delete all r-codes in Ams\Row\Account
And content of .pct\Ams\Row\Account
Then I get console output:
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Ams\Row\Account\Custom.cls [No r-code]
[PCTCompile] Ams\Row\Account\Main.cls [Table CRC]
[PCTCompile] Ams\Row\Account\Table.cls [Table CRC]

And RCODE-INFO:UNDO-THROW-SCOPE shows:
APIPRO10\Ams\Row\Account\Custom.r                           BLOCK-LEVEL
APIPRO10\Ams\Row\Account\Main.r                             BLOCK-LEVEL
APIPRO10\Ams\Row\Account\Table.r                            BLOCK-LEVEL

So it seems like it don't honour the multiCompile="True"!?

**Comment by torbenjc** [comment]
FYI:

Information from Progress SupportLink

Development has worked on the issue and confirms that the problem is only with RCODE-INFO:UNDO-THROW-SCOPE. The code still runs correctly, i.e. BLOCK-LEVEL UNDO, THROW is still in effect. The flag that controls the setting has no impact on runtime behaviour.

The bug fix will be included in OpenEdge 11.7.6 and 12.2, with the former being tentatively scheduled for a Q1 2020 release (subject to change).
