### ISSUE TITLE
Alternate create Alias API for DB Connection that does not require PCTAlias

### ISSUE THREAD

**Issue by zerovian** [Riverside-Software/pct#369]
### Subject of the issue
PCTAlias isn't registered as a typedef so I need an method on PCTConnection that doesn't require access to PCTAlias since it isn't available in the classpath for the gradle plugin project I'm working on

### Your environment
* irrelevent
* 12
* 1.10
* 211

### Actual behaviour
Nothing.  I can't add an alias to a connection because PCTAlias isn't in typedef.properties

### Expected behaviour
PCTConnection should have an addAlias(string, boolean) method to allow this

### Steps to reproduce
Tell us how to reproduce this issue.

**Comment by zerovian** [comment]
I will issue pull request for this

**Comment by gquerret** [comment]
There's already a addDBAlias method in PCTRun (thus available to almost any PCT task).
I've already used it in Groovy script:
```
ant.PCTLoadData(srcFile: file, table: stepName, dlcHome: options.dlc, callbackClass: callbackClassName, errorTolerance: errorTolerance, silent: true, numDec: '44', numSep: '46', centuryYearOffset: '1950', dateFormat: 'dmy') {
  DbAlias(name: 'LogDB', value: logicalNames['xxx'])
  dbs.each { DbConnection(dbname: it, dbdir: options.dbDir, logicalName: logicalNames[it], singleUser: dbsmode, username: username, password: password) }
  Parameter (name: 'dbUpdateNum', value: dir.getName())
  Parameter (name: 'dbUpdateStep', value: currUpdStep)
  Propath {
    propath.each { pathelement (location: it) }
  }
}
```

**Comment by zerovian** [comment]
I found away around it..basically doing what you did.  i'll close the pull request as it isn't needed.
