### ISSUE TITLE
Generating service/catalog files

### ISSUE THREAD

**Issue by hutcj** [Riverside-Software/pct#372]
### How to automatically generate service/catalog files
In the deployment process for a PASOE endpoint, I see 3 major steps: 
1. Compile ABL code
2. Generate service & catalog files (.services/ *.pidl, PASOEContent/static/ *.json)
3. Generate *.war file

I have successfully implemented steps 1 & 3 using PCT Ant tasks PCTCompile and ABLWebAppPackage. However, I do not see a way to use PCT/Ant to generate the service & catalog files. These files are required for the .war file to be generated successfully, and they are subject to change based upon the contents of the ABL procedures/classes.  

### Development environment
* Windows 10 1803
* OpenEdge 11.7.5
* Ant 1.9.8
* PCT-212

### Actual behaviour
This process that I am describing can be accomplished in PDSOE via right-click on a service -> Edit -> Finish to trigger re-generation of service/catalog files. Is there a PCT task that accomplishes this?

For example:

![image](https://user-images.githubusercontent.com/40180018/62131317-f8cdd680-b2a8-11e9-8f3b-565cbacd53d0.png)

![image](https://user-images.githubusercontent.com/40180018/62131365-0e430080-b2a9-11e9-80a0-a2edef33083a.png)

### Expected behaviour
The goal is to get away from having to perform this process manually & to incorporate it as part of the Ant build process.

**Comment by gquerret** [comment]
Out of office for now, but did you try the RestGen task ?

**Comment by hutcj** [comment]
Yes, I tried the RestGen task with a number of different options. It can be used to generate .paar files and .json catalogs in either a .zip or .war archive. However, this process relies on the existence of the .pidl files. In addition, the RestGen task doesn't actually create the .json catalogs - it copies them from PASOEContent/static, thus it can only "create" them if they already exist. I'm looking for the process that generates these .pidl and .json files.

**Comment by gquerret** [comment]
Closing this issue, discussion can be continue on Communities as there's currently no way to generate the PIDL files from Ant

**Comment by hutcj** [comment]
Link to discussion: https://community.progress.com/community_groups/openedge_development/f/19/p/59012/201943#201943
