### ISSUE TITLE
error when defining   <taskdef resource="extras115.properties" /> 

### ISSUE THREAD

**Issue by DenDuze** [Riverside-Software/pct#373]
### Subject of the issue
Error when trying to use the ClassDocumentation feature

### Your environment
* Windows Server 2012 R2 Standard
* OpenEdge version OE11.7 SP 01 (Build 1429)
* Ant version 1.10.6 (also tried with 1.10.3)
* PCT version 212

### Actual behaviour
I have a build-file that work fine but when I add all required things for the ClassDocumentation (described on https://github.com/Riverside-Software/pct/wiki/ClassDocumentation) I always get `[taskdef] Could not load definitions from resource extras115.properties. It could not be found.`

I tried with adding the classpath in that taskdef and without that classpath.
I tried with placing the required jars in the ANT_home, i tried with putting them as -lib parameters to the ant command.

I really do not get this to work (like explained on the ClassDocumentation website)

I removed all lines in my build.xml that are not important
```
<?xml version="1.0" encoding="UTF-8"?>
<project name="ClassDocumentation" default="main">
  <taskdef resource="PCT.properties" classpath="C:/Development/tools/PCT/PCT-212.jar" loaderRef="pct" />
  <typedef resource="types.properties" classpath="C:/Development/tools/PCT/PCT-212.jar" loaderRef="pct" />
  <taskdef resource="extras115.properties" /> 
  
  <!-- Main target starts here -->
  <target name="main" >
     <echo message="In the main task"/>
  </target>
</project>
```

And I get the following result
```
C:\Users\didier.d\AppData\Xpower\Projects\xdms.ABLunit\scripts>C:\Users\didier.d\own\Tools\apache-ant-1.10.6\bin\ant -buildfile G:\Projects\xdms.ABLunit\scripts

Buildfile: G:\Projects\xdms.ABLunit\scripts\build.xml
  [taskdef] Could not load definitions from resource extras115.properties. It could not be found.

main:
     [echo] In the main task

BUILD SUCCESSFUL
Total time: 0 seconds
```

Regards

**Comment by DenDuze** [comment]
Oeps forgot the content of the build-file

```
< ?xml version="1.0" encoding="UTF-8"?>
< project name="ClassDocumentation" default="main">
  < taskdef resource="PCT.properties" classpath="C:/Development/tools/PCT/PCT-212.jar" loaderRef="pct" />
  < typedef resource="types.properties" classpath="C:/Development/tools/PCT/PCT-212.jar" loaderRef="pct" />
  < taskdef resource="extras115.properties" /> 
  
  < !-- Main target starts here -->
  < target name="main" >
     < echo message="In the main task"/>
  < /target>
< /project>
```

**Comment by DenDuze** [comment]
Aha, I did not forget it but it's just not getting posted ;-)
Placed a space after every < and now it shows the code
< ?xml version="1.0" encoding="UTF-8"?>
< project name="ClassDocumentation" default="main">
  <taskdef resource="PCT.properties" classpath="C:/Development/tools/PCT/PCT-212.jar" loaderRef="pct" />
  < typedef resource="types.properties" classpath="C:/Development/tools/PCT/PCT-212.jar" loaderRef="pct" />
  < taskdef resource="extras115.properties" /> 
  
  < !-- Main target starts here -->
  < target name="main" >
     < echo message="In the main task"/>
  < /target>
< /project>`

**Comment by gquerret** [comment]
Don't hard-code the path to PCT in your build file, just use:
```
  <taskdef resource="PCT.properties" />
  <typedef resource="types.properties" />
  <taskdef resource="extras115.properties" /> 
```
And either:
* copy the required JAR files to $ANT_HOME/lib

Or
* add `-lib /path/to/PCT.jar -lib /path/to/ast.jar -lib /path/to/ast-dependencies.jar` in your command line

**Comment by DenDuze** [comment]
Sorry to reopen but I'm still not there.

Now I copied the PCT-212.jar into the ANT_HOME\lib directory (I do not like that but ok for testing).

When I have the following (test) build-file
< ?xml version="1.0" encoding="UTF-8"?>
< project name="test">
< taskdef resource="PCT.properties" />
  < typedef resource="types.properties" />
  < taskdef resource="extras115.properties" />
< PCTVersion />
< /project>

With the following cmd
ant -lib C:\Progress\oe11.7\java\ant-libs\ast.jar -lib C:\Progress\oe11.7\java\ant-libs\ast-depen
dencies.jar

I get the following result:
Buildfile: G:\Projects\xdms.ABLunit\scripts\build.xml

BUILD FAILED
G:\Projects\xdms.ABLunit\scripts\build.xml:5: taskdef A class needed by class za.co.mip.ablduck.ABLDuck cannot be found: org/eclipse/core/runtime/IPath using the classloader AntClassLoader[]

I need that extras115.properties (see wiki/ClassDocumentation)

Extra:
I also want to try the XMLDocumentation and for that I need <taskdef resource="extras.properties" /> (ref wiki)
But when I try that I get
Buildfile: G:\Projects\xdms.ABLunit\scripts\build.xml
  [taskdef] Could not load definitions from resource extras.properties. It could not be found.
[PCTVersion] PCT Version : pct-212-master-bf2b096f45e37bd8e52fffa32e83d8ecb830b8cb

BUILD SUCCESSFUL

Total time: 0 seconds

 Regards

**Comment by gquerret** [comment]
You probably have another PCT.jar somewhere in your classpath. What you've described should work (and in fact does work in my current environment).
Note that don't have to copy PCT.jar in ANT_HOME/lib, you can also reference it with -lib.
