### ISSUE TITLE
Profiler does not allow for space in outputFile.

### ISSUE THREAD

**Issue by kenherring** [Riverside-Software/pct#374]
### Profiler Doesn't allow for spaces in outputFile
When we use a space in the outputFile parameter of the profiler when running ABLUnit we get errors and it does not run.

### Your environment
* Operating system and version: Windows 10
* OpenEdge version: OpenEdge Release 11.7.2 as of Tue Oct 24 19:02:01 EDT 2017
* Ant version: 1.9.8
* PCT version: PCT Version : pct-212-master-bf2b096f45e37bd8e52fffa32e83d8ecb830b8cb

### Actual behaviour
When we run using the profiler as below we get the following error.

`<Profiler enabled="true" outputFile="c:\git space\results.prof" coverage="true" listings="listings"/>`

`  [ABLUnit] Invalid option ('space\results.prof') specified in profile configuration file 'C:\Users\kherring\AppData\Local\Temp\prof204563910.pf'. Skipping rest of file. (5940)`

### Expected behaviour
No error, and the profiler data is outputted to the file with a space in the path.

### Steps to reproduce
Use a profiler tag with ABLUnit such as the one listed above.

Note that I've tried adding my own extra quotes and such, but it seems they get stripped off before the .pf file is written to, thus there is no workaround.

I believe there is a one line change required.  The outputted -FILENAME flag should always be quoted.  We can see this being done for the listings flag a few lines down.  See these two lines:

https://github.com/Riverside-Software/pct/blob/2ca951efb1f799abc4a47c2c7f36255cd728de1a/src/java/com/phenix/pct/PCTRun.java#L627

https://github.com/Riverside-Software/pct/blob/2ca951efb1f799abc4a47c2c7f36255cd728de1a/src/java/com/phenix/pct/PCTRun.java#L645

PS- I know spaces are the 😈 but we run into this occasionally and it's always a pain to move to another directory once it comes up.

**Comment by gquerret** [comment]
Interesting to note that spaces in outputDir are handled: https://github.com/Riverside-Software/pct/blob/2ca951efb1f799abc4a47c2c7f36255cd728de1a/src/java/com/phenix/pct/PCTRun.java#L631
I'll surround the value of outputFile with double quotes

**Comment by gquerret** [comment]
> I know spaces are the 😈

Yes !
Fixed it anyway.
