### ISSUE TITLE
PCTLoadData only looks at first DBConnection in DBConnectionSet

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#379]
### Subject of the issue
If you give a DBConnectionSet to PCTLoadData, then only Data for the first DBConnection in the Set is loaded. The second, third, ... DBConnection is ignored. As a workaround I execute PCTLoadData now twice.

### Your environment
* Windows 10
* DCL 11.7.5
* Ant 1.10.5
* PCT 212

### Actual behaviour
Only Tables for first DBConnection are taken into account.

### Expected behaviour
I would expect that behind the scenes, for each database connection, a Load Data is done.

### Steps to reproduce
For instance:
```
  <DBConnectionSet id="ProgressDbConnection">
    <DBConnection dbName="${dbf.dir}/genrw" singleUser="true" userName="${fixed.db.user.name}" password="${db.user.pass}"/>
    <DBConnection dbName="${dbf.dir}/wiki" singleUser="true" userName="${fixed.db.user.name}" password="${db.user.pass}"/>
  </DBConnectionSet>
```

And then

```
<PCTLoadData srcDir="${basedir}/dbfiles/" dlcHome="${DLC}" paramFile="${basedir}/session.pf">
          <DBConnectionSet refid="ProgressDbConnection"/>
          <!-- genrw tables -->
          <Table name="gp_Language" />
          <!-- wiki tables -->
          <Table name="Article" /><Table name="ArticleTag" /><Table name="ArticleText" /><Table name="Author" /><Table name="Chapter" />
          <Table name="CommentTxt" /><Table name="LawArticle" /><Table name="Object" /><Table name="Order" /><Table name="Person" />
          <Table name="Property" /><Table name="PropertyDescription" /><Table name="Report" /><Table name="ReportTemplate" />
          <Table name="Result" /><Table name="ScientificArticle" /><Table name="Section" /><Table name="Tag" /><Table name="Unit" />
          <Table name="WikiHomePage" /><Table name="WikiLanguage" /><Table name="WikiPrinter" /><Table name="WikiTool" />
          <Table name="WikiUser" />
        </PCTLoadData>

```
Only data files for the genrw database connection will be loaded. So only gp_Language Table will be filled.

Kind regards, Lieven Cardoen

**Comment by gquerret** [comment]
As almost all PCTLoad or PCTDump, this task should accept only one DB connection. In fact, there was some code to enforce that, but it got lost when merging tasks a few years ago. You'll have execute PCTLoadData twice...
