### ISSUE TITLE
PCT is not removing temp files

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/pct#382]
Hello,

During a compile or unittest temp files are created in %TEMP% directory of the user.

- pctxxx.pl 3MB
- pctinitxxx.p
- profxxx.pf

These files aren't removed. Since were are starting for each unittest an ABLUnit task, which generates a pctxxx.pl file, the %TEMP% directory grows very quickly to a couple of GB.

PCT Version 210

**Comment by gquerret** [comment]
Temp files are supposed to be deleted after execution. Do you use debugPCT attribute ?

**Comment by lneumeier** [comment]
No. But I will check the user permissions for the %TEMP% directory.

**Comment by gquerret** [comment]
Oh, have a look at the release notes of PCT 211: https://github.com/Riverside-Software/pct/releases/tag/v211

**Comment by lneumeier** [comment]
Okay, Thank you,
