### ISSUE TITLE
ABLDuck - Problem with hierarchie

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#387]
### Subject of the issue
There is a problem with the hierarchie Tree

### Your environment
* Win10
* OpenEdge 11.7.4
* Ant 10
* PCT 213

### Actual behaviour
When my class is like that, I can't see parents methods in documentation :  
`CLASS Hello.Son INHERITS Father:`

But if my class is like that, it works fine : 
`CLASS Hello.Daughter INHERITS Hello.Father:`

But, fun fact, the `Hello.Father` can see his 2 daughter class

### Expected behaviour
The 2 way should work to declare a class.

### Steps to reproduce
See https://github.com/clement-brodu/OEdoc-sample

Thanks

**Comment by gquerret** [comment]
Wrong one...

**Comment by gquerret** [comment]
Merged in master
