### ISSUE TITLE
ABLDuck - encoding

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#388]
### Subject of the issue
We can't define the source file encoding.  
A property to specify it could be usefull.

### Your environment
* Win10
* OpenEdge 11.7.4
* Ant 10
* PCT 213

### Steps to reproduce
See https://github.com/clement-brodu/OEdoc-sample
I have a "é" character in `Hello.Father`

Thanks

**Comment by gquerret** [comment]
Très simple, il y a une faute d'orthographe, il faut écrirer "allez" :-D
