### ISSUE TITLE
ABLUnit: results.xml not found

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#393]
### Subject of the issue
results.xml not found during ABLUnit run.  The session crashes leaving me with no hint as to where the issue is.

### Your environment
Windows 10 Pro 64bit
OpenEdge 12.0 64bit
ANT 1.10.7
PCT v213

### Actual behaviour
During one of the ABLUnit tests, the sessions crashes leaving me with no idea where and why it crashed.  I have one very simple test that runs without issue, but when I add this new test in, it crashes.  I'm probably doing something wrong (I'm a realist), but the logs leave me with no clue where to start looking.  When I copy the test into a procedure editor attached to the same single-user database, I can run the Internal Procedures in the .p and it works as I thought it would.  All of the tests have catch blocks with messages, but none appear in the logs, or on screen.

### Expected behaviour
When the session crashes, I'd expect to have some log or process tell me where the issue was.

### Steps to reproduce
I'll attach as much of the process as possible.

**Comment by wilddoug** [comment]
[ant-v.txt](https://github.com/Riverside-Software/pct/files/4005673/ant-v.txt)
[target.txt](https://github.com/Riverside-Software/pct/files/4005674/target.txt)
[ablunit.log](https://github.com/Riverside-Software/pct/files/4005675/ablunit.log)


[ablunit138625049.txt](https://github.com/Riverside-Software/pct/files/4005676/ablunit138625049.txt)
[profiler192583985.txt](https://github.com/Riverside-Software/pct/files/4005677/profiler192583985.txt)

**Comment by wilddoug** [comment]
[suite-as.p.txt](https://github.com/Riverside-Software/pct/files/4005754/suite-as.p.txt)
[assharedinq.p.txt](https://github.com/Riverside-Software/pct/files/4005755/assharedinq.p.txt)

The test suite procedure and test program...

**Comment by gquerret** [comment]
Are you sure the session is crashing ? The last lines of `ant-v.txt` are:

```
  [ABLUnit] Trying to connect to : -pf D:\Jenkins\workspace\sxdev_gui_trunk\config\widb.pf -ld widb -1
  [ABLUnit] PROPATH : D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\trend,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\common,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\enums,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\twl,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\twl\common,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\twl\common\trigger,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\twl\reports,D:\Jenkins\workspace\sxdev_gui_trunk\gui-build\code\tests,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\trend,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\common,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\enums,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\twl,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\twl\common,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\twl\common\trigger,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\twl\reports,D:\Jenkins\workspace\sxdev_gui_trunk\gui-code\tests,c:\oe_64\120\tty\netlib\OpenEdge.Net.pl,c:\oe_64\120\tty\ablunit.pl,D:\Jenkins\workspace\sxdev_gui_trunk\temp\pct51059163.pl,.,c:\oe_64\120\tty,c:\oe_64\120\tty\adecomm.pl,c:\oe_64\120\tty\adecomp.pl,c:\oe_64\120\tty\adeedit.pl,c:\oe_64\120\tty\adeshar.pl,c:\oe_64\120\tty\dataadmin.pl,c:\oe_64\120\tty\OpenEdge.BusinessLogic.pl,c:\oe_64\120\tty\OpenEdge.Core.pl,c:\oe_64\120\tty\OpenEdge.ServerAdmin.pl,c:\oe_64\120\tty\prodict.pl,c:\oe_64\120,c:\oe_64\120\bin
  [ABLUnit] RUN ABLUnitCore.p
  [ABLUnit]
  [ABLUnit] QUIT statement found
  [ABLUnit] Exit code : 0
```

Which seems to indicate that the session didn't crash, but "just" that the results.xml file is not written. That may be the case if no unit tests are being executed as part of the suite. Can you confirm if this is specific to this test, or if this is the first unit tests that you're writing ?

**Comment by wilddoug** [comment]
In assharedinq.p, there are two tests - one that just looks at simple integers and asserts their values, another that does more work with the database, etc.
When I set the more complex test to "@ignore.", the testing procedure process finishes cleanly and correctly with a results,xml written to the directory.  So I have to assume the problem is the more complex test.  I just cannot figure out where in that test it is failing.
[ant-v.txt](https://github.com/Riverside-Software/pct/files/4017518/ant-v.txt)
[results.xml.txt](https://github.com/Riverside-Software/pct/files/4017522/results.xml.txt)

**Comment by wilddoug** [comment]
I've put messages in the test code, and can see the issue is when it is attempting to run the "@after." test.
The "@before." test runs perfectly, then the "@test". tests all run cleanly.  At the end, it should be running the "@after." code to remove or teardown the records created in the "@before." area.  But it never gets into that internal procedure.
When I have more information, I'll update here.

**Comment by wilddoug** [comment]
I was able to narrow down the issue to running the "@after." annotated internal procedure.  When I move the "@after." internal procedure to the bottom of the .p so it will be run last, and change the "@after." to be "@test.", the entire process works correctly and cleanly.  So the content of the internal procedure hasn't changed, only the annotation...
As soon as I annotate that internal procedure "@after." the process fails and the results.xml is never generated.  I'll attach the final working file.  "destruct" is the internal procedure whose annotation I'm changing from "@test." to "@after." and back again...
[assharedinq.p.txt](https://github.com/Riverside-Software/pct/files/4136386/assharedinq.p.txt)

**Comment by wilddoug** [comment]
And the exact same programs run through the ABLUnit process in the PDSOE cleanly either way.

**Comment by gquerret** [comment]
Will try to setup a test case

**Comment by gquerret** [comment]
I've not been able to reproduce your test. It seems the SX code is probably required to crash the AVM. Will contact you offline.
