### ISSUE TITLE
Ambiguous Class error during db connection

### ISSUE THREAD

**Issue by mzitx** [Riverside-Software/pct#396]
### Subject of the issue
Class ambiguous issue
![sedsa](https://user-images.githubusercontent.com/25603323/72507569-3bda3100-386c-11ea-861a-73fb01cebbd7.JPG)

### Your environment
* Centos 7
* OpenEdge version 11.7.5 
* Ant version 1.9.6
* PCT version 213

### Actual behaviour
I have a db field named class in my database. When I tried <DBConnection> to connect to the database, I got the issue of ambiguous class error.

### Expected behaviour
The db should be connected and compiling should be done.

### Steps to reproduce
Create a table with field name as "class", connect to the db via <DBConnection>

**Comment by gquerret** [comment]
Do you build PCT by yourself ? Or the "official" release from here: https://github.com/Riverside-Software/pct/releases/tag/V213 ?
If you add <PCTVersion /> in your build.xml file,  what is the output ?

**Comment by gquerret** [comment]
In fact, it seems that you compile pctCompile.p on the fly, which is unexpected.

**Comment by mzitx** [comment]
To your first comment, Yes, I have build PCT.jar by myself using Apache-Ant 1.9.6. I also used the .jar file you have provided. But the issue still persists.
I have a "Class" fields on multiple tables on my db. 
The issue persists irrespective of the OS.
![asdfdasf](https://user-images.githubusercontent.com/25603323/72517980-6cc26200-387c-11ea-9bbe-f999bacc52e8.JPG)

**Comment by gquerret** [comment]
I've tried with the official release, and there's no issue. It only happens because you're using your own version, which doesn't contain the rcode for v11. Include <PCTVersion /> in your build, that will tell you the version number you're using.

**Comment by mzitx** [comment]
I think we are having trouble communicating effectively. The program works fine when I connect to a different database ( just a prototype of what I actually need to use). However, when I try to connect production database ( contains multiple tables with field-name **'Class'** example icsel.class ) ant build fails with error code 196. Could you please suggest if the only option I have is to rename all my db fields that match the keyword "Class" ?

**Comment by gquerret** [comment]
I just see that the GitHub formatting removed something from my comments, so I'll try again... Include ```<PCTVersion />``` in your build.xml so that it will display the version number you're using.
You're not using the official build of PCT but a custom one, which does not include the rcode of the PCT procedures. Then it has to compile pct/pctCompile.p, and it fails because of this ambiguous reference to Class.

**Comment by mzitx** [comment]
I have included <PCTVersion /> in my build.xml and this is what I am seeing.
![ad](https://user-images.githubusercontent.com/25603323/72527289-7e156980-3890-11ea-9ff3-27f218d2db02.JPG)

My build.xml:
`<?xml version="1.0" encoding="utf-8"?>
<project name="myproject">
 <property environment="env" />
 <taskdef resource="PCT.properties" />
 <typedef resource="types.properties" />

 <target name="build" description="Builds source files">
 <PCTVersion />
 <PCTCompile destDir="myproject/target/oe" dlcHome="${env.DLC}">
<fileset dir="myproject/src/oe/" includes="*.p" >
  <exclude name="myproject/src/oe/test.p"/> 
  </fileset>
<DBConnection dbName="testdb" dbDir="F:\git\awesome\myproject\src" readOnly="true" />
</PCTCompile>
 </target>
</project>
`
I have a DB with table Customer field Class and Invoice field Class.
And this is what I am seeing when using "ant -v build"
![file](https://user-images.githubusercontent.com/25603323/72527680-6ab6ce00-3891-11ea-96d2-6e080aaf8231.png)

**Comment by mzitx** [comment]
I have used <PCTVersion /> and this is what I am seeing.
![file](https://user-images.githubusercontent.com/25603323/72527885-dac55400-3891-11ea-85c4-84d14c427ecc.png)

My build.xml is :
![sdvsav](https://user-images.githubusercontent.com/25603323/72528099-5de6aa00-3892-11ea-9718-161823dd6d0e.JPG)

 My DB schema is:
Customer table has field "Class" and Invoice table has field "Class"

**Comment by gquerret** [comment]
As I already said, use the official PCT build. 
`<PCTVersion />` will display something like `pct-213-master-something`

**Comment by mzitx** [comment]
I am using official Build.
I have downloaded the official build of PCT and PCT.jar from the link that you have provided as soon as you have given and still the problem persist. 
I downloaded PCT.jar you provided and copy pasted it into the apache-ant/lib/ 
and ran ant -v build 

**[PCTVersion] PCT Version : pct-214-${env.BRANCH_NAME}-${GIT_COMMIT}**

Please tell me as to how to set values for ${env.BRANCH_NAME}-${GIT_COMMIT}.
Also since you didn't faced any issues regarding name conflict from the field "Class".
Can you please post the screenshot of the terminal that you have done.

**Comment by gquerret** [comment]
I don't know your setup, but as long as you get the message `pct-214-...` then you're **not** using the official PCT.jar file. There's probably another pct.jar somewhere in your classpath.

**Comment by mzitx** [comment]
Thanks you so much @gquerret . My problem was finally solved. 
To solve the problem I have used following measures.
1. Used PCT.jar given by you
> https://github.com/Riverside-Software/pct/releases/tag/V213
2. Reinstalled and reconfigured Apache Ant 1.9.6 
This now resolves the error.
