### ISSUE TITLE
Enhancement request: PCTCompile option to not display any file, not even the failed compiles

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#401]
### Subject of the issue
We have a build process where in some stages it is normal to have compile issues.
* Some sources require other sources of the same project to be build first. To solve this we build that project twice. During the first build we want to ignore all errors, persistent compile errors will be shown during the second build
* One project is included in our build process but it is handled by another team that is still on Roundtable. Errors from that project are not relevant to us as that team has other techniques of tracking those issues.

Currently, the log output contains all these errors, but they are not relevant to this build process and can lead to people trying to solve issues in the wrong environment.

In both cases I'm still interested in the summary at the end 

### Actual behaviour
AFAIK display of Compile errors can not be disabled

### Proposed behaviour
An extra value for displayFiles to not show failed compiles either e.g.
* -1 Do not display failed compiles

**Comment by gquerret** [comment]
> Some sources require other sources of the same project to be build first. To solve this we build that project twice. During the first build we want to ignore all errors, persistent compile errors will be shown during the second build

Just wondering, is that a Progress bug?

The outputJson property was introduced recently. Maybe you can use it, and delete the file right after the build.

**Comment by gquerret** [comment]
Using outputType property will be enough for this case.
