### ISSUE TITLE
Loading Sequences

### ISSUE THREAD

**Issue by andrewmostello** [Riverside-Software/pct#402]
### Subject of the issue
Is it possible to load the sequence values dumped by `PCTDumpSequences`? There isn't a separate task for that, and I'm wondering whether that means it's:
* not possible
* not implemented; or
* should be done using PCTLoadData.

Thanks

**Comment by gquerret** [comment]
No specific task, but can easily be done with `PCTRun` and this code:
```
run prodict/load_seq.p ("_seqvals.d", directory_name).
return '0'.
```

**Comment by andrewmostello** [comment]
Ah, perfect. Thank you!
