### ISSUE TITLE
PCTCompile outputType json causes  SYSTEM ERROR: Memory violation. (49)

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#405]
### After adding outputType build crashes
I added `outputType="json"` and now the build process crashes

### Your environment
* Red Hat Enterprise Linux Server release 7.6 (Maipo)
* 12.1
* Ant 1.10.1
* PCT-215.jar

### Actual behaviour
Build crashes and protrace file is generated
```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] SYSTEM ERROR: Memory violation. (49)
[PCTCompile] ** Save file named core for analysis by Progress Software Corporation. (439)
[PCTCompile] Result: 2
```
protrace stack
[protrace.txt](https://github.com/Riverside-Software/pct/files/4274774/protrace.txt)

```
// trimmed, full protrace attached
** ABL Stack Trace **

--> printErrorsWarningsJson pct/compile.p at line 677  (pct/compile.r)
    pct/pctCompile.p at line 93  (pct/pctCompile.r)
    /tmp/pctinit196646576.p at line 161  (/tmp/pctinit196646576.p)
// trimmed

```

### Steps to reproduce
Not sure yet

**Comment by cverbiest** [comment]
I started digging in the code of compile.p and I wonder why the post processing of the json is required

```
hResult = DATASET dsResult:handle.
    hResult:WRITE-JSON("memptr", mptr).
    dsJsonObj = CAST( NEW ObjectModelParser():Parse(mptr), JsonObject).
    dsJsonObj = dsJsonObj:GetJsonObject("dsResult").

    dsJsonObj:Add("compiledFiles", iCompOK).
    dsJsonObj:Add("errorFiles", iCompFail).

    ASSIGN outFile = PCTDir + '/':U + 'project-result.json':U.
    dsJsonObj:WriteFile(outFile).
    SET-SIZE(mptr) = 0.
```

Wouldn't it be easier to add the status to the dataset dsResult ?
```
    CREATE ttProjectStatus.
    ttProjectStatus.compiledFiles = iCompOK.
    ttProjectStatus.errorFiles = iCompFail.

    ASSIGN outFile = PCTDir + '/':U + 'project-result.json':U.
    DATASET dsResult::WRITE-JSON("file", outFile).
```

**Comment by cverbiest** [comment]
I found the issue occurs when the user does not have enough rights on the preprocess directory.
I tried to isolate write-json to a .p to report to Progress tech support but my simple.p does not crash.

**Comment by gquerret** [comment]
> I started digging in the code of compile.p and I wonder why the post processing of the json is required

That really doesn't seem good code, and there's no reason to do that.

> Wouldn't it be easier to add the status to the dataset dsResult ?

Definitely yes, can you open a PR if you have time for that ?

**Comment by gquerret** [comment]
> I found the issue occurs when the user does not have enough rights on the preprocess directory.

Why do you write to the preprocess directory ?

**Comment by gquerret** [comment]
@cverbiest Can you try [build 618](https://ci.rssw.eu/job/PCT/job/master/618/) ?
The code managing JSON output has been improved.
