### ISSUE TITLE
PCTCompile allow multiple outputTypes

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#406]
### PCTCompile allow multiple outputTypes
With `outputType=json` compile errors are no longer logged to the screen.

I'd like to process the json file to mail errors to the appropriate developer but I'd still want to see the errors in the jenkins log.

It would be nice if multiple outputTypes could be selected e.g.  `outputType=echo,json`.

### Your environment
* Operating system and version
* OpenEdge version 12.1
* Ant version 1.10.1
* PCT version 215

### Actual behaviour
Selecting json output stops echo to the screen

### Expected behaviour
It should be possible to have both.

#### Looking for feedback before I try to add this myself

**Comment by gquerret** [comment]
+1 for me

**Comment by gquerret** [comment]
Merged in master
