### ISSUE TITLE
Add parameter -baseADE to PCTrun

### ISSUE THREAD

**Issue by KiltedKanuck** [Riverside-Software/pct#407]
### Subject of the issue
As a DevOps engineer I want to be able to specify the ADE r-code directory to the client so the client can add this directory and all procedure libraries contained in the directory to the PROPATH

### Your environment
* All
* 12.2
* 1.10.7
* pct-212-master-bf2b096f45e37bd8e52fffa32e83d8ecb830b8cb

### Actual behaviour
Currently you have to write the -baseADE and directory to a flat file. Include that flat file as a parameter file. When execution is complete, you must clean up that flat file

### Expected behaviour
Add an option to pass -baseADE to PCTRun as a run-time parameter

**Comment by KiltedKanuck** [comment]
I am more than happy to code this. What branch would you like to work in?

**Comment by gquerret** [comment]
You can use `<Option name="-baseADE" value="/path/to/directory" />` in any PCTRun task, no need to add the option in PCT.

**Comment by gquerret** [comment]
But you can still contribute code to PCT for `-baseADE` handling. It's just that if there's nothing on top of just "passing" the parameter to the AVM, then using `<Option>` is just fine.

**Comment by KiltedKanuck** [comment]
I will give the Option a try. I mainly need it for ABLUnit which inherits from PCTRun.

**Comment by KiltedKanuck** [comment]
Option works perfectly. Merci
