### ISSUE TITLE
Question - multi thread and class compilation

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#408]
Hello,

I'm working with PCT 215.

I need to compile a lot of classes (thousands), and Opendge compilation is very slow.

To improve it, I use the `numThreads` parameter (and `multicompile`)

I know you don't recomand it for class :
>  numThreads : Starts n parallel compilation threads. Don't use multiple threads when compiling classes.

But, after weeks of test, most of the time, it works fine.

But some times I have invalid rcode that are produced.

### My case : 
I have 2 classes Father and Son that inherits form fatfher
```
src/Father.cls
src/Son.cls
```
I build in an empty directory, and each thread compile 1 file.

But the thread who has `Son.cls` also compile `Father.cls`.
It's the default behavior : 
> When you compile a class definition file, ABL compiles the class definition file identified in the COMPILE statement and all class files in its inherited class hierarchy, by default.

I thinks there is a conflict between the 2 threads and I think it's why I have invalid rcode.
But it's not systematic.

### My Solutions ?

I search solutions and I found those 2 options : 
* each thread compile in a different temp directory and then I copy the rcode to the destdir
    * not easy to implement, I have not choose this one for now.
* I add a task to scan all rcodes after the compilation, and I parse it with your rcode-reader (I copy it from your sonar plugin). If the rcode is invalid, the build crash.
    * Here is the result : https://github.com/clement-brodu/pct/tree/feat/checkRCode

What do you think about this ?

Have you got some advices to build thousands classes faster ?

Thanks

**Comment by gquerret** [comment]
How slow is "very slow" ? How many classes exactly ?

**Comment by clement-brodu** [comment]
I have 2 450 classes in my project.

I made tests to compile with one thread only, but it never succeed, I always have this error :
```
16:49:24  [PCTCompile] Exception non g�r�e�: System.Runtime.InteropServices.SEHException: Un composant externe a lev� une exception.
16:49:24  [PCTCompile]    � _CxxThrowException(Void* , _s__ThrowInfo* )
16:49:24  [PCTCompile]    � Progress.ClrBridge.BrgTypeInspector.Inspect(BrgTypeInspector* , SByte* A_0)
16:49:24  [PCTCompile] Result: -1073741819
```

But before this error, it compile approximately 2250 classes in 50 min

**Comment by gquerret** [comment]
There might be more information in the protrace file, and that has to be reported to Progress if you can report it everytime you execute the build.

Try also compiling with multiCompile and a large -D.

**Comment by gquerret** [comment]
Did you try this option ?

**Comment by clement-brodu** [comment]
Here are some protraces :
[Protrace.zip](https://github.com/Riverside-Software/pct/files/4438514/Protrace.zip)

I tried with a `-D 4000` and the job succes, it seems it's the solution for `System.Runtime.InteropServices.SEHException`.

But it spend 26m with 1 thread, instead of 3min with 12 thread.

**Comment by gquerret** [comment]
Do you use multiCompile ? And there's a S: in the protrace files, is that a local drive ?
If you still want to fail the build, I'd recommend to do that as part of your script, you can even do that with Groovy.

**Comment by clement-brodu** [comment]
Yes I have set `multiCompile=true` a long time ago.

S: is a shared drive on our server that contains sources. We started to use git for some of our projects, but it's not easy for this one, we need to learn git to many people.

Indeed, may be I can try to do this in my pipeline librairy.
