### ISSUE TITLE
ProgressVersion "bitness" is missing

### ISSUE THREAD

**Issue by PeterJudgeZA** [Riverside-Software/pct#410]
### Subject of the issue
When trying to access the bitness , PCT errors. This is either a doc bug or a product bug .

The doc at https://github.com/Riverside-Software/pct/wiki/ProgressVersion describes the usage of this attribute.

The snippet below 
```
    <DlcHome value ="${env.DLC}" />
    <ProgressVersion majorVersion="dlc.major" minorVersion="dlc.minor" revision="dlc.sp" patchLevel="dlc.patch" bitness="dlc.bits" />
```

produces 
```
build.xml:24: ProgressVersion doesn't support the "bitness" attribute
```

### Your environment
* Windows 10
* OpenEdge 11.7.5
* Ant 1.9.8
* PCT 211 (my  bad)

### Expected behaviour
It should be possible to retrieve the bitness of the DLC executable used from the ProgressVersion task. This is only pertinent on Windows, since all other platforms are 64-bit.

It is good to know what bitness is in use , for echo or descriptive purposes, since the ABL's PROCESS-ARCHITECTURE preprocessor may be used by the application/code. This is different to the OS bitness  since OE on Windows supports 32- and 64-bit installs.

**Comment by gquerret** [comment]
Attribute was added in commit bf8aa108fa71238ae728e6cf5351dca35ced198b so it should be supported in v212. Unit tests are successful, and I've just executed the task locally (successfully). Can you confirm you're using the right version ?

**Comment by gquerret** [comment]
However, value is only useful on v10, as written in the doc. Specifically, I was looking for a quick and portable way to find which version was installed, but didn't find one. The reliable solution was to use PROCESS-ARCHITECTURE, which wasn't quick (AVM might not be instantiated). The quick solution was to look for prowin32, but that wasn't portable. If you have a good solution, feel free to post it :)

**Comment by PeterJudgeZA** [comment]
It's only Windows that has a 32-bit version, so maybe "prowin32 exists" is a good enough check. I assume that this won't work before 11.5 (? when you could have >1 install of the same version on Windows).

**Comment by gquerret** [comment]
Having a look at the code, I see that the attribute was only used internally, in order to find which rcode version should be used. Attribute wasn't used after v11 as rcode was the same in 32 and 64 bits. The commit I've mentioned just made the value visible from Ant scripts, even though it doesn't really make a lot of sense. I think I have a conversation somewhere about that in my inbox.

**Comment by gquerret** [comment]
Maybe this conversation: https://github.com/Riverside-Software/pct/issues/264

**Comment by gquerret** [comment]
Documentation has been updated
