### ISSUE TITLE
ProgressVersion uses tty/prostart.r which does not exist in pre-release versions

### ISSUE THREAD

**Issue by KiltedKanuck** [Riverside-Software/pct#411]
### Subject of the issue
ProgressVersion looks for tty/prostart.r. 

### Your environment
* Linux and NT64
* 12.3
* Gradle 6.1.1
* PCT-215

### Actual behaviour
PCTCompile run ProgressVersion which looks to read tty/prostart.r. This is fine for the CDImage of openedge. However when we are using PCT to compile against an unreleased version (12.2 or 12.3) the file tty/prostart.r does not exist in the pre-release package. Therefore we cannot use PCT to compile pre-release versions.

### Expected behaviour
1. ProgressVersion should look to find tty/prostart, and if it does not exist skip whatever it is doing
If rcode is truly needed for ProgressVersion then we can identify one that is always in the build

### Steps to reproduce
remove tty/prostart.r from your propath and execute PCTCompile

**Comment by gquerret** [comment]
It has been found years ago (at the beginning of PCT) that this rcode was always present on disk, and rcode version is the most reliable way to determine the Progress version. Building rcode when tty/ is not present was not the first use case of PCT.
It may be possible to find an option so that it doesn't fail at this point, but that's not the only required change.

**Comment by stefandrissen** [comment]
How about Progress provide the internal format of progress.cfg so that the [platform porting number](https://knowledgebase.progress.com/articles/Article/000025657) can be read directly from it?

**Comment by KiltedKanuck** [comment]
@gquerret This is only an issue for pre-release code [12.3 branch]. When we build OE in our internal environment the executable _progres and prowin are packaged alone. We use that package to build the r-code dependencies such as 'corelib' 'ade' 'ablunit' etc.  If prostart does not exists, perhaps PCT can 'skip' that bitness test instead for stopping.

**Comment by gquerret** [comment]
@KiltedKanuck This means that source code would have to be used in this case, as the rcode file format might be incompatible. But the ProgressVersion class has to be changed in order to handle that.

**Comment by gquerret** [comment]
Fixed
