### ISSUE TITLE
Add 'obsolete' tag on properties / methods / classes in AssemblyCatalog

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/pct#413]
In order to flag obsolete method calls in CABL, it would be good to have an 'obsolote' flag on properties / methods / classes in AssemblyCatalog task. It could be as simple as a boolean flag, but Java for example has a message associated, which could be displayed in SonarQube and SonarLint.

**Comment by mikefechner** [comment]
.NET provides an optional message too and the ability to cause a compile-error for the use of an obsolete method.

https://docs.microsoft.com/en-us/dotnet/api/system.obsoleteattribute?view=netframework-4.8

**Comment by mikefechner** [comment]
SCL-3001

**Comment by mikefechner** [comment]
Gilles, there's a challenge. Currently we only export method names, not arguments. So overloaded methods are only appearing once. Now the Obsolete attribute may or may not appear per overloaded variant of the method. 

And there are plenty of cases where ToString() is _not_ obsolete, but ToString(formatprovider) _is_ obsolete. Just to name a prominent example.

OK, to have overloaded methods appearing multiple times and adding the argument types to the method name?

**Comment by gquerret** [comment]
I'll have to recognize the signature in ABL, so we need conventions for argument types. I know that Java has a convention: https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.3.2
Is there such a convention in .Net ?

**Comment by mikefechner** [comment]
How about this, with OUTPUT on an (rare) output parameter:

```
      "ToString ()",
      "ToString (System.String, System.IFormatProvider)",
```

What else do you need?

**Comment by mikefechner** [comment]
And this would be an example with an obsolete method. Just let me know, how you need the data and I'll implement it that way.

```
    "name": "System.Windows.Forms.DpiAwarenessContext",
    "isAbstract": false,
    "isClass": false,
    "isEnum": true,
    "isInterface": false,
    "methods": [
      "GetHashCode ()",
      "ToString ()",
      {
        "name": "ToString (System.String, System.IFormatProvider)",
        "obsolete": {
          "message": "The provider argument is not used. Please use ToString(String).",
          "error": false
        }
      },
      "CompareTo (System.Object)",
      {
        "name": "ToString (System.IFormatProvider)",
        "obsolete": {
          "message": "The provider argument is not used. Please use ToString().",
          "error": false
        }
      },
      "HasFlag (System.Enum)",
      "GetTypeCode ()",
      "Equals (System.Object)",
      "ToString (System.String)",
      "GetType ()"
    ]
```

**Comment by gquerret** [comment]
Seems good. What will you use for basic data types ?

**Comment by mikefechner** [comment]
Primitive data types? I could map System.String to "CHARACTER" etc..

Note that in above sample, there is a "ToString ()" (string in the JSON array) which is _NOT_ obsolete and the obsolete variant "ToString (System.IFormatProvider)" which is represented as a JSON object to return the message and IsError flag from the Obsolte Annotation

**Comment by mikefechner** [comment]
Modified code is in https://github.com/consultingwerk/pct

**Comment by gquerret** [comment]
Excellent ! I'll include that in the main repo as quickly as possible.

**Comment by gquerret** [comment]
Is it possible to skip methods coming from parent classes ? The two obsolete versions of `ToString` are duplicated everywhere in the file.

**Comment by mikefechner** [comment]
> Is it possible to skip methods coming from parent classes

Sure thing. Changes are on https://github.com/consultingwerk/pct

Note, I've also made a small change to the procedure src\progress\pct\assembliesCatalog.p as now we'll need to include the core .NET framework assembly, so that type like System.Object and inherited methods like ToString() are present at least once in the output. 

Output for "our" Assemblies has shrunk from 81 to 36 MB.

**Comment by gquerret** [comment]
I'll have to change a bit the JSON structure so that I can read it automatically in Java. I've already modified the code locally, can you open a PR so that I can push it in your repo ?

**Comment by mikefechner** [comment]
> I'll have to change a bit the JSON structure so that I can read it automatically in Java.

Is that done already?

**Comment by gquerret** [comment]
Yes, I've just merged in origin/master. Thanks for your PR !
