### ISSUE TITLE
PCTCompile - a thread crash but the task doesn't fail

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#415]
### Subject of the issue
When a compilation thread crash, the task didn't fail in multithread

### Your environment
* Windows 10
* OpenEdge 11.7.4
* Ant 10
* PCT 215

### Actual behaviour
When I'm using multi thread compilation, I had a thread that stop for an unknown reason (a protrace is generated).

But the compile task didn't fail.

Here is the log : 
![image](https://user-images.githubusercontent.com/37274615/83638205-1ba3d800-a5a9-11ea-8570-665e89f5e0ea.png)

At the end I have "117 file(s) compiled" but there is 118 files in the folder, and it crash with one file (for an unknown reason, but it's not the point here).

If I'm in single thread mode, the task fail (it's better)

### Expected behaviour
It should fail if a thread is down.

May be we could detect "connection reset" in the log ?

### Steps to reproduce
Very difficult.

**Comment by gquerret** [comment]
Fixed in a4f73d6, please try one of the Jenkins builds after this commit.
