### ISSUE TITLE
Enhancement request: ABLDuck option to exclude external functions from documentation

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#417]
I noticed that AblDuck now also documents procedures.
Thank you it looks great.

I detected following issue , 

### External functions appear in documentation of a procedure

When we use a library  (persistent procedures) in our code we include a file containing the function definitions of that library. The documentation of a procedure also shows all functions present in the libraries used by that procedure.

What our framework does for libraries basically boils down to
```
/* mylibrary.i */
run mylibrary.p persistent set LIBRARY-HANDLE.
this-procedure:add-super-procedure(LIBRARY-HANDLE).
function libraryfunction returns character () in LIBRARY-HANDLE.
```

```
/* mylibrary.p */
function libraryfunction returns character () : 
/* documentation comment */
    return "myresult".
end function.

procedure libraryfunction : 
/* documentation comment */

end procedure .
```

### Your environment
* oe12.2
* PCT version : Latest

### Actual behaviour
Documentation for libraryfunction is generated for the procedure using the library

### Expected behaviour
Only functions actually coded in the procedure are shown

### To reproduce
I'll try to set up a sample project demonstration this.

**Comment by gquerret** [comment]
@spazzymoto Also for you :)

**Comment by spazzymoto** [comment]
I will take a look with my current refactor. Was just about to start the procedures side :)

**Comment by gquerret** [comment]
Won't be fixed in AblDuck (unless @spazzymoto takes care of it), and issue is not present in JsonDocumentation.
