### ISSUE TITLE
Enhancement request: ABLUnit should print the failed assert:equals details

### ISSUE THREAD

**Issue by SpaceNinjaApe** [Riverside-Software/pct#421]
### Subject of the issue
Feature-Request: (PCT) ABL-Unit should tell us the expected and actual values of an Failed assert-equals.

### Actual behaviour
At this time it only tells us which @Test function fails.
```
<testcase name="testName" status="Error" time",001">
     <error> Equals Assert at line xxx </error>
</testcase>
```

### Expected behaviour
Like in the Original ABL it should tell us the expected and actual value. If possible the line number aswell.
```
<testcase name="testName" status="FAILURE" time",001">
     <failure> Value x does not equal y at line xxx </failure>
</testcase>
```

Current workaround would be to write a catch in every test and print out the Error manually. I would like to avoid this.

Keep up the good work!

**Comment by SpaceNinjaApe** [comment]
For anyone interested:
If you're Running OE 11.6 and try to start the ABL Unit from Progress via ant, you will run into a `java.lang.NumberFormatException` which seems to be a bug in dlc/java/ant-ablunit.jar XMLUtilities.class

**Comment by gquerret** [comment]
I won't have time to have a look at this issue this week, but I'd like to confirm: do you use the ABLUnit task from PCT ? Or the one provided by Progress ? Your comment seems to indicate the latter.

**Comment by SpaceNinjaApe** [comment]
@gquerret im using the one that PCT provides. After i noticed that it's not the same i tried out the ABLUnit provided  by Progress. But as i stated its buggy so we hope for an PCT update. And just to clarify: this is an enhancement request. PCT ABLUnit is working just fine but could be improved.

**Comment by gquerret** [comment]
I'd like to confirm what you'd like to see ; current Ant output is similar to:
```
test:
  [ABLUnit] QUIT statement found
  [ABLUnit] Total tests run: 3, Failures: 1, Errors: 1
```

No details about the failures and errors. Details are in the results.xml file. What you'd like to see is something like:
```
test:
  [ABLUnit] QUIT statement found
  [ABLUnit] Total tests run: 3, Failures: 1, Errors: 1
  [ABLUnit]   eu.rssw.ABLUnitTest:test2 - Failure - Expected: TRUE but was: no
  [ABLUnit]   eu.rssw.ABLUnitTest:test2 - Error - ** Invalid character in numeric input (76)
```
So that you don't have to open the results.xml file for details ?

**Comment by SpaceNinjaApe** [comment]
Interesting! This is nothing like what i see in the result.xml. What Assert are you using?
![image](https://user-images.githubusercontent.com/28253325/88634156-4f394500-d0b6-11ea-868d-ffcd737926a8.png)
Just noticed that this is not the same function that actually runs:
`<error>Equals Consultingwerk.Assertion.Assert at line 592`

Seems that i first have to bypass this.

**Comment by SpaceNinjaApe** [comment]
Ok seems like this **problem is not related to PCT** itself. It's rather a problem related to Consultingwerks Assert
