### ISSUE TITLE
dbalias not used when compiling with more than 1 thread

### ISSUE THREAD

**Issue by piedabee** [Riverside-Software/pct#422]
### Your environment
* Operating system and version W10
* OpenEdge version 11.7.5
* Ant version 1.9.8
* PCT version 215

### Actual behaviour
When I compile my codebase PCTCompile with 1 thread everything compiles ok, but when I compile with more than 1 thread I get errors on code that uses a dbalias instead of the logical databasename.

### Expected behaviour
Compilation should be without errors, regardless of the number of threads used.

### Steps to reproduce
* Write some code (several procedure-files) that uses an alias instead of the actual logical databasename (say "sporty"  instead of "sports2000").
* connect to the database via a .pf-file that is referenced in the PCTCompile-task.
* Define the alias-name with `<dbalias name="sporty" value="sports2000"/>`
* Compile all the sources with numThreads="1" => everything should be OK.
* Compile all the sources with numThreads="4" => The sources with the alias produce a compilation-error stating: Unknown database name "sporty"

**Comment by gquerret** [comment]
Wasn't able to reproduce locally. I'll try to add the test to the full set, and see how it goes.

**Comment by gquerret** [comment]
Confirmed, `DBAlias` nodes are not handled in PCTBgRun (and thus multi-threaded PCTCompile). Will be fixed.

**Comment by gquerret** [comment]
Fixed, merged in master.

**Comment by piedabee** [comment]
Will this become available as a new PCT-version under https://mvnrepository.com/artifact/eu.rssw.pct/pct ?

**Comment by gquerret** [comment]
216 will be available on Maven Central, but there's no release date for now. You can download snapshots from https://ci.rssw.eu/job/pct/job/master/
