### ISSUE TITLE
PCTSchemaDoc links broken

### ISSUE THREAD

**Issue by psoverbey** [Riverside-Software/pct#424]
### Subject of the issue
Example links for PCTSchemaDoc are broken.

### Your environment
* Operating system and version
* OpenEdge version
* Ant version
* PCT version

### Actual behaviour
Links produce 404 errors.

### Expected behaviour
Links work.

### Steps to reproduce
Navigate to https://github.com/Riverside-Software/pct/wiki/PCTSchemaDoc and click on the Description links.

**Comment by gquerret** [comment]
Fixed, thanks !
