### ISSUE TITLE
Weird problem with a single procedure: Exception code: C0000005 ACCESS_VIOLATION

### ISSUE THREAD

**Issue by W1nstar** [Riverside-Software/pct#430]
### Your environment
Windows 10 Pro 1903
OpenEdge Release 11.7.3 as of Fri Apr 27 17:40:05 EDT 2018
Apache Ant(TM) version 1.10.1 compiled on February 2 2017
PCT V213

### Actual behaviour
I've been using PCT for years, never encountered any problem. Somehow, a single program can't be compiled by PCT, but it compiles fine in any prowin. The source code hasn't changed since 2016, and the machine has only suffered changes made by windows update.

Any PCTCompile ends up generating a protrace, wich shows this error: 
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FFB4A9B16E9 01:00000000000006E9 C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll

I've updated java, vcredist and windows update, but nothing has worked. I've tried, so far:

Changed the source code to another disk.
I've confirmed the source code compiles (and executes) just fine in any prowin.
Made sure the ant target does not not use xref or listings, as I saw here https://knowledgebase.progress.com/articles/Article/Compile-XREF-can-crash-when-the-include-file-is-unavailable that it can crash. 
I've tried putting the include code inside the source procedure.

So far, nothing has worked. It always crashes the prowin.

This is the full protrace:

```
=====================================================
PROGRESS stack trace as of Wed Oct 21 15:39:25 2020
=====================================================

Progress OpenEdge Release 11.7 build 1592 SP03 on WINNT 

Startup parameters:
-pf C:\dlc117_64\startup.pf,-cpinternal ISO8859-1,-cpstream ISO8859-1,-cpcoll Spanish9,-cpcase Basic,-d dmy,-numsep 46,-numdec 44,(end .pf),-b,-q,-cpinternal 1252,-param C:\Users\marcosg\AppData\Local\Temp\pct_params127075948.txt,-assemblies C:\proyectos\gomanage\dll,-p C:\Users\marcosg\AppData\Local\Temp\pctinit104793698.p

Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FFB4A9B16E9 01:00000000000006E9 C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll

Registers:
RAX:0000000000000020
RBX:0000000000000400
RCX:0000000000000400
RDX:0000000000000020
RSI:000001EFDD3DAD80
RDI:0000000000000000
R8 :00000000FB9F7AC7
R9 :0000000000000236
R10:000000004A9B1000
R11:00007FFB4A9B0000
R12:0000000000000080
R13:000000000000F000
R14:0000002000001000
R15:0000000001000000
CS:RIP:0033:00007FFB4A9B16E9
SS:RSP:002B:00000095C00FCF70  RBP:00000095C00FD0B0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202


Debugging dll: C:\dlc117_64\bin\DBGHELP.DLL
Symbol Path:
 C:\dlc117_64\bin;C:\dlc117_64\pdbfiles


Call Stack:
Address           Frame
00007FFB4A9B16E9  00000095C00FCF70  memcpy+3F9
00007FFAFB9DE45B  00000095C00FCFA0  dbut_chrcop+1B
00007FFAFB919107  00000095C00FD310  dbut_utSetNumFiles+14B0D7
00007FFAFB5DB3E1  00000095C00FD550  ProStartup+42041
00007FFAFB5AF3B8  00000095C00FD760  ProStartup+16018
00007FFAFB5B0244  00000095C00FD970  ProStartup+16EA4
00007FFAFB5B0244  00000095C00FDB80  ProStartup+16EA4
00007FFAFB5B0244  00000095C00FDD90  ProStartup+16EA4
00007FFAFB5B0244  00000095C00FDFA0  ProStartup+16EA4
00007FFAFB6096BC  00000095C00FE040  ProStartup+7031C
00007FFAFB93DE7E  00000095C00FEA70  sm_oearchPrepro+1A9E
00007FFAFB8250A4  00000095C00FEB80  dbut_utSetNumFiles+57074
00007FFAFB826BB2  00000095C00FF240  dbut_utSetNumFiles+58B82
00007FFAFB827472  00000095C00FF330  dbut_utSetNumFiles+59442
00007FFAFB8A43DA  00000095C00FF360  dbut_utSetNumFiles+D63AA
00007FFAFB827901  00000095C00FF3A0  dbut_utSetNumFiles+598D1
00007FFAFB80C956  00000095C00FF680  dbut_utSetNumFiles+3E926
00007FFAFB899405  00000095C00FF730  dbut_utSetNumFiles+CB3D5
00007FFAFB8A43DA  00000095C00FF760  dbut_utSetNumFiles+D63AA
00007FFAFB55AA6F  00000095C00FF790  dbut_utsetuid+724F
00007FFAFB4FDF89  00000095C00FF9A0  update_srvrLoggingLevel+1A7D9
00007FF7EFFD1131  00000095C00FFC30  0001:0000000000000131 C:\dlc117_64\bin\prowin.exe
00007FF7EFFD1377  00000095C00FFC70  0001:0000000000000377 C:\dlc117_64\bin\prowin.exe
00007FFB52C77C24  00000095C00FFCA0  BaseThreadInitThunk+14
00007FFB5420CEA1  00000095C00FFD20  RtlUserThreadStart+21


** ABL Stack Trace **

--> pctcomp.p at line 10  (C:\Users\marcosg\AppData\Local\Temp\pctcomp140865283\pctcomp.p)
    compileXref pct/compile.p at line 533  (pct/compile.r)
    pct/pctCompile.p at line 82  (pct/pctCompile.r)
    C:\Users\marcosg\AppData\Local\Temp\pctinit104793698.p at line 66  (C:\Users\marcosg\AppData\Local\Temp\pctinit104793698.p)

** Persistent procedures/Classes **

Handle  File Name
001001  pct/compile.r

** PROPATH **
c:\proyectos\e-commerce-5b\ABL,C:\proyectos\gomanage,C:\proyectos\gomanage\11206,C:\proyectos\gomanage\11206E,C:\Users\marcosg\AppData\Local\Temp\pctcomp140865283,C:\Users\marcosg\AppData\Local\Temp\pct56470626.pl,.,C:\dlc117_64\gui,C:\dlc117_64\gui\ablunit.pl,C:\dlc117_64\gui\adecomm.pl,C:\dlc117_64\gui\adecomp.pl,C:\dlc117_64\gui\adedesk.pl,C:\dlc117_64\gui\adedict.pl,C:\dlc117_64\gui\adeedit.pl,C:\dlc117_64\gui\adeicon.pl,C:\dlc117_64\gui\aderes.pl,C:\dlc117_64\gui\adeshar.pl,C:\dlc117_64\gui\adeuib.pl,C:\dlc117_64\gui\adeweb.pl,C:\dlc117_64\gui\adexml.pl,C:\dlc117_64\gui\dataadmin.pl,C:\dlc117_64\gui\OpenEdge.BusinessLogic.pl,C:\dlc117_64\gui\OpenEdge.Core.pl,C:\dlc117_64\gui\OpenEdge.ServerAdmin.pl,C:\dlc117_64\gui\prodict.pl,C:\dlc117_64\gui\protools.pl,C:\dlc117_64,C:\dlc117_64\bin

** Databases (logical/type/physical) **
   tlmp-c              PROGRESS  E:\basesCompila\tlmplus
   tlmp-1              PROGRESS  E:\basesCompila\tlmplus1
   tlmp-gd             PROGRESS  E:\basesCompila\tlmp-gd

** End of Protrace **
```

### Expected behaviour
This code's been compiled by PCT no problem for years, should continue to do so.

### Steps to reproduce
Can't share the file that does not compile, I'd like directions.

Thank you.

**Comment by gquerret** [comment]
Just in case, could you test with PCT v215 ?
The PCTCompile node where there's a failure will be useful too.
.Net code ? Classes ? Plain old .p and .w ?

**Comment by gquerret** [comment]
And does it fail on a single build agent ? Or on every development machine ?

**Comment by W1nstar** [comment]
Just tested it with 215, same error. 

I got it tested today on another machine, and **It does not error in another dev machine**. I am in the process of getting another machine ready to test, but I have to get this machine working and I don't really know what to look for.

This is the PCT ant node that I'm using to test:

	<target name="test">
	
		
		<PCTCompile displayFiles="2" destDir="c:/Progress/WRK/r2/" numThreads='1' dlcHome="C:\dlc117_64" cpinternal="1252" forceCompile="${fCompile}" graphicalMode="true"  assemblies="C:\proyectos\gomanage\dll">
            <DBConnectionSet refid="bases11act" />
            <fileset dir="c:/proyectos/e-commerce-5b/ABL">
                <include name="p10ecpccab12app.p" />
            </fileset>
            <propath>
                <pathelement path="c:/proyectos/e-commerce-5b/ABL;C:/proyectos/gomanage;C:/proyectos/gomanage/11206;C:/proyectos/gomanage/11206E"/>
            </propath>
        </PCTCompile> 
 
	
	</target>

The DBConnectionSet is pointing to empty databases. Same databases are used by both machines.

The code is a plain old .p with includes and nothing out of the ordinary in them, just functions, procedures and nothing else.

**Comment by gquerret** [comment]
```
> <fileset dir="c:/proyectos/e-commerce-5b/ABL">
>   <include name="p10ecpccab12app.p" />
> </fileset>
```

So it crashes when it compiles a single file ? If no .net code, could you try without the assemblies attribute ? Your stacktrace also mentions:
```
Progress OpenEdge Release 11.7 build 1592 SP03 on WINNT 
```

Are you sure you're using 11.7.3 ?

**Comment by W1nstar** [comment]
Tried without assemblies, fails the same. Prior to this I tried deleting all the \temp folder, and also fails. 

Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FFB4A9B16E9 01:00000000000006E9 C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll

Yes, 11.7.3 is the version I have installed. 11.7.3 is the version the proenv at at C:\dlc117_64\bin shows.

It seems like it's related to the code itself. There's a few for each, a few buffer-copy, some find exclusive and assign. If I delete one for each, it works. If I undo, and delete some other for each, it also works. I undo again, delete some find and assign, it works. Undo again, I delete some random assign sentence, and it compiles. 

I put it all together, and fails. Wich is what makes it weird because this source code dates from 2016 and has been compiled many, many times, on this machine... and of course it worked on our clients. It's a procedure that copies records from one table to another, nothing out of the ordinary here. 

Any idea? I can send it to you if you give me some email address.

**Comment by stefandrissen** [comment]
If you preprocess the file first, and compile the preprocessed file, does it crash?

**Comment by W1nstar** [comment]
> If you preprocess the file first, and compile the preprocessed file, does it crash?

Yes, it crashes. I set the additional attributes preprocess="true" and it generates a preprocess file in destDir\.pct and turns out that file is incompletely written, like it stopped mid-writing a sentence. That sentence isn't include code, and it's the line number 163. We have way longer .p's.

**Comment by stefandrissen** [comment]
When you preprocess the file in "manually" on that same machine with identical propath and other settings it does not crash?

**Comment by gquerret** [comment]
You can also open an issue with Progress Tech Support ; the AVM is crashing, you have a stacktrace, so they should be able to do something with that.
It's not the first time that such a weird behavior occurs. It usually involves .Net... You can try to increase maximumMemory and dirSize attributes, it has some impact on the build process. But I have in mind a recent example where I had to modify source code to be able to compile it correctly on the build server, as the existing version of the procedure kept producing wrong output on the build server (Windows version being the only difference between both servers).

**Comment by W1nstar** [comment]
> When you preprocess the file in "manually" on that same machine with identical propath and other settings it does not crash?

It does not crash. Gets preprocessed normally. Compiles (and works) just fine.


> You can also open an issue with Progress Tech Support ; the AVM is crashing, you have a stacktrace, so they should be able to do something with that.
> It's not the first time that such a weird behavior occurs. It usually involves .Net... You can try to increase maximumMemory and dirSize attributes, it has some impact on the build process. But I have in mind a recent example where I had to modify source code to be able to compile it correctly on the build server, as the existing version of the procedure kept producing wrong output on the build server (Windows version being the only difference between both servers).

I'm gonna look into those attributes.
