### ISSUE TITLE
Question - PCT & Groovy in Jenkins Pipeline

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#431]
### Subject of the issue
Hello,
I'm trying to migrate my build process from pure "ant" to Groovy (like you explain here https://github.com/Riverside-Software/pct/wiki/Using-PCT-with-Groovy).

I'm using Jenkins and I have some difficulties : 

- I can't use PCT task in groovy, but It works with ant :

OK -> This works
```
 withAnt(installation: 'Ant 1.10.5') {
    bat 'ant build'
}
```

KO -> `        ant.taskdef(resource: 'PCT.properties')` this line throw an exception, probably because Jenkins doesn't use the ant instance I want

- If I try to call a simple "echo", it seems to work, but I have no messages in Console Output. (not very practical to know what happen).
```
    def ant = new AntBuilder()
    ant.echo('hello from Ant!')
```

Do you have some advice or some examples for those 2 problems ?

Thanks,

**Comment by gquerret** [comment]
Your first example is a declarative Jenkins pipeline, which is based on Groovy, but still a different syntax from pure Groovy. WithAnt just inject Ant environment for the node where you're executing your code. If you want to execute Groovy code, you have to execute `java -jar groovy-pct.jar script.groovy parameters...`

**Comment by clement-brodu** [comment]
ok thank you for the answer, 
I had not considered this option yet.

It seems to be the solution, but for now I still have problems because I would like to store my script in a shared library to avoid duplication in all my projects.
I need to find a way to do this...
