### ISSUE TITLE
Strict compile options as error not working

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/pct#432]
I want to enable a few strict compile options as error when building with pct.
The options in the pctcompile statement only output as warning when set to true so thats no option.
I tried using the `<Option>` tag to set the -compileroptionsfile parameter but that doesn't seem to work.

```
<pctCompile
  ....
>
<Option name="-compileroptionsfile" value="C:\Temp\PCT_Test\CompilerOptions.txt" />
....
</PCTCompile>
```

Content of the options file:
```
require-field-qualifiers:error,
require-full-names:error,
require-return-values:error
```

I'm pretty sure this worked in the past but doesn't seem to do anything at the moment

### Your environment
* Windows 10
* OpenEdge 12.2.2
* PCT-215

**Comment by gquerret** [comment]
Yes, there's a problem when passing compilerOptionsFile : https://github.com/Riverside-Software/pct/issues/385#issuecomment-557614105
IIRC, it works if you pass those options with the `<Option>` node

**Comment by movedoa** [comment]
Isn't the option node only for command line parameters?
Could you give me an example how to set these options in the compile statement?

**Comment by movedoa** [comment]
Do you mean setting the requireReturnValues="TRUE" option in the PCTCompile node?
Because that only outputs warnings, i want the build to fail

**Comment by gquerret** [comment]
Those compiler warnings are in fact hard-coded so that they never fail the build. My initial answer was wrong. It will require code changes to make that possible. I can put that in the backlog.

**Comment by movedoa** [comment]
FYI It would be best for me if -compileroptionsfile would be working since it is a great way to have the options in one place and allows for a dynamic behaviour.

Maybe you could only set the options in the compiler when one of the attributes is set?

**Comment by gquerret** [comment]
I'll have a look if it's possible to do that, as there's already some clumsy code handling those options in various OE versions.

**Comment by gquerret** [comment]
Please test build 650 or 651 from here: https://ci.rssw.eu/job/PCT/job/master/
If compiler options are provided on the command line (through `-compileroptionsfile`) then they are not overridden by the PCT.

**Comment by gquerret** [comment]
@movedoa I meant build 651 or 652, build 650 doesn't contain this modification.

**Comment by movedoa** [comment]
I tested this with PCT-216 and it works now.
Thx for the fix
