### ISSUE TITLE
Question: Building PCT with the supplied Jenkinsfile

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#434]
### Subject of the issue

I added my github account to Jenkins as a Github organisation.
It started scanning my github repositories for repos with a Jenkinsfile and found PCT.

![image](https://user-images.githubusercontent.com/1312691/99815160-3b748b80-2b4a-11eb-8738-16a30d5626d3.png)

I managed to configure the openedge & jdk tool locations.
from the Jenkinsfile I guess I need to configure an RSSW environment

          withEnv(["PATH+SCAN=${tool name: 'SQScanner4', type: 'hudson.plugins.sonar.SonarRunnerInstallation'}/bin"]) {
            withSonarQubeEnv('RSSW') {

### Question
Where should I define RSSW and what properties should I provide ?

### Your environment
* Jenkins on linux master
* windows 2016 node
* Ant 1.9
* PCT master

### behaviour
The build hangs on 
```
[jacoco:coverage] Enhancing testng with coverage
Cancelling nested steps due to timeout
```

**Comment by cverbiest** [comment]
Found https://stackoverflow.com/questions/42763384/unknown-stage-section-withsonarqubeenv will try that

**Comment by gquerret** [comment]
Jenkinsfile have references to internal names, RSSW being the reference to the SonarQube server https://sonar.riverside-software.fr. You can define such a reference in your own Jenkins instance, and point to your own SQ server.
But I think that what is missing in your configuration are the nodes where unit tests are executed: you need a windows node with label 'windows' and a linux node with label 'linux'. You'll also need OpenEdge versions installed on those nodes. Maybe a bit cumbersome...

You can add another Jenkinsfile in your PCT fork, where unit tests won't be executed in the same way. Just tell Jenkins to use this separate Jenkinsfile when executing builds.
