### ISSUE TITLE
PCTBinaryLoad returned: -1073741819

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/pct#439]
While loading a certain *.bd file with PCTBinaryLoad (via Jenkins), we have the following error:

```
19:17:09 [PCTBinaryLoad] Sorting and index building group 7.
19:17:09 [PCTBinaryLoad] Sorting index group 7 complete.  Elapsed time: 0.000 (16761)
19:17:09 [PCTBinaryLoad] Building index 223 (tb_Icon) of group 7 (16757)
19:17:09 [PCTBinaryLoad] Building of indexes in group 7 completed.  Elapsed time: 0.000 (16762)
19:17:13 
19:17:13 BUILD FAILED
19:17:13 F:\jenkins_slave\workspace\glims-master-databases-progress-windows\build.made-appl.progress-db.xml:107: The following error occurred while executing this line:
19:17:13 F:\jenkins_slave\workspace\glims-master-databases-progress-windows\build.made-appl.progress-db.xml:307: PCTBinaryLoad returned: -1073741819
```
The protrace is mentioning an ACCESS_VIOLATION; some extracts of the protrace file below:
```
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00C82397 01:00231397 C:\OpenEdge\117\DLC\bin\_dbutil.exe
```
```
Call Stack:
Address   Frame
00C82397  008E5C7C  dbut_utOsUnlink+1737
00C6CACF  008E5CBC  bmReleaseBuffer+58DF
00C6B152  008E5D00  bmReleaseBuffer+3F62
00C79599  008E5D20  bmReleaseBuffer+123A9
00C799E1  008E5D44  bmReleaseBuffer+127F1
```

Now the weird thing is: the error is only raised with one particular *.bd file, we load +- 100 files, and the other onces are loaded correctly.
We have already tried recreating the *.bd file from the source database, but that didn't help.

When we execute the proutil command manually, no error is thrown.
`dbutil dbf/genro -C load glims/dbs/ds_Table.bd build indexes -cpinternal UTF-8`

We have already contacted progress tech support, but they are also not able to reproduce the issue.
So, is there a certain way to debug the commando's that are used by pct behind the scenes in order to find the issue?

**To Reproduce**
- create an empty database (utf)
- load the schema
- load some *.bd files from a certain directory
```
    <PCTBinaryLoad
          dlcHome="${DLC}"
          paramFile="${basedir}/_ant_dep/parameter_files/build_database_session.pf">

          <env key="PATH" value="${env.PATH}${path.separator}${DLC}/bin" />
          <PCTConnection dbDir="${dbfDir}" dbName="@{db}" />

          <fileset dir="${dbsDir}">
              <include name="*.bd"/>
          </fileset>

      </PCTBinaryLoad>
```

**Environment**
- Windows server 2019
- OpenEdge 11.7.5
- Ant 1.9.7
- PCT 2.1.5

**Comment by gquerret** [comment]
You can execute your Ant script with `-v` ; log output will contain the command lines being executed, and the directory where this is executed, as well as the environment.
BinaryLoad executes directly `_proutil -C load` and not `dbutil`, that may be the difference. But the `bat` files in `$DLC/bin` usually don't contain anything interesting.

**Comment by dominickdm** [comment]
I was able to reproduce the issue outside of pct with the proutil command. I'm investigating the crash further with progress support now.

Thank you for your assistance Gilles!

**Comment by gquerret** [comment]
Did you get feedback from Progress ?

**Comment by dominickdm** [comment]
We planned a meeting with progress to 'debug' the issue since it was not reproducible for them (neither for me on a local environment), but the issue was magically fixed with a new *.bd file that generated in our systems (after some data in the table was updated).

**Comment by gquerret** [comment]
Thank you Dominick !
