### ISSUE TITLE
Unable to use DynamicRun with DB connection in no-integrity mode

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/pct#444]
Based on discussion with @ChadThomsonPSC

**Describe the bug**
PCTDynRun can't connect to a database in no-integrity mode. Same procedure with PCTRun works perfectly.

**To Reproduce**
```xml
<PCTDynRun procedure="foo.p" dlcHome="${DLC}">
  <DBConnection dbName="db1" dbDir="db" singleUser="true" paramFile="nointegrity.pf" />
</PCTRun>
```

An error is raised:
```
x2:
[PCTDynRun] Unable to connect to '-db D:\Projets\xxx\db\db1 -pf D:\Projets\xxx\nointegrity.pf -1 '
[PCTDynRun] ** This session is being run with the no-integrity (-i) option. (512)
```

**Expected behavior**
Should be able to connect to the database

**Environment**
- OpenEdge version: 12.2
- Ant version: 1.10
- PCT version: 217

**Comment by gquerret** [comment]
Investigated internally, but looks like a bug in the AVM.

**Comment by gquerret** [comment]
Root cause of the problem:
```
ROUTINE-LEVEL ON ERROR UNDO, THROW.
CONNECT "-db sports2000 -1 -i" NO-ERROR.
MESSAGE ERROR-STATUS:ERROR.  // DB is connected, but error flag is set to true
```

@ChadThomsonPSC Did you report the issue ?

**Comment by ChadThomsonPSC** [comment]
I demonstrated the scenario to the ABL Language team owner, but I did not file a bug report.
I will follow-up and get a few more eyes on the issue.

**Comment by gquerret** [comment]
Won't be fixed.
