### ISSUE TITLE
PctCompile - requireReturnValues doesn't work with numThread > 1

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#445]
**Describe the bug**
requireReturnValues doesn't work in OE 12.2 with multi thread compilation

**To Reproduce**
try set requireReturnValues  to true

**Expected behavior**
should work

**Environment**
- Operating system and version : Win 10
- OpenEdge version : 12.2.4
- Ant version : 
- PCT version : last version

**Additional context**
-

**Comment by gquerret** [comment]
Merged in master, thank you for your PR !
