### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by timk519** [Riverside-Software/pct#450]
[test.zip](https://github.com/Riverside-Software/pct/files/6585825/test.zip)

**Describe the bug**
"How to build PCT?" has a command for executing the unit tests - this fails on my system.

The build instructions were successful. 

**To Reproduce**

cd to the "pct" top level directory.
Execute command:
ant -Dprofiler=true -lib dist/PCT.jar -file tests.xml test

Response:

test:
[jacoco:coverage] Enhancing testng with coverage
   [testng] Error: Could not find or load main class Files\PCT.lib
   [testng] Caused by: java.lang.ClassNotFoundException: Files\PCT.lib
   [testng] The tests failed.

BUILD SUCCESSFUL
Total time: 0 seconds

**Expected behavior**
Test should run to completion.

**Environment**
- Operating system and version Windows 10
- OpenEdge version 12.0
- Ant version 1.10.10
- PCT version Current version - downloaded yesterday

**Additional context**
PCT.jar is not in the ant/lib directory

**Comment by timk519** [comment]
This issue is related to a space in the directory structure not being properly escaped in the properties. Quoting "TESTLIBS" fixed one problem, and then the test failed for a similar reason elsewhere. 

<jvmarg line="-DDLC=&quot;${DLC}&quot; -DPROFILER=${PROFILER} -DTESTLIBS=&quot;${TESTLIBS}&quot; -DVERSION=${VERSION}" />

I'm attaching the updated test.
[test.zip](https://github.com/Riverside-Software/pct/files/6586441/test.zip)

**Comment by gquerret** [comment]
You're using Java 16, which is not supported by PCT. The current build process use Java 11.

**Comment by gquerret** [comment]
If you have OE 12 on your machine, you can use the JDK coming with this version.

**Comment by timk519** [comment]
Thx! 

Going to 11 allowed the tests to run. I still needed to add &quot; around the TESTLIBS reference.

A number of tests failed 
com.phenix.pct.PCTRunTest test50
Caused by: java.io.FileNotFoundException: C:\Users\timku\AppData\Local\Temp\PCTResult98902609.out (The system cannot find the file specified)

com.phenix.pct.AssemblyCatalogTest test1
com.phenix.pct.ClassDocumentationTest test1 test4 test5

Is this something I need to worry about?

Re-running the tests w/out deleting or changing anything returned 60 failures. Do I need to clear out test-output between runs?

**Comment by gquerret** [comment]
> I still needed to add " around the TESTLIBS reference.

Failure is more or less expected, build is never executed in a directory which contains spaces.

> com.phenix.pct.PCTRunTest test50
> Caused by: java.io.FileNotFoundException: C:\Users\timku\AppData\Local\Temp\PCTResult98902609.out (The system cannot find the file specified)

Might be related to the license that is installed in your environment. Apart from that, it shouldn't fail.

> com.phenix.pct.AssemblyCatalogTest test1

Use references to .net assemblies, so may depend on the OS and/or OE license.

> com.phenix.pct.ClassDocumentationTest test1 test4 test5

Yes, additional switches are used to test this class. You can find them in the Jenkinsfile, but unless you change anything in the ClassDocumentation, that's not important.
