### ISSUE TITLE
pct 218 return the error 4052 when compiling under the Openedge 11.5

### ISSUE THREAD

**Issue by csslu** [Riverside-Software/pct#451]
**Describe the bug**
```
00:03:24.318  [PCTVersion] PCT Version : pct-218-master-c2ca955509da5ca57066bb168f1521aae2cf86af
00:03:24.318  [PCTCompile] PCTCompile - Progress Code Compiler
00:03:27.611  [PCTCompile] **? is not a queryable attribute for PSEUDO-WIDGET. (4052)
00:03:27.611  [PCTCompile] **? is not a queryable attribute for PSEUDO-WIDGET. (4052)
00:03:27.611  [PCTCompile] **? is not a queryable attribute for PSEUDO-WIDGET. (4052)
00:03:27.611  [PCTCompile] **? is not a queryable attribute for PSEUDO-WIDGET. (4052)
00:03:27.611  [PCTCompile] **? is not a queryable attribute for PSEUDO-WIDGET. (4052)
00:03:27.611  [PCTCompile] **? is not a queryable attribute for PSEUDO-WIDGET. (4052)
```

**To Reproduce**
1. Create emptydb with Openedge 11.7
2. Start up emptydb with specific available port
3. Run the Jenkins pipeline to call ANT(1.9.7) to compile the code via pct (218) on the Openedge 11.5

**Expected behavior**
   it's working well on pct (215). Just expect it's working well same as 215

**Environment**
- Operating system and version  - Windows 2012 R2
- OpenEdge version - 11.5
- Ant version - 1.9.7
- PCT version - 218

**Additional context**

**Comment by gquerret** [comment]
Tests are not executed with 11.5 as it's an old version. I don't have 11.5 on my CI server, can you execute your build with `-DPCT-SRC=true` in your Ant command line ? That should raise a compilation error of the PCT code.

**Comment by pbibbyprimetics** [comment]
I'm having the same 4052 issue in OE11.6 but with just the basics in the installatin notes
Operating system and version - Windows 10 Enterprise
OpenEdge version - 11.6.4
Ant version - 1.10.10
PCT version - 218

after executing with -DPCT-SRC=true
```
** C:\Users\PAUL~1.BIB\AppData\Local\Temp\pct198692757\pct\compile.p Could not understand line 266. (198)
```

**Comment by gquerret** [comment]
Fixed in master branch, can you try [this snapshot](https://ci.rssw.eu/job/PCT/job/master/lastSuccessfulBuild/artifact/dist/PCT.jar) ?

**Comment by pbibbyprimetics** [comment]
snapshot doesnt exhibit error under 11.6 (as above)
