### ISSUE TITLE
Question: what is plan for supporting java 17 LTS which is coming in September?

### ISSUE THREAD

**Issue by zerovian** [Riverside-Software/pct#452]
**Describe the solution you'd like**
Is PCT going to support java 17 which is an LTS which is coming available later this year?

**Comment by gquerret** [comment]
There are currently no plans to support Java 17. Not to say that it won't be supported ; I just didn't start playing with this version.
I'll first have to see if Ant will support Java 17. I don't expect Progress to jump into this version directly in September, right ?
