### ISSUE TITLE
progPerc doesn't work multiple threads

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#453]
Hi,

When compiling classes with 1 thread, progPerc seems to be working.

However, when compiling procedures with 4 threads, I'm not seeing progress percentages... Is that expected behavior?

Thx, Lieven

**Comment by gquerret** [comment]
Yes, `progPerc` attribute is not implemented in multi-thread PCTCompile. I'll leave the issue open in case anybody would like to work on the implementation. I'd say it's quite easy to do that at the Java level when assigning files to each thread.

**Comment by tom9k** [comment]
Hi,

the same issue is with attribute **outputType=json**.
Is there any other way to get list of errors in file when multi-thread compile is used?

Thank You in advance, 

Tom

**Comment by gquerret** [comment]
@tom9k Yes, JSON outputType attribute is not supported in multi-thread compilation. The only way is to parse the stdout channel. Is that for a background process ?

**Comment by tom9k** [comment]
> @tom9k Yes, JSON outputType attribute is not supported in multi-thread compilation. The only way is to parse the stdout channel. Is that for a background process ?

I'm using Azure DevOps Pipelines to orchestrate Ant/PCTCompile tasks running locally on our on-premise server (using Microsoft Azure self-hosted agent). I would like to store list of errors locally (e.g. on a shared drive) to be available to developers even apart from Azure DevOps website. 

PCTCompile outputs errors to standard err (as *[PCTCompile] Error compiling file {1}* ) and it's "consumed" by Azure pipeline. I unfortunately don't know any way to "shadow" this output to a local file. 

Parallel output to JSON (or any other local file) would be perfect solution, but it is not supported when using multi-thread compiling.

Any advice would be appreciated. 

Tom

**Comment by gquerret** [comment]
I don't work with Azure DevOps so I can't give detailed instructions, but the idea is to notify the developers in case of build failure. All CI servers can be plugged to various systems, so just choose the right one (email, Slack, Webex, ...) and let the developers get the info from the alert (which usually contains the URL to the build log). You won't have direct access to the file name and line number where the error occured, but the developers should be able to read the log ;-)

**Comment by tom9k** [comment]
Hi, Gilles,

Azure DevOps is very similar to Jenkins and is customizable in many ways. 
It can send an e-mail after every failed job with links to captured Ant log and even let drill down to a git commit, which triggered failed build.
But I've been asked to offer to our developers something like compile.log - a list of errors from PCTCompile - something they are used to...  

Finally I've found the way by using [Ant Recorder task](http://ant.apache.org/manual/Tasks/recorder.html) 

But to add JSON feature to PCTCompile even in multi-thread would be nice.  ;-)

**Comment by lievencardoen** [comment]
Nobody feels the mission to program this... ;-)

I'll try to find some time in the coming months to do this.

**Comment by gquerret** [comment]
Excellent idea :-)

**Comment by gquerret** [comment]
Looks like it won't be fixed !
