### ISSUE TITLE
java.net.SocketTimeoutException: Accept timed out

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#454]
Hi,

It looks like all sources were compiled successfully, but at the end I'm getting next error:

```
     [exec] [pct:compile] 18,129 file(s) compiled
     [exec]      [echo] ********************************************************************************
     [exec]      [echo] Error compiling one or more Procedures
     [exec]      [echo] The following error occurred while executing this line:
     [exec]      [echo] C:\...l\build.xml:520: java.net.SocketTimeoutException: Accept timed out
     [exec]      [echo] ********************************************************************************
```

Any idea what could cause this?

Thx

**Comment by gquerret** [comment]
Given the log output, it looks like an Ant script triggers another one. Do you have a stacktrace ? I'd like to be sure if this comes from the multi-thread build or from something else. And how do you determine that there was an error ?

**Comment by lievencardoen** [comment]
I'll try and reproduce it.

**Comment by lievencardoen** [comment]
Haven't seen the error anymore...
