### ISSUE TITLE
Provide a way to manually set the jdk/jre

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/pct#456]
**Is your feature request related to a problem? Please describe.**
Because of reasons, the jdk path that is set in our java.properties file on out build servers does not point to the java install we want to use (it doesn't even exist in this case).
So we have a lot of warnings in our build log ([PCTRun] JAVA_HOME 'C:\Program Files\AdoptOpenJDK\jdk-11.0.10.9-hotspot' directory doesn't exist)

**Describe the solution you'd like**
A property to manually set the JDK would be nice, if set, this should take precedence over the setting in the properties file.
I could set it to the JAVA_HOME env variable in ant and have the flexibility i need.

Imho this should be a "global" property like DlcHome so i only have to set this once in the script.

**Comment by gquerret** [comment]
I've seen the same issue on my build nodes, you're not alone. I don't think this is coming from PCT, but rather from Progress startup scripts. I'll try to find a minute and see which script displays this message. Java is not used except in proxygen / restgen tasks.

**Comment by gquerret** [comment]
Header of $DLC/bin/java_env:
```
# There are 2 ways to use a different JAVA than tailored at
# install time:
#     1) modify the JAVA_HOME in this file to new JAVA
#        location (this affects all OpenEdge scripts)
#     2) set $JAVA_HOME in environment tp the new JAVA and
#        set FORCE_JAVA="no" in this script
```
So it seems that modifying a file in the install dir is required.

But then there's a test on the RDL variable:
```
# If in testing environment set FORCE_JAVA="no"
if [ -n "$RDL" ]
...
```

Executing `env RDL=1 $DLC/bin/pro` seems to be enough to disable reading `JAVA_HOME` from `$DLC/properties/java.properties`. As PCTRun doesn't rely on `pro` but directly on `_progres`, there are probably only a few places where you'd need to add the environment variable. You can use `<env key="RDL" value="1" />`
