### ISSUE TITLE
<pct:run> support catchStop parameter

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#457]
**Problem**
There is no attribute to set ``-catchStop``.

**Solution**
Add it.

**Alternative**
Use ``paramFile``.

**Additional context**
The catchStop parameter determines if the ``stop`` condition can be caught. When using 11.7 it is [off by default](https://docs.progress.com/bundle/openedge-startup-and-parameter-reference-117/page/Catch-STOP-catchStop.html), when using 12.2 it is [on by default](https://docs.progress.com/bundle/openedge-startup-and-parameter-reference-122/page/Catch-STOP-catchStop.html).

**Comment by gquerret** [comment]
You can use `<Option name="-catchStop" />` in your PCTRun task, that's easier than having to deal with a PF file.

**Comment by stefandrissen** [comment]
Ah, much better! Thanks, option works fine for me in this case.
