### ISSUE TITLE
PCTCreateDatabase - Possibility to add a keyword forget list (-k) for loading df-files 

### ISSUE THREAD

**Issue by dvreken** [Riverside-Software/pct#458]
**Is your feature request related to a problem? Please describe.**
Currently the (-k) cannot be provided while loading a DF.
For compiling it kan be added in the 'PF' file, called by the 'paramFile' attribute, but this one is not an valid attribute for PCTCreateDatabase 

**Describe the solution you'd like**
Could 'paramFile' (or 'forgetList') be added to PCTCreateDatabase ?

**Describe alternatives you've considered**
I am creating a work-round to load the DF with a generated script from ANT.

**Additional context**
Nothing to see other than the obvious:
- build.xml:371: The following error occurred while executing this line:
- build.xml:417: PCTCreateDatabase doesn't support the "paramFile" attribute

**Comment by gquerret** [comment]
The only supported attributes in this task are related to encodings.
Why do you need the -k attribute when loading a DF file ?

**Comment by cverbiest** [comment]
As far as I know -k has no function during load df. Remove -k from the parameter file you use during PCTCreateDatabase

**Comment by dvreken** [comment]
Thanks for the replies,

The 'need' for the '-k' is due to an existing application in which there is a table called 'session' in the DB.
However my work-around works (with a -k during the load of the DF), and plans are being made to rename this table but that also means a lot of code changes etc.

**Comment by gquerret** [comment]
Trying to load a 'session' table gives this output:
```
[PCTCreateDatabase] Copying DB C:\Progress\OpenEdge-12.2\empty8 to test
[PCTCreateDatabase] Loading C:\Users\gquer\projets\pct\testbox\PCTCreateBase\test9\schema1.df in database
[PCTCreateDatabase] ** Error during ADD TABLE session **
[PCTCreateDatabase] ** Line 3 ADD TABLE session
[PCTCreateDatabase] OpenEdge keywords can not be object names.
[PCTCreateDatabase] ...
```
Didn't try the `-k` option, I'll trust you 😄 

@dvreken You'll have to move the schema load from PCTCreateDatabase to PCTLoadSchema. You'll then be able to use `<Option name="-k" value="filename.txt" />`, as in:

```xml
<PCTCreateDatabase dbName="test" destDir="db" /> <!-- Don't use schemaFile attribute here -->
<PCTLoadSchema srcFile="schema.df">
  <DbConnection dbDir="db" dbName="test" singleUser="true" />
  <Option name="-k" value="filename.txt" />
</PCTLoadSchema>
```

**Comment by dvreken** [comment]
@gquerret 

Thanks for the feedback, I will move the schema load as you described.
