### ISSUE TITLE
How to configure SQL-Server Linked server

### ISSUE THREAD

**Issue by ivanbrizida** [Riverside-Software/pct#467]
In the file attached here there are information to connect OpenEdge databases and Linked server SQLServer databases. How do I use PCTConnection to connect that?

[bdpgswin11.pf.txt](https://github.com/Riverside-Software/sonar-openedge/files/7973779/bdpgswin11.pf.txt)

The OpenEdge database information is:

`-db cap -ld cap -U *** -P *** -S 5021 -H rjopvpgs02 -N tcp`

It translates to:

`<PCTConnection dbName="cap" dbPort="5021" hostName="rjopvpgs02" userName="***" password="***" protocol="tcp" singleUser="${singleUser}" />`

But the SQLServer via linked server information is:

`-db schema_INT -H RJOPVDSS01 -S 6551 -N tcp -db INTCAP_DEV -dt MSS -ld INTCapemisa      -Dsrv SVUB,1 -DataService INTCapemisa      -H RJOPVDSS01 -S 5162 -N tcp -znoencrypt`

How does it transtaltes to PCTConnection or any other way?

**Comment by gquerret** [comment]
Moved issue to PCT as PCTConnection is not part of Sonar.

Dataserver connection can be a bit tricky. You can use:
```
<DbConnection dbName="schema_INT" dbPort="6551" hostName="RJOPVDSS01" />
<DbConnection dbName="INTCAP_DEV" dbType="MSS" logicalName="INTCapemisa" dataService="INTCapemisa" hostname="INTCAP_DEV" dbPort="5162" />
```
I'm unsure about the `-Dsrv SVUB,1`, but I think you can put it as a standard command line option (use `<Option>`). Otherwise, you can use `<DbConnection dbName="INTCAP_DEV" paramFile="path/to/file.pf" />`

**Comment by cverbiest** [comment]
Is the SQL connection needed ? I see this issue was moved from Sonar to PCT. For compile and  analysis of the ABL code the connection to the Progress schema holder database should be enough.

**Comment by ivanbrizida** [comment]
Mr. cverbiest, yes, the SQL connection is needed. I will try first use PCTConnection. 

First, I included the linked server databases in the build.xml. The variable ${SONAR_CFG} is the path to the .pf file.

```
<DbConnection dbName="INTCAP_DEV" paramFile="${SONAR_CFG}\bdpgswin11.pf" />
```

I executed the build and the messages bellow were shown. I believe that the first line of the .pf file (-h 20) is to increase the open database table, it seems to allow only 3 databases. So for our porpouses, it must recognize the -h command:

```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Unable to connect to -db INTCAP_DEV -pf \\rjopvauto01\TC-Control\conexoes\bd\DSV\bdpgswin11.pf
[PCTCompile] Warning: -h is not a database parameter and was ignored. (1402)
[PCTCompile] Warning: -znoencrypt is not a database parameter and was ignored. (1402)
[PCTCompile] Warning: -znoencrypt is not a database parameter and was ignored. (1402)
[PCTCompile] Warning: -znoencrypt is not a database parameter and was ignored. (1402)
[PCTCompile] Warning: -znoencrypt is not a database parameter and was ignored. (1402)
[PCTCompile] Warning: -znoencrypt is not a database parameter and was ignored. (1402)
[PCTCompile] Warning: -znoencrypt is not a database parameter and was ignored. (1402)
[PCTCompile] ** Cannot find or open file C:\temp\DSV\build_id_63645\INTCAP_DEV.db, errno = 2. (43)

```
Then I realized that the paramFile makes PCTConnection try to connect all databases include in it. I reduced the number of databases connections to 3, but still are problems:

```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Unable to connect to -pf \\rjopvauto01\TC-Control\conexoes\bd\DSV\bdpgswin11.pf
[PCTCompile] Warning: -znoencrypt is not a database parameter and was ignored. (1402)
[PCTCompile] ** Not enough storage for login. (699)
[PCTCompile] Failed to connect to the MSS database. (6142)

```
It seems there is some problem with the linked server.

Then I commented the lines above and included the line bellow:

`<DbConnection dbName="INTCAP_DEV" dbType="MSS" logicalName="INTCapemisa" dataService="INTCapemisa" hostname="INTCAP_DEV" dbPort="5162" />
`

The error message was:

```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Unable to connect to -db INTCAP_DEV -S 5162 -ld INTCapemisa -DataService INTCapemisa -dt MSS -H INTCAP_DEV
[PCTCompile]  non-PROGRESS database INTCapemisa unknown. (1008)

```

Then I modified the connection to:

`<PCTConnection dbName="INTCAP_DEV" dbPort="6551" hostName="rjopvpgs02" userName="***" password="***" protocol="tcp" singleUser="${singleUser}" />`

As if the database would be recognized automatically by schema holder like I think cverbiest suggested. And the response was:

```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Unable to connect to -db INTCAP_DEV -N tcp -S 6551-1 -H rjopvpgs02 -U sistemas -P capemi
[PCTCompile] ** Could not connect to server for database INTCAP_DEV, errno 0. (1432)

```

I tried to change the port to 5162, but to no avail.

**Comment by gquerret** [comment]
You can try
```xml
<PCTRun paramFile="/path/to/bdpgswin.pf" ...
  <Option name="-h" value="20" />
</PCTRun>
```
With this mode, you won't be able to define aliases, but your session will be connected to the DBs. Otherwise, verify the PF file with your DBA.

**Comment by ivanbrizida** [comment]
PCTRun does not runs inside PCTConnection and when I run it outside PCTCompile, the option is ignored. In reality I don´t know where to put the PCTRun to make it work.

We solved the .pf problema of the linked server. So now the only problem is how to increase the number of the open database table.

I have this target to adjust. Can you find a solution to this?

```
<!-- targets -->
<target name="compile" description="Generate the warning and code smell files">
    <PCTCompile destDir="${snr}" dlcHome="${DLC}">
        <fileset dir="${snr}" includes="*.p,*.w"/>
        <propath>
            <pathelement location="${books}"/>
        </propath>
        <DbConnection paramFile="${SONAR_CFG}\bdpgswin11.pf" />
    </PCTCompile>
</target>
```

**Comment by stefandrissen** [comment]
https://github.com/Riverside-Software/pct/wiki/PCTCompile 

> [PCT](https://github.com/Riverside-Software/pct/wiki/PCT)Compile inherits attributes from PCT and [PCTRun](https://github.com/Riverside-Software/pct/wiki/PCTRun).

Since [-h](https://docs.progress.com/bundle/openedge-startup-and-parameter-reference-117/page/Number-of-Databases-h.html) is a client session parameter, you need to add it to PCTCompile with either ``paramFile`` or as nested ``option``.

**Comment by ivanbrizida** [comment]
I put the option tag as follows and it workded! 

```
<!-- targets -->
<target name="compilar" description="Gera os arquivos de warning e code smell">
    <PCTCompile destDir="${snr}" dlcHome="${DLC}">

        <Option name="-h" value="20" />

        <fileset dir="${snr}" includes="*.p,*.w"/>
        <propath>
            <pathelement location="${books}"/>
        </propath>
        <DbConnection paramFile="${SONAR_CFG}\bdpgswin11.pf" ></DbConnection>
    </PCTCompile>
</target>

```

Thanks!!

**Comment by ivanbrizida** [comment]
One last thing. The version 11 of OpenEdge ParamFile has the connection parameter -znoencrypt to encripty the password. Is there a way to make PCTConnection (or other way) accept this parameter ?

**Comment by gquerret** [comment]
You can use as many `<Option>` nodes as you want, so you can add `<Option name="-znoencrypt" />` after the existing one.

**Comment by ivanbrizida** [comment]
Option added and PCTCompile returned an error:

```
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Unable to connect to -pf \\rjopvauto01\TC-Control\conexoes\bd\DSV\bdpgswin11.pf
[PCTCompile] Login was denied because of an authorisation error. (6179)
[PCTCompile] -⌠-⌠
[PCTCompile] Failed to connect to the MSS database. (6142)
```

**Comment by gquerret** [comment]
You can execute `ant -v`, you'll see the command line being executed by PCT.
You can also try replacing `<DbConnection paramFile...` with `<Option name="-pf" value="..." />` and moving `-znoencrypt` before / after the other option. Not sure if this could have an impact, I've never used this option.

**Comment by ivanbrizida** [comment]
I changed DbConnection to Option and added the -znoencrypt, but returned this error:

```
[PCTCompile] Executing 'C:\DLC11\bin\_progres.exe' with arguments:
[PCTCompile] '-b'
[PCTCompile] '-q'
[PCTCompile] '-param'
[PCTCompile] 'C:\Users\u_tc_app\AppData\Local\Temp\2\pct_params72108500.txt'
[PCTCompile] '-h'
[PCTCompile] '20'
[PCTCompile] '-pf'
[PCTCompile] '\\rjopvauto01\TC-Control\conexoes\bd\DSV\bdpgswin11.pf'
[PCTCompile] '-znoencrypt'
[PCTCompile] '-p'
[PCTCompile] 'C:\Users\u_tc_app\AppData\Local\Temp\2\pctinit208100562.p'
[PCTCompile]
[PCTCompile] The ' characters around the executable and arguments are
[PCTCompile] not part of the command.
[PCTCompile] Login was denied because of an authorisation error. (6179)
[PCTCompile] -⌠-⌠
[PCTCompile] Failed to connect to the MSS database. (6142)
[PCTCompile] Result: 2

```

The problem, I think is that the -znoencrypt applies to some database connection lines of the .pf file. In other words, it is not for all the databases like the -h 20 is. It is necessary to apply this parameter to each line individually. I believe the .pf parser should be modified to handle this new Version 11 feature.

**Comment by gquerret** [comment]
Make it work with the plain command line, then just apply the same config to PCTRun. You may have to include the -znoencrypt option in the pf file (per database).

**Comment by ivanbrizida** [comment]
gquerret, I did as you suggested. I put the BENCapemisa database in a separeted .pf file:

```
<!-- targets -->
<target name="compilar" description="Gera os arquivos de warning e code smell">
		<PCTCompile destDir="${snr}" dlcHome="${DLC}">
		<Option name="-h" value="20" />
		<fileset dir="${snr}" includes="*.p,*.w"/>
		<propath>
			<pathelement location="${books}"/>
		</propath>
		<Option name="-pf" value="${SONAR_CFG}\bdpgswin11.pf" />
		<Option name="-pf" value="${SONAR_CFG}\BENCapemisa.pf" />
		<Option name="-znoencrypt" />
	</PCTCompile>
</target>

```

Then I put the `<Option name="-znoencrypt" />`  just after and executed the ant:

```
proenv>ant -v -buildfile sonar.xml
Apache Ant(TM) version 1.10.12 compiled on October 13 2021
Buildfile: C:\temp\DSV\build_id_63645\sonar.xml
Detected Java version: 11 in: C:\Program Files\Java\jdk-11.0.12
Detected OS: Windows Server 2012 R2
parsing buildfile C:\temp\DSV\build_id_63645\sonar.xml with URI = file:/C:/temp/DSV/build_id_63645/sonar.xml
Project base dir set to: C:\temp\DSV\build_id_63645
parsing buildfile jar:file:/C:/Ant/apache-ant-1.10.12/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/C:/Ant/apache-ant-1.10.12/lib/ant.jar!/o
rg/apache/tools/ant/antlib.xml from a zip file
 [property] Loading Environment env.
Property "env.sistema" has not been set
 [property] Loading \\rjopvauto01\TC-Control\conexoes\bd\DSV\sonar.cfg
Build sequence for target(s) `build' is [compilar, build]
Complete build sequence is [compilar, build, sonar, ]

compilar:
[PCTCompile] OpenEdge version found : OpenEdge Release 11.7.5 as of Fri Jun  7 09:06:03 EDT 2019
[PCTCompile] Using object : com.phenix.pct.ProgressV117
[PCTCompile] OpenEdge version found : OpenEdge Release 11.7.5 as of Fri Jun  7 09:06:03 EDT 2019
[PCTCompile] Using object : com.phenix.pct.ProgressV117
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] cpstream is not defined. You may have problems if file names have characters outside of ASCII range. You really should define it !
[PCTCompile] Current OS is Windows Server 2012 R2
[PCTCompile] Setting environment variable: DLC=C:\DLC11
[PCTCompile] Executing 'C:\DLC11\bin\_progres.exe' with arguments:
[PCTCompile] '-b'
[PCTCompile] '-q'
[PCTCompile] '-param'
[PCTCompile] 'C:\Users\u_tc_app\AppData\Local\Temp\2\pct_params123130776.txt'
[PCTCompile] '-h'
[PCTCompile] '20'
[PCTCompile] '-pf'
[PCTCompile] '\\rjopvauto01\TC-Control\conexoes\bd\DSV\bdpgswin11.pf'
[PCTCompile] '-pf'
[PCTCompile] '\\rjopvauto01\TC-Control\conexoes\bd\DSV\BENCapemisa.pf'
[PCTCompile] '-znoencrypt'
[PCTCompile] '-p'
[PCTCompile] 'C:\Users\u_tc_app\AppData\Local\Temp\2\pctinit86373742.p'
[PCTCompile]
[PCTCompile] The ' characters around the executable and arguments are
[PCTCompile] not part of the command.
[PCTCompile] Login was denied because of an authorisation error. (6179)
[PCTCompile] -⌠-⌠
[PCTCompile] Failed to connect to the MSS database. (6142)
[PCTCompile] Result: 2

BUILD FAILED
C:\temp\DSV\build_id_63645\sonar.xml:35: Progress procedure failed - Error reading return value
        at com.phenix.pct.PCTRun.execute(PCTRun.java:467)
        at com.phenix.pct.PCTCompile.execute(PCTCompile.java:328)

```

I don´t know more what to do. Could you answer with the XML that works, I´d appreciate.

**Comment by ivanbrizida** [comment]
Hi gquerret, we solved the problem. What was happening is that OpenEdge only accepts up to 20 characters long passwords and we use longer passwords around here. We changed the password lengths to comply and deleted the -snoencript parameter. It works perfectly.

Thanks for your help and you can close this issue.
