### ISSUE TITLE
C:\DLC11\bin\_progres.exe does not use -ininame definitions to compile

### ISSUE THREAD

**Issue by ivanbrizida** [Riverside-Software/pct#468]
**Description of the bug**
PCTCompile is using C:\DLC11\bin\\_progres.exe instead of C:\dlc11\bin\prowin.exe

**Evidence**
Because of this the error bellow is shown:

```
   Compilando: C:/Temp/DSV/build_id_64626/src/windows/win/lcspc001.W
ERRO: (L/C) 0 / 0
ERRO: 15090: WARNING: Executable statement at line 518 of file C:\Temp\DSV\build_id_64626\src\windows\win\lcspc001.W will not be reached. (15090)
ERRO: 4023: **The size phrase specified for BROWSE br_Proposta is not large enough. (4023)

```

**Expected behavior**
If prowin.exe was used the -ininame and -basekey would have their effect. Is it possible to make PCTcompile use prowin.exe as the compiler instead of _progres.exe ?

**Environment**
**Log**
[sonar.log.txt](https://github.com/Riverside-Software/pct/files/8073490/sonar.log.txt)

**ininame file**
[progress.ini.txt](https://github.com/Riverside-Software/pct/files/8073519/progress.ini.txt)

**Comment by jakejustus** [comment]
Use graphicalMode=“true”

**Comment by ivanbrizida** [comment]
Merci Gilles. It worked!
