### ISSUE TITLE
A java.net.SocketTimeoutException: Accept timed out fails the PCTCompile task sometimes

### ISSUE THREAD

**Issue by bctrdw** [Riverside-Software/pct#475]
**Describe the bug**
Sometimes we get the following exception in the PCTCompile task:
java.net.SocketTimeoutException: Accept timed out

**To Reproduce**
Unfortunately I don't know how to reproduce the problem because it does not always fails

**Expected behavior**
No exception so a good build

**Environment**
- Windows Server 2016 12 Core on a virtual machine
- OpenEdge 11.7.8
- Ant 1.9.8
- PCT 221
- AdoptOpenJDK 8.0.272.10

**Additional context**
Sometimes we get this build error from Jenkins and a rebuild of the same source code went just fine.
In the log is the folowing error written:

```
BUILD FAILED
D:\Jenkins\workspace\Corsa_trunk\ant-build.xml:1299: The following error occurred while executing this line:
D:\Jenkins\workspace\Corsa_trunk\ant-build.xml:1285: The following error occurred while executing this line:
D:\Jenkins\workspace\Corsa_trunk\ant-build.xml:191: java.net.SocketTimeoutException: Accept timed out
	at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	at java.net.ServerSocket.implAccept(ServerSocket.java:560)
	at java.net.ServerSocket.accept(ServerSocket.java:528)
	at com.phenix.pct.PCTBgRun$ListenerThread.run(PCTBgRun.java:678)
```

The ant target that failed is the following definition:

```xml
	<target name="compile.default.notrans">
		<mkdir dir="output/rcode/${platform}/${project}" />
		<mkdir dir="preproces/rcode/${platform}/${project}" />
		
		<PCTCompile destDir="preproces/rcode/${platform}/${project}"
		            preprocessDir="output/preproces/${platform}/${project}"
		            debugListingDir="output/preproces/${platform}/${project}"
		            xrefDir="output/preproces/${platform}/${project}"
         	            failOnError="True"
         	            graphicalMode="True"
         	            cpInternal="utf-8"
         	            cpStream="1252"
         	            numThreads="${env.NUMBER_OF_PROCESSORS}"
         	            iniFile="ant-build.ini"
         	            relativePaths="true">

			<PCTConnection refid="${platform}_dbcorsa" />

			<fileset dir="preproces/progress/${project}" casesensitive="False">
				<patternset refid="progress.sources" />
			</fileset>
			<fileset dir="sources/progress/${project}" casesensitive="False">
				<patternset refid="progress.sources" />
				<exclude name="${project}.p" />
				<exclude name="${project}release.p" />
			</fileset>
			<propath>
				<pathelement path="preproces/progress/${project}" />
				<pathelement path="sources/PASOE/AppServer" />
				<pathelement path="sources/MyCorsaNxT/srcweb" />				
				<pathelement path="sources/progress/srctrig" />
				<pathelement path="sources/progress/srcvartab" />
				<pathelement path="sources/progress/srcvadres" />
				<pathelement path="sources/progress/srcexplorer" />
				<pathelement path="sources/progress/srcdim" />
				<pathelement path="sources/progress/srccase" />
				<pathelement path="sources/progress/srcpab" />
				<pathelement path="sources/progress/srcstd" />
				<pathelement path="sources/progress/srcas" />
				<pathelement path="sources/progress/srctools" />
				<pathelement path="sources/progress/srcprogress11" />
				<pathelement path="sources/progress/srcprogress10" />
				<pathelement path="sources/progress/srcprogress117" />
			</propath>
		</PCTCompile>
		
	</target>
```

**Comment by gquerret** [comment]
Given the stacktrace (`at com.phenix.pct.PCTBgRun$ListenerThread.run(PCTBgRun.java:678)`), this means that some OpenEdge sessions can't be started (https://github.com/Riverside-Software/pct/blob/da2d99853f7fabb956d29525d95bd0d289f18103/src/java/com/phenix/pct/PCTBgRun.java#L678) before the server socket timeout. This timeout is set to 5 seconds. Or should I say hard-coded to 5 seconds. If your VM server is using over-provisioning and the physical host is busy, this can happen. Or if you use network connections (but you shouldn't...).
I can try adding an attribute for the server timeout ; if you know how to build PCT, the value is here: https://github.com/Riverside-Software/pct/blob/da2d99853f7fabb956d29525d95bd0d289f18103/src/java/com/phenix/pct/PCTBgRun.java#L653

**Comment by bctrdw** [comment]
Thanks, I have increased the TIMEOUT to 120000 to make it sure that this condition under normal conditions should not happen and rebuild-ed the PCT.jar.

If you can make it custom-able in the future I can update with an official build.

**Comment by gquerret** [comment]
@bctrdw  Did that solve your problem ?

**Comment by bctrdw** [comment]
Yes, I have now only successful builds

**Comment by gquerret** [comment]
Increased timeout in master branch to 30 seconds. That's to my mind more than enough, as the db connections are done **after** the session startup.
