### ISSUE TITLE
ABLDuck documentation needed on customisation of HTML

### ISSUE THREAD

**Issue by PeterJudgeZA** [Riverside-Software/pct#480]
ABLDuck has many features that we'd like to use, but I can't find any info on how or whether to customise the HTML - things like custom javascript (tag managers), CSS & images, copyright texts, etc etc etc.

Is this possible with ABLDuck?
If so, is there doc/info available on this anywhere?

**Comment by gquerret** [comment]
The ABLDuck task has been provided by @spazzymoto, based on the output of the PSC code parser (already used by Mike's documentation). There's already a discussion [here](https://github.com/Riverside-Software/pct/discussions/461) about the JsonDocumentation task. It may be good to reuse it (or create a new one) to start a documentation initiative. I think the ecosystem is small enough so it should be possible to supersede the existing tasks if the new one is better.
I'd be happy to coordinate the work and integrate the task in PCT.

**Comment by spazzymoto** [comment]
Hey guys,
Unfortunately there isn't that much customisation that can be done at the moment, besides whats here https://github.com/Riverside-Software/pct/wiki/ABLDuck and the example here https://spazzymoto.github.io/ablduck/.

As @gquerret mentioned i started rewriting it to use the JsonDocumentation task but have been a bit short on time with work and study commitments.

Maybe we should start the initiative for the new version by listing what features we would like, combining the good parts from each of the current ones, or new features.

Ill see if i can put some time aside each week to carry on with the dev.
