### ISSUE TITLE
Ansicolor Error for PCTCompile errors

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#481]
I have added AnsiColors to Jenkins. 
I got this working for my build, but I notice compile errors get INFO color instead of ERROR color

### Example
![image](https://user-images.githubusercontent.com/1312691/166939137-30d355fd-3b2f-494b-950b-f413e7bb4b2a.png)

**Describe the solution you'd like**

I'd like the compile errors in red like the Result: 10

**Additional context**
I'm using

    ant -logger org.apache.tools.ant.listener.AnsiColorLogger

* https://ant.apache.org/manual/api/org/apache/tools/ant/listener/AnsiColorLogger.html
* https://plugins.jenkins.io/ansicolor/

**Comment by gquerret** [comment]
IIRC, messages coming from external processes are always reported at the INFO level. Can you try using multiple threads ? In this case, Java is logging the message, and I think it's done with the right level. Could you try that ?

**Comment by cverbiest** [comment]
@gquerret  I tried it and I get ERROR colors for the compile errors now. 

Is the note _Don't use multiple threads when compiling classes._ still valid ?

If so, is there a way to get a _java_ compile with a single thread ?

**Comment by gquerret** [comment]
> Is the note Don't use multiple threads when compiling classes. still valid ?

It's technically still valid, the build can still fail if two threads try to compile the same hierarchy at the same time. But a lot of companies use multi-thread build with classes...

> If so, is there a way to get a java compile with a single thread ?

Replace `<PCTCompile>` with `<PCTCompileExt>` (or `pct:compile_ext`), and specify `numThreads=1`.
