### ISSUE TITLE
PCTCompile not copying the .r to the correct directory after compiling the .cls programs

### ISSUE THREAD

**Issue by tsp1423** [Riverside-Software/pct#482]
When i try to compile the below class the .r is not copying to correct destination path.

Src Structure - UI/Srv/JktClassess/DBAdmin/AIManager.cls
destDirectory - ts/build/

in Progress V11.7 32bit after compiling, the .r will be generated to ts/build/UI/Srv/JktClassess/DBAdmin/AIManager.r
but in Progress V12.2.7 64bit after compiling im getting the .r in ts/build/JktClassess/DBAdmin/AIManager.r

the package structure of the class is JktClassess.DBAdmin.AIManager.cls but its not affecting when i use Progress V11.7 32bit
im using -> Progress V12.2.7 64bit
ant V 1.10.12
JDK V11.0.14
PCT V221

**Comment by gquerret** [comment]
Run ant in verbose mode, there's probably more than just 32 bits vs 64 bits.

**Comment by tsp1423** [comment]
I took the scrcode zip file of PCTV221. In the existing code of src/progress/pct/compile.p (line: 353)
```
ASSIGN cSaveDir = (IF DestDir EQ ?
                       THEN ?
                       ELSE (IF cFileExt = ".cls":U OR lRelative
                               THEN outputDir
                               ELSE outputDir + '/':U + cBase)).
```

In this case: 
```
[PCTCompile] Compiling UI\Srv\JktClasses\DBAdmin\AIManager.cls in directory c:\git\jkt\Progress TO c:\ts\build
[PCTCompile] Compiling UI\Srv\JktClasses\DBAdmin\RebuildIndex.cls in directory c:\git\jkt\Progress TO c:\ts\build
```

the .r is copied to        ->C:\ts\build\JktClasses\DBAdmin\             -which is incorrect,  
but .r needed to be in ->C:\ts\build\UI\Srv\JktClasses\DBAdmin\  -which is correct 

So to get the .r in the above mentioned path I have made a small change by removing the .cls condition to the above code, build that and used the generated pct.jar
After modifing:src/progress/pct/compile.p
```
->ASSIGN cSaveDir = (IF DestDir EQ ?
                       THEN ?
                       ELSE (IF lRelative
                               THEN outputDir
                               ELSE outputDir + '/':U + cBase)).
```
below are the 2 classes which got compiled:
```
[PCTCompile] Compiling UI\Srv\JktClasses\DBAdmin\AIManager.cls in directory c:\git\intergy\Progress TO c:\ts\build/UI\Srv\JktClasses\DBAdmin\
[PCTCompile] Compiling UI\Srv\JktClasses\DBAdmin\RebuildIndex.cls in directory c:\git\intergy\Progress TO c:\ts\build/UI\Srv\JktClasses\DBAdmin\
```
As u can see after compiling the .r should copied to -> c:\ts\build/UI\Srv\JktClasses\DBAdmin\ 
as mentioned above but the .r have been copied to  -> c:\ts\build\UI\Srv\JktClasses\DBAdmin\JktClasses\DBAdmin

This is because the package structure of this class is -> JktClasses.DBAdmin.AIManager.cls 
so after compiling with the cSaveDir( c:\ts\build\UI\Srv\JktClasses\DBAdmin), the package structure(JktClasses.DBAdmin) is also adding.

how can avoid the above step ->package structure being added with cSaveDir?

**Comment by gquerret** [comment]
> how can avoid the above step ->package structure being added with cSaveDir?

Short answer, you can't and you shouldn't try to do that. Classes are always generated in a subdirectory matching the package name. In your case, you should use `<fileset src="c:\git\jkt\Progress\UI\Srv" includes="**/*.cls" />` and `destDir="C:\ts\build\UI\Srv"` in your PCTCompile node.

**Comment by tsp1423** [comment]
But We didnt face this issue before for old PCT.jar (attached below) which we used
only in the new version of PCT.jar V221 the classes are not copying to correct directory.

I observed that Checkhierarchy function has been added. Can i know why Checkhierarchy function is added and what was the  issue that it is addressing.

**Comment by gquerret** [comment]
> But We didnt face this issue before for old PCT.jar (attached below) which we used

The PCT.jar you were using is labelled `Version: 0.19-pre` and `Built-By: vobadm`, so:
* the version is more than 10 years old, and as it's a prerelease, it's impossible to know the exact commit ID
* it's not an official build, so it could include any custom code

> only in the new version of PCT.jar V221 the classes are not copying to correct directory.

I'd rather say that classes are generated in the correct directory in PCT221

> I observed that Checkhierarchy function has been added. Can i know why Checkhierarchy function is added and what was the issue that it is addressing.

You can have a look at the [changelog](https://github.com/Riverside-Software/pct/wiki/Changelog) or use git blame.
