### ISSUE TITLE
Working with PCT source code, either because you asked for it or because the compiled version is missing in JAR file

### ISSUE THREAD

**Issue by ShaikAhmed1234** [Riverside-Software/pct#484]
Hi 

Using the PCT-221 source code and modified the Compile.p and generated the pct.jar - but when I use this PCT.jar, it throws warning
"Working with PCT source code, either because you asked for it or because the compiled version is missing in JAR file"
<img width="725" alt="build1" src="https://user-images.githubusercontent.com/24850182/168064810-2bef77a6-cc1c-42c0-85bf-22bb084fdbf7.png">

Is this because the src code is not compiled(.r) ?

I changed the DLC in pct.build.properties to DLC12=C:\\Progress\\OpenEdge and run the build for PCT - I get this error.
<img width="724" alt="build2" src="https://user-images.githubusercontent.com/24850182/168065388-f1488752-12d1-40de-9122-3cdd21441be2.png">

Any support would be really appreciated.

**Comment by gquerret** [comment]
Link to [documentation](https://github.com/Riverside-Software/pct/blob/master/CONTRIBUTING.md#how-to-build-pct-)

**Comment by ShaikAhmed1234** [comment]
Thanks for replying back . I did follow the same steps but still I get these errors
<img width="653" alt="build3" src="https://user-images.githubusercontent.com/24850182/168070994-92cc130c-afca-40d1-9f2f-552c7ac38739.png">

**Comment by gquerret** [comment]
PCT uses its own source code, so first try to execute ant jar on unmodified source code
