### ISSUE TITLE
DLC/Version

### ISSUE THREAD

**Issue by KiltedKanuck** [Riverside-Software/pct#493]
For Version control of early release modules, Progress PM has decides to add a fourth octet to the OpenEdge version number. The fourth octet will, with alpha-numerics, specify the early release module (ERM) number. 
Example: 12.5.2.erm2

Please take this into consideration for future releases

**Comment by mikefechner** [comment]
I would suggest to share this information also using the OpenEdge CVP forum.

**Comment by gquerret** [comment]
Please open a pull request

**Comment by stefandrissen** [comment]
> For Version control of early release modules, Progress PM has decides to add a fourth octet to the OpenEdge version number. The fourth octet will, with alpha-numerics, specify the early release module (ERM) number. Example: 12.5.2.erm2

What does this mean?

````
message proversion.    // 12.5
message proversion(1). // 12.5.0.0.1175 -> five octets
````
https://abldojo.services.progress.com/?shareId=6352672c3fb02369b254a12e

Or is the intention to **populate** the fourth octet with some string that will potentially break existing customer code?

``message proversion(2)`` may be a better choice?

**Comment by mikefechner** [comment]
> Or is the intention to populate the fourth octet with some string that will potentially break existing customer code?

That is already happening in ESAP releases. 

PROVERSION: 12.6ALPHA 
PROVERSION(1): 12.6.0.0.1158.ALPHA

Did break some preprocessor code that did check INTEGER(ENTRY(2, PROVERSION)).

**Comment by KiltedKanuck** [comment]
I have made, what we thing will fix the issue. Waiting on engineering to provide an erm build to test with

**Comment by gquerret** [comment]
@KiltedKanuck I'll let you open the PR when it's ready (if still required).
