### ISSUE TITLE
Abldoc as md file 

### ISSUE THREAD

**Issue by ezazwar1** [Riverside-Software/pct#494]
Will it not be great if we will be able to generate the output of the ABl doc as md file and commit it back to the source repo that will be automatically linked to the wiki 

So what I am requesting in this feature is that the output which is generally a html/xml/json should also have an option to generate the md file. That once generated should have a task to call the source repo and commit those back to source repo 

That feature will be great

**Comment by gquerret** [comment]
The JsonDocumentation task generates a JSON file of all method/property documentation. It is then used in the [ABL plugin for VSCode](https://marketplace.visualstudio.com/items?itemName=RiversideSoftware.openedge-abl-lsp)

You can write a task to convert the JSON output to Markdown, but that won't be included in PCT.

> That once generated should have a task to call the source repo and commit those back to source repo

Generated files shouldn't go in the source repository, but in an artifact repository.

**Comment by ezazwar1** [comment]
I used the task JsonDocumentation , but seems like things like comment, author , perpose is missing in the output or maybe i am missing something

**Comment by gquerret** [comment]
Can you open a new issue with a code example ?
