### ISSUE TITLE
Is it possible to contribute to PCT docs

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#496]
I assume the https://github.com/Riverside-Software/pct-mkdocs project is used for building the PCT documentation.
But I can't locate the .md files it refers to. 

Is it possible to contribute to the PCT documentation ?

I'd like to update the PCTCompile outputType description to include the valid values.

**Comment by gquerret** [comment]
By default, all GitHub wiki pages have their own repository ; just append .wiki to the base URL ==> `git@github.com:Riverside-Software/pct.wiki.git`
I'm not sure if you can push there, let me know.

**Comment by gquerret** [comment]
pct-mkdocs is something I've tried recently, but wasn't convinced so that will be deleted.

**Comment by gquerret** [comment]
Wiki is also published here: https://wiki.rssw.eu/pct/Home (updated every 15 minutes)
It might become read / write in the future.

**Comment by cverbiest** [comment]
@gquerret 

I manually forked the wiki to `git@github.com:cverbiest/pct.wiki.git`, 
Apparently pull requests are not supported on github wiki's 

https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github 
https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

Can you pull this manually ?
Alternative, old-school, option, use git apply with the patch I attached

[0001-496-Update-PCTCompile-outputType-options.zip](https://github.com/Riverside-Software/pct/files/9989028/0001-496-Update-PCTCompile-outputType-options.zip)

**Comment by gquerret** [comment]
I've merged manually from your repo. Thanks !
