### ISSUE TITLE
pct:compile documentation: tempDir missing

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#497]
**Describe the bug**
The **documentation** for [pct:compile](https://github.com/Riverside-Software/pct/wiki/PCTCompile) does not mention that the session temp directory can be set. Fortunately I found #138 which mentioned that attribute tempDir can be used.

**Additional context**
When PDSOE workspace setting 'Refresh using native hooks or polling' is ticked, the AVM temp files are continuously triggering workspace refreshes that can be seen in the Eclipse 'Progress' view.

**Comment by gquerret** [comment]
The documentation mentions that the task inherits attributes from [PCT](https://github.com/Riverside-Software/pct/wiki/PCT) and [PCTRun](https://github.com/Riverside-Software/pct/wiki/PCTRun).
