### ISSUE TITLE
Allow Options for dbconnections, or add connectionRetries option, default 1

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/pct#498]
I'm trying to add the connection retries option to a DB connection

I tried

```xml
<DBConnection id="name" dbName="name" logicalName="name" hostName="hostname" dbPort="portnum">
  <Option name="-ct" value="1" />
</DBConnection>
```

but `DBConnection` doesn't support the nested `Option` element.

**Describe the solution you'd like**
The most flexible would be to have `<Option>` in DBConnection.

The easiest would be to have a connectionRetries parameter that defaults to 1. That way, I would not have to specify the parameter at all.

**Describe alternatives you've considered**
I could add a pf file containing -ct 1

**Additional context**
The current default value of 60 was established in the modem dial-in era. When I asked Gus about this parameter, he agreed 1 would be a good default nowadays.

**Comment by gquerret** [comment]
`<Option>` can be added at the DbConnection level, that will allow any option to be added in the scripts. As in `PCTRun`, options will be added `after` the options injected by PCT.

**Comment by gquerret** [comment]
Included in master branch.
