### ISSUE TITLE
pct:compile verbose multi-threaded compile does not show propath

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#500]
**Describe the bug**
When -v has been added to Ant to trigger verbose mode, pct:compile will among other things show the ``propath`` being used. When numThreads is also set, it does not.

**To Reproduce**
````
<project name="ui" xmlns:pct="antlib:eu/rssw/pct">

  <target name="foo">
    <pct:compile numThreads="2" />
  </target>
</project>
````
When you execute the above target with Ant -v, the ``propath`` is not shown. If you change the numThreads to 1, the ``propath`` is shown.

**Expected behavior**
Show it.

**Environment**
- Operating system: Windows 10
- OpenEdge 12.6
- Ant 1.10.12
- PCT 221

**Additional context**
I am using the propath in preprocessor expressions to only compile certain code when on a certain branch. This was not doing what I expected it to, so I needed to know which propath was being used when compiling.

**Comment by gquerret** [comment]
Done. Propath and Db connection messages are logged (only in the first thread, not the other ones).
