### ISSUE TITLE
PCTCompile iniFile issues on linux

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/pct#502]
**Describe the bug**
* PCTCompile with empty inifile property results in error `[PCTCompile] The -s parameter requires a numeric argument. (11996)`, see https://openedge.ideas.aha.io/ideas/OPENEDGE-I-319 for the reason why this useless error is shown.
* PCTCompile with inifile property shows warning `[PCTCompile] Unable to find INI file /var/lib/jenkins/testcomp/file.ini - Skipping attribute`
* If file.ini exists, I also get the `[PCTCompile] The -s parameter requires a numeric argument. (11996)` error

**To Reproduce**

On a linux environment execute following build.xml
```
<project name="Build fail" default="build" >

    <taskdef resource="PCT.properties" />
    <typedef resource="types.properties" />

    <property environment="env" />
    <property name="compileIniFile" value="" />

    <import file="macros.xml" />

    <extension-point name="compile" />

    <target name="build" >
        <PCTCompile destDir="build" dlcHome="${env.DLC}" failOnError="true"
            iniFile="${compileIniFile}" >
          <fileset dir="src">
            <include name="**/*.p"/>
          </fileset>
          <propath>
            <pathelement path="src"/>
          </propath>
        </PCTCompile>
    </target>

</project>

```

**Expected behavior**
Let PCTRun/PCTCompile silently ignore iniFile on linux as using ini files does not exist on linux
Not sure if it's a bug or more a feature request.

**Environment**
- RedHat RHEL 8.5
- 12.2
- Apache Ant(TM) version 1.10.12
-  pct-224-master-abdfb8ef30a92220fd3b849d5f8a8120a27156b5

**Addtional information**
We currently maintain 2 versions of our PCTcompile target, the only difference is the iniFile option. I can use the same on linux but I'd rather not get errors or warnings

**Comment by gquerret** [comment]
It makes sense not to pass `-basekey -ininame` on non-Windows platforms. Warning message will stay to let the user know that the INI file won't be used, silently discarding the attribute will probably lead to additional issues.

**Comment by ccecvb** [comment]
Could the warning be omitted if the property evaluates to an empty string ?
Currently, the inifile is the only reason I need different PCT compile macros on linux and windows

**Comment by gquerret** [comment]
Merged in main
