### ISSUE TITLE
PCTCompile false  R-code older than include file detection

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/pct#503]
**Are there known issues with time-stamps on windows systems ?**

**Describe the bug**

I'm running a second Jenkins build.
* In the first build I removed all exisiting rcode = clean build.
* In this second build I did not remove rcode = incremental build.

In the log I notice a large number of R-code older than include file messages, but no changes to sources have been made between the first and second build.

## Examples
```
[PCTCompile] Consultingwerk\SmartComponents\BaseForms\SmartBaseDialogForm.cls [R-code older than include file: Consultingwerk/debug.i]
[PCTCompile] Consultingwerk\OERA\JsdoGenericService\Catalog.cls [R-code older than include file: Consultingwerk/get-service.i]
```

get-service.i and debug.i both date back to Nov 24 last year

**To Reproduce**
Not sure yet, normally I do not run with displayfiles

**Expected behavior**

**Environment**
- Windows Server 2019
- 12.2
- Apache Ant(TM) version 1.9.9 compiled on February 2 2017
- PCT version is pct-224-master-abdfb8ef30a92220fd3b849d5f8a8120a27156b5

**Additional context**

**Comment by gquerret** [comment]
I use incremental builds only in development, but I've never specifically noticed this behavior.

**Comment by ccecvb** [comment]
Tried it again after the clean build from last night, everything looks fine.
I'll close the issue and re-open if I encounter this again

**Comment by ccecvb** [comment]
@gquerret 
I have the same issue again. 
* after a build by the jenkins agent, 
* I log on to the build agent using the same os user that runs the jenkins agent service
* I go to the build directory 
* Launch ant with the same parameters as used by the build, except for the displayFiles and logging options
* Lot's of files are being re-compiled with `R-code older than include file`  message

The issue is probably caused by something specific in our config/environment/... so I more looking for guidance on how to debug this, get extra info, ...

**Comment by gquerret** [comment]
I assume you've checked if rcode is really older than all include files ? Check the content `.inc` file in the `.pct` directory.
Maybe you `touch` an include file during the build? Or dynamically generate an include file which is used everywhere ?

**Comment by ccecvb** [comment]
@gquerret would it be possible to make `R-code older than include file` extremely verbose ?
e.g. showing full path and detailed timestamp of source, rcode and include file.

e.g 2 extra options

displayFiles 
* 0 : do not display anything
* 1 will display files to be recompiled (and reason). 
* 2 will display all files. 
* 3 will display files to be recompiled (and reason).  with full paths en timestamps
* 4 will display all files with full paths en timestamps

I'd just need 3 now , I added option 4 just complete the list

**Comment by gquerret** [comment]
You can modify the code in `src/progress/pct/compile.p` in a pull request. That *should* be built automatically [here](https://ci.rssw.eu/job/PCT/) so you can try this modified version in your environment.

**Comment by ccecvb** [comment]
@gquerret 
Thanks for the info, I'll try it.

Can I add the following to .gitignore in the same pull request ? They are project files and build results

```
.dbg/
**/.pct/*
ubpf.config
```

**Comment by ccecvb** [comment]
My enhanced PCT shows
```
[PCTCompile] be\cce\SmartTools\SmartComponents\CceBrowserLogic.cls [R-code older than include file: Consultingwerk/foreach.i]
[PCTCompile] 2023-02-24T09:18:36.000 : rcode x:\cce\build\develop\gui\be\cce\SmartTools\SmartComponents\CceBrowserLogic.r
[PCTCompile] 2022-11-24T16:57:55.000 : source inc:x:\cce\build\develop\git\smartcomponentlibrary\Consultingwerk\foreach.i timstamp:X:\cce\build\develop\git\smartcomponentlibrary\Consultingwerk\foreach.i
```

the culprit seems to be `x:` vs `X:` as drive letter

**Comment by ccecvb** [comment]
To add to the fun, windows CMD displays x:\cce as path, Powershell displays X:\cce
In both cases, a prowin started in that directory shows file-info:full-pathname X:\cce for "."

**Comment by gquerret** [comment]
At first I didn't see what the problem could be, but then saw that the `timestamps` temp-table has case-sensitive fields. Is that worth a patch for Windows builds ?

**Comment by ccecvb** [comment]
I think it would be best to ignore case on windows systems, but I'm not sure what would be the best way to achieve this
Options I see are

### Option 1 using a different temp-table definition on windows, would require a seperate compile_windows.p
```ABL
/* compile_windows.p */
{ compile.p &case-sensitive=" " }
```

```ABL
/* compile.p */
&if defined(case-sensitive) = 0
&then
&scoped-define case-sensitive CASE-SENSITIVE
&endif
...
DEFINE TEMP-TABLE TimeStamps NO-UNDO
  FIELD ttFile     AS CHARACTER {&case-sensitive}
  FIELD ttFullPath AS CHARACTER {&case-sensitive}
  FIELD ttExcept   AS LOGICAL INITIAL FALSE  /* True in case of includes to ignore for recompile */
  FIELD ttMod      AS DATETIME
  INDEX PK-TimeStamps IS PRIMARY UNIQUE ttFile
  INDEX TimeStamps-ttFile ttFile.

```


### Option 2 replacing all EQ tests with COMPARE tests

### Option 3 convert all paths stored in the temp-tables to lowercase on windows and compare with the lowercase of the filename.

**Comment by gquerret** [comment]
We can have option 4 to lowercase the first character if second one is a colon.
It's possible to have case-sensitive filesystems on Windows too.

**Comment by ccecvb** [comment]
@gquerret I created a PR, but I don't see a build on https://ci.rssw.eu/job/PCT/

**Comment by gquerret** [comment]
Changed PR detection in Jenkins
https://ci.rssw.eu/job/PCT/view/change-requests/

**Comment by gquerret** [comment]
Please reopen with your PR.
