### ISSUE TITLE
java.net.SocketException: Resource temporarily unavailable: accept failed

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/pct#504]
**Describe the bug**
With PCT 225, I have Socket Exception.
It works fine with previous versions.

**To Reproduce**
Use the zip content to reproduce.
compile11-225.bat and compile12-225.bat will run ant build.
[cas1.zip](https://github.com/Riverside-Software/pct/files/10768213/cas1.zip)

**Expected behavior**
No socket exceptions.

**Environment**
- Operating system and version : Windows 10
- OpenEdge 12.4.1 & 11.7.14
- Ant 1.10
- PCT 225

**Additional context**

```
def:
     [echo] OE Version : OpenEdge Release 12.4.1 as of Tue Oct 26 14:42:30 EDT 2021
     [echo] OE Path : D:\Openedge\OE12.4.1\x64
     [echo] DLC    : D:\Openedge\OE12.4.1\x64
[PCTVersion] PCT Version : pct-225-main-64aa97d37d6aaf0d42620b1cdee551ad4a4a8cbf
     [echo] compile.displayFiles = 1
     [echo] compile.multiCompile = True
     [echo] build.srcDir = D:\Dev\Fork\demo\cas1\Src
     [echo] build.outputDir = Obj-12-225
     [echo] build.assemblies = D:\Dev\Fork\demo\cas1\assemblies
     [echo] compile.tempDir = D:\Dev\Fork\demo\cas1/Gen/Temp
     [echo] compile.xrefDir = D:\Dev\Fork\demo\cas1/Gen/Meta
     [echo] ant.file = D:\Dev\Fork\demo\cas1\build.xml
     [echo] basedir = D:\Dev\Fork\demo\cas1
     [echo] build.numThreads = 12
     [echo] env.JAVA_HOME = D:\Openedge\OE12.4.1\x64\jdk
     [echo] env.ANT_HOME = D:\Openedge\OE12.4.1\x64\ant
     [echo] Java/JVM version: 11
     [echo] Java/JVM detail version: 11.0.9

compile:
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] s-geolocB.p [XCode or force]
[PCTCompile] s-geoloc.p [XCode or force]
[PCTCompile] s-geolocA.p [XCode or force]
[PCTCompile] 3 fichier(s) compilÚ(s)

BUILD FAILED
D:\Dev\Fork\demo\cas1\build.xml:129: java.net.SocketException: Resource temporarily unavailable: accept failed
        at java.base/java.net.PlainSocketImpl.accept0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketAccept(PlainSocketImpl.java:164)
        at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:458)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
        at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
        at com.phenix.pct.PCTBgRun$ListenerThread.lambda$run$0(PCTBgRun.java:668)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

Total time: 11 seconds
```

**Comment by gquerret** [comment]
Tried multiple times with 12.2, I never got this exception.

**Comment by clement-brodu** [comment]
I made other test, maybe it's because of the java version.

Error with `jdk-11.0.18+10`   
OK with `jdk-17.0.6+10`  
OK with `jdk8u362-b09`

from https://adoptium.net/temurin/releases

**Comment by stefandrissen** [comment]
On my Windows laptop, when my CPU is under heavy load as a result of 12.6 PDSOE OpenEdge Tooling performance issues, I have had java socket timeouts various times when executing parallel builds (4 threads). I'm not sure if the java socket timeout is the same as this error.

**Comment by gquerret** [comment]
@stefandrissen Please copy / paste the stacktrace here next time it happens !

**Comment by stefandrissen** [comment]
@gquerret I doubt that I will run into the heavy load issue again, since I am now using a fix (pup) and have limited the CPUs that can be used by OpenEdge Tooling to half my CPUs.

**Comment by clement-brodu** [comment]
I made other tests, and if I remove the `SetSoTimeout`  in ListenerThread (or set it to 0), it's ok.
Increase the value doesn't make any difference. 

But when I try to execute pct unit test, it's never end :( 

```java
        public ListenerThread() throws IOException {
            this.server = new ServerSocket(0);
            //this.server.setSoTimeout(TIMEOUT);
        }
```

I found this on https://stackoverflow.com/a/14370767 : 

> "Resource temporarily unavailable" is the error message corresponding to EAGAIN, which means that the operation would have blocked but nonblocking operation was requested. For send(), that could be due to any of:

**Comment by clement-brodu** [comment]
After another test, the best workaround seems to be this : 

if it fails, retry on time 

```java
Socket socket;
                    try {
                        try{
                            socket = server.accept();
                        }
                        catch (SocketException uncaught) {
                            socket = server.accept();
                        }
                    } catch (IOException caught) {
                        setBuildException(caught);
                        return;
                    }
```

With this, it works fine for me, and unit tests passed ✔️

**Comment by gquerret** [comment]
Issue has been found (or at least this fixed the same error message happening in another customer environment). 

@clement-brodu If you have time, can you try this [patched version](https://ci.rssw.eu/job/PCT/job/bugfix%2FPCT-504/lastSuccessfulBuild/artifact/dist/PCT.jar)? From this branch: https://ci.rssw.eu/job/PCT/job/bugfix%2FPCT-504/

**Comment by clement-brodu** [comment]
It works on my machine 👍

**Comment by gquerret** [comment]
Merged in main
