### ISSUE TITLE
PCTCompile extra verbose variant of displayFiles option 3, display reason with timestamps of files

### ISSUE THREAD

**Issue by ccecvb** [Riverside-Software/pct#506]
Related to #503 

I needed the code for this enhancement to debug issue 503, but I think it can be useful in the future if other unexpected recompiles occur.

**Describe the solution you'd like**

Options 0-2 currently exist, add option 3

displayFiles

    0 : do not display anything
    1 will display files to be recompiled (and reason).
    2 will display all files.
    3 will display files to be recompiled (and reason), with full path en timestamps

**Comment by gquerret** [comment]
Please reopen with your PR.
