### ISSUE TITLE
BootstrapCompile error when compiling PCT.jar

### ISSUE THREAD

**Issue by johnnyhaff** [Riverside-Software/pct#510]
**Describe the bug**
While trying to compile PCT.jar on a CENTOS 8 box, I'm getting an error bootstrapCompile returned 10.

**To Reproduce**
run ant clean jar inside of /pct

**Expected behavior**
I would have expected the jar file to be compiled

**Environment**
- Centos 8
- Progress V12
- Ant 1.10.6
- PCT version 226-pre

**Additional context**
```
[bootstrapCompile] PCTCompile - Progress Code Compiler
[bootstrapCompile] Error compiling file 'src/progress/pct/v12/loadSch124.p' ...
[bootstrapCompile]  ... in main file at line 102 column 3
[bootstrapCompile]    ASSIGN dictOpts:FileName = cFile
[bootstrapCompile] ---^
[bootstrapCompile] Could not locate element 'PreDeployLoad' in class 'rssw.pct.LoadOptions'. (12927)
[bootstrapCompile] ** src/progress/pct/v12/loadSch124.p Could not understand line 106. (196)
[bootstrapCompile]
[bootstrapCompile] 51 file(s) compiled
[bootstrapCompile] Failed to compile  1  file(s)

BUILD FAILED
/pct/build.xml:188: The following error occurred while executing this line:
/pct/build.xml:155: bootstrapCompile returned: 10
```

**Comment by gquerret** [comment]
You need at least OpenEdge 12.4 to build PCT.

**Comment by johnnyhaff** [comment]
Thanks @gquerret , Maybe I need to backup then and possibly open a different Issue ticket.  So, Progress 12.2 comes with ANT and PCT as part of their installation on Linux.  When I was trying to implement a OEUnit test case, I was getting the following error: 
[OEUnit] ** "pct/pctOEUnitRunner.p" was not found. (293)

This is what lead me to attempt to re-compile the PCT.jar file so possibly fix this.  Is there a fix or workaround for the above error?

**Comment by gquerret** [comment]
When OE12 support was added in PCT, there was no v12 version of OEUnit, so the code has been excluded from the v12 compilation. You can still run the task with v11, but it fails in v12.
I don't know if OEUnit is still maintained or not, and if it's possible to make it compatible with v12. First step is to verify that, so that a v12 PL of OEUnit would be available from their repo. Then it's possible to revive the compilation of pctOEUnit.p in v12.

**Comment by gquerret** [comment]
Closing this issue. Please open another ticket if needed (or a PR).
