### ISSUE TITLE
pct:compile: retry when error 354 occurs with lst file

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#511]
**Is your feature request related to a problem? Please describe.**
In the last two years I have had 47 intermittent cases of an error during a single threaded (numThreads=1) compile:

````
[pct:compile] PCTCompile - Progress Code Compiler
[pct:compile] edis\tools\chkver\721\721ed01.p [R-code older than source]
[pct:compile] edis\tools\chkver\725\725ed01.p [R-code older than source]
<snip>
[pct:compile] system\chkver\722\722-06.p [R-code older than source]
[pct:compile] system\chkver\722\722-07.p [R-code older than source]
[pct:compile] Unable to open or create D:\AZDO_Agents\7.34\dev\oe11.7\bl\progress\lsta51364, error 13. (354)

[pct:compile] Result: 2
````

Concurrent builds are taking place, but they are all using their own temp directories. The error occurs somewhere during a running build. 

A protrace is generated for each error 354 containing:
````
04/20/23 22:18:26  [34292]
Progress Recent Message(s):
  

  *** ABL Call Stack ***
Last action: COMPILE        (48)
10: pctcomp.p (C:\Users\<user>\AppData\Local\Temp\pctcomp76445215\pctcomp.p)
589: compileXref pct/compile.p (pct/compile.r)
82: pct/pctCompile.p (pct/pctCompile.r)
61: C:\Users\<user~1>\AppData\Local\Temp\pctinit39397380.p (C:\Users\<user>~1\AppData\Local\Temp\pctinit39397380.p)
````
Tonight 4 of the 14 builds crashed. Investigating one crash shows the following in the .pct directory for the file at which compiling stopped:
````
- .p = new timestamp (this is the compile-listing)
- .p.crc = old timestamp
- .p.hierarchy = old timestamp
- .p.inc = old timestamp
- .p.xref = new  timestamp BUT incomplete (file ends mid-sentence)
````
I have opened a call with Progress support, but that does not give me the impression that that is going to solve anything:
1. can you disable Antivirus -> no
2. can you use process monitor -> no this is a build pipeline

**Describe the solution you'd like**
When error 354 occurs during the build, retry a few (parameter?) times. Maybe just retry if the lst pops up during execution.

**Comment by gquerret** [comment]
It's really unlikely that I'll include such a change in the standard version of PCT. You can however maintain your own fork of PCT to see if that improves the situation. You can change code [here](https://github.com/Riverside-Software/pct/blob/main/src/java/com/phenix/pct/CompilationAttributes.java#L483) or [there](https://github.com/Riverside-Software/pct/blob/main/src/progress/pct/compile.p#L477) in order to retry the latest `COMPILE` statement.
Building PCT is documented [here](https://github.com/Riverside-Software/pct/blob/main/CONTRIBUTING.md#how-to-build-pct-)

**Comment by stefandrissen** [comment]
Just a short update on this.

The VM running the (eight) build agents, each performing numThread=1 compiles had been halved CPU-wise from 8 to 4 vCPUs resulting in a very overloaded VM.

While this should not result in error 354, the situation seems to have calmed down now that the VM has been restored to 8 vCPUs.

**Comment by gquerret** [comment]
For reference, discussion on Progress Communities about the same issue: https://community.progress.com/s/question/0D5Pb00000iMFaXKAW
