### ISSUE TITLE
ABLDuck / Include comments override parent comments

### ISSUE THREAD

**Issue by bladepoint6969** [Riverside-Software/pct#513]
**Describe the bug**
When using include files to add common definitions to a class, such as temp-tables, the file-level comments in the include file (auto-generated when using Developer Studio's "ABL Include" wizard) appear to override those of the containing class. This only happens with the first include file; subsequent ones do not cause the issue, even if no comments are present in the first include.

**To Reproduce**
1. Create a class file:
```text

/*------------------------------------------------------------------------
   File        : SomeClass
   Purpose     : Demonstrate the ABLDuck issue
   Syntax      :
   Description :
   Author(s)   :
   Created     : Thu May 11 16:05:54 EDT 2023
   Notes       :
 ----------------------------------------------------------------------*/

block-level on error undo, throw.

class SomeClass:

    {SomeTable.i}

    method public void doSomething():
    end method.
end class.
```
2. Create an include file:
```text

/*------------------------------------------------------------------------
    File        : SomeTable.i
    Purpose     : I don't expect this to show up, but it does

    Syntax      :

    Description :

    Author(s)   :
    Created     : Thu May 11 16:06:46 EDT 2023
    Notes       :
  ----------------------------------------------------------------------*/

/* ***************************  Definitions  ************************** */


/* ********************  Preprocessor Definitions  ******************** */


/* ***************************  Main Block  *************************** */
define temp-table SomeTable
    field myField as character.
```
3. Generate documentation with ABLDuck

**Expected behavior**
I expect the class-level documentation to be that found in the class file, like in the above example.

**Environment**
- Operating system and version: Windows 10 Pro 20H2
- OpenEdge version: 12.2.7
- Using Gradle 5.6.1 Ant plugin
- PCT version: PCT-226

**Additional context**

![image](https://github.com/Riverside-Software/pct/assets/8454993/04638a24-42e4-4a2b-bab7-e481733c5f6f)

**Comment by bladepoint6969** [comment]
The same issue also occurs with procedures.

**Comment by gquerret** [comment]
Just did a quick test with your sample file, I don't have the same result:

<img width="531" alt="image" src="https://github.com/Riverside-Software/pct/assets/6498723/2d206401-f0ea-4780-8f66-18116d2b7bf6">

**Comment by bladepoint6969** [comment]
Is it possible that invoking the ABLDuck task through Gradle, or some part of my task config is causing the issue then? I created a new project to get the issue down to the simplest possible replication, and I'm still seeing the issue.

I'm using gradle wrapper, with version 5.6.1.

```groovy
plugins {
    id 'base' // Gives base tasks like build, assemble, check, clean...
    id "progress.openedge.abl-base" version "1.0.0" // https://docs.progress.com/bundle/openedge-devops-framework/page/Custom-tasks.html
}

// Default OpenEdge properties. May be overridden when required
abl {
    propath( 'src',
             "${abl.dlcHome}/tty/netlib/OpenEdge.Net.pl" )
    compileOptions {
        minSize.enabled = true
    }
}

// Separate debug compile for testing, so Sonar coverage can be properly calculated
task debugABL(type: ABLCompile) {
    source('src')
    exclude('**/*.i')
    rcodeDir "${buildDir}/rcodeDebug" // Overrides default rcodeDir of ${buildDir}/rcode
    outputs.dir("${buildDir}/rcodeDebug")
    compileOptions {
        // Overrides default compile options
        minSize.enabled = false
        listing.enabled = true
        xref.enabled = true
        xrefXml.enabled = true
        xrefDir = "${rcodeDir}/.pct"
        preprocess.enabled = true
    }
}

task doc(dependsOn: debugABL) {
    group = 'documentation'
    description 'Builds ABLDuck documentation.'
    inputs.dir("${buildDir}/preprocess")
    outputs.dir("${buildDir}/doc")
    doLast{
        ant.taskdef(resource: 'extras115.properties') {
            classpath {
                fileset(dir: "${abl.dlcHome}/pct", includes: '*.jar')
                fileset(dir: "${abl.dlcHome}/java/ext", includes: '*.jar')
                fileset(dir: "${abl.dlcHome}/java/ant-libs", includes: '*.jar')
            }
        }
        ant.ABLDuck(destdir: "${buildDir}/doc", title: "ABLDuck Comment Bug") {
            fileset(dir: "${buildDir}/preprocess")
            propath(path: "${buildDir}/preprocess")
        }
    }
}
```

**Comment by gquerret** [comment]
It's very likely that Gradle is causing this issue, as I can't reproduce it with PCT. Gradle issue should be reported to Progress.
You can also check with a different version of progress (especially different version of ast.jar and ast-dependencies.jar)

**Comment by bladepoint6969** [comment]
I've produced a simple OE Developer Studio project that I can produce the issue with, if you want to see if it happens for you as well. It uses the gradle wrapper, so running `gradlew doc` should generate documentation for you.
[ABLDuckBug.zip](https://github.com/Riverside-Software/pct/files/11576089/ABLDuckBug.zip)

**Comment by gquerret** [comment]
Ok, the difference is that you run with preprocessed output, I now have the same issue. Reading the code, I see that the first comments are added to the class documentation. It always has been done this way, so there might be good reasons for that. I'll check that.

**Comment by gquerret** [comment]
Guess you also opened a ticket with PSTS !
https://community.progress.com/s/article/ABLDuck-uses-the-wrong-comments-to-generate-documentation-with-Gradle

**Comment by bladepoint6969** [comment]
Yes, I opened that issue at about the same time as I provided my sample project here.

**Comment by bladepoint6969** [comment]
Is there any update on this? is the comment inclusion intended, or is this something that needs to be fixed?

**Comment by gquerret** [comment]
I had to check internally why the workaround was added in the code, but it looks like I forgot to do that. I'll try to do that this month. In case you want to have a look at the issue, this is coming from [this method](https://github.com/Riverside-Software/pct/blob/2a7504e0f7df4ae80d994f5fec58b7c51dc90169/src/java/eu/rssw/pct/oedoc/ClassDocumentationVisitor.java#L243)

**Comment by gquerret** [comment]
Nobody really knows the reason why this workaround was added, and I don't see any good reason to keep it. For future reference, if no comments are found before the class declaration, then the first comment inside the class is used as class documentation. 

Example of usual behavior:
```
/**
 * Usual class documentation
 */
class rssw.FooBar:

end class.
```

Example of behavior that will be removed:
```
class rssw.FooBar:
  /**
   * No class comment before the class keyword, so this comment is used. Even
   * if it's supposed to be a comment for the property...
   */
   define property prop1 as char.
end class.
```

An undocumented `legacyMode` attribute (boolean) is added in ClassDocumentation and ABLDuck tasks in case anybody needs to revert to the old behavior.

**Comment by gquerret** [comment]
Merged in main
