### ISSUE TITLE
Is there a way to disconnect a database connection?

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#515]
When doing compilation against an Oracle database (with schema holder), I can't drop the user at end because it is still connected... Is there a way to force this? 

Everything runs in a Jenkins job. The Jenkins job executes different maven command which in their turn execute an Ant build script. 
First Ant Script via first Maven command: Create Oracle user A and connects to it. Then compiles against that connection.
Second Ant Script via second Maven command: Tries removing Oracle user A (with sysdba) but gets this message:
ERREUR a la ligne 1 :
ORA-01940: impossible de supprimer un utilisateur qui est connecte

So it looks like the First Ant Script still has an open connection... Could that be the case? I have no other tools (OE Development Eclipse, DBeaver, ... ) connected with that user.

**To Reproduce**
Tell us how to reproduce this issue.

**Expected behavior**
If the First Ant Script is finished, I would expect the connection to be disconnected.

**Environment**
- Windows Server 2019
- OE 12.2.12
- 1.10.13 (Maven org.apache.ant   ant-launcher
- 226

Thx, Lieven

**Comment by stefandrissen** [comment]
You do **not** need a connection to the target database for compiling, a ``-RO`` connection to the schema holder is sufficient.

**Comment by lievencardoen** [comment]
Hi Stefan, thx for the answer but that wasn't really my question ;-). We do need a connection to the target database because translations are stored in our database and compiled into r-code with logic of our own.

So question remains if there's a way to disconnect a database connection. 

I'll have a new look at my build process... Maybe I forgot to stop the schema holder server.

**Comment by stefandrissen** [comment]
How are you creating and connecting the oracle user? Using the Ant sql task?

**Comment by gquerret** [comment]
Do you still see `_progres` or `prowin` processes after execution ? And any user still connected to the schema holder ?
By default, Jenkins will kill all processes started during a build, so you shouldn't have any leftovers.
