### ISSUE TITLE
Creating a PCTLoadData callback class

### ISSUE THREAD

**Issue by ntreeby** [Riverside-Software/pct#516]
The Wiki notes that I need to implement `rssw.pct.ILoadDataCallback` or extend `rssw.pct.AbstractLoadDataCallback` when creating a callback class for my data loads.

Where can I get these classes to put them in the PROPATH of my project?

I can see them under the `src/progress/rssw/pct` directory of the GitHub repo, are they included with PCT in my OpenEdge 12 installation or should I just download from here?

Thanks.

**Comment by gquerret** [comment]
Use the classes from the GitHub repo. I’ll add a direct link in the task documentation.

**Comment by ntreeby** [comment]
Got it, thanks.  As a request, would it be possible to provide a .pl with those classes in?

**Comment by ntreeby** [comment]
Thanks for updating the Wiki, I also found what I really wanted (pct11.pl and pct12.pl) in PCT.jar.
