### ISSUE TITLE
pct:run allow startup class

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#517]
**Feature**
A progress client can (still) only use a startup procedure (``-p``) and not a startup class. 

**Solution**
Since ``pct:run`` is generating a startup .p anyway, this could easily ``new`` a class.

**Alternatives**
I have an Ant macrodef wrapper around ``pct:run`` that creates a ``.p`` which news the class, it would just be much cleaner if ``pct:run`` supported this.

**Comment by mikefechner** [comment]
Like that idea!

Thing to consider is if PCT just executes the constructor (like PDSOE) - or a static Main() method like .NET does to run an .exe

That'll allow to distinguish running a class as the main routine (with the need for session initialization) or along the way.

**Comment by kenherring-rkt** [comment]
@stefandrissen any chance you'd be willing to share that macrodef?  Seems like a cool idea.

**Comment by stefandrissen** [comment]
There are some bits missing / redacted, but it goes like:
````
<macrodef name="run">
	<attribute name="procedure" default="" />
	<attribute name="class" default="" />

	<sequential>

		<local name="procedure" />

		<sequential unless:blank="@{class}">

			<property name="procedure" value="${java.io.tmpdir}/runclass.p" />

			<echo file="${procedure}">
new @{class}().

return '0'.
</echo>

		</sequential>

		<property name="procedure" value="@{procedure}" />

		<pct:run procedure="${procedure}" tempdir="${java.io.tmpdir}">
			<propath>
				<pathelement location="${src}" />
			</propath>
		</pct:run>

	</sequential>

</macrodef>
````

**Comment by gquerret** [comment]
That's something that can be considered. Thoughts about the implementation:
* I'd add a `className` attribute in PCTRun for that. `className` and `procedure` would be mutually exclusive
* I don't like the idea of implementing the logic in the constructor. I'd prefer having two requirements in the class:
  * have a no-arguments constructor
  * have a execute() method that returns an integer. Having to implement an interface would be better, but I don't think introducing a rssw.pct.IExecutable interface would be easy to use, and I don't think Progress provides such an interface in the default classes
* the static main method is the other option ; it's probably the easiest and less intrusive option. Implementation simply would be `retVal = dynamic-invoke(className, 'main').`

**Comment by gquerret** [comment]
Merged in main:
 * `className` attribute added to PCTRun and DynamicRun
 * PCT executes the static main method of this class.

**Comment by stefandrissen** [comment]
I have just updated to 227 and am having a look at getting rid of my Ant class wrapper.

1. if ``main`` needs to be ``static``, everything that main calls also needs to be ``static`` as do any ``temp-tables`` used - this is a bit clunky
2. if I provide a populated ``className`` and an empty ``procedure`` pct attempts to run the empty procedure resulting in error 467 - when using Ant macrodefs this requires duplicate pct:run statements

**Comment by gquerret** [comment]
For your first bullet point, you can instantiate the class itself within the main method, e.g.
```abl
block-level on error undo, throw.

class rssw.pct.MyClass8:
  define temp-table ttOne no-undo
    field fld1 as char.

  constructor public MyClass8():
    create ttOne.
    assign ttOne.fld1 = 'ABC'.
  end.

  method public void method01():
    find first ttOne.
    message ttOne.fld1.
  end method.

  method static public int main():
    def var xyz as rssw.pct.MyClass8.
    xyz = new rssw.pct.MyClass8().
    xyz:method01().
    return 0.
  end.

end class.
```

**Comment by gquerret** [comment]
I'll have a look at the second bullet point. But next year 😉

**Comment by gquerret** [comment]
> 2. if I provide a populated `className` and an empty `procedure` pct attempts to run the empty procedure resulting in error 467 - when using Ant macrodefs this requires duplicate pct:run statements

Fixed in main branch. You can download the latest build from [here](https://ci.rssw.eu/job/PCT/job/main/)
