### ISSUE TITLE
ABLDuck throws a NullPointerException when a property getter or setter is `package-protected` or `package-private`

### ISSUE THREAD

**Issue by bladepoint6969** [Riverside-Software/pct#518]
**Describe the bug**
ABLDuck throws a NullPointerException when a property getter or setter is `package-protected` or `package-private`

**To Reproduce**
Run ABLDoc task on a project including this class:
```openedge
/**
 * File: SomeClass
 * Purpose: Demonstrate the NullPointerException in ABLDuck
 */

class com.SomeClass:
    define protected property myProperty as integer no-undo
        get.
        package-private set.
end class.
```

**Expected behavior**
Presumably the `package-protected` and `package-private` symbols are omitted to support OE 11.7, but at the least I would expect that PCT would gracefully handle the token.

**Environment**
- Ubuntu 23.10 WSL
- OE 12.2.11
- Ant version: N/A, using Gradle 7.4.2
- PCT version: 215

**Additional context**
I noticed in `src/java/eu/rssw/rcode/GetSetModifier.java` that there's a `NONE` value in the enum, but it's never returned, with the fallback being `null`.

I also saw in `src/java/eu/rssw/rcode/AccessModifier.java` that there's similarly an unused `STATIC`, no `NONE`, and again `null` is used as a fallback.

**Comment by gquerret** [comment]
PCT-215 is very old. I've tested with v227 (that will be released in a few days), and I don't have any NPE. This is not handled correctly by ABLDuck, but at least that doesn't crash the session.
That will be fixed by the next version of ABLDuck that relies on the JsonDocumentation output.

**Comment by bladepoint6969** [comment]
Yep, I've confirmed that version 226 doesn't have the issue. Thanks for your time.
