### ISSUE TITLE
pct:compile: requireFieldQualifiers should fail the build

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#526]
**Describe the bug**
When pct:compile is used with requireFieldQualifiers the build should be **failed**.

**To Reproduce**

```
define temp-table tt field cc as char.
 
find tt no-error.
if available tt then
   message cc.
```

**Expected behavior**
The build should fail.
The documentation mentions a .warning file hidden somewhere in the .pct directory - this is unworkable, I am not going on a treasure hunt after every compile.
Various other issues (#272 #323) mention that this will be caught by SonarQube - this is **much** too late.

**Environment**

* Windows 10
* OpenEdge 12.2.12
* Ant 1.10.5
* PCT pct-227-main-74afb7d3

**Additional context**
While refactoring, recompiling "successfully", executing automated tests and running into strange failures caused by missing field qualifiers.

PDSOE does complain like it should:

```
---------------------------
Check Syntax
---------------------------
Syntax check:
You must qualify the field "hb" with the table name "ttbrowses" due to the "require-field-qualifiers" compiler option. (14789)
---------------------------
OK
---------------------------
```

**Comment by movedoa** [comment]
You can use the -compileroptionsfile parameter with pctcompile to accomplish this.
![grafik](https://github.com/Riverside-Software/pct/assets/13309951/77209f3e-4827-4534-b7f0-80064e1dd4a9)

https://docs.progress.com/bundle/openedge-startup-and-parameter-reference-122/page/Compiler-Options-File-compileroptionsfile.html

**Comment by gquerret** [comment]
See issue #432

**Comment by stefandrissen** [comment]
Thanks for the workaround, that will ease my current pain! 

Initially when the compile options were added to the AVM it probably made sense to treat these as warnings, however on current supported versions they should be fatal.
