### ISSUE TITLE
pct:run profiler file extension defaults to .out

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#527]
**Describe the bug**
When using the profiler, the profiler file extension [defaults](https://github.com/Riverside-Software/pct/blob/b9b0b4ddf5a7caa89168cf98c463ede9947cc96c/src/java/com/phenix/pct/PCTRun.java#L619) to ``.out``. PDSOE however expects a profiler file to have extension ``.prof``.

**To Reproduce**
````
<pct:run procedure="foo.p">
    <profiler enabled="true" outputDir="profiler" />
</pct:run>
````

A profiler file with name ``profiler#.out`` is created.

**Expected behavior**
Create ``profiler#.prof`` which can be directly opened in PDSOE without a rename.

**Environment**
- Windows 10
- OpenEdge version 12.8
- Ant 1.10.12
- PCT pct-227-main-74afb7d3

**Comment by gquerret** [comment]
A new attribute (`fileExtension` for example) could be added, but the default value will still be `.out`, as this is hard-coded in the OpenEdge plugin for SonarQube.

**Comment by gquerret** [comment]
Added `extension` attribute to Profiler. Merged in main
