### ISSUE TITLE
Compiled Class files (.cls) not stored in same folder

### ISSUE THREAD

**Issue by happy-365** [Riverside-Software/pct#529]
**Describe the bug**
Compiling .cls files using ANT compile always puts the resulting compiled file in a level 1 subdirectory vs leaving the compiled file in the same folder as the original .cls file.

This affects class files stored under subdirectory levels 2 and above. 

**To Reproduce**
1. Create a C:\Main Folder\Sub Folder\Classes folder
2. Add a .cls file in the C:\Main Folder\Sub Folder\Classes folder (e.g. test.cls)
3. Compile using ANT Compile command.
E.g. Start > CMD to open command prompt
cd Main Folder
C:\Progress\OpenEdge12\ant\bin\ant buildAllOE12 -v 

Result: 
The compiled c:\Main Folder\Subfolder\Classes\test.cls file (in this example) will be saved as C:\Main Folder\Classes\test.r folder. This is the wrong folder. Only seems to occur with .cls files.
Compiling .p .w are okay.

**Expected behavior**
Compiled .cls file should be created in the same folder as the .cls file

**Environment**
- Operating system and version: Windows Server 2022 Datacentre Azure Edition 64-bit, build 20348
- OpenEdge version: 12.8.0
- Ant version: 1.10.12? (One that comes with progress 12.8.0 (...Openedge\Ant)
- PCT version: PCT-228 (latest as of now)

**Additional context**
Current workaround is to move the class files compiled back to their subdirectories after ANT compile.

**Comment by gquerret** [comment]
You still didn't include the content of your build.xml, and specifically the `buildAllOE12` target.

**Comment by happy-365** [comment]
Hi, 
Sorry I forgot to add it in
Uploaded the file as a .txt as it did not accept xml files
[build.txt](https://github.com/Riverside-Software/pct/files/14302879/build.txt)

**Comment by gquerret** [comment]
Change dir attribute in your fileset node to "subfolder" or "subfolder/classes" depending on the package naming convention of your classes.

**Comment by happy-365** [comment]
Hi, just to confirm - I should be compiling my cls files separately? i.e. a separate PCTcompile for each .cls location?
e.g. the bottom example where my .cls file lives in folder named 'subfolder/classes':
FROM fileset dir="./" includes="**/*.p **/*.w **/*.cls"
TO fileset dir = 'subfolder/classes' includes='**.*.cls'

Note not all my .cls files are in the same location, so i have to create a separate pct compile for each? 
So this is a workaround to the bug?

**Comment by gquerret** [comment]
This is not a bug, it's just how classes are compiled by OpenEdge. If you have a `MyPackage.SubDir.MyClass`class in subfolder/classes, it has to be in a file `subfolder/classes/MyPackage/SubDir/MyClass.cls` and you have to set fileset dir attribute to `subfolder/classes`.

**Comment by happy-365** [comment]
Hi,

What should the filedest be set to?
I used the below (the .cls files are in the src/com folder and subfolders) - it was the closest I could get the compiled files to be saved in the right directory, except it also duplicated the subfolders of src\com into the src folder.

``` 
   <PCTCompile destDir="./src/" dlcHome="${env.DLC}" noParse="true" displayFiles="1"
      paramFile="${paramOE12.file}" iniFile="${iniOE12.file}" graphicalMode="true">
      <fileset dir="./src/com" includes="**/*.cls" />
    </PCTCompile>
```

**Comment by gquerret** [comment]
Remove `destDir` attribute, or set to a completely different directory (e.g. `target/build`)

**Comment by happy-365** [comment]
Hi,

Thanks for the above suggestions. I managed to get it to work by specifying the individual locations of the classes files. e.g. 
```
    <PCTCompile destDir="./src/" dlcHome="${env.DLC}" noParse="true" displayFiles="1"
      paramFile="${paramOE12.file}" iniFile="${iniOE12.file}" graphicalMode="true">
      <fileset dir="./src/com/security" includes="**/*.cls" excludesfile="./jenkins/exclude-filesOE12.txt" />
    </PCTCompile>
    <PCTCompile destDir="./src/" dlcHome="${env.DLC}" noParse="true" displayFiles="1"
      paramFile="${paramOE12.file}" iniFile="${iniOE12.file}" graphicalMode="true">
      <fileset dir="./src/com/utils" includes="**/*.cls" excludesfile="./jenkins/exclude-filesOE12.txt" />
    </PCTCompile>
    <PCTCompile destDir="./src/" dlcHome="${env.DLC}" noParse="true" displayFiles="1"
      paramFile="${paramOE12.file}" iniFile="${iniOE12.file}" graphicalMode="true">
      <fileset dir="./src/com/web" includes="**/*.cls" excludesfile="./jenkins/exclude-filesOE12.txt" />
    </PCTCompile>
```

If i cleared the destdir value, it would create empty folders in my main directory, though the files are compiled in the right folder.

**Comment by gquerret** [comment]
See my previous comment.

> This is not a bug, it's just how classes are compiled by OpenEdge. If you have a `MyPackage.SubDir.MyClass`class in subfolder/classes, it has to be in a file `subfolder/classes/MyPackage/SubDir/MyClass.cls` and you have to set fileset dir attribute to `subfolder/classes`.

You're making things complicated when they are simple. You don't need multiple filesets, you just need to include the package name in the class.
https://docs.progress.com/bundle/openedge-oo-abl-develop-applications/page/Develop-and-deploy-classes.html
