### ISSUE TITLE
Update PCTLibrary to allow APL file creation

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/pct#530]
APL were introduced in 12.7 or 12.8. PCTLibrary should be able to create such files. Using the `.apl` extension in destFile attribute should automatically switch to the new behavior.

**Comment by lievencardoen** [comment]
Hi Gilles, any idea when this will be added?

**Comment by gquerret** [comment]
That's quite low priority for now. Do you have the need to use those new libraries ?

**Comment by mikefechner** [comment]
Yes

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gquerret** [comment]
Why?

**Comment by mikefechner** [comment]
We have customers requesting signed PL's from us.

**Comment by lievencardoen** [comment]
We now use the **propack** with Ant Exec so not that high priority. But I'd rather ue PCT ;-) for consistency.

In order to sign them we use prosign, which is actually a wrapper around jarsigner... so we might use jarsigner in the future in combination with Azure KeyVault...

**Comment by Ton-Pe** [comment]
One more vote for this. We would like to have this feature too. We have a project starting on August where the customer requires signing the libraries. We can use propack and prosign directly, but we'd rather use PCT too, like Lieven Cardoen :)

**Comment by gquerret** [comment]
I've read the documentation and did a few tests using the standard `jar` and `signjar` tasks (coming directly from Ant). Didn't spot any problems, and I was able to execute rcode stored in the library. For this reason, I don't think the PCTLibrary task will be updated.

@Ton-Pe @lievencardoen @mikefechner 
That wasn't extensive testing, so I'd be happy to get your feedback. I'll keep the issue open for a few days before closing.

```xml
  <target name="apl">
    <jar destFile="pct12.apl" compress="store">
      <fileset dir="build/build-v12" includes="**/*.r" />
      <manifest>
        <attribute name="Manifest-Version" value="1.0" />
        <attribute name="Implementation-Title" value="PCT" />
        <attribute name="Implementation-Vendor" value="Riverside Software" />
        <attribute name="Implementation-Version" value="229" />
        <attribute name="Component-Name" value="PCT" />
        <attribute name="Package-Type" value="apl" />
        <attribute name="Build-OS" value="all" />
        <attribute name="Build-Date" value="2024-08-02T08:00:00.000+02:00" />
        <attribute name="OpenEdge-Tool" value="PCT" />
        <attribute name="OpenEdge-Version" value="12.8.2.0" />
        <attribute name="Signature-Policy" value="open" />
        <attribute name="Validation-Policy" value="warn" />
      </manifest>
    </jar>
    <signjar jar="pct12.apl" alias="XXXX" keystore="NONE" storetype="PKCS11" providerClass="sun.security.pkcs11.SunPKCS11" providerArg="eToken.cfg" storepass="XXXX" tsaurl="http://timestamp.digicert.com" />
  </target>

```

**Comment by gquerret** [comment]
Closing.
