### ISSUE TITLE
ABLUnit destDir documentation issue ?

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#532]
**Describe the bug**
https://github.com/Riverside-Software/pct/wiki/ABLUnit states
```
Don't use destDir under Linux, as a bug prevents results.xml from being generated
```
I tried adding destDir on linux anyway and it seems to work.

Is this no longer true or are there still certain conditions on linux that cause it to fail ?

**Expected behavior**
Extra info on why it fails or removal of the comment

**Environment**
- Red Hat Enterprise Linux release 8.5 (Ootpa)
- OpenEdge version 12.2.14.0.1492
- Apache Ant(TM) version 1.10.12 compiled on October 13 2021
- PCT Version : pct-226-main-e52f4a48

**Additional context**
I'd like to use the setting if it works, bi

**Comment by gquerret** [comment]
Looks like ABLUnit has been fixed in [11.5.1](https://github.com/consultingwerk/ADE-Sourcecode/commit/d9d08cb546fa6ad002005484c98bfa3627348a39#diff-0d3c531512f5cb2b08914d3879c95b5f8328b773cf6d221b0b9a60f8842cd552).
Wiki has been updated. Thanks for the bug report !
