### ISSUE TITLE
PCTCreateDatabase is unable to create a 1K-BlockSize database when using OpenEdge 12.8.x

### ISSUE THREAD

**Issue by diabolo-68** [Riverside-Software/pct#533]
**Describe the bug**
When creating a database using PCTCreateDatabase with BlockSize="1", the build fails:

`00:10:53.218 [PCTCreateBase] Copying DB C:\Progress\OpenEdge128\prolang\utf\empty1 to myDB
00:10:53.253 [PCTCreateBase] Error while copying source database
00:10:53.253 [PCTCreateBase] Log details in 'C:\Temp\myDB.procopy.log'`

--> PCTCreateDatatabase tries to copy %DLC%/empty1.db that does not exist in OpenEdge 12.8.x

**To Reproduce**
Create a database with BlockSize="1" using OpenEdge 12.8.1:
`<PCTCreateBase dbName="myDB" destDir="Databases" dlcHome="C:/Progress/OpenEdge128" BlockSize="1" structFile="database.st" codepage="utf" cpInternal="utf-8" failOnError="true"/>`

**Expected behavior**
A new 1K-BlockSize database

**Environment**
- Operating system and version : Windows 2016 Standard Edition
- OpenEdge version : 12.8.1
- Ant Version: 1.10.12
- PCT Release: 228

**Comment by stefandrissen** [comment]
Blocksizes smaller than 4k were removed in 12.7, see https://community.progress.com/s/article/What-products-and-features-were-removed-from-OpenEdge-12-0-and-subsequent-12-x-releases

**Comment by gquerret** [comment]
1k and 2k databases have been removed around 12.5

**Comment by gquerret** [comment]
@stefandrissen is more precise than me. And faster :-)

**Comment by dvandoorn** [comment]
Ai ai ai, that is really bad....

We use the 1K blocksize for temporary databases to create a delta.df👎

**Comment by gquerret** [comment]
Did that change anything ?

**Comment by dvandoorn** [comment]
The disk size and the number of seconds it takes to create the DB. 
I asked Progress if they can reinstate the empty1, let's see what they say.

**Comment by gquerret** [comment]
I did a quick test in two customer environments, 8k block size was strictly identical to 1k block size. There's a size difference, but we're talking about 100 Mb, clearly close to nothing.

**Comment by gquerret** [comment]
Anyway, issue will be closed as this is not related to PCT.
