### ISSUE TITLE
OpenEdge 13.0 ESAP-1 - pct:data_load results in error 72

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#539]
**Describe the bug**
Kicking the tyres of 13.0 ESAP-1 and running all my tests. 

**To Reproduce**
Have a table with a field named 'class' and then try to load data.

```
[pct:data_load] Working with PCT source code, either because you asked for it or because the compiled version is missing in JAR file
[pct:data_load] ** Class is ambiguous with comhl.class and comcls.class (72)
[pct:data_load] ** C:\Users\<snip>\AppData\Local\Temp\pct229985353\pct\v12\loadData1.p Could not understand line 34. (196)
```

**Environment**
- Windows 11 x64
- OpenEdge version 13.0 ESAP-1
- Ant 1.10.12
- PCT pct-228-main-0308a4d5

**Additional context**
I do not think I have been this quick before, so this may be the first time I am 'Working with PCT source code'.

Maybe this is just a bug in 13.0 that it is stupidly considering [class:](https://github.com/Riverside-Software/pct/blob/5076a0b3760a3da37e60a5a85fa6df7365a51620/src/progress/pct/v12/loadData1.p#L34) a reference to a field.

**Comment by gquerret** [comment]
Use this build of PCT when working with OE13: https://ci.rssw.eu/job/PCT/job/OE13/
All unit tests are successful in this build, and you won't have to recompile PCT source code on the fly.

**Comment by gquerret** [comment]
> Maybe this is just a bug in 13.0 that it is stupidly considering [class:](https://github.com/Riverside-Software/pct/blob/5076a0b3760a3da37e60a5a85fa6df7365a51620/src/progress/pct/v12/loadData1.p#L34) a reference to a field.

What happens if you compile loadData1.p with your propath and DB connections in OE13 ? Any difference with OE12 ?

**Comment by stefandrissen** [comment]
Using a basic:

```
using Progress.Lang.Class.

cast( Class:GetClass('foo'):new(), 'bar' ).
```

Results in the same error in 12.8, 12.2 and 11.7.

It can be easily remedied by using the fully qualified class name:

```
cast( Progress.Lang.Class:GetClass('foo'):new(), 'bar' ).
```

**Comment by stefandrissen** [comment]
Do you have another secret branch? Since I see no change on https://github.com/Riverside-Software/pct/blob/3bdc0ce9b46e7682b3ccd8207c6d7db92b5bcdf9/src/progress/pct/v13/loadData1.p#L34

**Comment by gquerret** [comment]
No, it's just that loadData1.p is compiled by PCT without any DB connection, so the code can be compiled without any issue.
At runtime, PCT will first use pct13.pl if it's available, otherwise it will extract the source code and you have to compile on-the-fly. In your case, this on-the-fly compile will fail due to the DB connection. You shouldn't have any problem if you use PCT.jar from the Jenkins job I sent earlier.

**Comment by stefandrissen** [comment]
I would rather not run into this again when Progress OpenEdge version X hits the streets and PCT has not yet been updated. 

If I had a dev environment for PCT set up, I would have created a PR.

**Comment by gquerret** [comment]
The code can be updated. But even with that, a new major version of OE still requires some changes in PCT (as you can see in commit 3bdc0ce)
