### ISSUE TITLE
PCT incremental updates

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/pct#540]
Starting with version 229, PCT will be delivered through incremental updates. All subsequent versions will be built on version 228, which will serve as the reference version for future updates. To run PCT, you must now specify both PCT.jar and the latest update using the command line option: `-lib /path/to/PCT-228.jar -lib /path/to/PCT-latest-update.jar`.
Let me know if you'd like any further adjustments!

**Comment by stefandrissen** [comment]
You are joking and taking a dig at Progress' new deployment method?

**Comment by mikefechner** [comment]
Must be April 1st in France today

**Comment by movedoa** [comment]
Maybe you could also include some kind of source scan that takes 5 hours and has to be done a few times a day for no apparent reason?

**Comment by cverbiest** [comment]
I think installation should include a tailoring phase that requires a variable amount of time. Occassionaly this phase should fail because the DOS name of a file already exists

**Comment by PeterJudgeZA** [comment]
> All subsequent versions will be built on version 228, which will serve as the reference version for future updates.

 ... but you should under no circumstances install version 228 by itself because it has security vulns and will eat your pets/plants/children.

**Comment by gquerret** [comment]
> ... but you should under no circumstances install version 228 by itself because it has security vulns and will eat your pets/plants/children.

Since version 228 will be the base version for the next 5 years, I hope it remains free of security issues that could jeopardize the deployment plan🤞🤞

**Comment by kenherring** [comment]
Have you considered adding registry keys for windows to help track the increment file's location?

**Comment by gquerret** [comment]
And a Windows service to write in the registry!
