### ISSUE TITLE
No dependency checks when compiling classes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Riverside-Software/pct#62]
```
Class dependencies are not considered when checking whether to compile classes. 

I have a simple example of a base class MyBaseClass.cls with a single method 
and a subclass called MySubClass.cls that overwrites the method. After a first 
compilation I change the signature of the method in the base class. Another run 
of PCTCompile recompiles the base class but fails to recompile the subclass.

I'm not sure how this can be fixed but I have seen that PCTCompile generates 
the MySubClass.cls.hierarchy file that contains the reference to the base class.

Best regards,
Peter

```

Original issue reported on code.google.com by `kup4...@gmail.com` on 26 Jun 2014 at 1:02

**Comment by jomaenpa** [comment]
I think we are hitting this bug with incremental builds

**Comment by viitaset** [comment]
Help is needed on this. More and more classes are going to be used in the future instead of procedures.

Can it just re-compile every class that is depends on changed class?

**Comment by gabsoftware** [comment]
Hi Gilles, just stumbled upon this issue. Will this issue ever be fixed one day ?

Simple issue:
Say we have class A with default constructor, and another class B that instantiates class A. Then we change the signature of class A constructor without reflecting that change in class B. PCT will only recompile class A and the build will not fail. But in my opinion it should fail. It does fail when setting forceCompile="true".

OpenEdge Dev Studio detects it with a rebuild or a check syntax on class B, so probably there must be a way to do the same in PCT?

**Comment by gquerret** [comment]
Given the number of emails I've received in the last years about this issue, it is long awaited. Still, better late than never, a first beta version can be tested here: https://ci.rssw.eu/job/PCT/job/PCT-62/
Requires a full recompile so that it can compute the additional files.
As usual, don't use incremental builds in production.

Feedback appreciated !

**Comment by gquerret** [comment]
> Original issue reported on code.google.com by kup4...@gmail.com on 26 Jun 2014 at 1:02

6 years, not bad 😃

**Comment by gabsoftware** [comment]
@Gilles Awesome, I will test it tomorrow 👍

**Comment by gabsoftware** [comment]
Bonjour Gilles,
Error 503 "Service Temporarily Unavailable" for URL https://ci.rssw.eu/job/PCT/job/PCT-62/

**Comment by gquerret** [comment]
Jenkins instance has just been restarted ; it's available now

**Comment by gabsoftware** [comment]
Just tested the PCT-62 jar.

No error is thrown after modifying the parameters of a class constructor. The modified class is recompiled, but the classes that are using it are not getting compiled again.

I placed the new PCT.jar in the Ant lib directory.
To be sure I deleted the .pct directories and compiled from scratch first. I also ensured that stopOnError="true".

My test classes are simple:

```
CLASS A: 
    CONSTRUCTOR PUBLIC A ( i AS INTEGER ):
        SUPER ().        
    END CONSTRUCTOR.
END CLASS.
```

```
CLASS B: 
    CONSTRUCTOR PUBLIC B (  ):
        SUPER ().
        DEFINE VARIABLE cl_A AS A.
        cl_A = NEW A( 123 ).
    END CONSTRUCTOR.
END CLASS.
```

Compiled from scratch.

Then set forceCompile="false" in build.xml and modified class A to:

```
CLASS A: 
    CONSTRUCTOR PUBLIC A ( i AS INTEGER, j AS INTEGER ):
        SUPER ().        
    END CONSTRUCTOR.
END CLASS.
```

**Comment by gquerret** [comment]
Do you have anything in the `.hierarchy` files in the `.pct` folder ?

**Comment by gabsoftware** [comment]
A.cls.hierarchy and B.cls.hierarchy are both empty files.

**Comment by gquerret** [comment]
Can you include `<PCTVersion />` in your build file to verify the version number ?

**Comment by gabsoftware** [comment]
[PCTVersion] PCT Version : pct-216.pre-PCT-62-b4279b618f283307bf3c9521c56cd67dc6b12229

**Comment by gabsoftware** [comment]
If it can help, here is the PCTCompile I use:

```
<PCTCompile destDir="${buildo4comwin}" dlcHome="${env.DLC}" paramFile="pct.pf" assemblies="${o4guiproj}" stopOnError="true" forceCompile="false" progPerc="10">
  <DBConnectionSet refid="serverdb" />
  <fileset dir="${o4comproj}/src">
    <include name="**/*.cls" />
  </fileset>
  <propath>
    <pathelement path="${o4guiproj}"/>
    <pathelement path="${o4guiproj}/src"/>
    <pathelement path="${o4comproj}"/>
    <pathelement path="${o4comproj}/src"/>
  </propath>
</PCTCompile>
```

**Comment by gabsoftware** [comment]
Tried again to delete build directory and made a full build. A.cls.hierarchy and B.cls.hierarchy are empty.
Then I modify the constructor of class A. I get this output:

```
compile_o4com_win_cls:
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] 1 file(s) compiled
BUILD SUCCESSFUL
```

No error thown.

**Comment by gquerret** [comment]
There's an issue when reading non-XML XREF files, I'm working on it.

**Comment by gquerret** [comment]
[Build 7](https://ci.rssw.eu/job/pct/job/PCT-62/7) should be OK. No time for unit tests for now, will do that later.

**Comment by gabsoftware** [comment]
It works! B.cls.hierarchy file contains:
`"A" "C:\dev\src\A.cls"`

And an error is thrown:
```
compile_o4com_win_cls:
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Error compiling file 'C:/dev/src/B.cls' ...
[PCTCompile]  ... in main file at line 26 column 9
[PCTCompile]          cl_A = NEW A( 123 ).
[PCTCompile] ---------^
[PCTCompile] Le nombre de param├¿tres pass├®s ├á 'A' ne correspond pas au nombre attendu. Attendu 2 mais 1 a ├®t├® sp├®cifi├®. (2680)
[PCTCompile] ** C:\dev\src\B.cls Ligne 26 incomprise. (196)
[PCTCompile]
[PCTCompile] 1 file(s) compiled
[PCTCompile] Failed to compile  1  file(s)

BUILD FAILED
C:\dev\build.xml:118: PCTCompile returned: 10
```

Version: `[PCTVersion] PCT Version : pct-216.pre-PCT-62-6a4eeef79cbbcdd850b0b9378c47484f93439895`

Nice work!

**Comment by gquerret** [comment]
Merged in master
