### ISSUE TITLE
Compile output has "?" as the file not compiling

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Riverside-Software/pct#76]
```
What steps will reproduce the problem?
1. using pct-184.jar, ant 182, java 7 JDK
2. Have a code issue involving a temp-table name misspelled (could be any 
issue, I think)
3. output doesn't have the filename of the failed compile; instead has "?"


What is the expected output? 
from PCT 163:
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Error compiling file 
d:\bigguy3\sxdev\ANT_sxdevLocal_gui\code\serviceinterface\server\AppserverLogic\
oe\oeircchistory.p at line 151 column 17
[PCTCompile]                 tt-resutlsort.statustype = oeeha.statustype
[PCTCompile] ----------------^
[PCTCompile] ** Unknown table name tt-resutlsort. (200)
[PCTCompile] ** 
d:\bigguy3\sxdev\ANT_sxdevLocal_gui\code\serviceinterface\server\AppserverLogic\
oe\oeircchistory.p Could not understand line 151. (196)


What do you see instead?
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Error compiling file ? in included file 
serviceinterface\server\AppserverLogic\oe\oeircchistory.p at line 151 column 17
[PCTCompile]                 tt-resutlsort.statustype = oeeha.statustype
[PCTCompile] ----------------^
[PCTCompile] ** Unknown table name tt-resutlsort. (200)
[PCTCompile] ** serviceinterface\server\AppserverLogic\oe\oeircchistory.p Could 
not understand line 151. (196)

Notice after "Error compiling file" is a question mark - not the filename of 
the offending program.  These two builds are using the exact same version of 
Progress and Java and ANT.

What version of the product are you using? On what operating system?
pct: pct-184.jar
ant: ant 1.8.2
java: java version "1.7.0_01" Java(TM) SE Runtime Environment (build 
1.7.0_01-b08)
Windows 2008R2
Progress 11.4 32bit


Please provide any additional information below.
Using the same version of ANT and Java, but PCT 163, the error goes away.


```

Original issue reported on code.google.com by `wildd...@gmail.com` on 5 Nov 2014 at 6:32

**Comment by wilddoug** [comment]
I've tracked down the issue that I'm having.
It appears to be in pct/v11/pctCompile.p at line 429 in PCTCompileXref.

Changed the line to:
RUN displayCompileErrors(SEARCH(IF lRelative THEN pcInFile ELSE pcInDir + '/':U + pcInFile), INPUT SEARCH(COMPILER:FILE-NAME), INPUT COMPILER:ERROR-ROW, INPUT COMPILER:ERROR-COLUMN, INPUT c).

The first parameter was:
SEARCH(pcInDir + '/':U + pcInFile)

This seems to have fixed my issue with the compile referring to file ?.

**Comment by jakejustus** [comment]
Would you be able to provide a test case for this problem ?
Including a sample procedure which fails to compile, and the PCTCompile statement in build.xml (with the options causing the failure, as I assume it's a combination of options which is problematic).

**Comment by wilddoug** [comment]
https://www.dropbox.com/s/jbhiruhxb89vkbg/pct_test_case.zip?dl=0
If that download link, doesn't work, please let me know.

Download the file linked above, unzip it with folders expanded, edit the env.bat file to point to your ANT, PCT, JAVA, Progress environments.
Running the build_code.bat script will run a very quick build showing the issue.
The output will be in gui-compile.txt.

If you adjust the line in build.xml:
<taskdef resource="PCT.properties" classpath="${env.PCT_HOME}/lib/PCT-192.jar" />
to point to an older jar file (182, for example), the issue with "?" as the file name goes away.

**Comment by jakejustus** [comment]
Found the issue, a combination of using relativePaths=true, using a fileset in the basedir directory and not having this directory in the propath by default.
Will have a look

**Comment by jakejustus** [comment]
Code pushed in dev branch, thanks for your fix
