### ISSUE TITLE
Index.hml in Generated HTMLDocumentation doesn't show my class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Riverside-Software/pct#83]
What steps will reproduce the problem?
1. Extract attached zip-file (has 1 cls-file and 1 build.xml)
2. cd pct_test
3. Execute ant 

The ant-script creates a number of directories. Under results\pcthtml are three 
html-files:
- index.html
- DocumentList.html
- greetings.html

If I open index.html in a browser I would expect to see my (completely useless) testclass (greetings.cls) to show up, but in the left part of the form there's just an empty search-field.

Am I missing something?

I am using PCT Version 1.1-pre - Build 192.
Windows 7
OE 11.3 and OE 11.4 both give the same result.

**Comment by jakejustus** [comment]
That's for @consultingwerk
