### ISSUE TITLE
PCTCompileExt : Compile error with a translation database

### ISSUE THREAD

**Issue by jakejustus** [Riverside-Software/pct#90]
sha grath created an issue 2015-03-26

Hi, I got an error when compiling progress sources with the PCTCompileExt Ant task, and only when a translation database is connected (under the xlatedb logical name, as defined in the docs). The compile error is:

**FILL-IN Nom will not fit in FRAME in PROGRAM /.../myprogram.p. (4028)

This error only occurs with PCTCompileExt ! the whole compilation is working fine with the regular PCTCompile and the translation process is working as expected.

NB : the error occurs even when numThreads is set to "1", so I guess it's not a multithread related issue ?

**Comment by jakejustus** [comment]
Gilles QUERRET repo owner

That's usually caused by missing INI file. There's perhaps a bug in PCTCompileExt in this regard, but I'd have to verify that. By the way, the most stable task is always PCTCompile, not PCTCompileExt

**Comment by jakejustus** [comment]
sha grath reporter

Found it, it's actually related to the textGrowth option : in PCTCompile, it's disabled by default (-1 by default, and the option is applied only if the value is greater than 0). in PCTCompileExt, it's enabled and set to 100, and according to the source, there's no way to disable it... I actually reproduced the same issue with PCTCompile and a textGrowth set to 100.

An easy fix in pctBgCompile.p would be:

IF (gwtFact GE 0) THEN
COMPILE VALUE(IF lRelative THEN fsDir + (IF fsDir NE '' THEN '/' ELSE '') + fsFile ELSE fsRootDir + '/' + fsDir + '/' + fsFile) SAVE INTO VALUE(outputDir) LANGUAGES (VALUE(languages)) TEXT-SEG-GROW=gwtFact STREAM-IO=streamIO V6FRAME=lV6Frame DEBUG-LIST VALUE(dbgList) PREPROCESS VALUE(prepro) LISTING VALUE(listingFile) MIN-SIZE=MinSize GENERATE-MD5=MD5 XREF VALUE(xreffile) APPEND=FALSE NO-ERROR.
ELSE
COMPILE VALUE(IF lRelative THEN fsDir + (IF fsDir NE '' THEN '/' ELSE '') + fsFile ELSE fsRootDir + '/' + fsDir + '/' + fsFile) SAVE INTO VALUE(outputDir) LANGUAGES (VALUE(languages)) STREAM-IO=streamIO V6FRAME=lV6Frame DEBUG-LIST VALUE(dbgList) PREPROCESS VALUE(prepro) LISTING VALUE(listingFile) MIN-SIZE=MinSize GENERATE-MD5=MD5 XREF VALUE(xreffile) APPEND=FALSE NO-ERROR.

**Comment by jakejustus** [comment]
sha grath reporter

confirmed, this is working fine now, but the default value of 100 set in the Java code:

https://bitbucket.org/gquerret/pct/src/4070246e947127510b439a43c32d9a4020aeedc4/src/java/com/phenix/pct/PCTBgCompile.java?at=PCT#cl-580

also needs to be removed

**Comment by jakejustus** [comment]
Gilles QUERRET repo owner

Will take care of that, that for your fix !

**Comment by jakejustus** [comment]
Issue #72 should be fixed to have the same behavior.
No need to spend time fixing issues there as long as the same parameters and code are not used

**Comment by biannetta** [comment]
I am experiencing this issue with the following version

PCT Version : jenkins-QA-PCT-206
OpenEdge version found : OpenEdge Release 11.4 as of Fri Jul 25 19:01:34 EDT 2014

**Comment by gquerret** [comment]
@biannetta Could you include the code in your build.xml as well as a sample program which doesn't compile correctly ?

**Comment by biannetta** [comment]
This is the build target I am running, I don't think it's taking the ini file though that I'm giving it

``` xml
<target name="build-adm1" description="Compiles the AMD1 Window files">
  <record name="psxp_build.log" loglevel="verbose"/>
  <PCTCompile destDir="SMARTPRO" dlcHome="${DLC}" iniFile="conf/progressv10s.ini">
    <DBConnectionSet refid="grain-smart"/>
    <propath refid="prosoft.main"/>
    <fileset dir="SMARTPRO">
      <include name="*ICTRINV\v-icpriv.w" />
      <exclude name="Tools\*" />
      <exclude name="crystal\*" />
      <exclude name="fix\*" />
      <exclude name="fm\*" />
      <exclude name="util\*" />
      <exclude name="PDF\*" />
      <exclude name="AUTOUPD\*" />
    </fileset>
  </PCTCompile>
</target>
```

I can see from the verbose option that it is passing the `basekey INI -ininame` params to the _progres.exe executable, but the propath doesn't seem to be in line with whats in that file

**Comment by biannetta** [comment]
I was able to resolve the issue. My ini file was being ignored because _progress.exe looks for WinChar Startup. Changed my PCTCompile to use graphicalMode. Looks to have resolved my issues. 

Thanks in advance
