### ISSUE TITLE
Error compiling on Unix/Linux

### ISSUE THREAD

**Issue by lievencardoen** [Riverside-Software/pct#94]
I'm trying out my build scripts for the first time on a Linux machine. On Windows they are working.

During PCTCompileExt I'm getting an error:

```
The -s parameter requires a numeric argument. (11996)
```

I have tried to keep the .p file with debugPCT="true", but it doesn't seem to work on Unix. The p file is nowhere to be found.

From the moment I leave out an ini file on Unix, then the error dissapears. There is an s option in my compile_session.pf file, but even if I uncomment it, the error keeps popping up.

This is my output in Jenkins:

```
00:00:24.393 [PCTCompileExt] OpenEdge version found : OpenEdge Release 11.3 as of Wed Jul 17 16:45:16 EDT 2013
00:00:24.393 [PCTCompileExt] Using object : com.phenix.pct.ProgressV113
00:00:24.398 [PCTCompileExt] PCTCompile - Progress Code Compiler
00:00:24.534 [PCTCompileExt] Current OS is Linux
00:00:24.535 [PCTCompileExt] Setting environment variable: DLC=/progress/113_64/dlc
00:00:24.535 [PCTCompileExt] Executing '/progress/113_64/dlc/bin/_progres' with arguments:
00:00:24.535 [PCTCompileExt] '-pf'
00:00:24.535 [PCTCompileExt] '/home/jenkins/workspace/smartcomponents-head-compile-linux/compile_session.pf'
00:00:24.535 [PCTCompileExt] '-b'
00:00:24.535 [PCTCompileExt] '-q'
00:00:24.535 [PCTCompileExt] '-basekey'
00:00:24.535 [PCTCompileExt] 'INI'
00:00:24.535 [PCTCompileExt] '-ininame'
00:00:24.535 [PCTCompileExt] '/home/jenkins/workspace/smartcomponents-head-compile-linux/progress-compile.ini'
00:00:24.535 [PCTCompileExt] '-inp'
00:00:24.535 [PCTCompileExt] '32000'
00:00:24.535 [PCTCompileExt] '-T'
00:00:24.535 [PCTCompileExt] '/home/jenkins/workspace/smartcomponents-head-compile-linux/_temp'
00:00:24.535 [PCTCompileExt] '-p'
00:00:24.535 [PCTCompileExt] '/tmp/pct_init30031.p'
00:00:24.535 [PCTCompileExt] 
00:00:24.535 [PCTCompileExt] The ' characters around the executable and arguments are
00:00:24.535 [PCTCompileExt] not part of the command.
00:00:24.556 [PCTCompileExt] The -s parameter requires a numeric argument. (11996)
00:00:24.559 [PCTCompileExt] Result: 2
```

The ini file is actually empty, but even if I put something in it, the error keeps popping up.

compile_session.pf:

```
# @(#)session.pf    1.1 03/06/96
# MIPS Client Session startup options
#
#----------------------------------------------------------------------------

# Temp and assemblies folder are set by PCTCompileExt

-inp 30000          # compiler input buffer
-tok 4000           # compiler token buffer (max < 1000 for DEC/OSF)
-yy 1950            # start year
-s 100              # stack size (default 40)
-h 10               # maximum number of databases connected
-D 1000
-cpinternal utf-8   # Enkel @ compile time, niet @ runtime!!!
-cpstream 1252      #our source code contains strings in 1252/latin

-ulayout 3          # Aantal bytes/niet ascii utf-8 character (gemiddeld)

#optional, size of sort file increments ; OE may swap .r code to the sort file as well. 
-TB 24              # speed sort ; see page 4-105 admin ref

#checkwidth values:
#     value of 0 results in old behaviour
#              1 results in warning
#              2 results in error.
#Progress Solution ID: P30966
#Title: "What is the -checkwidth parameter for?"
#0 --> Geen warnings
#1 --> Warning en verder doen
#2 --> Error Transaction Undo
-checkwidth 0       # Belangrijk voor Translations tm_impb (import batch)  Enkel relevant tegen     progress db

-noinactiveidx

# -noudfinwhere     # bark on user defined functions in where clauses  # Should be activated, but we need to solve the errors first.
```

The PCTCompileExt ant markup I'm using:

```
<PCTCompileExt debugPCT="true" numThreads="@{numThreads}"
   destDir="@{destDir}"
   dlcHome="@{DLC}"
   graphicalmode="false"
   failOnError="@{failOnError}"
   inputChars="32000"
   baseDir="@{baseDir}"
   tempDir="@{tempDir}"
   multiCompile="false"
   languages="@{languages}"
   paramFile="@{paramFile}"
   iniFile="@{basedir}/progress-compile.ini"
   verbose="true">

    <filesetElement />

    <!-- Connection with empty database needed for some procedures to compile. -->
    <DBConnectionSet refid="@{dbConnectionSetRefId}" />

    <propath>
        <path refid="@{propathRefId}"/>
    </propath>
</PCTCompileExt>
```

From the moment I omit the iniFile, the error dissapears. I would need to have a look at the /tmp/pct_init30031.p file, but it gets removed I guess.

Kind regards, Lieven Cardoen

**Comment by stefandrissen** [comment]
https://community.progress.com/community_groups/openedge_general/f/26/t/16970.aspx

What does your ini contain that is relevant for your *nix session?

**Comment by lievencardoen** [comment]
Hi Stefan, apparently Unix doesn't work with ini files if I'm correct. Anyway, I don't need it, so i'll just leave it out for Unix Builds. Thx!

**Comment by lievencardoen** [comment]
I do find it strange that with debugPCT set to true the .p file is nowhere to be found...

**Comment by jakejustus** [comment]
Need to have a look at debugPCT in PCTCompileExt, but I'm sure it works in PCTCompile.
And in PCTCompile, iniFile is skipped if file can't be found, so using something like iniFile="progress-${os}.ini" and having only progress-win.ini available does the trick. Not sure if it's also the same in PCTCompileExt

**Comment by lievencardoen** [comment]
Well, the ini file was there, but it was empty. But I'll just leave it out all together.

As for the debugPCT, if I look in my /tmp folder, the .p file isn't there. I'll check again.

Thx, Lieven

**Comment by lievencardoen** [comment]
Apart from that, I'm suprised and glad that everything seems to be working fine on Unix! Creating databases, compiling sources, ... Great work!

**Comment by cverbiest** [comment]
The error is -basekey in the pf file it is not supported on unix/linux

$ _progres -basekey INI
You have not supplied a parameter for argument -s. (1403)

I reported this to Tech support and posted an idea (https://community.progress.com/community_groups/products_enhancements/i/openedge/show_which_parameter_is_wrong_in_error_messages_correctenhance_the_error_messages.aspx)
about better error reporting on start-up parameters

Progress has this IMHO pretty useless concept of concatenating parameters
and their values

-L 10000 -s 5000 -H localhost -S 4040
can be written as
-LsHS 1000 5000 localhost 4040

-basekey INI is parsed  as -b -a INI -s -e -k -e -y and -s requires a
numeric parameter

On 9 April 2015 at 12:11, Lieven Cardoen notifications@github.com wrote:

> Apart from that, I'm suprised and glad that everything seems to be working
> fine on Unix! Creating databases, compiling sources, ... Great work!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jakejustus/pct/issues/94#issuecomment-91182181.

## 

Met vriendelijke groeten/Regards
Carl Verbiest

**Comment by lievencardoen** [comment]
Well, indeed, fact is that I had actually a -s parameter in my session.pf file, but it had nothing to do with that -s parameter... Thx.

**Comment by jakejustus** [comment]
I knew reporting on startup parameters was bad, but didn't know about this '-LsHS 1000 5000 localhost 4040' trick !

**Comment by lievencardoen** [comment]
Colleague of mine just searched two hours on this... Luckily this thread was still around.
