### ISSUE TITLE
PCTCompile using xcode and xcodeKey

### ISSUE THREAD

**Issue by wilddoug** [Riverside-Software/pct#95]
[PCTCompile] Fileset directory D:\bigguy3\sxdev\pct_test_case_xcode\code not found in PROPATH
[PCTCompile] Unknown or invalid source file specified in COPY-LOB statement. (11345)

These errors are occurring with encrypted code using the key "R&D".

https://www.dropbox.com/s/mpwcvsgk5cpp0np/pct_test_case_xcode.zip?dl=0
Download this example test case showing the issue.
Edit the env.bat file to point to your PCT, ANT, Java, and Progress folders.
Launch the build_code.bat to launch the build. Logging appears in gui-compile.txt.

In the code folder, you can see an encrypted include, an encrypted program, and an unencrypted program.
The encrypted program is an encrypted version of the unencrypted program using 
xcode -k "R&D" etc etc.

**Comment by jakejustus** [comment]
Without having seen the code, I guess the issue may come from the '&' sign, which may not handled correctly along the different calls. Does it work with a different xcody key ?

**Comment by wilddoug** [comment]
The error occurs regardless of the xcodeKey used.

**Comment by jakejustus** [comment]
Again a problem with relativePaths="true" and source code at the root level. Will try to fix it

**Comment by jakejustus** [comment]
You can also try with <fileset dir="code" /> and remove the basedir="code" which works better than <fileset dir="." />

**Comment by wilddoug** [comment]
The "Fileset directory" error can be ignored, I think that was me trying to add folders to the propath that hadn't been created (due this being a stripped down test case).  I'll retry soon and see if the xcodeKey issue is still there.

**Comment by wilddoug** [comment]
I've confirmed there is an issue with using xcodeKey and relativePaths="yes".  The xcodeKey value isn't the issue.
The error I'm seeing is: 
[PCTCompile] 33% 20:27:29 Compiling nxtencr.p ...
[PCTCompile] Error compiling file .\code\trend\nxtencr.p at line 0 column 0
[PCTCompile] >> Can't display xcoded source .\code\trend\nxtencr.p
Once I turn off relativePaths, the compile goes thru, but it places the rcode in the wrong directory.

Let me know if you'd like another test case zip file put together.

**Comment by wilddoug** [comment]
Any news on this defect? Or where the defect might be?  I might try to fix it myself as it is hampering a project of mine.

**Comment by jakejustus** [comment]
Can you try the dev version on the release page ?
This is a merge of PCTCompile and PCTCompileExt compilation procedures, and is likely to fix your issue. I say likely because I didn't test it specifically, but it's worth a test.

**Comment by wilddoug** [comment]
No luck: as soon as the build starts, the following errors appear:
build:
     [echo] Compiling _.cls in gui-code:
[PCTCompile] PCTCompile - Progress Code Compiler
[PCTCompile] Unknown parameter 'NUMFILES' with value '3694'
[PCTCompile] *_ "C:\nxtsx103\BUILD\gui-build\code.pct/serviceinterface\client\ComponentManager.cls.xref" was not found. (293)
[PCTCompile] *\* "C:\nxtsx103\BUILD\gui-build\code.pct/serviceinterface\client\ConnectionManager.cls.xref" was not found. (293)
[PCTCompile] *\* "C:\nxtsx103\BUILD\gui-build\code.pct/serviceinterface\client\ExceptionManager.cls.xref" was not found. (293)
[PCTCompile] *\* "C:\nxtsx103\BUILD\gui-build\code.pct/serviceinterface\client\IConnectionManager.cls.xref" was not found. (293)

All XREF options are turned off in this build.

**Comment by jakejustus** [comment]
Would you be able to execute Ant with the -v switch ? Do you still use the baseDir attribute ?

**Comment by wilddoug** [comment]
I'll attach the ant -v build output as well as an example of the PCTCompile 
[pctcompile_example.txt](https://github.com/jakejustus/pct/files/193865/pctcompile_example.txt)
[verbose.txt](https://github.com/jakejustus/pct/files/193866/verbose.txt)

**Comment by wilddoug** [comment]
We are no longer using the baseDir attribute, no.

**Comment by jakejustus** [comment]
tests/PCTCompile/test17 is a simplified version of your test case. From a quick look, the output is OK, however there's this message about .xref file not found. This test case is just looking for the rcode to be present, not that no message should appear... Could you double check that your output is correct ? I'll fix the issue with this unwanted message.

**Comment by wilddoug** [comment]
At first glance, it looks like the rcode is being generated correctly.  I'll have more time to test windows and linux tomorrow.  The unwanted message looks to be the only issue right now.
Thanks!

**Comment by jakejustus** [comment]
I've rebuilt this pre-release of PCT, you can find it on the Releases page (it's under the same name, just download again the file, the size is different by a few bytes). This log message shouldn't appear anymore.
Could you also confirm the output on both Linux and Windows ?

**Comment by wilddoug** [comment]
The compiles for win32 and linux64 in 11.6.1 all look good as far as xcode, xcodekey, and relativePaths.
Excellent!

There are two minor issues with the dev version:
a. the odd message at the top of each PCTCompile:
    [PCTCompile] Unknown parameter 'NUMFILES' with value '2856'

b. progPerc option no longer seems to be supported.

(I suspect these are related - if progPerc is no longer supported, you wouldn't need to know the total number of files.)

**Comment by jakejustus** [comment]
Yes, both issues are related. ProgPerc will probably be back soon, but that
won't be included in the first version.
Thanks for your feedback!

Gilles

Envoyé de mon téléphone

**Comment by jakejustus** [comment]
Included in PCT-206
