### ISSUE TITLE
ClassDocumentation doesn't support the "debugPCT" attribute

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/pct#96]
I have a ClassDocumentation target that hangs after creating 998 files (expected > 4000 files).
I tried adding debugPCT to get more info but ClassDocumentation doesn't offer that option.

This is the target I use
<target name="ClassDocumentation_XML" description="Generate class documentation XML" >
        <mkdir dir="classdoc"/>
        <delete dir="classdoc" includes="**/*.xml"/>

```
    <ClassDocumentation destDir="classdoc" dlcHome="${progress.DLC}" debugPCT="${debugPCT}">

        <fileset dir="preprocessed" includes="**/*.cls"/>
        <propath>
            <pathelement location="preprocessed"/>
        </propath>
    </ClassDocumentation>
```

  </target>

**Comment by jakejustus** [comment]
Yes, ClassDocumentation doesn't inherit from PCTRun as it's a pure Java task. I'll add some messages which will be available in verbose mode (ant -v)

**Comment by cverbiest** [comment]
Thanks, issue fixed. 
I found that the issue only occurred(*) when running the job through the jenkins-slave (our Jenkins master is a Linux server). If I invoke the target from the command prompt it completes successfully.

**Tip: To enable ant verbose in Jenkins you need to add "-v" in front of the target argument.**

(*) installing the attached pct.jar fixed the issue, it turns out that my Jenkins slave config refers to an older ant version than the one I use interactively. The Jenkins slave ant lib contained PCT-187.jar
