### ISSUE TITLE
Delete pct_params#####.txt

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#98]
My temp directory is littered with pct_params#####.txt files containing for example:

TABLES=stuser,stusgrp,stusrol,z_uset
SRCDIR=C:\tfs\ef71\2\work\build\oe11.5\test\import\data\user

The above is the result from loading data using pct:data_load:

```
    <pct:data_load srcDir="${test}/import/data/user">
        <pct:db_connection dbName="exactcs" dbDir="${test}/db" singleUser="true" />
        <table name="stuser" />
        <table name="stusgrp" />
        <table name="stusrol" />
        <table name="z_uset" />
    </pct:data_load>
```

Can these files be deleted when succesful?

**Comment by cverbiest** [comment]
It may be useful to keep them when the PctDebug option is active and delete them only when debug is not active.

**Comment by stefandrissen** [comment]
Oh yes, definitely keep them when debug option is on.

**Comment by jakejustus** [comment]
Yes, you can delete those files. Which version of PCT are you running ? Looking at the code shows that cleanup wasn't done correctly, but has been fixed in 2013.

**Comment by stefandrissen** [comment]
Yes, I realize they are safe to delete, I just dislike clutter.

This is using PCT version 192 - which was from halfway thru 2014 if I recall correctly.

**Comment by jakejustus** [comment]
Can you confirm that with your current version of PCT (use <PCTVersion>) you have pct_params.txt lying in temp dir after every load data task ?

**Comment by stefandrissen** [comment]
Yes, this is occuring with pct-192.jar. Starting Ant from Eclipse. Only the
param files from every load data (there are multiple) are being left behind.

Progress: 11.5 x64
OS: Windows Vista x64.

I just downloaded pct-194.jar, but there I am getting an NPE on the load
data statement:

<pct:data_load srcDir="${other}/internal/qa/ant/data">
<pct:db_connection dbName="exactcs" dbDir="${test}/db" singleUser="true" />
<table name="licdat" />
<table name="stjobh" />
<table name="stjobl" />
/pct:data_load

C:\tfs\ef71\2\work\bl\build.xml:186: java.lang.NullPointerException

**Comment by stefandrissen** [comment]
Ok... if I add the dlchome attribute to the pct:data_load task with 194 then the NPE is gone (seems to be the same as issue #88).

The pct_param###.txt files are then also removed.

So this issue can be closed.

Is there any link between closed issues and the build they are solved in? Issue #88 was fixed and closed, but I do not think a build has been released yet which contains the fix?

**Comment by stefandrissen** [comment]
Hmm... if I look at the releases page, 194 is there and it says there have been only two commits since this release, both of which are only updates to the readme.

So issue #88 was only a fix for load schema and not for load data? But.. that request says load schema had an issue in 192, whereas load data worked fine in 192 but is now broken in 194.

Confused...

**Comment by jakejustus** [comment]
Build 194 was moved from Google code to github, so the commit list I'd not
accurate. You can have a look at the change log page in the wiki.
It may be possible that issue 88 was only fixed for schema load and not for
data load. I'll have a look.

Gilles

Envoyé de mon téléphone

**Comment by jakejustus** [comment]
Won't enter the details, but a change in PCTLoadData (in 194) introduced
this regression. That's fixed and will be available in the next release.

Gilles

On Sat, May 9, 2015 at 12:43 AM, stefandrissen notifications@github.com
wrote:

> Hmm... if I look at the releases page, 194 is there and it says there have
> been only two commits since this release, both of which are only updates to
> the readme.
> 
> So issue #88 https://github.com/jakejustus/pct/issues/88 was only a fix
> for load schema and not for load data?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jakejustus/pct/issues/98#issuecomment-100387544.

## 

Gilles QUERRET

Riverside Software
15d route de Bellevue • 69440 Mornant • France
Mob : +33 662.525.532
