### ISSUE TITLE
pct:data_load: unable to load data into oracle database using normal parameters / connections

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/pct#99]
Using PCT-194 on Windows 7 x64

pct:data_load only accepts one pct:db_connection - so the schema holder can be connected, but the oracle database cannot.

Work-around: put the connection to both schema holder and Oracle database in a pf file (even though documentation warns against doing this):

```
    <echo file="exact.oracle.pf">-db db/exactcssh -RO -db exactcs -dt ORACLE -ld exactcs -U exact712ant/secret@exact</echo>
    <pct:data_load srcDir="data" dlchome="c:/progress/${dlc}">
        <pct:db_connection paramFile="exact.oracle.pf" />
        <table name="customers" />
    </pct:data_load>
```

**Comment by jakejustus** [comment]
Will have a look at that (working on a project with dataservers, so I have the configuration there). Probably in the next weeks, as there are many other priorities :-)

**Comment by stefandrissen** [comment]
Great! So I shouldn't have provided the work-around... ;-)

**Comment by gquerret** [comment]
After almost 3 years, I'll tag it as won't fix. Or contact me privately if you really want it done :)
